### ISSUE TITLE
Getting message on background, but 'notification' is not called

### ISSUE THREAD

**Issue by yossale** [phonegap/phonegap-plugin-push#374] opened 2015-11-24 14:44 UTC
(phonegap-plugin-push 1.4.3, cordova android 5.0.0)

I'm sending a background notification, and following the logs, it arrives (see below), but the 'notification' function is not being called in the background. Why? 

```coffeescript
push.on 'notification', (data) ->
      log("PUSH_DEBUG: notification data: #{JSON.stringify(data)}")
```

The message contains only an 'info' key
```shell
D/PushPlugin_GCMIntentService( 6602): normalize extras
D/PushPlugin_GCMIntentService( 6602): key = info
D/PushPlugin_GCMIntentService( 6602): replace key info with info
D/PushPlugin_GCMIntentService( 6602): key = collapse_key
D/PushPlugin_GCMIntentService( 6602): replace key collapse_key with collapse_key
D/PushPlugin_GCMIntentService( 6602): background
D/PushPlugin_GCMIntentService( 6602): message =[null]
D/PushPlugin_GCMIntentService( 6602): title =[null]
D/PushPlugin_GCMIntentService( 6602): send notification event
V/PushPlugin( 6602): sendExtras: caching extras to send at a later time.
```

**Comment by yossale** [comment] 2015-11-25 10:23
The 'notification' is being called when the app is running in the background, but if the app is completely closed, it doesnt

**Comment by flinux** [comment] 2015-11-25 11:08
Same problem here with windows universal, 'notification' isn't called if the app is completely closed.

**Comment by macdonst** [comment] 2015-11-25 16:13
@yossale this is a duplicate of #158. Please go vote it up.

The root cause is when you kill the app you also kill the service that is registered to receive the push. I need to look at a way to automatically restart that service if the app is killed.

**Closed by macdonst** 2015-11-25 16:13 UTC
Labels: duplicate
