### ISSUE TITLE
GC MIntentService.java:565: error: cannot find symbol mBuilder.setColor(iconColor);

### ISSUE THREAD

**Issue by Ziv-Barber** [phonegap/phonegap-plugin-push#393] opened 2015-12-03 16:02 UTC
platforms\android\src\com\adobe\phonegap\push\GC MIntentService.java:565: error: cannot find symbol             mBuilder.setColor(iconColor);                     ^   symbol:   method setColor(int)   location: variable mBuilder of type Builder

**Comment by macdonst** [comment] 2015-12-03 16:15
@Ziv-Barber please stop opening this issue. You already did with issue #217 where I directed you to:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#compilation

This is a duplicate of #51 which has been addressed Ad nauseam.

**Closed by macdonst** 2015-12-03 16:15 UTC
Labels: duplicate

**Comment by Ziv-Barber** [comment] 2015-12-03 16:28
Sorry. Anyway, I just comment this line to make it to compile.

**Comment by macdonst** [comment] 2015-12-03 17:27
Update your Android Compat Library

**Comment by Ziv-Barber** [comment] 2015-12-03 18:47
OK, after fighting with it for hours, this is the only way to make this plugin to work with the facebook plugin:

1. You MUST install a patched com.phonegap.plugins.facebookconnect plugin that using android-support-v13.jar and NOT the normal one that using android-support-v4.jar.

2. Replace android-support-v13.jar in platforms/android\com.phonegap.plugins.facebookconnect/FacebookLib/libs with the LAST version from Google SDK (extras/android/support/v13).

3. Edit build.gradle, find the comments with "SUB-PROJECT DEPENDENCIES", change them to anything you want. We just don't want the Cordova script to find them or it'll destroy our changes. Now comment out all the lines between the comments that match this:
compile "com.google.android.gms:play-services ...
or
compile "com.android.support:support-v13 ...
then save the file.

Now you can compile your project without getting any error.

**Comment by macdonst** [comment] 2015-12-03 19:31
@Ziv-Barber did you see our docs on how to get this to peacefully co-exist with the Facebook plugin?

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#co-existing-with-facebook-plugin

**Comment by Ziv-Barber** [comment] 2015-12-03 19:41
@macdonst, yes I saw but I also saw the comments that it's not working.
Anyway, now it working for me BUT I can't find out how to setup custom res files.
I want to use custom notification icons for Android 5+. I know that I need to configure android.icon with the name of the res file but how can I put custom res file that is neither icon or splash image?

**Comment by barocsi** [comment] 2016-01-24 19:18
I have no facebook plugin installed, followed everything as described above.
And still...
GCMIntentService.java:571: error: cannot find symbol

**Comment by zigzag-way** [comment] 2016-08-30 05:58
I also still have the same problem

**Comment by jonystorm** [comment] 2016-10-17 04:01
+1
