### ISSUE TITLE
Error: Could not parse project.pbxproj: SyntaxError: Expected "/*", "//", or "{" but "<" found.

### ISSUE THREAD

**Issue by chandu193** [phonegap/phonegap-plugin-push#1931] opened 2017-08-31 10:35 UTC
Issue: 
On running "**ionic cordova platform add ios**" gives the following error
`Appzuis-Mac-mini:moyoex Appzui$ ionic cordova platform add ios --save
> cordova platform add ios --save
✖ Running command - failed!
[ERROR] Exception: Using cordova-fetch for cordova-ios@^4.4.0

        Adding ios project...
        Creating Cordova project for the iOS platform:
        	Path: ../../../../../../appzui/desktop/moyo/moyo/moyo/moyoex/platforms/ios
        	Package: com.appzui.moyonutrilife
        	Name: Nutrilife
        iOS project created with cordova-ios@4.4.0
        Discovered plugin "cordova-plugin-badge" in config.xml. Adding it to the project
        Installing "cordova-plugin-badge" for ios
        Adding cordova-plugin-badge to package.json
        Saved plugin info for "cordova-plugin-badge" to config.xml
        Discovered plugin "cordova-plugin-console" in config.xml. Adding it to the project
        Installing "cordova-plugin-console" for ios
        Adding cordova-plugin-console to package.json
        Saved plugin info for "cordova-plugin-console" to config.xml
        Discovered plugin "cordova-plugin-device" in config.xml. Adding it to the project
        Installing "cordova-plugin-device" for ios
        Adding cordova-plugin-device to package.json
        Saved plugin info for "cordova-plugin-device" to config.xml
        Discovered plugin "cordova-plugin-google-analytics" in config.xml. Adding it to the project
        Installing "cordova-plugin-google-analytics" for ios
        Adding cordova-plugin-google-analytics to package.json
        Saved plugin info for "cordova-plugin-google-analytics" to config.xml
        Discovered plugin "cordova-plugin-splashscreen" in config.xml. Adding it to the project
        Installing "cordova-plugin-splashscreen" for ios
        Adding cordova-plugin-splashscreen to package.json
        Saved plugin info for "cordova-plugin-splashscreen" to config.xml
        Discovered plugin "cordova-plugin-statusbar" in config.xml. Adding it to the project
        Installing "cordova-plugin-statusbar" for ios
        Adding cordova-plugin-statusbar to package.json
        Saved plugin info for "cordova-plugin-statusbar" to config.xml
        Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
        Installing "cordova-plugin-whitelist" for ios
        Adding cordova-plugin-whitelist to package.json
        Saved plugin info for "cordova-plugin-whitelist" to config.xml
        Discovered plugin "cordova-plugin-youtube-video-player" in config.xml. Adding it to the project
        Installing "cordova-plugin-youtube-video-player" for ios
        Adding cordova-plugin-youtube-video-player to package.json
        Saved plugin info for "cordova-plugin-youtube-video-player" to config.xml
        Discovered plugin "cordova-sqlite-storage" in config.xml. Adding it to the project
        Installing "cordova-sqlite-storage" for ios
        installing external dependencies via npm
        npm install of external dependencies ok
        Adding cordova-sqlite-storage to package.json
        Saved plugin info for "cordova-sqlite-storage" to config.xml
        Discovered plugin "ionic-plugin-keyboard" in config.xml. Adding it to the project
        Installing "ionic-plugin-keyboard" for ios
        Adding ionic-plugin-keyboard to package.json
        Saved plugin info for "ionic-plugin-keyboard" to config.xml
        Discovered plugin "phonegap-plugin-push" in config.xml. Adding it to the project
        Installing "phonegap-plugin-push" for ios
        Adding phonegap-plugin-push to package.json
        Saved plugin info for "phonegap-plugin-push" to config.xml
        **Error: Could not parse project.pbxproj: SyntaxError: Expected "/*", "//", or "{" but "<" found.**
        
`
platform and plugins are added successfully but on running **ionic cordova build ios** it throws the following error:

`Appzuis-Mac-mini:moyoex Appzui$ ionic cordova build ios
[INFO] Running app-scripts build: --platform ios --target cordova
       
[14:49:35]  build dev started ... 
[14:49:35]  clean started ... 
[14:49:35]  clean finished in 28 ms 
[14:49:35]  copy started ... 
[14:49:35]  transpile started ... 
[14:49:48]  transpile finished in 12.86 s 
[14:49:48]  preprocess started ... 
[14:49:48]  deeplinks started ... 
[14:49:48]  deeplinks finished in 95 ms 
[14:49:48]  preprocess finished in 96 ms 
[14:49:48]  webpack started ... 
[14:49:49]  copy finished in 14.22 s 
[14:50:04]  webpack finished in 16.59 s 
[14:50:04]  sass started ... 
[14:50:07]  sass finished in 2.23 s 
[14:50:07]  postprocess started ... 
[14:50:07]  removed unused font files 
[14:50:07]  postprocess finished in 93 ms 
[14:50:07]  lint started ... 
[14:50:07]  build dev finished in 32.11 s 
> ionic cordova prepare
> cordova prepare
✖ Running command - failed!
[ERROR] An error occurred while running cordova prepare (exit code 1):

        
        Error: Could not parse project.pbxproj: SyntaxError: Expected "/*", "//", or "{" but "<" found.

`

Additional info:
IOS version: 10.12.6
xcode version: 8.3.3
ionic info:
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.3.0

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1 
    Node              : v6.10.3
    npm               : 3.10.10 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 

this issue occurs while adding phonegap-plugin-push plugin. If I run ionic cordova build ios 
 without this plugin installed on the system, it builds successfully. It would be great if someone can help me in fixing this issue. 
Thanks

**Comment by pawan-mittal** [comment] 2017-09-07 17:29
I am also facing same issue. Any fix for this. Please provide some solution to it.

**Comment by macdonst** [comment] 2017-09-07 19:47
@chandu193 @pawan-mittal I can't reproduce this in my limited test. You'd be better off opening this on Ionic forums.

**Closed by macdonst** 2017-09-07 19:47 UTC
Labels: ionic, ios, question

**Comment by pawan-mittal** [comment] 2017-09-08 07:48
@chandu193 is it fixed for you ?

**Comment by pawan-mittal** [comment] 2017-09-08 08:52
After uninstalling CocoaPods and re-installing it with latest version solved issue for me. 
Thanks @macdonst for confirmation.
