### ISSUE TITLE
The .on('notification') event is not being called on IOS.

### ISSUE THREAD

**Issue by gs-sramesh** [phonegap/phonegap-plugin-push#1629] opened 2017-03-06 05:49 UTC
### Expected Behaviour
The ```.on('notification')``` method should be called when user clicks on a notification on IOS devices.

### Actual Behaviour
The method, mentioned above  is not being called on IOS devices.

### Reproduce Scenario (including but not limited to)

Send a push to IOS device. The notification appears on the device. Click on it and ```.on('notification')``` is not called. Just opens up the app and goes to home screen.

#### Steps to Reproduce 

```
// Client side -- Register for push on IOS device everytime the app launches and resumes.

PushNotification.init({
          android: {
            senderID: "mySenderId",
            forceShow: true,
            "icon": "icon",
            "clearNotifications": false

          },
          ios: {
              senderID: "mySenderId",
              gcmSandbox: false,
              alert: "true",
              badge: "true",
              sound: "true"
          }
});
```

```
  // On the server side, send the following JSON from FCM
{
  "notification": {
	"title": "Test Notification",
        "body": "This offer expires at 11:30 or whatever"	
	},
  "data":{
        "extra": {
          "url": "someurl"
        }
    },
  "to": "$someid"
}

```

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

All versions of IOS

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Works well on android

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.5.0
    cordova platform version android           4.3.1        

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.9.4

#### Sample Push Data Payload

```
{
  "notification": {
	"title": "Test Notification",
        "body": "This offer expires at 11:30 or whatever"	
	},
  "data":{
        "extra": {
          "url": "someurl"
        }
    },
  "to": "$someid"
}
```
#### Sample Code that illustrates the problem
  NA
#### Logs taken while reproducing problem

No errors.

**Comment by macdonst** [comment] 2017-03-06 12:05
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by gs-sramesh** [comment] 2017-03-06 13:36
@macdonst I am unable to reopen the issue. I have updated the question to match the guidelines.

**Comment by macdonst** [comment] 2017-03-06 13:39
@gs-sramesh when do your register the `on('notification')` event handler? I wonder if it is a race condition.

**Comment by gs-sramesh** [comment] 2017-03-06 13:42
I register it on ```deviceready```. 

```
$ionicPlatform.ready(function() {
  // Registering the device here.
})

**Comment by fredgalvao** [comment] 2017-03-06 13:50
Make sure you're registering and applying the listener on the same javascript thread (no assync context between them), and try again (if that's not already the case).

**Comment by gs-sramesh** [comment] 2017-03-06 13:51
I register on ```window``` object and listen to it on ```window``` object. There is async specific operation that I am doing.

**Comment by Jarvey** [comment] 2017-03-06 21:26
@macdonst there are multiple issues open related to this behaviour, I'm als one of them that have the same problem that the on('notification') event handler is not triggered on iOS and Android. I tried different payloads followed different instruction suggested on other open issues, non of them work.

**Comment by fredgalvao** [comment] 2017-03-06 21:54
@Jarvey and @gs-sramesh , can both of you please post the complete code that shows where the `.init()` and `.on('notification')` are called?
Something like this:
```js
window.whatever = function () {
	prepareSomeData();

	var push = PushNotification.init({
		android: {
			senderID: "12345679"
		},
		browser: {
			pushServiceURL: 'http://push.api.phonegap.com/v1/push'
		},
		ios    : {
			alert: "true",
			badge: true,
			sound: 'false'
		},
		windows: {}
	});

	maybeDoSomethingInBetween();

	push.on('registration', function (data) {
		console.log(data.registrationId);
	});

	doSomeOtherStuff();
}

$ionicPlatform.ready(function () {
	window.whatever();
});
```

I just want to check if the `init` part and the `.on()` part are distant from each other or if both are in a strange spot during runtime.

**Comment by gs-sramesh** [comment] 2017-03-07 07:20
@fredgalvao 

```
 // This is my app.js file
 $ionicPlatform.ready(function () {
        // Some processing here!
        
       // Register device for push
	pushService.regForPush()

      // Register for push even on resume
      document.addEventListener("resume", function() {
        pushService.regForPush()
      }, false);
});
```

```
  // This is my pushService file
   window.pushPlugin = PushNotification.init({
          android: {
            senderID: "mySenderId",
            forceShow: true,
            "icon": "icon",
            "iconColor": "#fffff",
            "clearNotifications": false

          },
          ios: {
              senderID: "mySenderId",
              gcmSandbox: false,
              alert: "true",
              badge: "true",
              sound: "true"
          },
        });

        window.pushPlugin.on('registration', function(data) {
          deferred.resolve(data.registrationId);
        });

        window.pushPlugin.on('notification', function(data) {
          // This never gets called
          navigateFromColdStart(data.additionalData.extra);
        });

        window.pushPlugin.on('error', function(e) {
          deferred.reject(e);
        });
```

In my console I see, that ```window.pushPlugin``` is defined and all the methods exist. The same code works perfectly on ```android``` but with different JSON format for android. But for ```IOS``` this wont work.

**Comment by fredgalvao** [comment] 2017-03-07 07:57
Can you get the logs from XCode? Also, what is the JSON payload/notification you're sending exactly?

As a side note, I don't think you need to re-register when the app `resume`s.

**Comment by gs-sramesh** [comment] 2017-03-07 08:37
I am testing on a simulator right now. I dont have access to an actual device right now. Previously I did post the logs on a different issues and logs seem to be fine. No errors. 

The exact JSON payload I am sending is:

```
{
	"notification": {
	"title": "You have a new message",
        "body": "Hello there, Hi"
	},
	"data":{
          "extra": {
              "url": "m2e://det?id=V6oLws5kr",
          }     
    },
  "to": "$dTWdULfXZxM:APA91bZeKB0CLjNLDgxSUNt6ILom_kxiKvHWvigmA8mNV8QsG0A_1i-ARWD5gMCGR_gWUctsoZNBmS1j2fgjKgxcpZccO_1v3eVFrV1zGRjqlJxxxxxxxxx"
}
```

**Comment by Jarvey** [comment] 2017-03-07 09:06
To make it easy I removed all functions and code from the .run function in my app.
I tested it on device with the code below.

On app startup the push.on('registration' handler is triggered and a alert shows me the devicetoken object.

I have the app open in the foreground and send 4 different payloads.
push.on('notification' has never triggered.

````javascript
.run(function($rootScope, $localStorage, $ionicPlatform) {
    $ionicPlatform.ready(function() {
        var push = PushNotification.init({
	     ios: {
	          alert: "true",
	          badge: "true",
	          sound: "true",
	          clearBadge: "false"
	     },
	     android: {
	           senderID: "157226324649",
	           sound: "true",
	           vibrate: "false",
	           clearBadge: "false",
	           iconColor: "#34363a"
	     }
        });
		
        push.on('registration', function(data) {
	     //store devicetoken
	        alert(data);
	 });
	  
	 push.on('notification', function(data) {
	     alert('notification received');
         });
		
	push.on('error', function(e) {
             // e.message
             alert('notification error')
	});	
  }); //ionic ready closing tag
});
````

## xCode app startup console output:
[3001:1227857] Apache Cordova native platform version 4.3.1 is starting.
[3001:1227857] Multi-tasking -> Device: YES, App: YES
[3001:1227857] Using UIWebView
[3001:1227857] [CDVTimer][handleopenurl] 0.055015ms
[3001:1227857] [CDVTimer][intentandnavigationfilter] 1.605988ms
[3001:1227857] [CDVTimer][gesturehandler] 0.042975ms
[3001:1227857] [CDVTimer][splashscreen] 28.846025ms
[3001:1227857] [CDVTimer][statusbar] 7.822990ms
[3001:1227857] [CDVTimer][keyboard] 0.794053ms
[3001:1227857] [CDVTimer][threedeetouch] 0.068009ms
[3001:1227857] [CDVTimer][TotalPluginStartup] 39.763033ms
[3001:1227857] createNotificationChecker
[3001:1227857] not coldstart
[3001:1227857] active
[3001:1227857] PushPlugin skip clear badge
[3001:1227857] Resetting plugins due to page load.
[3001:1227857] Finished load of: file:///patch to indexfile of app
[3001:1227896] Push Plugin register called
[3001:1227896] PushPlugin.register: setting badge to false
[3001:1227896] PushPlugin.register: clear badge is set to 0
[3001:1227896] PushPlugin.register: better button setup
[3001:1227896] GCM Sender ID (null)
[3001:1227896] Using APNS Notification
[3001:1227857] Push Plugin register success: <long code 12345...>
[3001:1227894] Push Plugin register called
[3001:1227894] PushPlugin.register: setting badge to false
[3001:1227894] PushPlugin.register: clear badge is set to 0
[3001:1227894] PushPlugin.register: better button setup
[3001:1227894] GCM Sender ID (null)
[3001:1227894] Using APNS Notification
[3001:1227857] Push Plugin register success: <long code 12345...>
[3001:1227924] WF: === Starting WebFilter logging for process Teaming
[3001:1227924] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
[3001:1227924] WF: _WebFilterIsActive returning: NO


## Test Payload 1:
````javascript
{
    "aps": {
        "alert": {
	"title": "Test notification",
	"body": "hello this is a test"
    }
    "badge": 1,
    "sound": "bikeringer.wav",
    "payload": {
    "channel": 12345,
        "profile": "54321",
	"categorie_type": "test-category"
    }
  }
}
````

###  xCode console output:
[3001:1227857] didReceiveNotification with fetchCompletionHandler
[3001:1227857] app active
[3001:1227857] Notification received
[3001:1227857] Push Plugin key: payload
[3001:1227857] Push Plugin key: alert
[3001:1227857] Push Plugin key: badge
[3001:1227857] Push Plugin key: sound


## Test Payload 2:
````javascript
{
    "aps": {
        "alert": "Test notification",
    }
}
````

### xCode console output:
[3001:1227857] didReceiveNotification with fetchCompletionHandler
[3001:1227857] app active
[3001:1227857] Notification received
[3001:1227857] Push Plugin key: alert


## Test Payload 3:
````javascript
{
    "aps": {
        "data": "Test notification",
        "badge": 1
     }
}
````

### xCode console output:
[3001:1227857] didReceiveNotification with fetchCompletionHandler
[3001:1227857] app active
[3001:1227857] Notification received
[3001:1227857] Push Plugin key: badge
[3001:1227857] Push Plugin key: data

**Comment by macdonst** [comment] 2017-03-07 13:04
@gs-sramesh you can't test push on the iOS simulator you need a real device. I'm changing this to a docs issue.

**Comment by gs-sramesh** [comment] 2017-03-07 13:23
@macdonst I know that. I did test it on a real device. My previous comment I just mentioned that I dont have real device with me right now.

**Comment by Jarvey** [comment] 2017-03-08 07:40
@macdonst  @fredgalvao any idea why we and others are having problems with the .on('notification') handler.

**Comment by gs-sramesh** [comment] 2017-03-12 10:10
@macdonst @fredgalvao @Jarvey Any solutions to this?

**Comment by macdonst** [comment] 2017-03-12 16:53
@gs-sramesh I can't fix what I can't reproduce. @fredgalvao asked for you to provide some logs from XCode in order to help diagnose what is going on and you haven't done that yet.

If I had to offer a wild ass guess which I'm loath to do without more details I refer you back to my initial comment from 6 days ago where I said it _"sounds like a race condition"_.  Looking at the code you posted but without logs to verify my guess here is what I think is happening.

1. First time the app starts you get to (A) and the app successfully registers with the remote push service.
2. Your app is put into the back ground.
3. You send a push to the device and the end users clicks on it in the notification shade.
4. This causes your app to `resume` which in turn fires the `resume` event at (B)
5. Your `resume` event handler calls your ` pushService.regForPush()` method at (C)
6. At (D) you are re-registering with the remote push service. This is recreating the PushNotification object which will remove all your event listeners as [per this line of code](https://github.com/phonegap/phonegap-plugin-push/blob/master/www/push.js#L18) 
7. Finally a new event listener for `notification` is setup at (E) but by that time it is probably too late and the native side has already tried and failed to deliver the push to the Javascript side.

```
// This is my app.js file
 $ionicPlatform.ready(function () {
        // Some processing here!
        
       // Register device for push
	pushService.regForPush() // (A)

      // Register for push even on resume
      document.addEventListener("resume", function() { // (B)
        pushService.regForPush() // (C)
      }, false);
});

// This is my pushService file
   window.pushPlugin = PushNotification.init({ // (D)
          android: {
            senderID: "mySenderId",
            forceShow: true,
            "icon": "icon",
            "iconColor": "#fffff",
            "clearNotifications": false

          },
          ios: {
              senderID: "mySenderId",
              gcmSandbox: false,
              alert: "true",
              badge: "true",
              sound: "true"
          },
        });

        window.pushPlugin.on('registration', function(data) {
          deferred.resolve(data.registrationId);
        });

        window.pushPlugin.on('notification', function(data) { (E)
          // This never gets called
          navigateFromColdStart(data.additionalData.extra);
        });

        window.pushPlugin.on('error', function(e) {
          deferred.reject(e);
        });
```

My blind recommendation in this case is to remove:


```
      // Register for push even on resume
      document.addEventListener("resume", function() { // (B)
        pushService.regForPush() // (C)
      }, false);
```

from your `$ionicPlatform.ready` function.

**Comment by fredgalvao** [comment] 2017-03-12 23:21
Complementing what @macdonst said, which goes side-by-side with my suspicion of the `resume` re-registration, what I was suspecting was an assync context inbetween the plugin initialization and the `notification` event registration, but it seems none of you are going through that specific issue (according to the code provided by both of you).

That leaves me with 2 possible explanations:
- certificate/provisioning profile issues (this has been the case, I'd say, 80% of the time people didn't get it working). However, IIRC the code would fail sooner than that if it was caused by certificates (so most probably not it).
- malformed payload (more on this later)

### Payloaded with issues

I'll ask both of you to read (or re-read) the topics and examples used on [the docs here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#gcm-and-additional-data). If, after re-validating those details (GCM on iOS is a mess), and removing the `resume` code, the issue persists, then we have a real problem.

**Comment by macdonst** [comment] 2017-03-22 23:30
Closing for inactivity and the suggestion to remove the init call on resume.

**Closed by macdonst** 2017-03-22 23:30 UTC
Labels: docs, ios

**Comment by joshsirota** [comment] 2017-09-26 19:36
Was this ever fixed? I'm having exactly the same issue (native side receives and processes notification, but my javascript-side notification handler is never called). I don't have any of this "resume" business, just straightforward calls.

**Comment by srameshr** [comment] 2017-09-27 04:24
@joshsirota I migrated my app to react native :1st_place_medal:

**Comment by manojsingh047** [comment] 2018-02-20 16:16
Same Issue.
