### ISSUE TITLE
App with phonegap-plugin-push won't build if bitcode is enabled

### ISSUE THREAD

**Issue by panaggio** [phonegap/phonegap-plugin-push#697] opened 2016-03-11 19:39 UTC
### Expected Behaviour

App should build properly using bitcode.

### Actual Behaviour

App won't build if bitcode is enable (and I can't disable it because I'm building a watch app).

#### Steps to Reproduce 

Create cordova project, add ios platform, add push plugin, run `cordova prepare`, open project on Xcode, create watch app target, enable bitcode on all targets.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 8+, Watch OS 2

Build target used: iPhone 5 + Apple Watch

#### Logs taken while reproducing problem

```
ld: '<...>/Plugins/phonegap-plugin-push/GCM/Libraries/libGGLCloudMessaging.a(GGLContext+CloudMessaging.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by macdonst** [comment] 2016-03-11 23:48
Duplicate of #446

**Closed** 2016-03-11 23:48 UTC
Labels: duplicate
