### ISSUE TITLE
Application crash on notification

### ISSUE THREAD

**Issue by Alphatiger** [phonegap/phonegap-plugin-push#1917] opened 2017-08-24 08:35 UTC
### Expected Behaviour
After sucessfull regsitration with FCM (plugin version 2.0) got registration id, app should recieve notification
### Actual Behaviour
app crashes whenever notification is sent from FCM console 

#### Steps to Reproduce 
Install latest version
Get registration id
send notification
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
ANDROID 6.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
SAMSUNG
#### Cordova CLI version and cordova platform version
CORDOVA CLI 7.0
CORDOVA ANDROID 6.2.3
 

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.0

**Comment by macdonst** [comment] 2017-08-24 18:17
@Alphatiger can you reproduce the problem while running `adb logcat` to capture the crash?

**Comment by Alphatiger** [comment] 2017-08-25 11:23
Below is the Log
*************************************
08-25 16:51:18.231: E/AndroidRuntime(15392): FATAL EXCEPTION: main
08-25 16:51:18.231: E/AndroidRuntime(15392): Process: XXX.XXX.XXXX, PID: 15392
08-25 16:51:18.231: E/AndroidRuntime(15392): java.lang.NoSuchMethodError: com.google.firebase.iid.zzq.zzJU
08-25 16:51:18.231: E/AndroidRuntime(15392): 	at com.google.firebase.messaging.FirebaseMessagingService.zzn(Unknown Source)
08-25 16:51:18.231: E/AndroidRuntime(15392): 	at com.google.firebase.iid.zzb.onStartCommand(Unknown Source)
08-25 16:51:18.231: E/AndroidRuntime(15392): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2907)
08-25 16:51:18.231: E/AndroidRuntime(15392): 	at android.app.ActivityThread.access$2100(ActivityThread.java:151)
08-25 16:51:18.231: E/AndroidRuntime(15392): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1439)
08-25 16:51:18.231: E/AndroidRuntime(15392): 	at android.os.Handler.dispatchMessage(Handler.java:110)
08-25 16:51:18.231: E/AndroidRuntime(15392): 	at android.os.Looper.loop(Looper.java:193)
08-25 16:51:18.231: E/AndroidRuntime(15392): 	at android.app.ActivityThread.main(ActivityThread.java:5333)
08-25 16:51:18.231: E/AndroidRuntime(15392): 	at java.lang.reflect.Method.invokeNative(Native Method)
08-25 16:51:18.231: E/AndroidRuntime(15392): 	at java.lang.reflect.Method.invoke(Method.java:515)
08-25 16:51:18.231: E/AndroidRuntime(15392): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
08-25 16:51:18.231: E/AndroidRuntime(15392): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
08-25 16:51:18.231: E/AndroidRuntime(15392): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by Alphatiger** [comment] 2017-08-25 11:38
Hi

I have been using cordova-admobpro-firebase which was mentioned as compatible with FCM based plugins.

Once admobpro firebase plugin is removed, phonegap push plugin  is working properly.

let me know if this bug should be closed or some changes can be done inside this plugin itself.

**Comment by macdonst** [comment] 2017-08-26 19:05
@Alphatiger I don't think the two plugins are currently compatible. Probably need to resolve #1718 first before this can be tackled.

**Comment by josiahbryan** [comment] 2017-09-07 19:40
:+1:  This happens for me, too. However, I'm not using the cordova-admobpro-firebase plugin.

When my app crashed on my Android 8.0 device with the 2.0 push plugin, I was able to capture this stack trace via the Google Play Console reporting dashboard.  At first blush, it looks similar to the stack trace above, but I figured I'd include it here just incase.

```
java.lang.NoSuchMethodError: No static method zzJU()Lcom/google/firebase/iid/zzq; in class Lcom/google/firebase/iid/zzq; or its super classes (declaration of 'com.google.firebase.iid.zzq' appears in /data/app/com.vyalux.filos-2/base.apk)
	at com.google.firebase.messaging.FirebaseMessagingService.zzn(Unknown Source:0)
	at com.google.firebase.iid.zzb.onStartCommand(Unknown Source:13)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3539)
	at android.app.ActivityThread.-wrap20(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```

**Comment by macdonst** [comment] 2017-09-07 19:53
@Alphatiger @josiahbryan can you let me know what the dependencies section of your `platforms/android/build.gradle` file looks like? For instance mine is:

```
dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    debugCompile(project(path: "CordovaLib", configuration: "debug"))
    releaseCompile(project(path: "CordovaLib", configuration: "release"))
    compile "com.android.support:support-v13:25.1.0"
    compile "me.leolin:ShortcutBadger:1.1.17@aar"
    compile "com.google.firebase:firebase-messaging:11.0.1"
    // SUB-PROJECT DEPENDENCIES END
}
```

**Comment by josiahbryan** [comment] 2017-09-07 19:55
Gladly! Except...using Phone Gap Build ...any idea how to get at the `build.gradle` from PGB?

**Comment by macdonst** [comment] 2017-09-07 19:57
@josiahbryan uh, you can't. I suspect it is an issue where more than one plugin is including Play Services/FCM and it is causing issues. Can you list which plugins you are using instead?

**Comment by josiahbryan** [comment] 2017-09-07 20:02
Here's the table of plugins from Phone Gap Build that I'm using. Note it shows the push plugin 1.9.0 because I just rebuilt again because 1.9.0 does not crash. The crash does happen with this same plugin list, just with the latest push plugin ver from npm instead of 1.9.

```
Plugin | Source | Version | Installed | Latest | Platforms
-- | -- | -- | -- | -- | --
https://github.com/vyalux/Toast-PhoneGap-Plugin.git | git | * | d5c7688 | n/a | android,ios,winphone
https://github.com/tomloprod/cordova-plugin-headercolor.git | git | * | 0dd0af0 | n/a | android,ios,winphone
https://github.com/dpa99c/cordova-android-play-services-gradle-release | git | * | 6c040f7 | n/a | android,ios,winphone
cordova-background-geolocation-lt | npm | * | 2.8.3 | n/a | android,ios,winphone
cordova-plugin-battery-status | npm | * | 1.2.4 | n/a | android,ios,winphone
cordova-plugin-camera | npm | * | 2.4.1 | n/a | android,ios,winphone
cordova-plugin-console | npm | * | 1.0.7 | n/a | android,ios,winphone
cordova-plugin-contacts | npm | * | 2.3.1 | n/a | android,ios,winphone
cordova-plugin-device | npm | * | 1.1.6 | n/a | android,ios,winphone
cordova-plugin-device-motion | npm | * | 1.2.5 | n/a | android,ios,winphone
cordova-plugin-device-orientation | npm | * | 1.0.7 | n/a | android,ios,winphone
cordova-plugin-dialogs | npm | ~1.3.3 | 1.3.3 | n/a | android,ios,winphone
cordova-plugin-file | npm | * | n/a | n/a | android,ios,winphone
cordova-plugin-file-transfer | npm | * | 1.6.3 | n/a | android,ios,winphone
cordova-plugin-geolocation | npm | * | 2.4.3 | n/a | android,ios,winphone
cordova-plugin-globalization | npm | * | 1.0.7 | n/a | android,ios,winphone
cordova-plugin-inappbrowser | npm | * | 1.7.1 | n/a | android,ios,winphone
cordova-plugin-media | npm | * | 3.0.1 | n/a | android,ios,winphone
cordova-plugin-media-capture | npm | * | 1.4.3 | n/a | android,ios,winphone
cordova-plugin-network-information | npm | * | 1.3.3 | n/a | android,ios,winphone
cordova-plugin-splashscreen | npm | * | 4.0.3 | n/a | android,ios,winphone
cordova-plugin-statusbar | npm | * | 2.2.3 | n/a | android,ios,winphone
cordova-plugin-vibration | npm | * | 2.1.5 | n/a | android,ios,winphone
cordova-plugin-whitelist | npm | * | 1.3.2 | n/a | android,ios,winphone
https://github.com/vyalux/secondary-icon | git | * | 995869d | n/a | android,ios,winphone
phonegap-plugin-push | npm | ~1.9.0 | 1.9.4 | n/a | android,ios,winphone
uk.co.workingedge.phonegap.plugin.launchnavigator | npm | * | 4.0.4 | n/a | android,ios,winphone

```

**Comment by macdonst** [comment] 2017-09-08 00:20
@josiahbryan I'd drop `cordova-android-play-services-gradle-release` and upgrade to 2.0.0 and it probably will work. That plugin will include a play services that will conflict with this plugin. You shouldn't need it anymore.

**Comment by josiahbryan** [comment] 2017-09-11 00:18
@macdonst  Thanks, I'll try that next time we re-build!

**Comment by totiherms** [comment] 2017-09-29 11:29
same crash for me when a notification is received:

java.lang.NoSuchMethodError: No static method zzJU()Lcom/google/firebase/iid/zzq; in class Lcom/google/firebase/iid/zzq; or its super classes (declaration of 'com.google.firebase.iid.zzq' appears in /data/app/com.flsida.avhis-1/base.apk)
                                                                    at com.google.firebase.messaging.FirebaseMessagingService.zzn(Unknown Source)
                                                                    at com.google.firebase.iid.zzb.onStartCommand(Unknown Source)
                                                                    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3209)
                                                                    at android.app.ActivityThread.-wrap17(ActivityThread.java)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1586)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                    at android.os.Looper.loop(Looper.java:207)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5728)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

Pluguins list:

com.synconset.imagepicker 2.1.8 "ImagePicker"
cordova-opentok-android-permissions 1.0.0 "Cordova Opentok/WebRTC Android Permissions"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-health 1.0.0 "Cordova Health"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-whitelist 1.3.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.0.0 "PushPlugin"

any ideas?

**Comment by yodemo** [comment] 2017-10-02 03:48
Second that, I have the same issue.

**Comment by graphefruit** [comment] 2017-10-10 13:20
Having the same issue.
```phonegap-plugin-push 2.0.0 "PushPlugin"``
Crash:
```

10-11 00:12:52.076 11937 11937 E AndroidRuntime: java.lang.NoSuchMethodError: No static method zzJU()Lcom/google/firebase/iid/zzq; in class Lcom/google/firebase/iid/zzq; or its super classes (declaration of 'com.google.firebase.iid.zzq' appears in /data/app/com.test.app-1/base.apk)

10-11 00:12:52.076 11937 11937 E AndroidRuntime: 	at com.google.firebase.messaging.FirebaseMessagingService.zzn(Unknown Source)

10-11 00:12:52.076 11937 11937 E AndroidRuntime: 	at com.google.firebase.iid.zzb.onStartCommand(Unknown Source)
```

dependencies:
```
dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    debugCompile(project(path: "CordovaLib", configuration: "debug"))
    releaseCompile(project(path: "CordovaLib", configuration: "release"))
    compile "com.google.android.gms:play-services-analytics:11.0.+"
    compile "com.android.support:support-v13:25.1.0"
    compile "me.leolin:ShortcutBadger:1.1.17@aar"
    compile "com.google.firebase:firebase-messaging:11.0.1"
    compile "com.android.support:support-v4:24.1.1+"
    // SUB-PROJECT DEPENDENCIES END
}
```

Any ideas?

**Comment by joakimsoren** [comment] 2017-10-20 09:50
Had the same problem that the application crashed when receiving push after upgrading to phonegap 2.0.0. I solved it by installing cordova-plugin-fcm. `cordova plugin add cordova-plugin-fcm`. Hope that helps!
`

**Comment by macdonst** [comment] 2017-11-27 21:01
Generally this is being caused when two plugins are using different versions of FCM. Now that we have make changes for issue #1718 we should be able to pin the same FCM version for all plugins.

**Comment by macdonst** [comment] 2018-02-12 15:40
This is a duplicate of #2129. Please try the suggested work around: https://github.com/phonegap/phonegap-plugin-push/issues/2129#issuecomment-357669732

and comment on #2129 to let me know that it works.

**Closed by macdonst** 2018-02-12 15:40 UTC
Labels: android, duplicate, question
