### ISSUE TITLE
Cannot add platform if app name includes special characters

### ISSUE THREAD

**Issue by SalRocco** [phonegap/phonegap-plugin-push#1658] opened 2017-03-30 12:59 UTC
### Expected Behaviour
Successful platform add

### Actual Behaviour
```
test-ionic-one git:(develop) : ionic platform add ios               
Adding ios project...


Creating Cordova project for the iOS platform:


	Path: platforms/ios

	Package: com.ionicframework.xxxx426134

	**Name: test-ionic&one**

iOS project created with cordova-ios@4.3.1


**Installing "phonegap-plugin-push" for ios**

     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   

     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

   100 1085k    0 1085k    0     0  1500k      0 --:--:-- --:--:-- --:--:-- 1499k


     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current


                                    Dload  Upload   Total   Spent    Left  Speed
   

     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

   100 1596k    0 1596k    0     0  2006k      0 --:--:-- --:--:-- --:--:-- 2005k


     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                    Dload  Upload   Total   Spent    Left  Speed
   

     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

   100  119k  100  119k    0     0   520k      0 --:--:-- --:--:-- --:--:--  523k


     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   

     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

   100 1850k  100 1850k    0     0  2345k      0 --:--:-- --:--:-- --:--:-- 2342k


     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   

     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

   100 13396  100 13396    0     0  75079      0 --:--:-- --:--:-- --:--:-- 75258


     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   

   100 1171k  100 1171k    0     0  1988k      0 --:--:-- --:--:-- --:--:-- 1988k


Failed to install 'phonegap-plugin-push':Error: pod: Command failed with exit code 1 Error output:
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100 1085k    0 1085k    0     0  1500k      0 --:--:-- --:--:-- --:--:-- 1499k
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100 1596k    0 1596k    0     0  2006k      0 --:--:-- --:--:-- --:--:-- 2005k
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100  119k  100  119k    0     0   520k      0 --:--:-- --:--:-- --:--:--  523k
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100 1850k  100 1850k    0     0  2345k      0 --:--:-- --:--:-- --:--:-- 2342k
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100 13396  100 13396    0     0  75079      0 --:--:-- --:--:-- --:--:-- 75258
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100 1171k  100 1171k    0     0  1988k      0 --:--:-- --:--:-- --:--:-- 1988k
    at ChildProcess.whenDone (/Users/XXXXXX/Desktop/XXXXXX/XXXXXX/test-ionic-one/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:513:12)


Error: pod: Command failed with exit code 1 Error output:
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100 1085k    0 1085k    0     0  1500k      0 --:--:-- --:--:-- --:--:-- 1499k
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100 1596k    0 1596k    0     0  2006k      0 --:--:-- --:--:-- --:--:-- 2005k
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100  119k  100  119k    0     0   520k      0 --:--:-- --:--:-- --:--:--  523k
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100 1850k  100 1850k    0     0  2345k      0 --:--:-- --:--:-- --:--:-- 2342k
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100 13396  100 13396    0     0  75079      0 --:--:-- --:--:-- --:--:-- 75258
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100 1171k  100 1171k    0     0  1988k      0 --:--:-- --:--:-- --:--:-- 1988k
```

#### Steps to Reproduce 
1) `ionic start --v2 test-ionic-one blank`
2) `cd test-ionic-one`
3) in config.xml change `<name>test-ionic-one</name>` into `<name>udemy-ionic&amp;one</name>`
4) `ionic serve` -> ctrl+c
5) `ionic plugin add phonegap-plugin-push`
6) `ionic platform add ios`

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
MacOS 10.12.1

#### Cordova CLI version and cordova platform version
cordova --version -> 6.5.0
cordova platform version ios -> 4.3.1

#### Plugin version
phonegap-plugin-push 1.10.0 "PushPlugin"

**Comment by jcesarmobile** [comment] 2017-03-30 13:11
Does it also happen if you don't add the plugin? 
I don't think the problem is the plugin, it's Cordova the one that doesn't allow special characters on the app name

**Comment by SalRocco** [comment] 2017-03-30 13:28
This don't happen without the plugin.

**Comment by macdonst** [comment] 2017-04-03 19:46
@SalRocco this may be an issue with cordova-ios. I'm looking into it.

**Comment by macdonst** [comment] 2017-04-03 22:31
@SalRocco this is an issue with Cordova iOS. Check out:

https://issues.apache.org/jira/browse/CB-12402
https://issues.apache.org/jira/browse/CB-12206

and has been fixed with this commit:

https://github.com/apache/cordova-ios/pull/288

and will be included with an upcoming cordova-ios release.

**Closed by macdonst** 2017-04-03 22:31 UTC
Labels: ios, question

**Comment by jefsteward** [comment] 2017-04-07 13:39
@macdonst hi, my config xml contain special character like ampersand. I understand the solution is in the next release. How can I use the current fixed commit cordova-ios? I am using ionic (Default is ionic platform add ios)

**Comment by macdonst** [comment] 2017-04-08 14:06
@jefsteward you can try adding the cordova-ios nightly.

`cordova platform add ios@nightly` 

should take care of that.
