### ISSUE TITLE
[iOS] Specific Action when app opened by clicking on push

### ISSUE THREAD

**Issue by ahlidap** [phonegap/phonegap-plugin-push#582] opened 2016-02-05 17:23 UTC
Hi,

as I'm using GCM to send push notifications to iOS, action buttons are not supported, so I'm trying to get my app to execute some function when it is opened by clicking on notification.

How can I do this?
I've read that I could do it on the success callback of the ```on('notification'``` event but it won't work.

If I put some code to execute on that callback and receive a push:

1.
--- a. If I click on push notification, my code will execute twice

2.
--- a. I open the app by click on app icon (code is executed once).
--- b. after close the app, I click on push. code is executed once again.

Is there any solution?
iOS 9 and phonegapBuild

**Comment by macdonst** [comment] 2016-02-07 15:13
@ahlidap so you want to know if the app was started by a push notification? Duplicate of #501.

**Closed by macdonst** 2016-02-07 15:13 UTC
Labels: duplicate

**Comment by Nick-lab** [comment] 2018-05-22 17:12
why not just add an implementation for 
```
if(notification.wasTapped){
    //run code here
}
```
