### ISSUE TITLE
WNS Channel URL not renew in background after several time with no open the app

### ISSUE THREAD

**Issue by gilvandev** [phonegap/phonegap-plugin-push#853] opened 2016-05-01 12:56 UTC
WNS provide to every app a Channel URL to address the notifications to every device with the app. But this URL expires every 30 days and...needs to renew! But isn't going on with the plugin...after 30 days without open the app, the Channel URL expires and the device doesn't receive push notifications.

It's possibel implement a backgroud task to renew this?
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Windows/Windows Phone 8.1 and Windows 10
#### Cordova CLI version and cordova platform version
    cordova --version                                    #6.1.1
#### Plugin version
    cordova plugin version | grep phonegap-plugin-push   #all versions

**Comment by rakatyal** [comment] 2016-05-02 18:34
@gilvandev: We are currently looking at ways to support background tasks through this plugin. Currently there doesn't seem to be a workaround for this issue. I can update you when we make any progress on this.

**Comment by macdonst** [comment] 2016-05-02 19:36
Duplicate of #264

**Closed by macdonst** 2016-05-02 19:36 UTC
Labels: duplicate, windows
