### ISSUE TITLE
Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']

### ISSUE THREAD

**Issue by shahdeep1989** [phonegap/phonegap-plugin-push#1910] opened 2017-08-19 19:16 UTC
When I am trying to prepare android build "cordova build android" it is going to fail. This happen only when I am installing phonegap-plugin-push (https://github.com/phonegap/phonegap-plugin-push) and cordova-plugin-mauron85-background-geolocation (https://github.com/mauron85/cordova-plugin-background-geolocation) together. If I will remove one plugin from this than it will build android successfully. But both together is not working. Detailed log for error has been provided below.

### Expected Behaviour
It should prepare android build successfully.

### Actual Behaviour
Android build getting failed

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 7.0.1
    cordova platform version android           # e.g. 6.2.3

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. latest on git (2.0.0)

#### Logs taken while reproducing problem
FAILURE: Build failed with an exception.

* Where:
Script '/Applications/MAMP/htdocs/Client'sProject/LimoLush/Bitbucket/Agent/limolushagentapp/platforms/android/phonegap-plugin-push/riderebelsagent-push.gradle' line: 38

* What went wrong:
A problem occurred evaluating root project 'android'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.64 secs
Error: /Applications/MAMP/htdocs/Client'sProject/LimoLush/Bitbucket/Agent/limolushagentapp/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script '/Applications/MAMP/htdocs/Client'sProject/LimoLush/Bitbucket/Agent/limolushagentapp/platforms/android/phonegap-plugin-push/riderebelsagent-push.gradle' line: 38

* What went wrong:
A problem occurred evaluating root project 'android'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by shyamal890** [comment] 2017-08-20 14:15
+1

**Comment by macdonst** [comment] 2017-08-20 14:53
This is a duplicate of #1718

**Closed by macdonst** 2017-08-20 14:53 UTC
Labels: duplicate

**Comment by Vickypr1902** [comment] 2018-05-22 07:29
![screenshot 151 _li](https://user-images.githubusercontent.com/37625636/40348016-e7741a1e-5dbf-11e8-973f-3b31d566401a.jpg)



```
import java.util.regex.Pattern

def doExtractStringFromManifest(name) {
    def manifestFile = file("AndroidManifest.xml")
    if (!manifestFile.exists()) {
      manifestFile = file("src/main/AndroidManifest.xml")
    }
    def pattern = Pattern.compile(name + "=\"(.*?)\"")
    def matcher = pattern.matcher(manifestFile.getText())
    matcher.find()
    return matcher.group(1)
}

android {
    defaultConfig {
        multiDexEnabled true
        applicationId = doExtractStringFromManifest("package")
    }
}

buildscript {
	repositories {
      jcenter()
			mavenLocal()
  }
  dependencies {
      classpath 'com.android.tools.build:gradle:+'
      classpath 'com.google.gms:google-services:3.0.0'
  }
}

// apply plugin: 'com.google.gms.google-services'
// class must be used instead of id(string) to be able to apply plugin from non-root gradle file
ext.postBuildExtras = {
// line 35
    apply plugin: com.google.gms.googleservices.GoogleServicesPlugin
//line35
}

```

**Comment by jcesarmobile** [comment] 2018-05-22 08:55
Please, don't comment on closed issues.

Also, your code is very old, current android-push.gradle no longer have those lines
