### ISSUE TITLE
Last Android SDK breaked push plugin again (Same as #909)

### ISSUE THREAD

**Issue by rafatol** [phonegap/phonegap-plugin-push#1319] opened 2016-10-25 19:19 UTC
With the last revision of Android SDK i can't start an existing app project anymore. Aparently the same problem of issue #909.

Platform: Android 6.0.1

Versions:
Cordova - 6.3.1
Cordova Platform Version - 5.1.1

Android SDK Extra revisions:
Android Support Repository - 39
Google Play Services - 37
Google Repository - 38

Logcat:

```
10-25 17:15:15.682 12918 12989 V SQLitePlugin: Android db implementation: Android-sqlite-connector (NDK)
10-25 17:15:15.687 12918 12991 V info    : Open sqlite db: /data/user/0/br.com.dynamicasoft.sicredi/databases/app.db
10-25 17:15:15.732 12918 12989 V PushPlugin: execute: action=init
10-25 17:15:15.787 12918 12993 V PushPlugin: execute: data=[{"android":{"senderID":"XXXXXXXXXXXX","icon":"pin"},"ios":{"alert":"true","badge":"true","sound":"true"}}]
10-25 17:15:15.797 12918 12993 V PushPlugin: execute: jo={"senderID":"XXXXXXXXXXXX","icon":"pin"}
10-25 17:15:15.797 12918 12993 V PushPlugin: execute: senderID=XXXXXXXXXXXX
10-25 17:15:15.812 12918 12918 I chromium: [INFO:CONSOLE(179)] "OPEN database: app.db - OK", source: file:///android_asset/www/plugins/cordova-sqlite-ext/www/SQLitePlugin.js (179)
10-25 17:15:15.867 12918 12993 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-4
10-25 17:15:15.867 12918 12993 E AndroidRuntime: Process: br.com.dynamicasoft.sicredi, PID: 12918
10-25 17:15:15.867 12918 12993 E AndroidRuntime: Theme: themes:{}
10-25 17:15:15.867 12918 12993 E AndroidRuntime: java.lang.NoSuchMethodError: No static method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Lcom/google/android/gms/common/util/zzx; or its super classes (declaration of 'com.google.android.gms.common.util.zzx' appears in /data/app/br.com.dynamicasoft.sicredi-1/base.apk)
10-25 17:15:15.867 12918 12993 E AndroidRuntime:        at com.google.android.gms.iid.zzd.zzeC(Unknown Source)
10-25 17:15:15.867 12918 12993 E AndroidRuntime:        at com.google.android.gms.iid.zzd.<init>(Unknown Source)
10-25 17:15:15.867 12918 12993 E AndroidRuntime:        at com.google.android.gms.iid.zzd.<init>(Unknown Source)
10-25 17:15:15.867 12918 12993 E AndroidRuntime:        at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
10-25 17:15:15.867 12918 12993 E AndroidRuntime:        at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
10-25 17:15:15.867 12918 12993 E AndroidRuntime:        at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:77)
10-25 17:15:15.867 12918 12993 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-25 17:15:15.867 12918 12993 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-25 17:15:15.867 12918 12993 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
10-25 17:15:15.872  2413  2709 W ActivityManager:   Force finishing activity br.com.dynamicasoft.sicredi/.MainActivity
10-25 17:15:15.932 12918 12918 D JsMessageQueue: Set native->JS mode to null
10-25 17:15:15.942 12918 12918 W cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 12918
```

Thanks ;-)

**Comment by macdonst** [comment] 2016-10-25 21:42
@rafatol seriously! Dammit Google, get you shit together. I'll go update my dependencies and try and reproduce. If I can I'll look into a work around.

**Comment by kiliankoller** [comment] 2016-10-26 07:20
Same problem here:
cordova@6.3.1
cordova-android@6.0.0
Android 7.0 SDK
Android Support Repository: 39
Google Play Services: 37
Google Repository: 38

```
              --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
                  Process: com.treefin.app, PID: 13490
                  java.lang.NoSuchMethodError: No static method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Lcom/google/android/gms/common/util/zzx; or its super classes (declaration of 'com.google.android.gms.common.util.zzx' appears in /data/app/com.treefin.app-1/base.apk)
                      at com.google.android.gms.iid.zzd.zzeC(Unknown Source)
                      at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                      at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                      at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
                      at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
                      at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:77)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                      at java.lang.Thread.run(Thread.java:761)
```

**Comment by tgsouto** [comment] 2016-10-26 12:42
Same problem here:
cordova@6.3.1
cordova-android@5.2.2
Android Support Repository: 39
Google Play Services: 37
Google Repository: 38

`E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-3
                  Process: br.com.test.app, PID: 1827
                  java.lang.NoSuchMethodError: No static method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Lcom/google/android/gms/common/util/zzx; or its super classes (declaration of 'com.google.android.gms.common.util.zzx' appears in /data/app/br.com.test.app-2/base.apk)
                      at com.google.android.gms.iid.zzd.zzeC(Unknown Source)
                      at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                      at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                      at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
                      at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
                      at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:77)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                      at java.lang.Thread.run(Thread.java:818)
`

**Comment by Mossito** [comment] 2016-10-26 21:45
I have the exact same problem, i can help testing if needed :)

E/AndroidRuntime(13293): FATAL EXCEPTION: pool-1-thread-3
E/AndroidRuntime(13293): Process: com.wuiti.wuiti, PID: 13293
E/AndroidRuntime(13293): java.lang.NoSuchMethodError: No static method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Lcom/google/android/gms/common/util/zzx; or its super classes (declaration of 'com.google.android.gms.common.util.zzx' appears in /data/app/com.wuiti.wuiti-2/base.apk)
E/AndroidRuntime(13293): 	at com.google.android.gms.iid.zzd.zzeC(Unknown Source)
E/AndroidRuntime(13293): 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
E/AndroidRuntime(13293): 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
E/AndroidRuntime(13293): 	at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
E/AndroidRuntime(13293): 	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
E/AndroidRuntime(13293): 	at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:75)
E/AndroidRuntime(13293): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(13293): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(13293): 	at java.lang.Thread.run(Thread.java:818)

**Comment by chris-armstrong** [comment] 2016-10-27 03:25
I've experienced the same issue and tracked it down to the Google Play Services library for GCM included in the plugin.xml. This line:
```
    <framework src="com.google.android.gms:play-services-gcm:9.0.2+"/>
```
causes an older version of the gcm library to be included. This version is quite old compared to the other Google Play Services libraries, and when newer Google Play Services libraries are included in the same binary, the app crashes on a stack trace similar to the above.

I've solved the problem in my application by forking the phonegap-push-plugin (I already use a fork of this for Intercom) and replacing the above line with a more flexible version spec e.g.:
```
    <framework src="com.google.android.gms:play-services-gcm:9.+"/>
```
which gets the latest 9.*.* library. There may be a better version spec that can at least say "use 9.0.2 or any minor+patch version greater than this" instead of just "use 9.0.*", which seems to be what the above specifies. I'm not familiar enough with Gradle versioning to know the correct answer here.

**Comment by hung-doan** [comment] 2016-10-27 06:26
Get the same issue here.
After update to the lastest version of Google Play Service (v 37) , It crash my app.

```
# Date: 2016-10-26T08:03:20Z
# OS Version: 6.0.1
# Device: Nexus 7
# RAM Free: 61.2%
# Disk Free: 69.9%

#0. Crashed: pool-1-thread-3: 0 0 0x0000000000000000
       at com.google.android.gms.iid.zzd.zzeC(Unknown Source)
       at com.google.android.gms.iid.zzd.<init>(Unknown Source)
       at com.google.android.gms.iid.zzd.<init>(Unknown Source)
       at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
       at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
       at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:77)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

--

Fatal Exception: java.lang.NoSuchMethodError: No static method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Lcom/google/android/gms/common/util/zzx; or its super classes (declaration of 'com.google.android.gms.common.util.zzx' appears in /data/app/vn.rims.vams.viettin-2/base.apk)
       at com.google.android.gms.iid.zzd.zzeC(Unknown Source)
       at com.google.android.gms.iid.zzd.<init>(Unknown Source)
       at com.google.android.gms.iid.zzd.<init>(Unknown Source)
       at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
       at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
       at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:77)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
	
#0. Crashed: pool-1-thread-3: 0 0 0x0000000000000000
       at com.google.android.gms.iid.zzd.zzeC(Unknown Source)
       at com.google.android.gms.iid.zzd.<init>(Unknown Source)
       at com.google.android.gms.iid.zzd.<init>(Unknown Source)
       at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
       at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
       at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:77)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by hung-doan** [comment] 2016-10-27 06:57
It works after I changed dependency to  com.google.android.gms:play-services-gcm:9.8.0

**Comment by tgsouto** [comment] 2016-10-27 11:53
Thanks @chris-armstrong, it works for me.

**Comment by gregavola** [comment] 2016-10-27 17:18
@chris-armstrong I have a very similar issue, but I use Intercom, but don't use push notifications. The app crashes on launch:

```FATAL EXCEPTION: IntentService[Intercom GCM Registration Service]
                                                            Process: com.XXXX.app, PID: 2807
                                                            java.lang.NoSuchMethodError: No static method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Lcom/google/android/gms/common/util/zzx; or its super classes (declaration of 'com.google.android.gms.common.util.zzx' appears in /data/app/com.XXX.app-1/base.apk)
                                                           ```

**Comment by macdonst** [comment] 2016-10-27 17:33
@hung-doan do you want to send a PR for me? Set the GCM to 9.8+ and it should take care of the problem. I'm currently speaking at a conference so it'll help me and everyone else out.

**Comment by hung-doan** [comment] 2016-10-28 00:56
@macdonst Sure, I'm glad to do that. 

PR is available https://github.com/phonegap/phonegap-plugin-push/pull/1323

**Comment by fredgalvao** [comment] 2016-10-30 20:50
For people who haven't solved this yet, you can reinstall the plugin from the github url and test it. The PR has been merged.

**Comment by macdonst** [comment] 2016-10-31 19:04
Anyone have a chance to test the update in master? I'd like to do a release today if I hear things are fixed.

**Comment by kiliankoller** [comment] 2016-10-31 19:08
Works great, thanks for fixing!

**Comment by macdonst** [comment] 2016-11-01 00:44
Released 1.8.4 with the fix.

**Closed by macdonst** 2016-11-01 00:44 UTC
Labels: android, bug

**Comment by neosekar** [comment] 2017-02-23 07:50
Get same issue here. I am using push plugin version is 1.9.1. Please help me in this.

**Comment by jcesarmobile** [comment] 2017-02-23 14:01
@neosekar just update to v1.9.4

**Comment by rockneverdies55** [comment] 2017-04-04 23:03
I had the same issue in v1.9.2 but updating to `v1.9.4` worked out.
