### ISSUE TITLE
Launch notification not received on iOS10

### ISSUE THREAD

**Issue by NoNameProvided** [phonegap/phonegap-plugin-push#1228] opened 2016-09-19 11:02 UTC
### Expected Behaviour

On iOS10 clicking on a notification opens the app and the plugin emits the clicked notification. 

### Actual Behaviour

App is opened, but the notification is not emitted.

#### Steps to Reproduce 

- Take a working push notification setup (with APN)
- Send a notification while the app is in the background
- Click the notification
- See that the notification is not emitted to the listeners. 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 10

#### Cordova CLI version and cordova platform version

Cordova version: 6.3.1
Cordova platform version:  ios 4.2.0

#### Plugin version

1.8.1

#### Sample Push Data Payload

```json
{
	"raw": {
		"title": "New Message!",
		"additionalData": {
			"foreground": false,
			"coldstart": false,
			"payload": {
				"customData": "Anything I want"
			}
		},
		"message": "You have received a new message request from Michael Apple."
	},
	"text": "You have received a new message request from Michael Apple.",
	"title": "New Message!",
	"app": {
		"asleep": true,
		"closed": false
	},
	"payload": {
		"customData": "Anything I want"
	}
}
```

#### Sample Code that illustrates the problem

This issue happens in an Ionic 2 app so the code is in Typescript, and I am using the ionic cloud wrapper around the plugin. 

```ts
// Part of PushService
// ...
public launchNotification: BehaviorSubject<IPushMessage> = new BehaviorSubject<IPushMessage>(undefined);
public notification: BehaviorSubject<IPushMessage> = new BehaviorSubject<IPushMessage>(undefined);
// ...
this.notificationSubscription = this.push.rx.notification().subscribe(this.handleRecievedNotification.bind(this));

handleRecievedNotification(message: IPushMessage) {
     console.debug('[PushService] Notification received.', message);
     this.notification.next(message);
     if( message.app.asleep || message.app.closed ) {
       this.launchNotification.next(message);
     }
   }
```

```ts
// app.ts
// ...
this.pushService.launchNotification.subscribe( message => {
    console.info('[App] App was started by clicking on a notification.', message);
});
```

This function never get triggered. Notification with `message.app.asleep = true` or `message.app.closed = true` are never received.

#### Logs taken while reproducing problem

Log from the NOT WORKING iPhone 6 when taping a notification while the app is in the background.

```
2016-09-19 12:59:57.637799 xxx[1837:544765] active
2016-09-19 12:59:57.638208 xxx[1837:544765] PushPlugin skip clear badge
```

Log from the WORKING older iPhone with the same notification: 

```
2016-09-19 12:57:45.690 xxx[222:17831] didReceiveNotification with fetchCompletionHandler
2016-09-19 12:57:45.690 xxx[222:17831] app in-active
2016-09-19 12:57:45.691 xxx[222:17831] just put it in the shade
2016-09-19 12:57:46.016 xxx[222:17831] active
2016-09-19 12:57:46.017 xxx[222:17831] PushPlugin skip clear badge
2016-09-19 12:57:46.018 xxx[222:17831] Notification received
2016-09-19 12:57:46.018 xxx[222:17831] Push Plugin key: alert
```

**Comment by macdonst** [comment] 2016-09-19 13:26
@NoNameProvided this is a duplicate of #1199 and I've release 1.8.2 to fix it.

**Closed by macdonst** 2016-09-19 13:26 UTC
Labels: duplicate

**Comment by NoNameProvided** [comment] 2016-09-19 14:05
Ohh, I haven't found that. Thanks!

**Comment by macdonst** [comment] 2016-09-19 15:27
@NoNameProvided any suggestions on how I can make it easier for people to find this information? I added the fixed issues the CHANGELOG but is there any other way you can think I can help find the answers?

**Comment by NoNameProvided** [comment] 2016-09-19 15:36
I think it's just my bad, I have searched the answers and I have found #1112 first. After I saw it's still open, I thought the issue have not been addressed yet. I should have look more carefully. :)

**Comment by macdonst** [comment] 2016-09-19 15:50
@NoNameProvided no problem, I'm always looking for a way to improve.
