### ISSUE TITLE
iOS sometimes incorrectly registers with FCM

### ISSUE THREAD

**Issue by kylemellander** [phonegap/phonegap-plugin-push#2543] opened 2018-09-07 15:51 UTC
### Expected Behaviour

When the iOS cordova app contains
```
	<key>IS_GCM_ENABLED</key>
	<false/>
```
in the GoogleService-Info.plist file, it should not register with FCM.

### Actual Behaviour

The app sometimes registers with both services.  When this happens, the hook from `push.on(registration, (data) => {})` has a `data.registrationType` of `APNS` in both scenarios, however, on occasion, I will receive multiple registrations on the app load, some will be the standard 64 character APNS registration id, but sometimes it is the longer FCM style key (even though it says APNS).

#### Steps to Reproduce 

- Create a Cordova app
- Add the phonegap-plugin-push plugin
- Make sure the app is configured with a valid push certificate from APNS
- Generate a GoogleService-Info.plist from google
- Change the value of IS_GSM_ENABLED to false
- Include `<resource-file src="GoogleService-Info.plist" target="app/GoogleService-Info.plist"/>` in your config.xml file
- In the javascript you run when loading your app, set up the push notifications as per the readme
- add to the code:
```
push.on('registration', function(data) {
  // use APNS_SANDBOX if you in a dev build - I have only tested on production like builds
  if(data.registrationType === 'APNS' && data.registrationId.length > 64) {
    alert('the app registered with FCM:' + data.registrationId)
  }
})
```
- Because this is a race issue, the occurrence is sporadic.  To replicate, hard close the app and reopen it several times.  Eventually, you will receive the alert.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

tested on:
- iOS 9.3.5
- iOS 11.4.1

#### Cordova CLI version and cordova platform version

    cordova --version    8.0.0 
    cordova platform version ios  ios 4.5.5

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.2.3

#### Sample Push Data Payload

N/A

#### Sample Code that illustrates the problem

N/A

**Comment by macdonst** [comment] 2018-09-07 16:05
@kylemellander this is a duplicate of #2542 right?

**Closed by macdonst** 2018-09-07 16:05 UTC
Labels: duplicate

**Comment by kylemellander** [comment] 2018-09-07 16:10
sorry - the first did not look like it posted!
