### ISSUE TITLE
 clicks on notification in notification center dont start the app

### ISSUE THREAD

**Issue by manufuentescr** [phonegap/phonegap-plugin-push#1664] opened 2017-04-03 20:17 UTC
### Expected Behaviour

 click in notification and start the aplication

### Actual Behaviour

The notification is hidden and the application did not start

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android API 23 - 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Samsung Galxai S6 Edge Plus

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.5.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.9.4

#### Sample Push Data Payload
```
{
   "to":"fPZXfhd_LBc:DRB",
  "data":{"title":"Test","message":"Test Message","image":"https:\/\/cdn2.iconfinder.com\/data\/icons\/humano2\/48x48\/apps\/sticky-notes.png","CustomKey":"1_3","content-available":"1"},
"priority":"high",
"content-available":"1"
}
```
#### Sample Code that illustrates the problem

```javascript
	var push = PushNotification.init(
	{
		"android":
		{
		   "senderID": "XXXXXXXX"
		}
	});

	push.on('registration', function(data) 
	{
		console.log("registration event: " + data.registrationId);
		if(user.token!=data.registrationId)
		{
			user.token = data.registrationId;
			console.log("New Token Google "+data.registrationId);
			if(user_login==true)
			{
				update_token_google(data.registrationId);
			}			
		}
		else
		{
			console.log("Same token");
		}
	});

	push.on('error', function(e) 
	{
	   alert("push error = " + e.message);
	});	  

	push.on('notification', function(data) {
		
		console.log('notification event' + JSON.stringify(data));
		if (data.additionalData.foreground) 
		{
			console.log("Push notification clicked app open id_envio = "+data.additionalData.Customkey);
        } 
		else 
		{
			if (data.additionalData.coldstart)
			{
			  console.log("Push notification clicked app background id_envio = "+data.additionalData.Customkey);
			}
			else
			{
			  console.log("Push notification clicked app closed id_envio = "+data.additionalData.Customkey);
			}	
		}
		push.finish(function()
		{
			 console.log('success');
		},function() 
		{
			 console.log('error');
		});
	 });
```
#### Logs taken while reproducing problem

D/PushPlugin_GCMIntentService: onMessage - from: 6174549XXXXXX
D/PushPlugin_GCMIntentService: normalize extras
 D/PushPlugin_GCMIntentService: key = content-available
 D/PushPlugin_GCMIntentService: replace key content-available with content-available
 D/PushPlugin_GCMIntentService: key = google.sent_time
 D/PushPlugin_GCMIntentService: replace key google.sent_time with google.sent_time
 D/PushPlugin_GCMIntentService: key = CustomKey
D/PushPlugin_GCMIntentService: replace key CustomKey with CustomKey
 D/PushPlugin_GCMIntentService: key = image
 D/PushPlugin_GCMIntentService: replace key image with image
 D/PushPlugin_GCMIntentService: key = title
D/PushPlugin_GCMIntentService: replace key title with title
D/PushPlugin_GCMIntentService: no locale found for key = title, error Value Test of type java.lang.String cannot be converted to JSONObject
 D/PushPlugin_GCMIntentService: key = google.message_id
 D/PushPlugin_GCMIntentService: replace key google.message_id with google.message_id
 D/PushPlugin_GCMIntentService: key = message
 D/PushPlugin_GCMIntentService: replace key message with message
 D/PushPlugin_GCMIntentService: no locale found for key = message, error Value Test of type java.lang.String cannot be converted to JSONObject
D/PushPlugin_GCMIntentService: background
D/PushPlugin_GCMIntentService: message =[Test Message]
 D/PushPlugin_GCMIntentService: title =[Test]
 D/PushPlugin_GCMIntentService: contentAvailable =[1]
 D/PushPlugin_GCMIntentService: forceStart =[null]
 D/PushPlugin_GCMIntentService: create notification
 E/PushPlugin_GCMIntentService: Number format exception - Error parsing notId: Invalid int: "null"
 D/PushPlugin_GCMIntentService: stored icon=null
 D/PushPlugin_GCMIntentService: stored iconColor=null
 D/PushPlugin_GCMIntentService: stored sound=true
D/PushPlugin_GCMIntentService: stored vibrate=true
 D/PushPlugin_GCMIntentService: no icon resource found - using application icon
 D/PushPlugin_GCMIntentService: using remote large-icon from gcm
 D/PushPlugin_GCMIntentService: create actions: with in-line
 D/PushPlugin_GCMIntentService: app is not running and content available true
D/PushPlugin_GCMIntentService: send notification event
 V/PushPlugin: sendExtras: caching extras to send at a later time.

**Comment by macdonst** [comment] 2017-04-03 20:34
@manufuentescr what does you AndroidManifest.xml file look like?

**Comment by manufuentescr** [comment] 2017-04-03 20:42
```xml
<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="10000" android:versionName="1.0.0" package="xxxxxxx" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/icon" android:label="@string/app_name" android:largeHeap="true" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleInstance" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <provider android:authorities="${applicationId}.provider" android:exported="false" android:grantUriPermissions="true" android:name="android.support.v4.content.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/provider_paths" />
        </provider>
        <receiver android:name="com.adobe.phonegap.push.BackgroundActionButtonHandler" />
        <receiver android:exported="true" android:name="com.google.android.gms.gcm.GcmReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>
        <service android:exported="false" android:name="com.adobe.phonegap.push.GCMIntentService">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>
        <service android:exported="false" android:name="com.adobe.phonegap.push.PushInstanceIDListenerService">
            <intent-filter>
                <action android:name="com.google.android.gms.iid.InstanceID" />
            </intent-filter>
        </service>
        <service android:exported="false" android:name="com.adobe.phonegap.push.RegistrationIntentService" />
        <meta-data android:name="com.transistorsoft.locationmanager.license" android:value="4bbb513c013111eae951647fd4f9e79f127fce6f7a00e9d327db9xxx" />
        <meta-data android:name="com.google.android.geo.API_KEY" android:value="XXXXXXX" />
        <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
    </application>
    <uses-sdk android:minSdkVersion="15" android:targetSdkVersion="25" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.RECORD_VIDEO" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.WRITE_CONTACTS" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-feature android:name="android.hardware.location.gps" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />
    <uses-permission android:name="${applicationId}.permission.PushHandlerActivity" />
    <permission android:name="${applicationId}.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <permission android:name="${applicationId}.permission.PushHandlerActivity" android:protectionLevel="signature" />
    <uses-permission android:name="com.google.android.providers.gsf.permission.READ_GSERVICES" />
    <uses-feature android:glEsVersion="0x00020000" android:required="true" />
    <uses-feature android:name="android.hardware.location" />
</manifest>
```

**Comment by macdonst** [comment] 2017-04-03 20:52
@manufuentescr this is actually a duplicate of #1646. Something is adding `android:launchMode="singleInstance"` to your AndroidManifest.xml and that is keeping the application from being brought to the front. It should be `singleTop` which is normal for a PhoneGap app or `standard`.

**Closed by macdonst** 2017-04-03 20:52 UTC
Labels: android, duplicate

**Comment by manufuentescr** [comment] 2017-04-03 21:12
I make the change, but it still does not start the application

**Comment by macdonst** [comment] 2017-04-03 21:14
@manufuentescr bring the discussion over to #1646. Please make sure you clean your Android project and double check the AndroidManifest.xml file to make sure your change took place.

If you are still having an issue grab some logs and place them in #1646.
