### ISSUE TITLE
Push authorization not request (iOS)

### ISSUE THREAD

**Issue by lucasabba** [phonegap/phonegap-plugin-push#762] opened 2016-03-29 19:36 UTC
### Expected Behaviour

iOS alert to request push authorization
### Actual Behaviour

permission for notifications not asked.

No registrationId generated

In iPhone settings -> my app page  there isn't push option 
#### Steps to Reproduce

I'm using the sample code from this plugin page
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 9.3
#### Cordova CLI version and cordova platform version

```
cordova --version          5.3.3
cordova platform version ios 3.9.2
```
#### Plugin version

phonegap-plugin-push 1.6.1 "PushPlugin"
#### Sample Push Data Payload

N A
#### Sample Code that illustrates the problem

The sample code from plugin page
#### Logs taken while reproducing problem

I saw that i have this problem only with iOS 9.3 infant i tried this on iOS 9.2.1 and its work fine! I already read this https://github.com/phonegap/phonegap-plugin-push/issues/752 but i don't understand if the problem is the same and how to resolve.

Thanks to all!

**Comment by macdonst** [comment] 2016-03-30 14:21
@lucasabba version 1.6.1 of the plugin does not support cordova-ios 3.9.2. You'll have to upgrade to cordova-ios 4.0.0 or later.

https://github.com/phonegap/phonegap-plugin-push/blob/master/plugin.xml#L26

**Comment by macdonst** [comment] 2016-04-11 18:09
Closing, assume fixed. Re-open if you still have the problem.

**Comment by lucasabba** [comment] 2016-04-17 18:05
Update:
cordova --version 6.1.1
cordova platform version iOS 4.1.1
phonegap-plugin-push 1.6.1 "PushPlugin"

Same problem descripted in first post

Thanks to all

**Comment by macdonst** [comment] 2016-04-18 03:41
@lucasabba do you have the certificates that match your bundle ID installed?

**Comment by lucasabba** [comment] 2016-04-18 04:43
Yes, certificates is valid and match my bundle id. On iOS 9.2.X it's all ok

**Comment by macdonst** [comment] 2016-04-18 13:46
@lucasabba I don't know what to tell you as I can't reproduce this. I'd try:

```
cordova plugin rm phonegap-plugin-push
cordova platform rm ios
cordova platform add ios@4.1.1
cordova plugin add phonegap-plugin-push --variable SENDER_ID=XXXXXXXX
```

**Comment by macdonst** [comment] 2016-05-26 17:58
@lucasabba any luck getting this resolved?

**Comment by sergiowalls** [comment] 2016-07-13 11:42
Same problem...

> PhoneGap (iOS / Android / Windows)
> cli-6.1.0 (4.1.0 / 5.1.1 / 4.3.1)

Only fails when build thought phonegap remote build, when I make a local build it works properly

Any ideas?

**Comment by macdonst** [comment] 2017-06-28 19:23
Closing, inactivity. Please comment/re-open if you have more details.

**Closed by macdonst** 2017-06-28 19:23 UTC
Labels: ios, question
