### ISSUE TITLE
Receiving multiple notification but sending just one

### ISSUE THREAD

**Issue by angeloparchitelli** [phonegap/phonegap-plugin-push#2152] opened 2018-01-18 09:24 UTC
### Expected Behaviour
Just one notification should be received

### Actual Behaviour
Notification keep coming with a variable interval (from 2min to 5min for notify)

### Reproduce Scenario (including but not limited to)
Sending just one notification in two cases: 
1) sync request with curl (php) to FCM.
2) async req. with NodeJS

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.0
Android 5.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Asus Zenfone 3
Asus Zenfone 2

#### Cordova CLI version and cordova platform version

    cordova --version                                    
8.0.0
    cordova platform version android                     # e.g. 4.1.1
6.3.0
#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3
2.1.2

# FCM Server 
11.6.2

#### Sample Push Data Payload
JSON data with 
to, data, time_to_live (integer 0), priority: high 

#### Logs taken while reproducing problem
Same not-id, name notification, same title, same text, same body

**Comment by angeloparchitelli** [comment] 2018-01-18 09:42
The retry pattern is: 2min, 4min, 8min,....30 min, looks like an FCM retry loop.

**Comment by jdcermeron** [comment] 2018-01-18 18:10
Same problem, only on Android

**Comment by mahesh-vi** [comment] 2018-01-19 06:49
Same issue occur to me also. Only Android 8 (Orea)

**Comment by macdonst** [comment] 2018-01-19 19:38
@angeloparchitelli yeah, it seems like the device is not acknowledging reception of the push message as that looks like a back off interval. Can you get me the logs from `adb logcat`? Just to confirm you've only tested with those two ASUS phones?

@jdcermeron & @mahesh-vi which version of Android and what device are you using?

**Comment by jdcermeron** [comment] 2018-01-19 20:10
device: BQ Aquaris M4.5
android version: 6.0 

I get same behavior with cordova-plugin-fcm
tested with cordova-plugin-firebase and works fine, 1 send -> 1 received

**Comment by angeloparchitelli** [comment] 2018-01-21 11:07
@macdonst yes but unfortunately I haven't possibility to extract the `adb logcat` rows, but I checked all log rows and didn't find any function error. I tested the application only Asus phone.
I used another plugin to send the ACK to FCM to dismitt the queue of test messages.

**Comment by alex-polosky** [comment] 2018-01-31 03:03
I'm also getting the same error. How did you handle a work around for this? 

Also, what should I be looking for in adb logcat?

**Comment by kevin-lot** [comment] 2018-01-31 18:42
Same error here with OnePlus 3 on Android O.

cordova : 8.0.0
cordova-android : 7.0.0
phonegap-plugin-push : 2.1.2 with FCM_VERSION : 11.6.2

```
{
	"to": "eknR-vfV7es:xxxxxxx",
    "data": {
   		"title": "Hello",
		"message": "My message",
		"style": "inbox",
   		"object": "feedback",
   		"objectId": "xxx"
   }
}

```

**Comment by alex-polosky** [comment] 2018-01-31 22:41
So, as it turns out it's due to the way FCM notifications just work. Anyone running into this issue, just RTFM and you'll be able to figure out what's going on. For the convenience, I've explained briefly what's going on below.

If you app is in the background, it will not receive a notification message itself upon clicking the notification. What you'll need to do is send two notifications, one with 'notification' as the payload, and another with 'data' as the payload that includes "content_available": "true" and "content-available": 1. 

It doesn't look like there's currently any way to detect when the user has clicked the notification when in background. However, what one can do is subscribe to the event that gets sent when the app regains focus (I forget what it's called, I apologize), and also set a flag upon receiving the notification. The data notification will immediately be routed to the notification handler. Then, when the app regains focus, check the flag that your data notification set, and you'll be able to tell if the user either a) clicked the notification, or b) opened the app after receiving the notification.

Hopefully this helps anyone having the issue! I think it might be a good idea to highlight this directly in the index doc with an example push. Mine are below (note that I'm using django-push-notifications):

        content_data = {
            "content-available": 1,
            "content_available": "true",
            "someobj": {
            }
        }

        content_message = {
            "body": message,
            "visibility": 1, # We want to always be able to see this on a locked screen
            "sound": "default",
        }

I also cannot recall which pieces go where, please check the docs here to learn more:
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md

**Comment by kevin-lot** [comment] 2018-02-01 17:42
Sorry @alex-polosky doesn't respond this issue at all.
I read PAYLOAD.md mutiple times and do 100 tests.

First, your recommendations don't work, a payload like this, it is not compatible with plugin : 
```
{
  "notification": {
    "title": "My title",
    "body": "My body"
  }
}
```
This payload will be intercepted only by OS (and not by application) and shows the icon application instead of icon defined in plugin configuration.

**Surprisingly, I received notification multiple times too with this payload.**


Any help would be welcome.
Best regards.

**Comment by alex-polosky** [comment] 2018-02-02 00:30
@kevin-lot 
Right, I stated I was using a django package that was auto formatting my notifications that get pushed out. The notifications end up looking like this:

    content_data = {
        "content-available": 1,
        "content_available": "true",
        "data": {
            "someobj": {
            }
        }
    }

    content_message = {
        "notification": {
            "body": message,
            "visibility": 1, # We want to always be able to see this on a locked screen
            "sound": "default",
        }
    }

The first one will be pushed and handled by your app. The second one may or not be pushed and handled by your app, depending on if it is in the foreground or not. I highly recommend using this method to ensure that your app always receives the data notification, and it is actually the recommended way of doing things by Google itself.

I noticed that the FCM version of my plugin was outdated, so I had to ensure that I used this version: 11.6.2. You can do this by following the commands (remember if you're using ionic to prepend this with ionic):

    cordova plugin remove phonegap-plugin-push
    cordova plugin add phonegap-plugin-push --variable FCM_VERSION=11.6.2

You'll also want to ensure that whatever other plugins that use Google services, or Firebase services, are using the same FCM version. Do you have the logs for your android build when running (ionic) cordova build android (--debug)? I can take a look through those and see if I can view any discrepancies. 

Also, if you could provide your config.xml (with any data regarding your actual app stripped out if you want that to remain anonymous), I can filter through that to see if there's any conflicts.

Lastly, I'd just like to state that I'm not developing this plugin, I just spent maybe 5 days in a row figuring out the whole FCM/GCM/APNS systems and whatnot.

**Comment by macdonst** [comment] 2018-02-02 01:09
I believe this is a duplicate of #2097 which is fixed by updating the fcm library to 11.6.2. I'm going to push a 2.1.3 to npm in a few moments.

@alex-polosky you don't need to send two push notifications. If you send one using the `notification` payload then this plugin won't know anything about it as the OS will take over.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

**Comment by alex-polosky** [comment] 2018-02-02 01:27
@macdonst, doesn't that mean that I do in fact have to send two notifications? If I send the notification payload, then as you stated the plugin won't receive the payload. I need to receive the data that's contained in the data payload, so that means that I do in fact need to send two.

Either way, my code is working as is so I'm going to leave it. Also, according to Google's documentation on FCM notification pushes, that's how one should be handling it anyways. anything for the notification should not be contained in the data payload.

**Comment by macdonst** [comment] 2018-02-02 02:05
@alex-polosky right, I know that's how Google documents FCM but because we need the native layer to pass the info to the javascript layer to do fun things like background push, action buttons, etc. 

So while Google says send in `notification` their docs also state that the `onMessageReceived` method of the apps Service that receives pushes will not be called. This means if your app is in the background the plugin will not setup the correct icon, large image, sound, action button, etc. etc.

So my recommendation is for folks to send everything in `data` as the plugin will look for things like `title`, `body`, etc.  and display the push notification for you instead of letting the OS do it. And if you need to pass any data along to the JS layer it will be able to as `data` messages does call the `onMessageReceived` method of the apps Service that receives pushes.

**Comment by alex-polosky** [comment] 2018-02-02 02:42
@macdonst ah okay well that all makes good sense then. I apologize for the misunderstanding and I appreciate you explaining in a way that I was able to understand.

So it looks like I'll have to create my own FCM send methods on my server to be able to handle any of the extra push notification features that this plugin allows. At least I've delved deep enough into django-push-notifications to know how the internals work.

**Comment by kevin-lot** [comment] 2018-02-04 20:34
@macdonst 
For me, I give a try with last [master](https://github.com/phonegap/phonegap-plugin-push/commit/58e87593e749d5c6da2a45906a8c7c9309d6b09a).
The plugin works great again (without multiple notifications).

**Comment by macdonst** [comment] 2018-02-04 20:49
@kevin-lot I released a 2.1.3 as well which should be equivalent to what is in `master`.

**Comment by hazaveh** [comment] 2018-02-08 06:30
2.1.3 fixed multiple notifications for me on OREO. but now i have issues on older devices (tested on android M) when the application is on foreground i receive each message as 3 times. 

can you please look into it.

**Comment by macdonst** [comment] 2018-02-12 02:37
@hazaveh I can't reproduce on older devices. Mind you with a bunch of different versions of Play Services floating around make stuff like this hard to pin down.

**Closed** 2018-02-12 02:36 UTC
Labels: android, duplicate, question
