### ISSUE TITLE
android  I not found  /app or  mobile/

### ISSUE THREAD

**Issue by gitHubLie** [phonegap/phonegap-plugin-push#498] opened 2016-01-13 11:44 UTC
I have this problem .

GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.

but  I not found  /app or  mobile/
I used this plugin .how to do it  fix ? thanks

**Comment by macdonst** [comment] 2016-01-13 14:52
@gitHubLie duplicate of #492, this does not affect the ability of the plugin to receive push messages.

**Closed by macdonst** 2016-01-13 14:52 UTC
Labels: duplicate

**Comment by gitHubLie** [comment] 2016-01-14 00:32
but my app con't  return registrationId for android ,ios is ok . when android don't call registration ,can you help me ? 
push.on('registration', function(data) {
            alert("1111"+data.registrationId);
});

**Comment by gitHubLie** [comment] 2016-01-14 01:22
I try again run my app . ERROR is  MISSING_INSTANCEID_SERVICE ???

**Comment by macdonst** [comment] 2016-01-14 01:37
@gitHubLie please read https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/ISSUES.md
