### ISSUE TITLE
background notification question

### ISSUE THREAD

**Issue by superainovacoes** [phonegap/phonegap-plugin-push#756] opened 2016-03-28 20:21 UTC
### Expected Behaviour
event/notifcation for receive/clear/read the push notification on device

Scenario: i need to make a request for an api to set a date when the push delivere to the device, another request to set a date when the app is open by clicking the push and if possible an request when the user clear/slide to remove the push.

### Actual Behaviour
notification event is fired only when the client click to push notification

### Reproduce Scenario (including but not limited to) - on nodejs
```
var gcm = require('node-gcm');
var gcmService = new gcm.Sender('###');
var message = new gcm.Message();
message.addData('content-available', '1');
message.addData('title', 'title');
message.addData('message', 'message');
gcmService.send(message, {
	registrationTokens: [###]
});
```

#### Steps to Reproduce - on phonegap
```
var PN = PushNotification.init(###);
PN.on('notification', function(data) {
	//fired only when user click the notification
});
```

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
android moto-x first gen.

#### Cordova CLI version and cordova platform version
PhoneGap (iOS / Android / Windows)
cli-6.0.0 (4.0.1 / 5.1.0 / 4.3.0)

#### Plugin version
phonegap-plugin-push - 1.6.1    
```
<plugin name="phonegap-plugin-push">
     <param name="SENDER_ID" value="###" />
</plugin> 
```

#### Sample Push Data Payload
none

#### Sample Code that illustrates the problem - expected
```
var PN = PushNotification.init(###);

PN.on('notification.arrived', function(data) {
	//fired only when notification arrives the device
});

PN.on('notification.clear', function(data) {
	//fired only when user click clear/slide to remove notification
});

PN.on('notification.open', function(data) {
	//fired only when user click the notification
});
```

#### Logs taken while reproducing problem
none

**Comment by macdonst** [comment] 2016-03-28 21:17
@superainovacoes sorry to be a jerk but I'm going to start closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

**Comment by superainovacoes** [comment] 2016-03-28 21:51
sorry @macdonst, any more info needed just ask.

**Comment by macdonst** [comment] 2016-03-29 13:47
@superainovacoes right, this is a duplicate of #158. Please comment on that issue.

**Closed by macdonst** 2016-03-29 13:47 UTC
Labels: duplicate
