### ISSUE TITLE
How to send apn-topic on registration using APN

### ISSUE THREAD

**Issue by vtellez** [phonegap/phonegap-plugin-push#921] opened 2016-05-24 10:06 UTC
Hi! I am reading the documentation and I am wondering: How can I submit the apn-topic on registration event?

I see there is a field:

```
 var push = PushNotification.init({
            android: {
                senderID: "XXXX"
            },
            ios: {
                alert: "true",
                badge: "true",
                sound: "true",
                senderID: "XXXXX",
                gcmSandbox: "true",
                topics: ['bundle.id']
            },
        });
```

But this is only when we are using GCM service. I want to use APN but if I use this:

```
 var push = PushNotification.init({
            android: {
                senderID: "452017922647"
            },
            ios: {
                alert: "true",
                badge: "true",
                sound: "true"
            },
        });
```

I am always reciving {“reason”:”DeviceTokenNotForTopic”} when I try to send a push notification from my server

**Comment by macdonst** [comment] 2016-05-24 13:44
@vtellez you can't. APNS doesn't actually support topics. When Apple documentation refers to topics they mean the bundle ID of the app. So an App can only have one topic. If you want to have topics on iOS you'll either need to GCM or use a push service that handles topics for you like Amazon SNS. Does this answer your question?

**Comment by vtellez** [comment] 2016-05-24 13:47
@macdonst  thank you very much for your response.

I don't want to use topics, my problem is that I define my widegt id in the config.xml as the bundle id but When I try to send the push notification, it seems that the token is not register for this bundle id.

I also have this ticket with a better explain

#920

**Comment by macdonst** [comment] 2016-05-24 13:48
Closing this a basically a duplicate of #920. Let's handle it on that issue.

**Closed by macdonst** 2016-05-24 13:48 UTC
Labels: duplicate, ios, question
