### ISSUE TITLE
IOS: on registration fired twice

### ISSUE THREAD

**Issue by Moussawi7** [phonegap/phonegap-plugin-push#185] opened 2015-09-30 13:55 UTC
Hi,
I already installed the latest version of this plugin and it seem the on "registration" callback is fired twice.
```javascript
function initialize() {
    alert("at init");//fired once
    var push = PushNotification.init({"android": {"senderID": "12345679"}, "ios": {"alert": "true", "badge": "true", "sound": "true"}, "windows": {}});
    push.on('registration', function(data) {
        alert("at registration");//fired twice
    });
}
```
Thanks.

**Comment by macdonst** [comment] 2015-09-30 14:23
Probably a duplicate of #57 please comment on that issue.

**Closed by macdonst** 2015-09-30 14:23 UTC
