### ISSUE TITLE
Empty registrationId Android

### ISSUE THREAD

**Issue by brambogaerts** [phonegap/phonegap-plugin-push#265] opened 2015-10-26 18:25 UTC
I am using Parse.com to send push messages to my Ionic app. Therefore, I am using their senderID.

```
var push = PushNotification.init({
	"android": {
		"senderID": "1076345567071"
	},
	"ios": {
		"alert": "true",
		"badge": "true",
		"sound": "true"
	}
});
```

The onRegistration event does fire for Android, but the registrationId field is empty, so I am unable to receive push notifications.

**Comment by macdonst** [comment] 2015-10-26 18:42
@brambogaerts Don't use the senderID from Parse. Use the GCM one you had to provide to Parse.

https://github.com/phonegap/phonegap-plugin-push#pushnotificationinitoptions

**Comment by brambogaerts** [comment] 2015-10-26 18:58
@macdonst Thanks for your speedy reply. However, I have created a new app from scratch to test with, and used my own senderID I provided to Parse, and I still get the same results...

**Comment by brambogaerts** [comment] 2015-10-26 19:06
As I was looking through the log items, I found this:
`E/PushPlugin: execute: Got JSON Exception TIMEOUT`
Internet connection is working.

**Comment by macdonst** [comment] 2015-10-26 20:43
@brambogaerts I am unable to reproduce your problem. Got a reproduction scenario/code I can look at?

**Comment by brambogaerts** [comment] 2015-10-26 21:37
Well, the problem fixed itself. Somewhere between cleaning all kinds of caches and reinstalling every part imaginable, I managed to get the correct ID. Thanks for your response!

**Comment by macdonst** [comment] 2015-10-27 02:30
Closing, re-open if you can reproduce.

**Closed by macdonst** 2015-10-27 02:30 UTC

**Comment by thomasjonas** [comment] 2015-10-27 11:50
Colleague of @brambogaerts here... Since we have bad wifi reception in the space we're working we setup a wifi using OS X's Internet Sharing. Somehow this is related to this problem as we got a real registrationId when we connected to a proper router... @macdonst any idea how that could be possible?

**Comment by macdonst** [comment] 2015-10-27 13:45
@thomasjonas sorry no. Networking is like black magic to me. Especially when you get into connection sharing and captive gateways.
