### ISSUE TITLE
Unfortunately, [App Title Here] has stopped - 2.1.3

### ISSUE THREAD

**Issue by Sebartus** [phonegap/phonegap-plugin-push#2184] opened 2018-02-03 19:54 UTC
Phonegap Build version: cli-8.0.0
Plugin version: 2.1.3 
Android version: 4.4.2
Device: Samsung Galaxy Note 2

App built successfull on Phonegap Build page but when I try open it on the phone I get message:
Unfortunately, [App Title Here] has stopped.

Similar like here but this example is for Cordova CLI not Phonegap Build:
https://github.com/phonegap/phonegap-plugin-push/issues/2129

If I use plugin version lower than 2.1.3 with cli-8.0.0 I'm not able built successfull on Phonegap Build.

Only combination PB cli-7.0.1 with plugin version 2.0.0 works.

I hope that this information will help find solution because cli-8.0.0 give big update on Android plaform.

**Comment by macdonst** [comment] 2018-02-04 20:45
@Sebartus what stack trace do you see in `adb logcat` when the app crashes?

**Comment by macdonst** [comment] 2018-02-16 12:41
Pretty sure this is a duplicate of #2051

**Closed by macdonst** 2018-02-16 12:41 UTC
Labels: android, duplicate, question
