### ISSUE TITLE
build fail on android 

### ISSUE THREAD

**Issue by roysG** [phonegap/phonegap-plugin-push#149] opened 2015-09-16 21:21 UTC
info:

Your system information:

Cordova CLI: 5.3.1
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.7.0
ios-sim version: 5.0.1
OS: Mac OS X Yosemite
Node Version: v4.0.0
Xcode version: Xcode 6.3.2 Build version 6D2105

Error:

testApps/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:398: cannot find symbol
symbol  : method setColor(int)
location: class android.support.v4.app.NotificationCompat.Builder
            mBuilder.setColor(iconColor);
                    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/Admin/www/picktags.com/public_html/testApps/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
100 warnings
:compileDebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by roysG** [comment] 2015-09-17 08:43
any updates?

**Comment by macdonst** [comment] 2015-09-17 12:53
@roysG your issue is a duplicate of #51 so I'm going to close it. There is info on how to work around it there. In short you have an older version of 'android-support-v13.jar' being picked up by your system. You may need to update it via the 'android' command. 

Also, the 'master' branch has switched to using Gradle so this issue will go away during the next release.

**Closed by macdonst** 2015-09-17 12:53 UTC
