### ISSUE TITLE
Android 8: Message received but not shown in notification shade, no sound either

### ISSUE THREAD

**Issue by bardu** [phonegap/phonegap-plugin-push#1963] opened 2017-09-19 21:29 UTC
### Expected Behaviour
Show message in notification shade and play sound when app is in background.

### Actual Behaviour
According to logcat message is received, according to app console log notification handler is invoked, however, no message in notification shade, no sound, no vibration.
Works with iOS.

### Reproduce Scenario (including but not limited to)
Migrated from GCM to FCM and followed the installation requirements for plugin-push v2.x

#### Steps to Reproduce 
Downloaded all require Android SDK's and tools via Android Studio SDKManager. Run android build from cordova-cli

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 8.0.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Google Pixel XL

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.0.1
    cordova platform version android          6.2.3                

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.0.0

#### Sample Push Data Payload
```
var message = new gcm.Message({
                                "delayWhileIdle": true,
                                "timeToLive": 3,
                                "data": {
                                    "title": config.gcm.message_title,
                                    "body": data.new_val.desc,
                                    "sound": "default",
                                    "content-available": "1",
                                    "priority": 2,
                                    "badge": 1,
                                    "notId": androidNotId,
                                    "extra": {
                                        "url": "deals"
                                    }
                                }
                            }),
                sender  = new gcm.Sender(config.gcm.api_key);
                
                sender.send(message, {topic: '/topics/' + topic.topic.concat('-android')}, function(err, response) {
                    if (err) {
                        console.log('Error sending push notification to Android');
                        console.error(err);
                    }
                    else {
                        console.log('Push Android success: ' + JSON.stringify(response));
                    }
                });
```

#### Sample Code that illustrates the problem
```
 window.gcmPush = PushNotification.init({
            android: {
                sound: "true",
                vibration: "true",
                topics: map(androidTopics, 'topic')
            },
            ios: {
                fcmSandbox: "false",
                alert: "true",
                badge: "true",
                sound: "true",
                vibration: "true",
                clearBadge: "true",
                topics: map(iosTopics, 'topic')
            }
        });
```
#### Logs taken while reproducing problem

09-19 11:51:32.533 21905 23485 D Push_Plugin: key = content-available
09-19 11:51:32.533 21905 23485 D Push_Plugin: key = priority
09-19 11:51:32.533 21905 23485 D Push_Plugin: key = count
09-19 11:51:32.533 21905 23485 D Push_Plugin: key = extra
09-19 11:51:32.534 21905 23485 D Push_Plugin: key = notId
09-19 11:51:32.538 21905 23485 D Push_Plugin: key = sound
09-19 11:51:32.538 21905 23485 D Push_Plugin: key = title
09-19 11:51:32.539 21905 23485 D Push_Plugin: key = message
09-19 11:51:32.539 21905 23485 D Push_Plugin: key = coldstart
09-19 11:51:32.539 21905 23485 D Push_Plugin: key = foreground
09-19 11:51:32.548 21905 23485 V Push_Plugin: extrasToJSON: {"count":"1","sound":"default","title":"Local is Smart","message":"Damn android 8","additionalData":{"content-available":"1","priority":"2","extra":{"url":"deals"},"notId":"76240","coldstart":true,"foreground":false}}

**Comment by macdonst** [comment] 2017-09-19 21:43
@bardu what does your AndroidManifest.xml look like, specifically the min & target sdk values?

**Comment by bardu** [comment] 2017-09-19 21:50
@macdonst:

`<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="26" /> `

**Comment by macdonst** [comment] 2017-09-19 22:41
@bardu this is a duplicate of #1949.

You can either set the target SDK to 25 or install the latest plugin from github. I'm going to do a new release of the plugin soon to support some Android 8 changes.

**Closed by macdonst** 2017-09-19 22:41 UTC
Labels: android, duplicate

**Comment by bardu** [comment] 2017-10-10 20:35
@macdonst   just today I installed the latest like

`cordova plugin add phonegap-plugin-push@latest --save`

But the issue still persists.

Any release date for v2.1.0?
