### ISSUE TITLE
[iOS] Beeping twice when receive notification.

### ISSUE THREAD

**Issue by hung-doan** [phonegap/phonegap-plugin-push#907] opened 2016-05-20 13:45 UTC
### Expected Behaviour

Beeping once for a notification
### Actual Behaviour

Beeping twice for a notification
#### Steps to Reproduce

Step 1: Login to user A (push.init(...))
Step 3: Send notification NA1 to user A
Step 4: Beeping twice when receive notification.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 9.3.2
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

iPhone 5
#### Cordova CLI version and cordova platform version

```
cordova --version                             
=> 6.1.1
cordova platform version ios                  
=> 4.1.1
```
#### Plugin version

```
cordova plugin version | grep phonegap-plugin-push 
=> 1.6.3
```
#### Sample Push Data Payload

```
{
  "to": "/topics/ios_5a89ecdb-3ddb-e411-80d7-001e671a4bb2",
  "priority": "high",
  "notification": {
    "title": "Test GCM",
    "sound": "ring.caf"
    "body": "I wish,..."
  }
}
```

"5a89ecdb-3ddb-e411-80d7-001e671a4bb2" is user id
#### Sample Code that illustrates the problem

Configuration: 

```
var topicIos = 'ios_' + currentUserId;
                        push = PushNotification.init({
                                ios: {
                                senderID: appDomainConfigs.gcmSenderId, // GCM Sender ID (project ID)
                                alert: true,
                                badge: true,
                                sound: true,
                                gcmSandbox: true,
                                'topics': [topicIos]
                            }
                        });
```

iOS Notification setting for Application: 
- Allow notification = true
- Show in Notification Center = true
- Sound = true
- Badge App icon = true
- Show on Lock Screen = true
#### Logs taken while reproducing problem

IMPORTANT NOTES: 
1. In Android I did not meet this issue
2. If my phone is in locked state, It just Beeping once.

**Comment by hungdoan2** [comment] 2016-05-26 09:16
Update: 
My device, after 2 days. It work as expected without any change! 
But my colleague still meet this issues.

**Comment by finalspy** [comment] 2016-10-04 13:03
I can confirm this strange behavior on an iphone6, iOS 9.3.5, phonegap push plugin 1.8.2, cordova --version 6.1.1,cordova platform version ios 4.1.1, and : 
1. In Android I did not meet this issue
2. If my phone is in locked state, It just Beeping once.

I can also say that if we choose None or Alert style when unlocked in phone preferences, it only ring/vibrate once, but if the unlocked style is set to banner, then it ring/vibrate twice again.

Did someone find a solution ?

**Comment by hungdoan2** [comment] 2016-10-05 05:48
@finalspy I didn't find any solution because It will work correctly after a period. So my solution is leave this issue alone 😢

**Comment by macdonst** [comment] 2017-06-28 20:04
Closing as original reported had the problem go away and I never could reproduce

**Closed by macdonst** 2017-06-28 20:04 UTC
Labels: ios, retest
