### ISSUE TITLE
push.on('notification') is not firing when app is removed from active app list - Android

### ISSUE THREAD

**Issue by haclairvoyant** [phonegap/phonegap-plugin-push#1102] opened 2016-07-20 18:43 UTC
### Expected Behaviour
When app is removed from active app list or you can say you clear the app by clearing the RAM, server sends a notification to the device, it is shown in the notification bar and the related event should get executed either by clicking on it or as soon as notification arrives in the device.

### Actual Behaviour
When the app is not in active app list than no event is executed when notification arrives. When the app is in background(active app running in background) or in foreground event get executed as soon as notification arrives but doesn't execute when it is not in active app list. It was working few days ago but today when I updated the Cordova and was re-testing some features it didn't work.

#### Steps to Reproduce 
1. Remove the app from active app list by clearing the used RAM
2. Send GCM notification from server
3. Device receives the notification but attached event doesn't execute either by clicking or on arrival

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.1, 6.0, 4.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Lenevo A700 -  Marshmellow 6.0
One plus one - Lolilop 5.1
Samsung - Kitkat 4.2

#### Cordova CLI version and cordova platform version
Ionic - 1.7.14
Cordova - 6.2.0
cordova platform version android - 5.1.1

#### Plugin version
Push Plugin - 1.6.3

#### Sample Code that illustrates the problem
```
push.on('notification', function(data) {
 executeEvent(data);
});
```

Responses would be appreciated.

**Comment by macdonst** [comment] 2016-07-21 16:25
@haclairvoyant duplicate of #158

**Closed by macdonst** 2016-07-21 16:25 UTC
Labels: duplicate
