### ISSUE TITLE
Incompatibility with cordova-plugin-local-notifications

### ISSUE THREAD

**Issue by panaggio** [phonegap/phonegap-plugin-push#1106] opened 2016-07-22 03:07 UTC
### Expected Behaviour

Both plugins should work together without any interference.

### Actual Behaviour

Some interference exists.

It depends on the order they load, execute or something like that, but one of the following happen:

* Push notifications work perfectly and no local notifications are shown
* Local notifications work perfectly and push notifications work with some issues (like not showing action buttons)

### Reproduce Scenario (including but not limited to)

Have both phonegap-plugin-push and cordova-plugin-local-notifications installed and use both.

#### Steps to Reproduce 

* Show push notification
* Show local notification
* Show push notification
* Bingo (push notifications won't show action buttons anymore, or local notifications will never show up)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 9.3.3

#### Cordova CLI version and cordova platform version

```
% cordova --version
6.2.0
%  cordova platform version ios
Installed platforms:
  ios 4.1.1
```

#### Plugin version

```
% cordova plugin version
[...]
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
phonegap-plugin-push 1.7.4 "PushPlugin"
```

#### Sample Push Data Payload

Nothing special. Just a payload with action buttons

#### Sample Code that illustrates the problem

```js
// Action button code
var actionButtonClick = function(data) {
    // Triggers a local notification and stop happening or
    // stop showing action buttons (hence this is never able to be called again)
    cordova.plugins.notification.local.schedule({
        title: 'foo',
        text: 'bar',
    });
};
```

or
```js
// Triggers a local notification and stop happening or
// stop showing action buttons (hence this is never able to be called again)
cordova.plugins.notification.local.schedule({
    title: 'foo',
    text: 'bar',
});

// Standard push handling code
// Push action button will never show up anymore
};
```

#### Logs taken while reproducing problem

I think it's worthless, but here are the logs for the local notifications won't show up problem:

```
2016-07-21 23:52:15.248 HelloCordova[334:55891] didReceiveNotification with fetchCompletionHandler
2016-07-21 23:52:15.248 HelloCordova[334:55891] app in-active
2016-07-21 23:52:15.249 HelloCordova[334:55891] this should be a silent push
2016-07-21 23:52:15.250 HelloCordova[334:55891] Push Plugin notId 98765432
2016-07-21 23:52:15.251 HelloCordova[334:55891] Notification received
2016-07-21 23:52:15.251 HelloCordova[334:55891] Push Plugin key: alert
2016-07-21 23:52:15.252 HelloCordova[334:55891] Push Plugin key: category
2016-07-21 23:52:15.252 HelloCordova[334:55891] Push Plugin key: badge
2016-07-21 23:52:15.253 HelloCordova[334:55891] Push Plugin key: sound
2016-07-21 23:52:15.253 HelloCordova[334:55891] Push Plugin key: content-available
2016-07-21 23:52:15.341 HelloCordova[334:55891] [push] notification: {"0":{"count":77,"sound":"default","additionalData":{"foreground":false,"document":"bar","category":"a","coldstart":false,"notId":98765432,"content-available":1},"message":"Foo"}}
2016-07-21 23:52:18.872 HelloCordova[334:55891] Push Plugin handleActionWithIdentifier app.accept
2016-07-21 23:52:18.873 HelloCordova[334:55891] Push Plugin userInfo {
    aps =     {
        alert = Foo;
        badge = 77;
        category = a;
        "content-available" = 1;
        sound = default;
    };
    callback = "app.accept";
    document = bar;
    notId = 98765432;
}
2016-07-21 23:52:18.873 HelloCordova[334:55891] Push Plugin notId 98765432
2016-07-21 23:52:18.873 HelloCordova[334:55891] Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.
2016-07-21 23:52:18.874 HelloCordova[334:55891] Notification received
2016-07-21 23:52:18.874 HelloCordova[334:55891] Push Plugin key: alert
2016-07-21 23:52:18.874 HelloCordova[334:55891] Push Plugin key: category
2016-07-21 23:52:18.874 HelloCordova[334:55891] Push Plugin key: badge
2016-07-21 23:52:18.874 HelloCordova[334:55891] Push Plugin key: sound
2016-07-21 23:52:18.879 HelloCordova[334:55891] Push Plugin key: content-available
2016-07-21 23:52:18.888 HelloCordova[334:55891] [push] notification: {"0":{"count":77,"sound":"default","additionalData":{"callback":"app.accept","foreground":false,"document":"bar","content-available":1,"category":"a","notId":98765432,"coldstart":false},"message":"Foo"}}
2016-07-21 23:52:27.313 HelloCordova[334:55891] didReceiveNotification with fetchCompletionHandler
2016-07-21 23:52:27.313 HelloCordova[334:55891] app in-active
2016-07-21 23:52:27.314 HelloCordova[334:55891] this should be a silent push
2016-07-21 23:52:27.314 HelloCordova[334:55891] Push Plugin notId 98765432
2016-07-21 23:52:27.314 HelloCordova[334:55891] Warning: Application delegate received call to -application:handleActionWithIdentifier:forRemoteNotification:completionHandler: but the completion handler was never called.
2016-07-21 23:52:27.314 HelloCordova[334:55891] Notification received
2016-07-21 23:52:27.314 HelloCordova[334:55891] Push Plugin key: alert
2016-07-21 23:52:27.315 HelloCordova[334:55891] Push Plugin key: category
2016-07-21 23:52:27.319 HelloCordova[334:55891] Push Plugin key: badge
2016-07-21 23:52:27.319 HelloCordova[334:55891] Push Plugin key: sound
2016-07-21 23:52:27.319 HelloCordova[334:55891] Push Plugin key: content-available
2016-07-21 23:52:27.376 HelloCordova[334:55891] [push] notification: {"0":{"count":77,"sound":"default","additionalData":{"foreground":false,"document":"bar","category":"a","coldstart":false,"notId":98765432,"content-available":1},"message":"Foo"}}
2016-07-21 23:52:27.389 HelloCordova[334:55891] THREAD WARNING: ['Console'] took '13.355957' ms. Plugin should use a background thread.
2016-07-21 23:52:31.278 HelloCordova[334:55891] Push Plugin handleActionWithIdentifier app.accept
2016-07-21 23:52:31.278 HelloCordova[334:55891] Push Plugin userInfo {
    aps =     {
        alert = Foo;
        badge = 77;
        category = a;
        "content-available" = 1;
        sound = default;
    };
    callback = "app.accept";
    document = bar;
    notId = 98765432;
}
2016-07-21 23:52:31.279 HelloCordova[334:55891] Push Plugin notId 98765432
2016-07-21 23:52:31.280 HelloCordova[334:55891] Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.
2016-07-21 23:52:31.280 HelloCordova[334:55891] Notification received
2016-07-21 23:52:31.280 HelloCordova[334:55891] Push Plugin key: alert
2016-07-21 23:52:31.281 HelloCordova[334:55891] Push Plugin key: category
2016-07-21 23:52:31.281 HelloCordova[334:55891] Push Plugin key: badge
2016-07-21 23:52:31.281 HelloCordova[334:55891] Push Plugin key: sound
2016-07-21 23:52:31.287 HelloCordova[334:55891] Push Plugin key: content-available
2016-07-21 23:52:31.293 HelloCordova[334:55891] [push] notification: {"0":{"count":77,"sound":"default","additionalData":{"callback":"app.accept","foreground":false,"document":"bar","content-available":1,"category":"a","notId":98765432,"coldstart":false},"message":"Foo"}}
```

And here are the logs of the actions buttons never show up problem:

```
2016-07-22 00:06:28.239 HelloCordova[344:59278] didReceiveNotification with fetchCompletionHandler
2016-07-22 00:06:28.240 HelloCordova[344:59278] app in-active
2016-07-22 00:06:28.240 HelloCordova[344:59278] this should be a silent push
2016-07-22 00:06:28.244 HelloCordova[344:59278] Push Plugin notId 98765432
2016-07-22 00:06:28.244 HelloCordova[344:59278] Notification received
2016-07-22 00:06:28.244 HelloCordova[344:59278] Push Plugin key: alert
2016-07-22 00:06:28.245 HelloCordova[344:59278] Push Plugin key: category
2016-07-22 00:06:28.250 HelloCordova[344:59278] Push Plugin key: badge
2016-07-22 00:06:28.287 HelloCordova[344:59278] Push Plugin key: sound
2016-07-22 00:06:28.287 HelloCordova[344:59278] Push Plugin key: content-available
2016-07-22 00:06:28.323 HelloCordova[344:59278] [push] notification: {"0":{"count":77,"sound":"default","additionalData":{"foreground":false,"document":"bar","category":"a","coldstart":false,"notId":98765432,"content-available":1},"message":"Foo"}}
```

**Comment by panaggio** [comment] 2016-07-22 03:08
Sister issue: https://github.com/katzer/cordova-plugin-local-notifications/issues/1049

**Comment by macdonst** [comment] 2016-07-22 04:06
Duplicate of #682

**Closed by macdonst** 2016-07-22 04:06 UTC
Labels: duplicate
