### ISSUE TITLE
version 1.2.3

### ISSUE THREAD

**Issue by colonna-mike** [phonegap/phonegap-plugin-push#134] opened 2015-09-15 01:40 UTC
Go to compile the latest version and I'm now getting:

 Error: Plugin phonegap-plugin-push failed to install.

I just step back a version ( 1.2.2  and all worked ...)

**Comment by macdonst** [comment] 2015-09-15 15:31
@colonna-mike can you paste your compilation errors? Also, how are you adding the plugin to your app?

**Comment by colonna-mike** [comment] 2015-09-15 22:04
I'm using Intel XDK  and looks like for some reason I can't access the logs anymore. I'm really not liking this environment very much lately. let me see what I can do to get the logs for you..

**Comment by macdonst** [comment] 2015-09-16 04:06
@colonna-mike this is a duplicate of issue #130 then which was another user who was building with Intel XDK.

**Closed by macdonst** 2015-09-16 04:06 UTC
