### ISSUE TITLE
Register fail iOS 10.

### ISSUE THREAD

**Issue by samukt** [phonegap/phonegap-plugin-push#1154] opened 2016-08-10 15:28 UTC
It's working fine on iOS 9, but when i test on iOS 10 (beta) it doesn't work.
### Reproduce Scenario (including but not limited to)

```
2016-08-10 12:25:31.658087 XXXXX[299:12855] Push Plugin register called
2016-08-10 12:25:31.658230 XXXXX[299:12855] PushPlugin.register: setting badge to false
2016-08-10 12:25:31.658259 XXXXX[299:12855] PushPlugin.register: clear badge is set to 0
2016-08-10 12:25:31.658277 XXXXX[299:12855] PushPlugin.register: better button setup
2016-08-10 12:25:31.658393 XXXXX[299:12855] GCM Sender ID (null)
2016-08-10 12:25:31.658413 XXXXX[299:12855] Using APNS Notification
2016-08-10 12:25:31.665839 XXXXX[299:11181] Push Plugin register failed
```
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS10

I think it needs to be known because iOS 10 is coming...

**Comment by macdonst** [comment] 2016-08-10 23:29
@samukt what version of the iOS 10 beta do you have installed? I tested this before vacation and it was working okay.

**Comment by samukt** [comment] 2016-08-11 00:38
iOS 10 (beta 4)

I'm using the same version of the app (production in app store) on both versions of iOS.
In 9 it's working with no problems. In 10 the register is failing on register.

**Comment by macdonst** [comment] 2016-08-11 00:42
@samukt is your iOS 10 app in production? Make sure you are signing the iOS 10 app with the correct certificate. You might be signing with production and talking to development APNS server or vice versa.

**Comment by samukt** [comment] 2016-08-11 02:17
Found it!

Not sure if it's new or doesn't needed in Xcode 7.
Xcode 8 now have option:

- Add the Push Notifications entitlement to your entitlements file.

In Capabilities of the project, is jut click on fix to work.

**Comment by jacquesdev** [comment] 2016-08-22 12:11
@samukt - what version of the phonegap-plugin-push version are you using?

**Comment by jacquesdev** [comment] 2016-08-22 12:20
This url is also useful https://www.sitepoint.com/developing-push-notifications-for-ios-10/

**Comment by briananderson1222** [comment] 2016-09-07 19:48
Curious if there are plans for this functionality to be generated with a newer version of this Push Plugin? It seems that enabling this capability may be a requirement for XCode 8 going forward

**Comment by jacquesdev** [comment] 2016-09-08 08:15
@briananderson1222 - I totally agree, it's going to be a pain if we need to manually do it.

**Comment by chaffeqa** [comment] 2016-09-10 15:50
I can confirm this is a requirement for xcode8 and iOS10

**Comment by briananderson1222** [comment] 2016-09-12 19:45
@macdonst Curious if this https://github.com/phonegap/phonegap-plugin-push/pull/902 might fix this issue by dynamically using the entitlements specified in the provisioning profile

**Comment by macdonst** [comment] 2016-09-14 19:02
Looking into a solution now.

**Comment by macdonst** [comment] 2016-09-14 22:42
I talked to @shazron about this and we will need to make some changes in cordova-ios 4.3.0 in order to support the .entitlements file as we want to fix this not only for `aps-environment` but for other capabilities that may also be required going forward.

**Comment by shazron** [comment] 2016-09-15 00:38
Watch this issue: https://issues.apache.org/jira/browse/CB-11854

**Comment by briananderson1222** [comment] 2016-09-15 13:33
Thanks @macdonst @shazron .. any idea on timeline for a fix like that given that iOS 8 was released yesterday?

**Comment by jcesarmobile** [comment] 2016-09-15 14:03
On my [file picker plugin ](https://github.com/jcesarmobile/FilePicker-Phonegap-iOS-Plugin) @EddyVerbruggen added a hook to write the .entitlements file, can't we just do that?

**Comment by briananderson1222** [comment] 2016-09-15 14:51
@jcesarmobile something like that was my backup plan until we can see this fix come through. It'd be nice though if cordova supported this without needing this specific plugin to implement its own hook

**Comment by shazron** [comment] 2016-09-15 22:36
Hooks are undesirable for cloud builders like PhoneGap Build, that can't run hooks

Sent a PR: https://github.com/apache/cordova-ios/pull/256

**Comment by shazron** [comment] 2016-09-16 20:22
PR merged in, should be in for future cordova-ios 4.3.0 release. You can test this with the nightly platform released tonight at 8PM PDT.

**Comment by macdonst** [comment] 2016-09-17 19:59
Assigning this issue to the 1.9.0 milestone as it will force users to take cordova-ios 4.3.0.

**Comment by psirenny** [comment] 2016-09-18 17:32
Is upgrading to cordova 4.3.0 nightly enough or do we still need to manually enable the entitlement?

**Comment by briananderson1222** [comment] 2016-09-20 16:38
@shazron what is the recommended way of adding properties to these entitlement files?

**Comment by shazron** [comment] 2016-09-20 18:05
@briananderson1222 the plugin.xml should have something like
```
<config-file parent="aps-environment" target="*/Entitlements-Debug.plist">
          <string>development</string>
</config-file>
```

**Comment by Bart-Holland** [comment] 2016-09-26 15:32
What if you are not in Debug, but in release:

```
<config-file parent="aps-environment" target="*/Entitlements-Release.plist">
          <string>???</string>
</config-file>
```

what should be entered in stead of ???

**Comment by manojbojja** [comment] 2016-09-27 01:34
Ios 10.0.8 (1.8.2 push plugin) not receiving notifications. After checking in xcode too. Registering is fine but push.on is not firing in any app state.

**Comment by jcesarmobile** [comment] 2016-09-27 10:19
@Bart-Holland it's supposed to be `production`

**Comment by Bart-Holland** [comment] 2016-09-27 11:39
@jcesarmobile Thanks doesn't seem to work for me though. Something else is not going well :8ball:

**Comment by briananderson1222** [comment] 2016-09-27 21:51
@Bart-Holland I believe you need to wait for Release 1.9.0 or a related PR (which I have not seen) as this is a change in the `plugin.xml` not the `config.xml`... I'm all ears if someone has a way of implementing this sooner without requiring a custom build

**Comment by PvanHengel** [comment] 2016-10-02 18:43
Good morning, was able to get everything "working", you must use the nightly build of the cordova ios platform until they release 4.3, the latest version (4.2.1) does not work.  You need that for a few reasons, for me its how i was able to get the team name and certs setup properly using the build.config file.  In addition to that you need to use the latest 1.8.2 of this, however as per the above, you need to manually modify the entitlements files, (debugger gets development key and release get production key) .  We  are using jenkins for CI so it was easy enough to plug in there, however for obvious reasons it should be a part of this plugin, when can we expect 1.9 release?  I'm sure that there are many other things for xcode 8 / ios 10 that we want to add, but this is a severe bug, as all push notifications don't work after the upgrade, so its somewhat critical for me, and i'm sure many others.

**Comment by lucorn** [comment] 2016-10-07 23:13
Is there any workaround for building Cordova apps from Visual Studio?

**Comment by kaynz** [comment] 2016-10-13 06:50
@macdonst Maybe you should commit a big hint into the readme so that people see that the plugin is actually not working with iOS 10. They all investigate time to create bug reports with stack traces.

**Comment by kntmrkm** [comment] 2016-10-20 04:57
iOS10 registration will fail until `cordova-ios 4.3.0` and `phonegap-plugin-push 1.9.0`?

I confirmed that iOS9.3.5 works fine, but iOS10.0.2 got below error.

`no valid 'aps-environment' entitlement string found for application`.

Btw, below setting is temporary solution?

```
<config-file parent="aps-environment" target="*/Entitlements-Debug.plist">
          <string>development</string>
</config-file>
```

I tried that. but does not solve problem.
`plugins/phonegap-plugin-push/plugin.xml`  is the file?  right?

**Comment by PvanHengel** [comment] 2016-10-20 10:58
No it needs to go into the root of out output Xcode project not the cofig xml.

**Comment by Kjens93** [comment] 2016-10-20 15:28
Hey guys, we need to remember to maintain support for both **development** and **production** aps environments:
```
<key>aps-environment</key>
<string>development</string>
```
versus
```
<key>aps-environment</key>
<string>production</string>
```

**Comment by bradleyjames** [comment] 2016-10-20 17:09
Actually I don't believe you do.  Xcode handles that for you.

http://stackoverflow.com/questions/39625258/xcode-8-aps-environment-entitlement-wont-set-to-production

**Comment by PvanHengel** [comment] 2016-10-25 18:17
It does if you manually open and turn it on but since Cordova doesn't do that the build fails.  Full automation can't be done without the file

**Comment by bradleyjames** [comment] 2016-10-26 11:23
Sorry, I wasn't clear.  My point was that this file doesn't need to be updated to a value of "production". The provisioning process handles that for you but it never updates the file on disk to say "production".  But yes, the file does need to exist for the build.

**Comment by oceanpad** [comment] 2016-10-28 09:59
Unlike xcode 7, xcode 8 need developer turn on push notifications capabilities switch
[http://stackoverflow.com/questions/39266891/xcode-8-push-notification-capabilities-and-entitlements-file-setting](http://stackoverflow.com/questions/39266891/xcode-8-push-notification-capabilities-and-entitlements-file-setting)
![image](https://cloud.githubusercontent.com/assets/13033318/19802845/28859dd8-9d38-11e6-918c-bf139092c2dd.png)

**Closed** 2016-11-03 18:19 UTC
Labels: enhancement, ios

**Comment by Kjens93** [comment] 2016-11-10 06:23
Just updated to 1.9.0, still not registering on iOS.

**Comment by KapilPowar** [comment] 2016-11-10 09:35
iOS 10 registration fails with cordova iOS 4.3.0 plugin. With older plugin 4.2.1 works fine.
