### ISSUE TITLE
push.on('registration', callback) not firing iOS

### ISSUE THREAD

**Issue by Zaeembinrehman** [phonegap/phonegap-plugin-push#760] opened 2016-03-29 15:25 UTC
Hi,

The push.on('registration', callback) event is not getting fired on iOS. Any suggestions. Here is the snippet of the code:

```
function push_notifications(){
    alert('iOS push notification');
    // push notifications methods
    var push_notification = PushNotification.init({
      android: {
        senderID: "xxxxxxxxxxxx",
        sound: true,
        vibrate: true
      },
      ios: {
        alert: "true",
        badge: "true",
        sound: "true"
      },
      windows: {}
    });

    push_notification.on('registration', function(data) {
      alert('on registration event fired');  
    });

    push_notification.on('notification', function(data) {
      alert('iOS on notification');
      // alert(data.message);
      // data.message,
      // data.title,
      // data.count,
      // data.sound,
      // data.image,
      // data.additionalData
    });


    push_notification.unregister(function() {
      alert('success in unregister');
    }, function() {
      alert('error in unregister');
    });


    push_notification.on('error', function(e) {
      alert(e.message);
      console.log(e.message);
    });

  }
```

**Comment by macdonst** [comment] 2016-03-29 19:01
@Zaeembinrehman this sure looks like a duplicate of #752.

Stop calling the unregister function after the init function.

**Closed by macdonst** 2016-03-29 19:01 UTC
Labels: duplicate

**Comment by Zaeembinrehman** [comment] 2016-04-05 13:54
@macdonst 

I just changed the flow for unregister, and still not getting the registration event fired.

I created a new provision (APNs enabled) and generated the build again through the build server.

Using:
- Windows 8
- Phonegap Version: cli-5.2.0
- iOS Phonegap Version: 3.9.1

**Comment by mayur8188** [comment] 2016-05-21 20:20
same issue with me also.

**Comment by Zaeembinrehman** [comment] 2016-05-21 21:54
@mayur8188 , if you are using adobe cloud build and your iOS building version is 3.9.1 then try setting the an attribut in the config file for your push plugin as:

<plugin name="phonegap-plugin-push" spec="1.5.3">
    <param name="SENDER_ID" value="YOUR_ID_HERE" />
</plugin>

the latest version of push plugin doesn't work with iOS building version is 3.9.1

Hope that helps!
