### ISSUE TITLE
Push PLugin Not Working on Android

### ISSUE THREAD

**Issue by SardarKhan299** [phonegap/phonegap-plugin-push#209] opened 2015-10-07 10:20 UTC
i am going to work on this project  i am using  phonegap 5.0 with cli and i am developing app for android in eclipse and android version is 5.1 and API leve is 22.Now the error is

10-07 13:01:14.282: E/Web Console(9564): Uncaught TypeError: Object function (options) {
10-07 13:01:14.282: E/Web Console(9564):     this._handlers = {
10-07 13:01:14.282: E/Web Console(9564):         'registration': [],
10-07 13:01:14.282: E/Web Console(9564):         'notification': [],
10-07 13:01:14.282: E/Web Console(9564):         'error': []
10-07 13:01:14.282: E/Web Console(9564):     };
10-07 13:01:14.282: E/Web Console(9564):     // require options parameter
10-07 13:01:14.282: E/Web Console(9564):     if (typeof options === 'undefined') {
10-07 13:01:14.282: E/Web Console(9564):         throw new Error('The options argument is required.');
10-07 13:01:14.282: E/Web Console(9564):     }
10-07 13:01:14.282: E/Web Console(9564):     // store the options to this object instance
10-07 13:01:14.282: E/Web Console(9564):     this.options = options;
10-07 13:01:14.282: E/Web Console(9564):     // triggered on registration and notification
10-07 13:01:14.282: E/Web Console(9564):     var that = this;
10-07 13:01:14.282: E/Web Console(9564):     var success = function(result) {
10-07 13:01:14.282: E/Web Console(9564):         if (result && typeof result.registrationId !== 'undefined') {
10-07 13:01:14.282: E/Web Console(9564):             that.emit('registration', result);
10-07 13:01:14.282: E/Web Console(9564):         } else if (result && typeof result.callback !== 'undefined') {
10-07 13:01:14.282: E/Web Console(9564):             var executeFunctionByName = function(functionName, context /*, args */) {
10-07 13:01:14.282: E/Web Console(9564):                 var args = Array.prototype.slice.call(arguments, 2);
10-07 13:01:14.282: E/Web Console(9564):                 var namespaces = functionName.split(".");
10-07 13:01:14.282: E/Web Console(9564):                 var func = namespaces.pop();
10-07 13:01:14.282: E/Web Console(9564):                 for (var i = 0; i < namespaces.length; i++) {
10-07 13:01:14.282: E/Web Console(9564):                     context = context[namespaces[i]];
10-07 13:01:14.282: E/Web Console(9564):                 }
10-07 13:01:14.282: E/Web Console(9564):                 return context[func].apply(context, args);
10-07 13:01:14.282: E/Web Console(9564):             }
10-07 13:01:14.282: E/Web Console(9564):            
10-07 13:01:14.282: E/Web Console(9564):             executeFunctionByName(result.callback, window, result);
10-07 13:01:14.282: E/Web Console(9564):         } else if (result) {
10-07 13:01:14.282: E/Web Console(9564):             that.emit('notification', result);
10-07 13:01:14.282: E/Web Console(9564):         }
10-07 13:01:14.282: E/Web Console(9564):     };
10-07 13:01:14.282: E/Web Console(9564):     // triggered on error
10-07 13:01:14.282: E/Web Console(9564):     var fail = function(msg) {
10-07 13:01:14.282: E/Web Console(9564):         var e = (typeof msg === 'string') ? new Error(msg) : msg;
10-07 13:01:14.282: E/Web Console(9564):         that.emit('error', e);
10-07 13:01:14.282: E/Web Console(9564):     };
10-07 13:01:14.282: E/Web Console(9564):     // wait at least one process tick to allow event subscriptions
10-07 13:01:14.282: E/Web Console(9564):     setTimeout(function() {
10-07 13:01:14.282: E/Web Console(9564):         exec(success, fail, 'PushNotification', 'init', [options]);
10-07 13:01:14.282: E/Web Console(9564):     }, 10);
10-07 13:01:14.282: E/Web Console(9564): } has no method 'init' at file:///android_asset/www/js/Module.js:8
10-07 13:01:14.392: D/TilesManager(9564): Starting TG #0, 0x5f73f420
10-07 13:01:14.392: D/TilesManager(9564): new EGLContext from framework: 5e306a90
10-07 13:01:14.392: D/GLWebViewState(9564): Reinit shader
10-07 13:01:14.442: D/netstack(9564): netstack: Request Priority is ON
10-07 13:01:14.462: D/chromium(9564): Unknown chromium error: -6
10-07 13:01:14.532: D/GLWebViewState(9564): Reinit transferQueue
10-07 13:01:14.542: E/Web Console(9564): Uncaught Error: Module phonegap-plugin-push.PushNotification does not exist. at file:///android_asset/www/cordova.js:1418
10-07 13:01:18.742: I/Web Console(9564): deviceready has not fired after 5 seconds. at file:///android_asset/www/cordova.js:1183
10-07 13:01:18.742: I/Web Console(9564): Channel not fired: onPluginsReady at file:///android_asset/www/cordova.js:1176
10-07 13:01:18.742: I/Web Console(9564): Channel not fired: onCordovaReady at file:///android_asset/www/cordova.js:1176
can any one please help me to solve this problem

**Comment by macdonst** [comment] 2015-10-08 16:55
@SardarKhan299 how did you add the plugin to the project? Cause to me it looks like the module wrapper did not get included. Did you just copy the push.js file into your project?

**Comment by robsjunqueira** [comment] 2015-10-20 11:59
This code works for me:

devicePushReg: function(data) {
    	alert('PushRegistratio ID: ' + data.registrationId + '\n');
    },
    devicePushNotification: function(data) {
    	alert('PushNotificationTitle: ' + data.title + '\nPushNotificationMessage: ' + data.message + '\n');
    },
    devicePushError: function(e) {
    	alert('PushErrorMessage: ' + error.message + '\n');
    },
    devicePush: function() {
        var push = PushNotification.init({
            "android": {"senderID": "XXXXXXXXXXXX"},  // XXXXXXXXXXXX = project ID
            "ios": {"alert": "true", "badge": "true", "sound": "true"},
            "windows": {}
        }, this.devicePushReg, this.devicePushNotification, this.devicePushError);
        
        push.on('registration', this.devicePushReg);
        push.on('notification', this.devicePushNotification);
        push.on('error', this.devicePushError);
    },

**Comment by SardarKhan299** [comment] 2015-10-20 12:03
yes i have copy the push plugin to my project but it doesnot works for me

**Comment by SardarKhan299** [comment] 2015-10-20 12:03
this code gives the above error on my eclipse

**Comment by robsjunqueira** [comment] 2015-10-21 13:34
Check the manifest file: 

com.phonegap.idhome = my test project

<?xml version='1.0' encoding='utf-8'?>
<manifest android:versionCode="1" android:versionName="1.0.0" package="com.phonegap.idhome" xmlns:android="http://schemas.android.com/apk/res/android">
    android:hardwareAccelerated="true"
    
            <uses-sdk android:minSdkVersion="11" android:targetSdkVersion="24" />
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.GET_TASKS" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <permission android:name="com.phonegap.idhome.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="com.phonegap.idhome.permission.C2D_MESSAGE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <application android:allowBackup="true" android:hardwareAccelerated="true" android:icon="@drawable/icon" android:label="@string/app_name">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/app_name" android:name="MainActivity" android:theme="@android:style/Theme.Black.NoTitleBar">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name="com.adobe.phonegap.push.PushHandlerActivity" />
        <receiver android:name="com.adobe.phonegap.push.CordovaGCMBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="com.phonegap.idhome" />
            </intent-filter>
        </receiver>
        <service android:name="com.adobe.phonegap.push.GCMIntentService" />
        <receiver android:exported="false" android:name="de.appplant.cordova.plugin.localnotification.TriggerReceiver" />
        <receiver android:exported="false" android:name="de.appplant.cordova.plugin.localnotification.ClearReceiver" />
        <activity android:exported="false" android:launchMode="singleInstance" android:name="de.appplant.cordova.plugin.localnotification.ClickActivity" android:theme="@android:style/Theme.NoDisplay" />
        <receiver android:exported="false" android:name="de.appplant.cordova.plugin.notification.TriggerReceiver" />
        <receiver android:exported="false" android:name="de.appplant.cordova.plugin.notification.ClearReceiver" />
        <receiver android:exported="false" android:name="de.appplant.cordova.plugin.localnotification.RestoreReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <activity android:exported="false" android:launchMode="singleInstance" android:name="de.appplant.cordova.plugin.notification.ClickActivity" android:theme="@android:style/Theme.NoDisplay" />
    </application>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
</manifest>

**Comment by macdonst** [comment] 2015-10-21 15:15
@SardarKhan299 Again I go back to my original question, how did you add the plugin to the project? Did you use the cordova or phonegap CLI?

**Comment by robsjunqueira** [comment] 2015-10-21 17:02
phonegap CLI:

phonegap plugin add phonegap-plugin-push

**Comment by SardarKhan299** [comment] 2015-10-22 04:50
i am using phonegap cli and phonegap push plugin

**Comment by macdonst** [comment] 2015-10-28 16:06
@SardarKhan299 please re-open if you still have the problem on 1.4.0 and can provide a reproduction scenario.

**Comment by SardarKhan299** [comment] 2015-10-28 16:16
Yes i still have the problem

**Comment by macdonst** [comment] 2015-10-28 17:07
@SardarKhan299 then please provide a detailed reproduction scenario.

**Comment by SardarKhan299** [comment] 2015-10-28 17:13
am going to work on this project i am using phonegap 5.0 with cli and i am
developing app for android in eclipse and android version is 5.1 and API
leve is 22.Now the error is

10-07 13:01:14.282: E/Web Console(9564): Uncaught TypeError: Object
function (options) {
10-07 13:01:14.282: E/Web Console(9564): this._handlers = {
10-07 13:01:14.282: E/Web Console(9564): 'registration': [],
10-07 13:01:14.282: E/Web Console(9564): 'notification': [],
10-07 13:01:14.282: E/Web Console(9564): 'error': []
10-07 13:01:14.282: E/Web Console(9564): };
10-07 13:01:14.282: E/Web Console(9564): // require options parameter
10-07 13:01:14.282: E/Web Console(9564): if (typeof options ===
'undefined') {
10-07 13:01:14.282: E/Web Console(9564): throw new Error('The options
argument is required.');
10-07 13:01:14.282: E/Web Console(9564): }
10-07 13:01:14.282: E/Web Console(9564): // store the options to this
object instance
10-07 13:01:14.282: E/Web Console(9564): this.options = options;
10-07 13:01:14.282: E/Web Console(9564): // triggered on registration and
notification
10-07 13:01:14.282: E/Web Console(9564): var that = this;
10-07 13:01:14.282: E/Web Console(9564): var success = function(result) {
10-07 13:01:14.282: E/Web Console(9564): if (result && typeof
result.registrationId !== 'undefined') {
10-07 13:01:14.282: E/Web Console(9564): that.emit('registration', result);
10-07 13:01:14.282: E/Web Console(9564): } else if (result && typeof
result.callback !== 'undefined') {
10-07 13:01:14.282: E/Web Console(9564): var executeFunctionByName =
function(functionName, context /*, args */) {
10-07 13:01:14.282: E/Web Console(9564): var args =
Array.prototype.slice.call(arguments, 2);
10-07 13:01:14.282: E/Web Console(9564): var namespaces =
functionName.split(".");
10-07 13:01:14.282: E/Web Console(9564): var func = namespaces.pop();
10-07 13:01:14.282: E/Web Console(9564): for (var i = 0; i <
namespaces.length; i++) {
10-07 13:01:14.282: E/Web Console(9564): context = context[namespaces[i]];
10-07 13:01:14.282: E/Web Console(9564): }
10-07 13:01:14.282: E/Web Console(9564): return
context[func].apply(context, args);
10-07 13:01:14.282: E/Web Console(9564): }
10-07 13:01:14.282: E/Web Console(9564):

10-07 13:01:14.282: E/Web Console(9564):
executeFunctionByName(result.callback, window, result);
10-07 13:01:14.282: E/Web Console(9564): } else if (result) {
10-07 13:01:14.282: E/Web Console(9564): that.emit('notification', result);
10-07 13:01:14.282: E/Web Console(9564): }
10-07 13:01:14.282: E/Web Console(9564): };
10-07 13:01:14.282: E/Web Console(9564): // triggered on error
10-07 13:01:14.282: E/Web Console(9564): var fail = function(msg) {
10-07 13:01:14.282: E/Web Console(9564): var e = (typeof msg === 'string')
? new Error(msg) : msg;
10-07 13:01:14.282: E/Web Console(9564): that.emit('error', e);
10-07 13:01:14.282: E/Web Console(9564): };
10-07 13:01:14.282: E/Web Console(9564): // wait at least one process tick
to allow event subscriptions
10-07 13:01:14.282: E/Web Console(9564): setTimeout(function() {
10-07 13:01:14.282: E/Web Console(9564): exec(success, fail,
'PushNotification', 'init', [options]);
10-07 13:01:14.282: E/Web Console(9564): }, 10);
10-07 13:01:14.282: E/Web Console(9564): } has no method 'init' at
file:///android_asset/www/js/Module.js:8
10-07 13:01:14.392: D/TilesManager(9564): Starting TG #0, 0x5f73f420
10-07 13:01:14.392: D/TilesManager(9564): new EGLContext from framework:
5e306a90
10-07 13:01:14.392: D/GLWebViewState(9564): Reinit shader
10-07 13:01:14.442: D/netstack(9564): netstack: Request Priority is ON
10-07 13:01:14.462: D/chromium(9564): Unknown chromium error: -6
10-07 13:01:14.532: D/GLWebViewState(9564): Reinit transferQueue
10-07 13:01:14.542: E/Web Console(9564): Uncaught Error: Module
phonegap-plugin-push.PushNotification does not exist. at
file:///android_asset/www/cordova.js:1418
10-07 13:01:18.742: I/Web Console(9564): deviceready has not fired after 5
seconds. at file:///android_asset/www/cordova.js:1183
10-07 13:01:18.742: I/Web Console(9564): Channel not fired: onPluginsReady
at file:///android_asset/www/cordova.js:1176
10-07 13:01:18.742: I/Web Console(9564): Channel not fired: onCordovaReady
at file:///android_asset/www/cordova.js:1176
can any one please help me to solve this problem

**Comment by macdonst** [comment] 2015-10-28 17:43
@SardarKhan299 are you using ionic? Something is screwed up here as you are not even getting the "deviceready" event. Maybe show me some code on how you make the call to push.init()?

**Comment by macdonst** [comment] 2015-11-23 18:12
Closing, no input for almost a month.

**Closed by macdonst** 2015-11-23 18:12 UTC
Labels: question
