### ISSUE TITLE
Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin" For input string: "+"

### ISSUE THREAD

**Issue by Ziv-Barber** [phonegap/phonegap-plugin-push#1928] opened 2017-08-30 19:50 UTC
### Expected Behaviour
To compile with Android

### Actual Behaviour
Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin" For input string: "+"

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Cordova 7.0.1
Cordova Android 6.2.3

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by Ziv-Barber** [comment] 2017-08-30 20:05
Workaround:
Use:
cordova plugin add phonegap-plugin-push@1.10.5
The versions above 1.10.5 are broken

**Comment by macdonst** [comment] 2017-08-30 20:08
Duplicate of #1718

**Closed by macdonst** 2017-08-30 20:08 UTC
