### ISSUE TITLE
No sound, no vibration, data.sound & data.vibrate fields not as documented

### ISSUE THREAD

**Issue by ppetree** [phonegap/phonegap-plugin-push#1147] opened 2016-08-05 20:55 UTC
### Expected Behaviour

Payloads are different per platform and doesn't follow documentation for payloads.
Default sound to be played and vibration if those flags are set
### Actual Behaviour

Payload is not per documentation:
-   data.vibrate doesn't exist - this in in additionalData and different between platforms (see below)

No sound played, no vibration.
Android fails to set badge
### Reproduce Scenario (including but not limited to)

Sending using GCM to both platforms.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 9.3.3 on an iPad3, iPhone 4s, iPhone 5
Android 4.2.2 on a NextTab (latest version for that device) 
#### Cordova CLI version and cordova platform version

CLI 5.4.1 for both Android and iOS
#### Plugin version

1.6.4 (latest version that works with XDK)
#### Sample Push Data Payload

**Apple fields to GCM:** 

```
{"priority":"high","notification":{"body":"Life threatening emergency; Heart attack","title":"Medical Emergency","vibrate":true,"custom_field_1":46,"custom_field_2":"2","sound":"default"},"registration_ids":["m_zCoZhBNDE:blahblahblah","mvIqmUsmOYk:blahblahblah"]}
```

**iOS Push Payload:**

```
{"title":"Medical Emergency",
"sound":"default",
"additionalData":{"foreground":false,
                  "gcm.message_id":"0:1470426723672831%b7f1dca2b7f1dca2",
                  "gcm.notification.vibrate":"true",
                  "gcm.notification.custom_field_1":"44",
                  "coldstart":false,
                  "gcm.notification.custom_field_2":"2"},
"message":"Life threatening emergency; Heart attack"}
```

**Android fields to GCM:** 

```
{"priority":"high","data":{"message":"Life threatening emergency; Heart attack","alert":"Medical Emergency","title":"Medical Emergency","category":"Medical Emergency","style":"inbox","vibrate":true,"sound":"default","custom_field_1":46,"custom_field_2":"2"},"registration_ids":["cW5Z_tJ7qo8:blahblahblah"]}
```

**Android Push Payload:**

```
{"message":"Life threatening emergency; Heart attack",
"additionalData":{"category":"Medical Emergency",
                  "custom_field_1":"44",
                  "collapse_key":"do_not_collapse",
                  "custom_field_2":"2",
                  "style":"inbox",
                  "coldstart":false,
                  "vibrate":"true",
                  "foreground":false},
"sound":"default",
"title":"Medical Emergency"}
```
#### Sample Code that illustrates the problem

```
  push.on('notification', function(data) {
      var info = [];
      var msgid;
      var vibrate;
      var sound;

      // data.message,
      // data.title,

      // these two are simply not true...
      // data.sound,
      // data.image,

      // data.count,
      push.setApplicationIconBadgeNumber(function() {
          console.log('icon badge set!');
        }, function() {
          console.log('icon badge failed!');
      }, getUnreads()+1);


      // data.additionalData
      console.log("<p>" +data.title +": " +data.message +"\n\nDebuging Details:\n" +JSON.stringify(data) +"</p>" );

      // alert(data.title +": " +data.message +"\n\nDebuging Details:\n" +JSON.stringify(data));
      switch(device.platform)
      {
        case "Android":
          info['msgid'] = data.additionalData.custom_field_1;   // android
          info['vibrate'] = data.additionalData.vibrate;  
          navigator.vibrate(1000, 3000, 1000, 3000, 1000);
          break;

        case "iOS":
          info['msgid'] = data.additionalData["gcm.notification.custom_field_1"];
          info['vibrate'] = data.additionalData["gcm.notification.vibrate"];
          navigator.vibrate(1000);
          push.finish(function() {
            // ios only console.log("processing of push data is finished");
          });
          break;
      }

  });
```

**Comment by macdonst** [comment] 2016-08-06 15:42
@ppetree hey, apparently I'm not very good at writing documentation as you've mis-understood what I've written. I'd like to clarify the docs then and perhaps you can help me by indicating where I went wrong.

So you have a number of things but let me try and address them all:

- The badge is not set on Android, possibly this is because your phone [does not support badges](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#badges).
- You say you are not getting vibration and sound but I don't see how you [initialized the plugin](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushnotificationinitoptions). You will need to make sure that those options are enabled. For instance:

```
var push = PushNotification.init({
    android: {
        senderID: "12345679",
        sound: true,
        vibrate: true
    },
    ios: {
        alert: "true",
        badge: true,
        sound: 'false'
    }
});
```
- You will never see `data.vibrate` that is not a top level member of the push data I include when calling the push event. Anything you send in the push payload to GCM/APNS that isn't [listed in this table](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#callback-parameters-2) will end up in `data.additionalData`.
- Finally, when your app is the in the foreground the plugin doesn't play a sound or vibrate the phone. That is up to you to handle in the notification event listener. It is only when the app is in the background and the notification appears in the shade that sound/vibration happen. This is by design. When the user is actively using your app having it vibrate and play a sound is distracting so I leave it up to individual app developers to decide how they want to handle it.

If this anser helps, please help me make the docs better.

**Comment by ppetree** [comment] 2016-08-06 15:56
Funny.  I woke up this morning and realized (before coffee even) that I had forgotten to include the initialization code.  It's here:

`  var push = PushNotification.init({
      android: {
          senderID: "35xxxxxxxxx",
          sound: true,
          vibrate: true,
          clearNotifications: true,   // clear notifications from shade on app start
          forceShow: true             // ??
      },
      ios: {
          senderID: "35xxxxxxxxx",
          alert: true,
          badge: true,
          sound: true
          // sandbox: true
      },
      windows: {}
  });
`

The documentation shows
`
      // data.message,
      // data.title,
      // data.sound,
      // data.image,
      // data.count,
      // data.additionalData
`

One of the reasons I included both sides is that there is scant little documentation on sending through GCM to this plugin.  It's mostly trial and error and I think, by the time most developers get it working, they never have time to post and help others.  Hopefully, this will help those who come behind me.  

I did notice there is also a difference between 'sound' and 'soundName' - these little platform dependencies are not obvious.  From the docs, I really expected the plugin was going to 'harmonize' the two platforms so that I only had one set of code to deal with.  

Also, that may account for why I wasn't getting any sound on the Android but not why I'm not getting any sound on the iOS devices.  I question whether sound: true = sound: "true" = sound: default = sound = "default.

It is also completely unclear to me how to pass or play custom sounds.  

Thanks for working on a Saturday...

**Comment by macdonst** [comment] 2016-08-06 16:53
@ppetree Don't get the `PushNotification.init()` parameters confused with the payload to the `on('notification')` event handler. The first controls the plugin behaviour. The second is the data received from the remote messaging system.

The GCM support on iOS is not great but since Google has deprecated GCM in favour if Firebase Cloud Messagin (FCM) we've decided just to make FCM support in v2.0.0 better instead of focusing on a deprecated method.

On Android when you send the payload you would use `soundname` but you can also use `sound` as I check both properties when the push arrives. Yes, the plugin harmonizes the client side API. I can't do anything about making the server side harmonized. Both GCM and APNS expect their payloads in a certain format.

If you use:

```
var push = PushNotification.init({
    android: {
        senderID: "12345679",
        sound: true,
        vibrate: true
    },
    ios: {
        alert: "true",
        badge: true,
        sound: 'false'
    }
});
```

and send this payload to Android:

```
{
    "registration_ids": ["my device id"],
    "data": {
        "title": "Default",
        "message": "Plays default notification sound",
        "sound": "default"
    }
}
```

you should hear the default sound when the application is in the background. 

For iOS using GCM the payload would be:

```
{
    "registration_ids": ["my device id"],
    "notification": {
        "title": "Default",
        "body": "Plays default notification sound",
        "sound": "default"
    }
}
```

Note on Android the object is called `data` and on iOS it is called `notification`. Stupid that we have to do this but hoping it is fixed in FCM.

To play custom sounds they need to be part of [res/raw on Android](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#sound) and the [bundle on iOS](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#sound-1) then you just give it the name of the file without extension when you send the push.

**Comment by ppetree** [comment] 2016-08-06 17:02
And that has been my issue, no sound is being played on either platform.

I'm using the 2nd custom field to pass in the message type so I can figure out which sound to play from that but was hoping I could just pass in the name... apparently, XDK makes it rather difficult to get the sound files in the correct location.

I won't have another build until Monday... I'll let you know what changing sound to soundname caused on the Android.  Still nothing on the ios.

**Comment by macdonst** [comment] 2016-08-06 17:04
@ppetree oh, XDK. I get you now. Yeah, that will be a pain. Try changing value of sound or soundname from `default` to `ringtone` on Android just to make sure the sound property is being picked up. I'm pretty sure this is an issue with XDK not placing the sound files where they are needed in the Android/iOS projects. Maybe @tony-- can comment if he is around.

**Comment by tony--** [comment] 2016-08-08 15:35
@macdonst @ppetree 
How does the custom sound get included in the project?  
Intel XDK build system does not currently support hooks, but if the sound file is declared in plugin.xml it should get installed to the right place, e.g.:
```
<?xml version="1.0" encoding="UTF-8"?>

<plugin xmlns="http://apache.org/cordova/ns/plugins/1.0"
    xmlns:rim="http://www.blackberry.com/ns/widgets"
    xmlns:android="http://schemas.android.com/apk/res/android"
    id="intel-xdk-custom-sound-installer-test"
    version="0.0.1">
    <name>Custom Sound Installer</name>
    <description>Test installing custom sounds to res/raw</description>

    <platform name="android">
        <source-file src="xdkbeep.wav" target-dir="res/raw" />
    </platform>

</plugin>
```

I just tested using a plugin similar to the above with the Intel XDK build system and the resulting .apk had res/raw/xdkbeep.wav:
```
[~/Downloads/phonegap-push-issue-1147.cordova.crosswalk.201608082523]$ tar -tvf cordova_project-armv7.android.20160808152750.apk | grep beep
-rwxrwxrwx  0 0      0        9702 Aug  8 15:25 res/raw/xdkbeep.wav
```

One thing to keep in mind with Android is that different devices support different sound formats.
Even if the sound file is in the right place, it might not play if it is in the wrong format.

**Comment by ppetree** [comment] 2016-08-10 20:38
@tony @macdonst

Great info... certainly leads to an awesome workaround.

When you modify the plugin.xml and add the xdkbeep.wav, where do you need
to put the wave file so that it gets picked up and included in the build?
My guess is somewhere in the plugin directory but I wouldn't know exactly
where.

In my case there are only two custom sound files... one sounds like the
emergency broadcast alert you here on radio or TV and the other like three
short bwerps from a siren when you're getting pulled over.by the police.
The rest of the alerts can be the normal/default sound... which is played
on the iPhone and iPad but still not on the Android device.

**Comment by tony--** [comment] 2016-08-10 20:41
@ppetree Plugin file location is relative to the root directory of the plugin.  As written in the example, the files would go in the root of the plugin directory (in the same directory as plugin.xml).

**Comment by ppetree** [comment] 2016-08-10 22:25
Thanks @tony That was my first instinct but I find many things about this process to be counter intuitive. I strongly prefer XDK over the "other" ways but there are parts that just don't add up.

**Comment by ppetree** [comment] 2016-11-23 19:58
Okay, I'm circling back around to this... it's the last remaining issue before release.

Adding the sound file to the plugin-push plugin.xml file is a bad idea.  If you do this you have to remove the plugin from your project and add it again in order for the sound files to get included.  It's far easier to create a simple plugin that does nothing other than install the files. I have done this using this code (for anyone who needs it):

`
<?xml version="1.0" encoding="UTF-8"?>  
<plugin xmlns="http://apache.org/cordova/ns/plugins/1.0" id="sounds-phonegap-push-plugin" version="1.0.0"> 

    <name>Adding custom sounds to Phonegap XDK builds</name> 
    <description>Add customized sounds to XDK phonegap builds.</description> 
    <license>MIT</license> 

    <engines> 
        <engine name="cordova" version=">=3.0.0" /> 
    </engines>  

     
    <platform name="android">        
        
        <resource-file src="snd/eas.wav" target="res/raw/eas.wav" />
        <resource-file src="snd/bwerp.wav" target="res/raw/bwerp.wav" />
    </platform>  

     
    <platform name="ios">
        
        <resource-file src="snd/eas.wav" target="res/raw/eas.wav" />
        <resource-file src="snd/bwerp.wav" target="res/raw/bwerp.wav" />
    </platform>     
</plugin>
`

Now, the .wav soundfiles are indeed installed in the res/raw folder as eas.wav and bwerp.wav. However, I still get no custom sound.

In my push class which sends the push notification via GCM, I have these lines of code.
        $this->pushMessageAndroid['soundname'] = "eas";   // EAS sound
        $this->pushMessageApple['sound'] = "eas";

On Android, I get no sound using these settings. However, if I set these lines to "default" then the default sound gets played.

On iOS I get the default sound regardless.

**Closed** 2016-12-02 19:26 UTC
Labels: question
