### ISSUE TITLE
Receive Notifications in Background

### ISSUE THREAD

**Issue by christocracy** [phonegap/phonegap-plugin-push#93] opened 2015-09-01 19:46 UTC
This plugin is unable to receive notifications while in the background since it doesn't implement [application:didReceiveRemoteNotification:fetchCompletionHandler:](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/#//apple_ref/occ/intfm/UIApplicationDelegate/application:didReceiveRemoteNotification:fetchCompletionHandler:)

![](https://www.dropbox.com/s/7xms78km574vvbr/Screenshot%202015-09-01%2015.45.07.png?dl=1)

**Discussion**
>Use this method to process incoming remote notifications for your app. Unlike the 
>`application:didReceiveRemoteNotification:` method, which is called **only when your app is running in >the foreground**, the system calls this method when your app is running in the **foreground or background**

Clearly [this logic](https://github.com/phonegap/phonegap-plugin-push/blob/master/src/ios/AppDelegate%2Bnotification.m#L74) in `didReceiveRemoteNotification` is useless, since that method is **only called in the foreground**.

```
    if (appState == UIApplicationStateActive) {   // <-- Will always be true.
        PushPlugin *pushHandler = [self getCommandInstance:@"PushNotification"];
        pushHandler.notificationMessage = userInfo;
        pushHandler.isInline = YES;
        [pushHandler notificationReceived];
    } else {
        //save it for later
        self.launchNotification = userInfo;
    }
```

**Comment by greg84** [comment] 2015-09-01 23:01
I've been debugging this with xcode. The else block is hit when the application is started as a result of the user tapping a notification when the app is not in the foreground (i.e. in the task switcher). In this case the plugin invokes the javascript 'notification' event callback with details of the push message when the init method is called.

Out of interest, do you know if implementing the `fetchCompletionHandler` variant of this method would allow javascript to run inside the Cordova web view when the app is started in the background?

As a side note, after the app is force quit (double tap home, swipe up) and the device is locked, tapping a notification will bypass the `didReceiveRemoteNotification` event completely. Although this seems to be by design - see #50.

**Comment by christocracy** [comment] 2015-09-01 23:11
I created a [cordova plugin](https://github.com/christocracy/cordova-plugin-background-notification/blob/master/src/ios/CDVBackgroundNotification.m#L81) some time ago when using UrbanAirship to receive notifications in the background.

Implementing the `fetchCompletionHandler` variant *does* allow Javascript to run when the app is started in the background.

The important thing is that one must allow Javascript to [signal the end](https://github.com/christocracy/cordova-plugin-background-notification/blob/master/src/ios/CDVBackgroundNotification.m#L81) of the `fetchCompletionHandler`.

For example:

```
var pushPlugin = window.PushNotification;

pushPlugin.on('notification', function(data) {
    // do stuff with data
   .
   .
   .
   // Signal to native code that our task is complete so it can finish the completionHandler
   pushPlugin.finish();
});
```

**Comment by cmartin81** [comment] 2015-09-04 09:27
+1 for this feature

**Comment by macdonst** [comment] 2015-09-04 11:51
@christocracy please feel free to send a PR with this functionality.

**Comment by christocracy** [comment] 2015-09-04 12:10
When PhoneGap fixes their plugin and stops including static jar files (eg android-support-v4.jar), breaking other peoples' plugins, I'll consider contributing a PR.

**Comment by cmartin81** [comment] 2015-09-04 14:05
Are there any other good plugins for push I can use that does not break other plugins?

**Comment by slorber** [comment] 2015-09-04 15:16
@christocracy what exactly do you mean by "receive notifications while in the background"?

Because on this [issue](https://github.com/phonegap/phonegap-plugin-push/issues/101#issuecomment-137755947) I notice I can receive notifications only when the app is in foreground. When the app is closed or not in the foreground, nothing happens at all.

I don't know if this is what this issue is about but for me this is not an enhancement but a bug as it makes the plugin barely unusable :'(

**Comment by christocracy** [comment] 2015-09-04 15:32
For ios in particular, an app can receive a push notification while the app is in the background.  iOS can awaken the app in the background and provide **exactly** 30s of background running-time.

But only if the push-plugin implements the [application:didReceiveRemoteNotification:fetchCompletionHandler:](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/#//apple_ref/occ/intfm/UIApplicationDelegate/application:didReceiveRemoteNotification:fetchCompletionHandler:) method variant

This plugin does not implement this variant thus an iOS app cannot be awakened in the background due to a push request.

An example usage of this feature could be a server which desires to know the geolocation of a device or devices.  The server could send a *silent* "where are you?" push-request with a JSON-body only (e.g.: `{"action":"getCurrentPosition"}`).  The app on the device would awaken, decode the JSON-body and choose to fetch the device's current-position and send it back to the server.

This is how Apple's "Find Friends" app works.

**Comment by slorber** [comment] 2015-09-04 15:50
Ok so that seems nice for background sync but it may not be related to my problem :) thanks

**Comment by larsar** [comment] 2015-09-04 17:15
+1

**Comment by berndartmueller** [comment] 2015-09-05 13:30
Does this mean that right now this plugin can not handle push notifications when app is in background?

**Comment by christocracy** [comment] 2015-09-05 13:50
Without a doubt, this plugin can only receive a Push notification while
running in the foreground.




On Saturday, September 5, 2015, Bernd Artmüller <notifications@github.com>
wrote:

> Does this mean that right now this plugin can not handle push
> notifications when app is in background?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-plugin-push/issues/93#issuecomment-137955991>
> .
>


-- 
Snet form Gmail Mobile

**Comment by berndartmueller** [comment] 2015-09-05 13:53
Hmm, is there a simple way to fix this myself? I tried to enable "Remote notifications" but that did not work.

**Comment by christocracy** [comment] 2015-09-05 13:59
No simple way.  It needs an obj-c method implemented including some careful handling of the completionHandler callback, as I clearly documented above, including an example usage from one of my plugins.

**Comment by berndartmueller** [comment] 2015-09-05 14:07
Ok, but the deprecated plugin https://github.com/phonegap-build/PushPlugin also does not implement the "application:didReceiveRemoteNotification:fetchCompletionHandler:" method, nevertheless background notifications are working.

**Comment by christocracy** [comment] 2015-09-05 14:17
You're not understanding.

Speaking of iOS, in particular, With your app running in background, you
will see a notification appear, of course.  This is done automatically by
the OS.

However, your JavaScript callback is not being executed.  What if the push
notification has a JSON payload that your app needs to decode and
respond-to?

The JavaScript callback cannot be executed in the background with this
plugin.


On Saturday, September 5, 2015, Bernd Artmüller <notifications@github.com>
wrote:

> Ok, but the deprecated plugin https://github.com/phonegap-build/PushPlugin
> also does not implement the
> "application:didReceiveRemoteNotification:fetchCompletionHandler:" method,
> nevertheless background notifications are working.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-plugin-push/issues/93#issuecomment-137958359>
> .
>


-- 
Snet form Gmail Mobile

**Comment by berndartmueller** [comment] 2015-09-05 14:22
Oh sorry, then we are talking about different things. I'm sending push notifications to my unlocked iOS device (app is in background) and would like them to display with a banner. iOS receives the notification but does not display it with a banner (like WhatsApp).

**Comment by christocracy** [comment] 2015-09-05 14:26
If you want to execute a js callback in background due to push, this plugin
won't do it

On Saturday, September 5, 2015, Bernd Artmüller <notifications@github.com>
wrote:

> Oh sorry, then we are talking about different things. I'm sending push
> notifications to my unlocked iOS device (app is in background) and would
> like them to display with a banner. iOS receives the notification but does
> not display it with a banner (like WhatsApp).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-plugin-push/issues/93#issuecomment-137959991>
> .
>


-- 
Snet form Gmail Mobile

**Comment by slorber** [comment] 2015-09-07 09:50
@christocracy I'm trying to understand a little better to know if issue #109 is a duplicate or not

I'm thinking of different usecases:

#### Receiving notifications in foreground: 
No problem here.

#### Receiving notification in background and notification to the user:
When the user clicks on the notification, the app should open and the notification callback be triggered.

#### Receiving notification in background, and executing callback while still in background
As far as I understand this is your usecase no? I understand that you want to be able to run js code for 30 seconds inside the Cordova app, without even putting this app in foreground.


I think #109 is more about the 2nd case, as the user mention he "opens the app" while you never open the app in your usecase

**Comment by christocracy** [comment] 2015-09-07 09:53
My concern is use-case #3.

On Monday, September 7, 2015, Sébastien Lorber <notifications@github.com>
wrote:

> @christocracy <https://github.com/christocracy> I'm trying to understand
> a little better to know if issue #109
> <https://github.com/phonegap/phonegap-plugin-push/issues/109> is a
> duplicate or not
>
> I'm thinking of different usecases:
> Receiving notifications in foreground:
>
> No problem here.
> Receiving notification in background and notification to the user:
>
> When the user clicks on the notification, the app should open and the
> notification callback be triggered.
> Receiving notification in background, and executing callback while still
> in background
>
> As far as I understand this is your usecase no? I understand that you want
> to be able to run js code for 30 seconds inside the Cordova app, without
> even putting this app in foreground.
>
> I think #109 <https://github.com/phonegap/phonegap-plugin-push/issues/109>
> is more about the 2nd case, as the user mention he "opens the app" while
> you never open the app in your usecase
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-plugin-push/issues/93#issuecomment-138254852>
> .
>


-- 
Snet form Gmail Mobile

**Comment by alexislg2** [comment] 2015-09-07 21:58
Concern of https://github.com/phonegap/phonegap-plugin-push/issues/109 is indeed use-case 2. https://github.com/phonegap/phonegap-plugin-push/issues/109 is therefore not a duplicate of https://github.com/phonegap/phonegap-plugin-push/issues/93

**Comment by AndersNederhoed** [comment] 2015-09-13 16:09
+1

**Comment by mellinas** [comment] 2015-09-14 13:40
+1

**Comment by GabrielFerraz** [comment] 2015-09-16 21:11
+1

**Comment by oscarabilleira** [comment] 2015-09-17 06:08
+1 any advance on this issue

**Comment by christocracy** [comment] 2015-09-17 06:20
Crickets is all you'll get from @phonegap.  I clearly described exactly what needs to be done.  

I could implement it in 3 hours but I'm not touching this plugin until they support grade and stop including static jars.

**Comment by fredgalvao** [comment] 2015-09-17 20:43
It does now, @christocracy . Since https://github.com/phonegap/phonegap-plugin-push/commit/6b5bebb85c94cca0a734c743b37a50fccc57c8c7, this project has been enabled to work with gradle dependencies properly, so if that was the only concern blocking this feature, we're on our way to freedom :smile:

**Comment by slorber** [comment] 2015-09-18 09:59
@christocracy 

About your code snippet

```javascript
var pushPlugin = window.PushNotification;

pushPlugin.on('notification', function(data) {
    // do stuff with data
   .
   .
   .
   // Execute an Async xhr
   $.post({
       url: 'foo.com',
       callback: function() {
           pushPlugin.finish();  // <-- signal to native code that our task is complete.
       }
   });
});
```

As far as I understand, this feature may allow that callback to run into the background.

Maybe we should use another separate callback then no?

Having stuff running in the background does it mean there's nothing to be shawn in status bar? If there is still something to be shawn in status bar, when user clicks on that notification isn't it supposed to run the "notification" callback (thus making it run twice?)

Just an idea, but IMHO I think there should be a separate callback. To prevent concurrency issues I think the callback should provide a mean to tell the plugin the end (not global `pushPlugin.finish()`)

Also the callback could provide the absility to tell the plugin wether or not this notification has been totally handled in the background (ie weither or not we should show something in the status bar).
Maybe we should not show the statusbar notification until the done() method has been called.


In the end something like that:

```javascript
var pushPlugin = window.PushNotification;

pushPlugin.on('backgroundNotification', function(data,doneCallback) {
   $.post({
       url: 'foo.com',
       callback: function() {
           // use showInStatusBar: false if all the stuff has been done in background and you don't want the user to be notified at all
           doneCallback({ showInStatusBar: true });
       }
   });
});

pushPlugin.on('notification', function(data) {
    // do stuff with data
});
```

Just some ideas, I don't really know how it works on iOS so....

**Comment by cmartin81** [comment] 2015-09-18 10:51
In my case I want to check if  the user is still logged in and display a **local** notification with content that is fetched from the server (and not  display a message if the user is signed out). 

I agree that we should have a separate method for backgroundNotification.

**Comment by fredgalvao** [comment] 2015-09-18 19:32
@slorber 's approach seems reasonable. +1 on that.
Such an event and feature would make me not need to edit GCMIntentService.java with some custom code of mine and also make my new custom code work on both ios and android. I'm looking foward to that!

**Comment by garrettlangley** [comment] 2015-09-24 11:16
@macdonst what is the expected timeline for this fix?

**Comment by GabrielePrestifilippo** [comment] 2015-09-27 14:06
+1

**Comment by Benew** [comment] 2015-10-01 15:30
+1

**Comment by fouzko** [comment] 2015-10-01 15:31
+1

**Comment by VincentPuget** [comment] 2015-10-01 15:31
+1

**Comment by cmartin81** [comment] 2015-10-01 19:31
I am really looking forward to this fix!

**Comment by silasakk** [comment] 2015-10-05 02:25
+1

**Comment by kait85** [comment] 2015-10-05 22:30
+1 !

**Comment by uriva** [comment] 2015-10-06 14:07
+1

**Comment by elliotdennis** [comment] 2015-10-06 18:52
+1

**Comment by ramyacl** [comment] 2015-10-14 09:22
-(void)application:(UIApplication *)application
didReceiveRemoteNotification:(NSDictionary *)userInfo
      fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler{}
 How to call the above method in ios?

**Comment by VioletaCalvo** [comment] 2015-10-23 14:49
+1

**Comment by macdonst** [comment] 2015-10-23 14:56
It's coming all, pull branch `issue93` if you want to test. You'll need to send "content-available: 1" in your "aps" payload.

**Comment by christocracy** [comment] 2015-10-23 15:50
#93 is Looking good :)

**Comment by GabrielePrestifilippo** [comment] 2015-10-23 16:20
With #93, is it working just on iOS or also with Android?

**Comment by macdonst** [comment] 2015-10-23 16:34
@GabrielePrestifilippo yeah, it will work with iOS and Android. I need to document it.

**Comment by macdonst** [comment] 2015-10-23 16:38
@christocracy cool, thanks for the review. I need to clean it up but I hope to have it out by Monday.

**Comment by silasakk** [comment] 2015-10-25 09:50
android  cannot trigger  notification when background process but ios OK
push.on('notification', function (data) {

});

**Closed** 2015-10-26 18:24 UTC
Labels: enhancement

**Comment by rastermax** [comment] 2015-11-25 03:38
@macdonst  THANKS for the work on this feature.

I updated the plugin through cordova rm plugin and cordova add plugin, but from what I see (im new to cordova dev), the version i get is not the latest from git ? is there a normal delay between versions here and the ones we get from cordova add plugin ?

thanks in advance
and again thanks for taking the time to improve this plugin.

**Comment by gongfan99** [comment] 2015-12-21 07:24
I am curious about a question of GCM payload. For example, if I need to show notification in the shade when app is in background, this plugin requires the payload to be like:

```javascript
{
	"to" : registrationId,
	"data" :
	{
		"title" : "Portugal vs. Denmark",
		"message" : "Data: please check score",
		"myOwnData": "blablabla"
	}
}
```

However, per "Hybrid messages with both notification and data payload" section of Google's official website: https://developers.google.com/cloud-messaging/concept-options

It mentions "notification" and "data" fields. And "title", "message" should be put in the "notification" so that Android will show them in the shade for background app. My speculation is that this plugin modifies the default Android behavior so that "title", "message" can be put in "data" field. Is this correct?

**Comment by macdonst** [comment] 2015-12-21 15:46
@rastermax if you do an add directly from the git url you'll get the current development version. It may or may not be stable.

@gongfan99 the latest version of the plugin should work with data/notification in the same payload.

**Comment by deceadmin** [comment] 2016-01-03 19:26
Hi,
I am not able to run the use-case #3 mentioned above. In "onnotification" function I'm saving message to local database. For both Android and iOS (and for both app is running in background and closed completely) notification alert is handled by OS and when user taps the message my code is running (saves to db). But, if I directly open app (not by clicking the notification), nothing happens (onnotification event is not called). 
I've tried combinations of content-available and other payload data in the examples. What is the point I am missing?
I'm using ionic service to send notification messages. 
<img width="1280" alt="screen shot 2016-01-03 at 21 24 55" src="https://cloud.githubusercontent.com/assets/14159882/12080341/90e1b0c4-b260-11e5-8320-f14e66f96068.png">

**Comment by mravi123** [comment] 2016-01-08 18:35
background notification not working on android

**Comment by barocsi** [comment] 2016-01-24 22:20
I do receive the notification however when it opens the application the push notification wont work instead:
Error in Success callbackId: PushNotification1215169404 : TypeError: Cannot read property 'id' of undefined

**Comment by macdonst** [comment] 2016-01-25 14:11
@barocsi then you need to look at where you access 'id' in your `on('notification')` event handler.

**Comment by barocsi** [comment] 2016-01-25 16:32
Thanks @macdonst the problem was on my side.

**Comment by boyfunky** [comment] 2016-02-25 10:49
has anyone been able to receive notifications in background on android? i cant seem to catch it at all and i always get an error when i do this as well 

```
var pushPlugin = window.PushPlugin;
pushPlugin.on('notification', function(notification) {

})

var pushPlugin = window.PushNotification; 
pushPlugin.on('notification', function(notification) {

})
```

All not working and all give me the same error, pushPlugin.on('notification') is not a function. How do i call the phonegap-plugin-push from my deviceready event?

**Comment by slorber** [comment] 2016-02-25 13:08
`PushNotification.init(cfg).on("notification",...)` ?

@boyfunky just try the hello world example first maybe?

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/EXAMPLES.md

**Comment by gongfan99** [comment] 2016-02-26 19:32
@boyfunky make sure you run "cordova plugin add phonegap-plugin-push" before you run "cordova build"

**Comment by boyfunky** [comment] 2016-03-02 03:31
@gongfan99 yes i have already done that. @deceadmin how did you solve ur issue. I am having the same exact issue.

**Comment by rastermax** [comment] 2016-03-02 14:15
hi, maybe that can help.
Recently I cleared my server code to send a notification and reading the
docs about payload and what appears when app is off or in background here
is what my server (nodejs) code looks like:

var notifMessage = new gcm.Message({
    collapseKey: "MyAppGeneral",
    delayWhileIdle: false,
    timeToLive: 3, //weeks
    // what is shown
    notification: {
        title: "SpotiQuiz Message",
        icon: "icon",
        body: "THIS IS A TEST"
    },
    //attached payload
    data: {
        nico1: "secret data1",
        nico2: "secret data2"
    }
});



var regTokens = [obj.android_push_id]; //destination user push id

var sender = new gcm.Sender(GOOGLE_CLOUD_MESSAGING_KEY); //your GOOGLE
PUSH KEY FOR YOUR APP

sender.send(notifMessage, {registrationTokens:regTokens},
function(err,response){
   if(err){
       console.log("notifUser:ERROR:Could not send android notification");
   } else {
       console.log("notifUser:NotifSents:"+response);
   }
});




Hope it can help.

**Comment by deceadmin** [comment] 2016-03-03 18:30
@boyfunky, i could not solve it

**Comment by asinha08** [comment] 2016-04-04 15:12
For Android it so doesn't work when app is in background.

Is there any alternate plugin. which do not have such issues?

**Comment by ShaunBrassell** [comment] 2016-04-22 11:37
I finally solved my background android issue! I would receive fine when app in the foreground, and would happily receive the tray notification when in the background, but my push.on('notification', function(data) {} would not fire at all in the background .... which is what I really wanted as I want to activate the GPS without the user having to click the tray notification. I knew I had to set content_available = 1 ... BUUUUT it is content-available and NOT content_available!! Silly mistake, but I think the "content_available": true, example in the docs threw me!

Hope that helps someone!

 When looking at the android debug, I saw that

**Comment by pravinsa** [comment] 2017-01-04 06:34
Hello All
I receive notification in background but while tap on notification, i am unable to get data.

**Comment by bfx** [comment] 2017-01-17 11:41
No event-handler called with background app on iOS (it works on android), using GCM/FCM.
- phonegap-plugin-push@1.9.2
Using node-gcm to test with these payloads:

```
var message = new gcm.Message({
    priority: "high", //needed when using FCM > iOS
    data: {
      title: "data title",
      message: "data message",
      "content-available": 1,
    },
   notification: { title: "title", body: "message"},
    // as documented in PAYLOAD.md
   aps: {
      "content-available": 1,
    },
    notId: 42
});

```

Is documentation here updated? 
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications-1

**Comment by christocracy** [comment] 2017-01-17 12:33
Does your iOS app have the background "notification" entitlement in the
.plist?
-- 
Snet form Gmail Mobile

**Comment by bfx** [comment] 2017-01-17 12:58
It's a ionic app, and on xcode I've enabled the remote notifications in Background Modes.
I've "remote-notifications" in UIBackgroundModes in the info.plist.

**Comment by coderroggie** [comment] 2017-02-16 01:03
@bfx This may be a bit dated but I'm working through the same documentation now on version 2.0.x version of the code.  I believe the docs you are referring to above referencing the payload are in fact the docs for the APNS version of the API.  If I understand it properly, node-gcm sends to google who turns around and sends to APNS for you.  https://firebase.google.com/docs/cloud-messaging/http-server-ref indicates you should likely be sending something like:
```
var message = new gcm.Message({
    priority: "high", //needed when using FCM > iOS
    data: {
      title: "data title",
      message: "data message",
    },
   notification: { title: "title", body: "message"},
   content-available: 1,                  
   notId: 42
});
```
Note the ```content-available:1``` is no longer a child of ```aps```.  I'm assuming (but don't know for sure) that fcm turns around and sends something like you see documented in Payload to APNS.

Hope that helps, but as with most things, YMMV.

Cheerio.

**Comment by vovikdrg** [comment] 2017-06-08 14:56
@coderroggie btw content-available should be "content_available": true,
