### ISSUE TITLE
Pushes with title and message

### ISSUE THREAD

**Issue by ferdelcorro** [phonegap/phonegap-plugin-push#2046] opened 2017-10-31 18:03 UTC
### Expected Behaviour
A want to hide push and never display a message

### Actual Behaviour
I sended two messages (one on silence mode and other with title/message) and my app is displaying both.

cordova version 7.1.0
cordova-android version 6.3.0
plugin version 1.10.5

#### Sample Push Data Payload
I dont send a message/title
![captura de pantalla de 2017-10-31 14-35-58](https://user-images.githubusercontent.com/9002601/32240474-34ae5682-be4c-11e7-86e1-ed1c4694d33a.png)

I dont send a message/title but the push display my app name if it doesn't has this fields.
![screenshot_2017-10-31-14-32-40](https://user-images.githubusercontent.com/9002601/32240456-294ea85a-be4c-11e7-9aef-42a463e28b55.png)

And i have a png in my /platform/android/res/drawable and the pushes don't use it.
`
push = PushNotification.init({
                android: {
                    senderID: androidSenderID,
                    sound: "true",
                    icon: "new_icon",
                    iconColor: "#95D1C4"
                },
                ios: {
                    senderID: androidSenderID,
                    alert: "true",
                    badge: "true",
                    sound: "true"
                },
                windows: {}
            });
`

**Comment by macdonst** [comment] 2017-10-31 18:20
@ferdelcorro the actual payloads you send would be helpful and log via `adb logcat | grep Push` would also be nice.

**Comment by ferdelcorro** [comment] 2017-10-31 19:16
This is my json to GCM
![captura de pantalla de 2017-10-31 16-10-30](https://user-images.githubusercontent.com/9002601/32244241-b4356de6-be56-11e7-9fbd-73194c3edbc6.png)

and this is my adb logcat | grep Push
![captura de pantalla de 2017-10-31 16-09-21](https://user-images.githubusercontent.com/9002601/32244238-b1818896-be56-11e7-97c2-7f77ef48ed9b.png)

**Comment by ferdelcorro** [comment] 2017-11-01 01:31
I discovered, the pushes don't have sound and vibration :(

**Comment by macdonst** [comment] 2017-11-01 03:00
@ferdelcorro take out the `notification: { badge: 23 }` part and see what happens.

**Comment by ferdelcorro** [comment] 2017-11-01 12:41
My wrong, i am sending badge in data not in notification, i change it to a test and forgot revert my change to sended you a picture, do i need remove from data to? @macdonst

**Comment by macdonst** [comment] 2017-11-01 14:42
@ferdelcorro no but if I could see the actual payload you are sending that would really help. Also, can you just past the text instead of a screen shot?

**Comment by ferdelcorro** [comment] 2017-11-01 17:50
fer@Fer:~/Escritorio/ionicApp/platforms/android/build/outputs/apk$ adb logcat | grep Push

V/PushPlugin(12739): execute: action=init
V/PushPlugin(12739): execute: data=[{"android":{"senderID":"senderID","sound":"true","icon":"new_icon","iconColor":"#95D1C4"},"ios":{"senderID":"senderID","alert":"true","badge":"true","sound":"true"},"windows":{}}]
V/PushPlugin(12739): execute: jo={"senderID":"senderID","sound":"true","icon":"new_icon","iconColor":"#95D1C4"}
V/PushPlugin(12739): execute: senderID=senderID
V/PushPlugin(12739): onRegistered: {"registrationId":"fGP8J0W8AeI:APA91bEY2iK4JijrowPghi0OpvTMycT88Wvi5UTrT8r-ZLoCtYlUQbj0099te-zCWwO-jJSX_534ajkVIn-bmgxR9hP6I6D3Cpy_WQnqoCxQNJjJyrlH8dHOqe34CXB6AGZmYTWS9Fp4"}
D/PushPlugin_GCMIntentService(12739): onMessage - from: senderID
D/PushPlugin_GCMIntentService(12739): normalize extras
D/PushPlugin_GCMIntentService(12739): key = google.sent_time
D/PushPlugin_GCMIntentService(12739): replace key google.sent_time with google.sent_time
D/PushPlugin_GCMIntentService(12739): key = payload
D/PushPlugin_GCMIntentService(12739): replace key payload with payload
D/PushPlugin_GCMIntentService(12739): key = google.message_id
D/PushPlugin_GCMIntentService(12739): replace key google.message_id with google.message_id
D/PushPlugin_GCMIntentService(12739): key = notification
D/PushPlugin_GCMIntentService(12739): notifkey = badge
D/PushPlugin_GCMIntentService(12739): replace key badge with count
D/PushPlugin_GCMIntentService(12739): key = collapse_key
D/PushPlugin_GCMIntentService(12739): replace key collapse_key with collapse_key
D/PushPlugin_GCMIntentService(12739): foreground
D/PushPlugin(12739): convert extras to json
D/PushPlugin(12739): key = google.sent_time
D/PushPlugin(12739): key = payload
D/PushPlugin(12739): key = count
D/PushPlugin(12739): key = google.message_id
D/PushPlugin(12739): key = coldstart
D/PushPlugin(12739): key = collapse_key
D/PushPlugin(12739): key = foreground
V/PushPlugin(12739): extrasToJSON: {"count":"3","additionalData":{"payload":{"global_badges":{"notifications_associated_account":null,"competition-detail_quantity":[{"count":4,"target":77369260}],"questions_quantity":3,"messenger_quantity":131,"id":136165659,"competition_quantity":4,"notifications_quantity":0},"function":"updateQuestions","question_id":5088299653},"google.message_id":"0:1509558479740480%bc50674abc50674a","coldstart":false,"collapse_key":"com.real_trends","foreground":true}}
D/SystemWebChromeClient(12739): file:///android_asset/www/js/common/services/PushNotificationsModule.js: Line 25 : updateQuestionsFunction
I/chromium(12739): [INFO:CONSOLE(25)] "updateQuestionsFunction", source: file:///android_asset/www/js/common/services/PushNotificationsModule.js (25)
D/PushPlugin_GCMIntentService(12739): onMessage - from: senderID
D/PushPlugin_GCMIntentService(12739): normalize extras
D/PushPlugin_GCMIntentService(12739): key = google.sent_time
D/PushPlugin_GCMIntentService(12739): replace key google.sent_time with google.sent_time
D/PushPlugin_GCMIntentService(12739): key = payload
D/PushPlugin_GCMIntentService(12739): replace key payload with payload
D/PushPlugin_GCMIntentService(12739): key = google.message_id
D/PushPlugin_GCMIntentService(12739): replace key google.message_id with google.message_id
D/PushPlugin_GCMIntentService(12739): key = notification
D/PushPlugin_GCMIntentService(12739): notifkey = badge
D/PushPlugin_GCMIntentService(12739): replace key badge with count
D/PushPlugin_GCMIntentService(12739): key = collapse_key
D/PushPlugin_GCMIntentService(12739): replace key collapse_key with collapse_key
D/PushPlugin_GCMIntentService(12739): foreground
D/PushPlugin(12739): convert extras to json
D/PushPlugin(12739): key = google.sent_time
D/PushPlugin(12739): key = payload
D/PushPlugin(12739): key = count
D/PushPlugin(12739): key = google.message_id
D/PushPlugin(12739): key = coldstart
D/PushPlugin(12739): key = collapse_key
D/PushPlugin(12739): key = foreground
V/PushPlugin(12739): extrasToJSON: {"count":"3","additionalData":{"payload":{"global_badges":{"notifications_associated_account":null,"competition-detail_quantity":[{"count":4,"target":77369260}],"questions_quantity":3,"messenger_quantity":131,"id":136165659,"competition_quantity":4,"notifications_quantity":0},"function":"updateSales","order_id":1521441872,"open":true},"google.message_id":"0:1509558479938509%bc50674abc50674a","coldstart":false,"collapse_key":"com.real_trends","foreground":true}}
D/SystemWebChromeClient(12739): file:///android_asset/www/js/common/services/PushNotificationsModule.js: Line 42 : updateSalesFunction
I/chromium(12739): [INFO:CONSOLE(42)] "updateSalesFunction", source: file:///android_asset/www/js/common/services/PushNotificationsModule.js (42)
D/PushPlugin_GCMIntentService(12739): onMessage - from: senderID
D/PushPlugin_GCMIntentService(12739): normalize extras
D/PushPlugin_GCMIntentService(12739): key = google.sent_time
D/PushPlugin_GCMIntentService(12739): replace key google.sent_time with google.sent_time
D/PushPlugin_GCMIntentService(12739): key = payload
D/PushPlugin_GCMIntentService(12739): replace key payload with payload
D/PushPlugin_GCMIntentService(12739): key = google.message_id
D/PushPlugin_GCMIntentService(12739): replace key google.message_id with google.message_id
D/PushPlugin_GCMIntentService(12739): key = notification
D/PushPlugin_GCMIntentService(12739): notifkey = badge
D/PushPlugin_GCMIntentService(12739): replace key badge with count
D/PushPlugin_GCMIntentService(12739): key = collapse_key
D/PushPlugin_GCMIntentService(12739): replace key collapse_key with collapse_key
D/PushPlugin_GCMIntentService(12739): foreground
D/PushPlugin(12739): convert extras to json
D/PushPlugin(12739): key = google.sent_time
D/PushPlugin(12739): key = payload
D/PushPlugin(12739): key = count
D/PushPlugin(12739): key = google.message_id
D/PushPlugin(12739): key = coldstart
D/PushPlugin(12739): key = collapse_key
D/PushPlugin(12739): key = foreground
V/PushPlugin(12739): extrasToJSON: {"count":"3","additionalData":{"payload":{"global_badges":{"notifications_associated_account":null,"competition-detail_quantity":[{"count":4,"target":77369260}],"questions_quantity":3,"messenger_quantity":131,"id":136165659,"competition_quantity":4,"notifications_quantity":0},"from_mark_unread":false,"function":"updateOrders","order_id":1521441872},"google.message_id":"0:1509558480467967%bc50674abc50674a","coldstart":false,"collapse_key":"com.real_trends","foreground":true}}
D/PushPlugin_GCMIntentService(12739): onMessage - from: senderID
D/PushPlugin_GCMIntentService(12739): normalize extras
D/PushPlugin_GCMIntentService(12739): key = google.sent_time
D/PushPlugin_GCMIntentService(12739): replace key google.sent_time with google.sent_time
D/PushPlugin_GCMIntentService(12739): key = payload
D/PushPlugin_GCMIntentService(12739): replace key payload with payload
D/PushPlugin_GCMIntentService(12739): key = google.message_id
D/PushPlugin_GCMIntentService(12739): replace key google.message_id with google.message_id
D/PushPlugin_GCMIntentService(12739): key = notification
D/PushPlugin_GCMIntentService(12739): notifkey = badge
D/PushPlugin_GCMIntentService(12739): replace key badge with count
D/PushPlugin_GCMIntentService(12739): key = collapse_key
D/PushPlugin_GCMIntentService(12739): replace key collapse_key with collapse_key
D/PushPlugin_GCMIntentService(12739): foreground
D/PushPlugin(12739): convert extras to json
D/PushPlugin(12739): key = google.sent_time
D/PushPlugin(12739): key = payload
D/PushPlugin(12739): key = count
D/PushPlugin(12739): key = google.message_id
D/PushPlugin(12739): key = coldstart
D/PushPlugin(12739): key = collapse_key
D/PushPlugin(12739): key = foreground
V/PushPlugin(12739): extrasToJSON: {"count":"3","additionalData":{"payload":{"global_badges":{"notifications_associated_account":null,"competition-detail_quantity":[{"count":4,"target":77369260}],"questions_quantity":3,"messenger_quantity":131,"id":136165659,"competition_quantity":4,"notifications_quantity":0},"from_mark_unread":false,"function":"updateOrders","order_id":1521441872},"google.message_id":"0:1509558480476358%bc50674abc50674a","coldstart":false,"collapse_key":"com.real_trends","foreground":true}}
D/PushPlugin_GCMIntentService(12739): onMessage - from: senderID
D/PushPlugin_GCMIntentService(12739): normalize extras
D/PushPlugin_GCMIntentService(12739): key = google.sent_time
D/PushPlugin_GCMIntentService(12739): replace key google.sent_time with google.sent_time
D/PushPlugin_GCMIntentService(12739): key = payload
D/PushPlugin_GCMIntentService(12739): replace key payload with payload
D/PushPlugin_GCMIntentService(12739): key = google.message_id
D/PushPlugin_GCMIntentService(12739): replace key google.message_id with google.message_id
D/PushPlugin_GCMIntentService(12739): key = notification
D/PushPlugin_GCMIntentService(12739): notifkey = body
D/PushPlugin_GCMIntentService(12739): replace key body with message
D/PushPlugin_GCMIntentService(12739): no locale found for key = message, error Value Háganse of type java.lang.String cannot be converted to JSONObject
D/PushPlugin_GCMIntentService(12739): notifkey = badge
D/PushPlugin_GCMIntentService(12739): replace key badge with count
D/PushPlugin_GCMIntentService(12739): notifkey = title
D/PushPlugin_GCMIntentService(12739): replace key title with title
D/PushPlugin_GCMIntentService(12739): no locale found for key = title, error Value Recibiste of type java.lang.String cannot be converted to JSONObject
D/PushPlugin_GCMIntentService(12739): key = collapse_key
D/PushPlugin_GCMIntentService(12739): replace key collapse_key with collapse_key
D/PushPlugin_GCMIntentService(12739): foreground
D/PushPlugin(12739): convert extras to json
D/PushPlugin(12739): key = google.sent_time
D/PushPlugin(12739): key = payload
D/PushPlugin(12739): key = count
D/PushPlugin(12739): key = title
D/PushPlugin(12739): key = google.message_id
D/PushPlugin(12739): key = message
D/PushPlugin(12739): key = coldstart
D/PushPlugin(12739): key = collapse_key
D/PushPlugin(12739): key = foreground
V/PushPlugin(12739): extrasToJSON: {"count":"3","title":"Recibiste un nuevo mensaje","message":"Háganse cargo. Saludos.","additionalData":{"payload":{"global_badges":{"notifications_associated_account":null,"competition-detail_quantity":[{"count":4,"target":77369260}],"questions_quantity":3,"messenger_quantity":131,"id":136165659,"competition_quantity":4,"notifications_quantity":0},"from_mark_unread":false,"function":"updateOrders","order_id":1515942402},"google.message_id":"0:1509558483749639%bc50674abc50674a","coldstart":false,"collapse_key":"com.real_trends","foreground":true}}
D/PushPlugin_GCMIntentService(12739): onMessage - from: senderID
D/PushPlugin_GCMIntentService(12739): normalize extras
D/PushPlugin_GCMIntentService(12739): key = google.sent_time
D/PushPlugin_GCMIntentService(12739): replace key google.sent_time with google.sent_time
D/PushPlugin_GCMIntentService(12739): key = payload
D/PushPlugin_GCMIntentService(12739): replace key payload with payload
D/PushPlugin_GCMIntentService(12739): key = google.message_id
D/PushPlugin_GCMIntentService(12739): replace key google.message_id with google.message_id
D/PushPlugin_GCMIntentService(12739): key = notification
D/PushPlugin_GCMIntentService(12739): notifkey = body
D/PushPlugin_GCMIntentService(12739): replace key body with message
D/PushPlugin_GCMIntentService(12739): no locale found for key = message, error Value Funda of type java.lang.String cannot be converted to JSONObject
D/PushPlugin_GCMIntentService(12739): notifkey = badge
D/PushPlugin_GCMIntentService(12739): replace key badge with count
D/PushPlugin_GCMIntentService(12739): notifkey = title
D/PushPlugin_GCMIntentService(12739): replace key title with title
D/PushPlugin_GCMIntentService(12739): no locale found for key = title, error Value Recibiste of type java.lang.String cannot be converted to JSONObject
D/PushPlugin_GCMIntentService(12739): key = collapse_key
D/PushPlugin_GCMIntentService(12739): replace key collapse_key with collapse_key
D/PushPlugin_GCMIntentService(12739): foreground
D/PushPlugin(12739): convert extras to json
D/PushPlugin(12739): key = google.sent_time
D/PushPlugin(12739): key = payload
D/PushPlugin(12739): key = count
D/PushPlugin(12739): key = title
D/PushPlugin(12739): key = google.message_id
D/PushPlugin(12739): key = message
D/PushPlugin(12739): key = coldstart
D/PushPlugin(12739): key = collapse_key
D/PushPlugin(12739): key = foreground
V/PushPlugin(12739): extrasToJSON: {"count":"4","title":"Recibiste una nueva pregunta","message":"Funda Fashion Case Gold Iphone 5s Se 6s 7 8 Plus + Templado","additionalData":{"payload":{"global_badges":{"notifications_associated_account":null,"competition-detail_quantity":[{"count":4,"target":77369260}],"questions_quantity":4,"messenger_quantity":131,"id":136165659,"competition_quantity":4,"notifications_quantity":0},"function":"updateQuestions","question_id":5088165390},"google.message_id":"0:1509558488700369%bc50674abc50674a","coldstart":false,"collapse_key":"com.real_trends","foreground":true}}
D/SystemWebChromeClient(12739): file:///android_asset/www/js/common/services/PushNotificationsModule.js: Line 25 : updateQuestionsFunction
I/chromium(12739): [INFO:CONSOLE(25)] "updateQuestionsFunction", source: file:///android_asset/www/js/common/services/PushNotificationsModule.js (25)
D/PushPlugin_GCMIntentService(12739): onMessage - from: senderID
D/PushPlugin_GCMIntentService(12739): normalize extras
D/PushPlugin_GCMIntentService(12739): key = google.sent_time
D/PushPlugin_GCMIntentService(12739): replace key google.sent_time with google.sent_time
D/PushPlugin_GCMIntentService(12739): key = payload
D/PushPlugin_GCMIntentService(12739): replace key payload with payload
D/PushPlugin_GCMIntentService(12739): key = google.message_id
D/PushPlugin_GCMIntentService(12739): replace key google.message_id with google.message_id
D/PushPlugin_GCMIntentService(12739): key = notification
D/PushPlugin_GCMIntentService(12739): notifkey = body
D/PushPlugin_GCMIntentService(12739): replace key body with message
D/PushPlugin_GCMIntentService(12739): no locale found for key = message, error Value Batería of type java.lang.String cannot be converted to JSONObject
D/PushPlugin_GCMIntentService(12739): notifkey = badge
D/PushPlugin_GCMIntentService(12739): replace key badge with count
D/PushPlugin_GCMIntentService(12739): notifkey = title
D/PushPlugin_GCMIntentService(12739): replace key title with title
D/PushPlugin_GCMIntentService(12739): no locale found for key = title, error Value Recibiste of type java.lang.String cannot be converted to JSONObject
D/PushPlugin_GCMIntentService(12739): key = collapse_key
D/PushPlugin_GCMIntentService(12739): replace key collapse_key with collapse_key
D/PushPlugin_GCMIntentService(12739): foreground
D/PushPlugin(12739): convert extras to json
D/PushPlugin(12739): key = google.sent_time
D/PushPlugin(12739): key = payload
D/PushPlugin(12739): key = count
D/PushPlugin(12739): key = title
D/PushPlugin(12739): key = google.message_id
D/PushPlugin(12739): key = message
D/PushPlugin(12739): key = coldstart
D/PushPlugin(12739): key = collapse_key
D/PushPlugin(12739): key = foreground
V/PushPlugin(12739): extrasToJSON: {"count":"5","title":"Recibiste una nueva pregunta","message":"Batería Original Para Sony Xperia Z1 L39h","additionalData":{"payload":{"global_badges":{"notifications_associated_account":null,"competition-detail_quantity":[{"count":4,"target":77369260}],"questions_quantity":5,"messenger_quantity":131,"id":136165659,"competition_quantity":4,"notifications_quantity":0},"function":"updateQuestions","question_id":5088165654},"google.message_id":"0:1509558496381840%bc50674abc50674a","coldstart":false,"collapse_key":"com.real_trends","foreground":true}}
D/SystemWebChromeClient(12739): file:///android_asset/www/js/common/services/PushNotificationsModule.js: Line 25 : updateQuestionsFunction
I/chromium(12739): [INFO:CONSOLE(25)] "updateQuestionsFunction", source: file:///android_asset/www/js/common/services/PushNotificationsModule.js (25)

**Comment by ferdelcorroRT** [comment] 2017-11-05 16:28
@macdonst any idea? I have all my users with this problem

**Comment by ferdelcorro** [comment] 2017-11-05 16:29
@macdonst  any idea? I have all my users with this problem

**Comment by ferdelcorro** [comment] 2017-11-06 16:16
This is a push without title and without message
{"priority": "high", "notification": {"badge": 109}, "data": {"payload": {"function": "updateQuestions", "global_badges": {"competition-detail_quantity": [], "notifications_associated_account": null, "notifications_quantity": 0, "messenger_quantity": 0, "competition_quantity": 0, "questions_quantity": 109, "id": 229961964}, "question_id": 5089172018}}, "registration_ids": ["crnUPofj0hw:APA91bHf80bJiW_ExvHscgQeqRxaqPu1AJm2EUM9R4QaebqO5dyBzC4TIw_LJmOO_csj5Z8aHvK7YFCLKw4Z3_HI9Iguw99ABCvmh6zP35i7EwnSmOst6a8_DyWYplh2j3x70nf7uy9O"]}

This is a push with title and message
{"priority": "high", "notification": {"body": "Funda Aluminio Motomo Para Sony Xperia E4g Z1 Z2 Z3 Z4 Z5", "badge": 110, "title": "Recibiste una nueva pregunta"}, "data": {"payload": {"function": "updateQuestions", "global_badges": {"competition-detail_quantity": [], "notifications_associated_account": null, "notifications_quantity": 0, "messenger_quantity": 0, "competition_quantity": 0, "questions_quantity": 110, "id": 229961964}, "question_id": 5088250587}}, "registration_ids": ["crnUPofj0hw:APA91bHf80bJiW_ExvHscgQeqRxaqPu1AJm2EUM9R4QaebqO5dyBzC4TIw_LJmOO_csj5Z8aHvK7YFCLKw4Z3_HI9Iguw99ABCvmh6zP35i7EwnSmOst6a8_DyWYplh2j3x70nf7uy9O"]}

**Comment by ferdelcorro** [comment] 2017-11-06 17:43
I found the error, for some reason a $rootScope field didn't work when i saved if the device is an android or an ios. I don't know why this field works fine in others places.

My error, thanks @macdonst

**Comment by fredgalvao** [comment] 2017-11-06 18:55
@ferdelcorro  If the issue is fixed for you, please close it.

Also, a tip: try not to trust `$rootScope` too much!

**Closed** 2017-11-06 21:43 UTC
Labels: android, question
