### ISSUE TITLE
Stacking using Ionic

### ISSUE THREAD

**Issue by binoculars88** [phonegap/phonegap-plugin-push#482] opened 2016-01-07 22:27 UTC
How could I use stacking using this plugin in Ionic?
I'm able to use notId, but not stacking... What am I doing wrong?

This is the PHP script I'm using for the curl request:

    $data = array(
    'user_ids' => [...],
    'notification' => array
    (
        'alert' => $notif_msg,
        "android" => array
        (
            'title' => $notif_title,
            "style"=> "inbox",
            "summaryText"=> "There are %n% notifications",
            "payload" => array
            (
                "msg" => $popup_msg,
                "msg_title" => $popup_title,
                "notif_type" => $type
            )
        ),

        "ios" => array
        (
            'title' => $notif_title,
            "payload" => array
            (
                "msg" => $popup_msg,
                "msg_title" => $popup_title,
                "notif_type" => $type
            )
        )
    )
    );

**Comment by macdonst** [comment] 2016-01-08 22:05
@binoculars88 that doesn't look right at all. What JSON payload does that create?

**Comment by sickrandir** [comment] 2016-01-11 17:25
@macdonst can you please provide an example of what should be the complete structure to be sent to achieve stacking on android?
I'm experiencing problems too with Ionic push service and latest push plugin. 
Either I'm sending the wrong format or Ionic Push is messing up my messages.

**Comment by macdonst** [comment] 2016-01-11 19:17
Here is what I send to achieve and inbox style message:

```
{
  "registration_ids": ["xxxx"],
  "data": {
    "title": "My Title",
    "message": "My first message",
    "style": "inbox",
    "summaryText": "There are %n% notifications"
  }
}
```

and the second message

```
{
  "registration_ids": ["xxxx"],
  "data": {
    "title": "My Title",
    "message": "My second message",
    "style": "inbox",
    "summaryText": "There are %n% notifications"
  }
}
```

That creates the inbox style.

**Comment by Telemakhos** [comment] 2016-01-11 20:19
@binoculars88 Apparently the Ionic PUSH API doesn't take those params. An ionic team member confirmed me that all the available params via API are the ones that appear [here](http://docs.ionic.io/docs/push-sending-push#section-using-the-rest-api) in their docs' example:

```
{
  "tokens":[
    "b284a6f7545368d2d3f753263e3e2f2b7795be5263ed7c95017f628730edeaad",
    "d609f7cba82fdd0a568d5ada649cddc5ebb65f08e7fc72599d8d47390bfc0f20"
  ],
  "notification":{
    "alert":"Hello World!",
    "ios":{
      "badge":1,
      "sound":"ping.aiff",
      "expiry": 1423238641,
      "priority": 10,
      "contentAvailable": 1,
      "payload":{
        "key1":"value",
        "key2":"value"
      }
    },
    "android":{
      "collapseKey":"foo",
      "delayWhileIdle":true,
      "timeToLive":300,
      "payload":{
        "key1":"value",
        "key2":"value"
      }
    }
  }
}
```
He told me that "style" and "summaryText" should be configured in the plugin init, but I'm trying right now and the stacking is not working... Here's the config I'm using:

```
$ionicPush.init({
  	"debug": true,
    "pluginConfig": {
        "ios": {
            "badge": true,
            "sound": true
        },
        "android": {
	        "icon": "notification_icon",
	        "iconColor": "blue",
	        "style": "inbox",
	        "summaryText": "You've got %n% notifications"
        }
    },
  	"onNotification": function(notification) {
    	var payload = notification.payload;
    	console.log(notification, payload);
  	},
  	"onRegister": function(data) {
  		if(user) {
  			$ionicPush.addTokenToUser(user);
			if(user.id) {
            	user.save();
            }	
  		}
    	console.log(data.token);
  	}
});

$ionicPush.register();
```

but it seems that @macdonst sends those via backend... right?

**Comment by macdonst** [comment] 2016-01-11 20:28
@binoculars88 no, they should not be part of the plugin init. I'm not an expert on what the Ionic push service allows so I think it would be better if you work with them on this issue.

**Comment by sickrandir** [comment] 2016-01-12 09:35
@Telemakhos that's what I experienced after quite a bit of testing. I saw that the only way to include those parameters with the Ionic Push service is by putting them in the payload field.
Of course in that way the parameters are not recognized and used by the Push Plugin on reception.
I have a local patch for 1.4.0 Push Plugin for android that reads the 'extras' parameters even if they are included in the payload but I do not have the time to port it to the newest releases and I also think that is something that should be fixed by the Ionic developers. At the very least Ionic Push should be much clearer about this limitation since it's only natural that more and more people will try to use this plugin (especially since the old one is deprecated) in pair with the Ionic Push service and they'll expect to leverage all the features of the plugin.

**Comment by macdonst** [comment] 2016-01-12 13:12
@sickrandir Yeah, I've worked with @ericb over at Ionic with regards to this plugin. Maybe he can chime in on this issue.

**Comment by ericb** [comment] 2016-01-12 17:05
Hey guys,

There's a lot of different information floating in this thread so I'm going to address what I think are the main points (feel free to ping me with any further questions).

First, I just want to say that in the future, any questions regarding the ionic push service should be posted to one of the ionic repo's (see the [issues docs](http://docs.ionic.io/docs/issues)) -- posting here only delays someone from Ionic actually being able to address an issue and adds unnecessary confusion to the plugin issues listing.

As for getting any of the push plugin settings to work with the ionic api, there are two things to note here:

1. Any properties the push plugin expects to be sent via GCM should be set in the `android.payload` property when making requests to the ionic push service.

2. Many of you probably at least tried the above, but did not see anything change, this is because the ionic push service was not properly passing along all the payload information to GCM. As of writing this message they should now be working correctly.

Here is an example of the request body sent to the ionic-service:

```json
{
    "tokens": ["YOUR-TOKEN"],
    "notification": {
        "alert":"testing", 
        "title": "Test Notification",
        "android": {
            "payload": {
                "style": "inbox",
                "summaryText": "%n% Unread Notifications"
            }
        }
    }
}
```

Hope that clears up some of the issues people are having, and let me know if there are any other questions anyone has, or if you happen to find other properties that do not seem to be working correctly.

Cheers :beers:

**Comment by macdonst** [comment] 2016-01-12 17:09
Thanks @ericb. 

All, please re-test and close if this solves your issue.

**Comment by sickrandir** [comment] 2016-01-12 17:14
@ericb thank you for taking the time to comment here. That is exactly how I'm currently sending push with ionic push. However with that format "style" and "summaryText" parameters are not picked-up correctly by the plugin and the notifications just replace each other like in the standard behaviour. I just tested it using ionic 1.2.1 and Push Plugin 1.5.2

**Comment by Telemakhos** [comment] 2016-01-12 17:20
@sickrandir Just tested "style" and "summaryText" and it's working now... I'll try to test other parameters (vibration, images, etc) later today

**Comment by sickrandir** [comment] 2016-01-12 17:35
Sorry guys, my bad. It's working also for me now. Thanks a lot!

**Comment by ericb** [comment] 2016-01-12 17:37
@sickrandir Can you post an example of your request body, both @Telemakhos and myself have tested and it works. It might be worth mentioning that you can only see the inbox format if you've pulled down on your notifications area.

**Comment by ericb** [comment] 2016-01-12 17:37
oops, just saw your latest comment, disregard :) :+1:

**Closed** 2016-01-12 17:50 UTC
Labels: question

**Comment by pallaviMN** [comment] 2016-02-02 16:19
@sickrandir and @Telemakhos  , can you please tell me how did you resolve this? Either in the client side or Server Side. Please can you send Payload details. Even i am using ionic & facing the same issue, unable to resolve. Is there any changes to be done at the client side? Which plugin have you used for Push Notifications

**Comment by ScottSpittle** [comment] 2016-04-13 20:50
I would also like to know how you resolved this. I'm using :

- "ionic": "driftyco/ionic-bower#cd7ca5852cc13b148e6c8b9c8628f00e6d4a01c3"
- phonegap-plugin-push 1.6.2 "PushPlugin"

Payload : 
` var url = 'https://api.ionic.io/push/notifications';

   // Build the request object
   var args = {
       headers: {
           'Content-Type': 'application/json',
           'Authorization': 'Bearer ' + jwt
       },
       "data": {
           "tokens": pushToken,
           "profile": profile,
           "notification": {
               "android": {
                   "stack": 3,
                   "payload": {
                       "style": "inbox",
                       "summaryInbox": "inbox",
                       "notId": Math.floor((Math.random() * 100) + 1)
                   },
                   "icon": "logo.png",
                   "title": "Potential Cameras on Route",
                   "message": alert.name ,
                   "image": "logo.png"
               }
           }
       }
   };`

**Comment by ericb** [comment] 2016-04-13 20:58
@ScottSpittle If looks like you're using the beta API. The examples I posted above was for our alpha api. You need to push those properties exactly as the push plugin shows, but using the `data` property of the `android` property in the beta api. The `payload` property is for custom use with the ionic platform client.

Anything referenced using the GCM data property via the plugin needs to be referenced this way.

So to modify your previous example:

```javascript
   var url = 'https://api.ionic.io/push/notifications';

   // Build the request object
   var args = {
       headers: {
           'Content-Type': 'application/json',
           'Authorization': 'Bearer ' + jwt
       },
       "data": {
           "tokens": pushToken,
           "profile": profile,
           "notification": {
               "android": {
                   "stack": 3,
                   "data": {
                       "style": "inbox",
                       "summaryInbox": "inbox",
                       "notId": Math.floor((Math.random() * 100) + 1)
                   },
                   "payload": {
                       "custom_app_thing": "yes"
                   },
                   "icon": "logo.png",
                   "title": "Title",
                   "message": 'Message' ,
                   "image": "logo.png"
               }
           }
       }
   };
```

**Comment by ScottSpittle** [comment] 2016-04-13 21:00
@ericb Thanks for the response, I'll try that out ASAP and get back to you.

**Comment by ScottSpittle** [comment] 2016-04-14 16:49
@ericb I tried your snippit, unfortunately with no success, any more help would be greatly appreciated.

API sends the following to IONIC:
```
   var url = 'https://api.ionic.io/push/notifications';

   // Build the request object
   var args = {
       headers: {
           'Content-Type': 'application/json',
           'Authorization': 'Bearer ' + jwt
       },
       "data": {
           "tokens": pushToken,
           "profile": profile,
           "notification": {
               "android": {
                   "stack": 3,
                   "data": {
                       "style": "inbox",
                       "summaryInbox": "inbox",
                       "notId": Math.floor((Math.random() * 100) + 1)
                   },
                   "payload": {
                       "custom_app_thing": "yes"
                   },
                   "icon": "logo.png",
                   "title": "Title",
                   "message": 'Message' ,
                   "image": "logo.png"
               }
           }
       }
   };
```

The APP receives:
http://puu.sh/oi2f9/80e7864411.png

Problems I'm having are;
* Notifications are not stacking
* Image for the notification is blank as apposed to my application Icon

Thanks again for any help

**Comment by seanhoilett** [comment] 2016-04-24 03:46
@ScottSpittle You will have to [create  ic_stat_icon.png files](https://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.space.trim=1&source.space.pad=0&name=ic_stat_example) and add them to your drawable folder. Then make reference to it in your pluginConfig or in your POST Request

```
$ionicPush.init({
                "debug": true,
                "onNotification": onPushNotification,
                "onRegister": function(token) {
                  $ionicPush.saveToken(token);
                },
                pluginConfig: {
                    android:{
                        "icon":"ic_stat_icon",
                        "iconColor": "#1357A7"
                    }
                }
            });
```

@ericb I'm having the same problem with the notId. It gets sent to the push plugin nested under ```data:{``` when it is looking for it at the root
