### ISSUE TITLE
Few of the Android >= 8.0 sometimes not receiving notifications (Even it is sent successful from server)

### ISSUE THREAD

**Issue by razam217** [phonegap/phonegap-plugin-push#2545] opened 2018-09-12 08:45 UTC
### Expected Behaviour
All Android phones should receive every type of notification correctly.

### Actual Behaviour
There are few customers, around 20-30, are reporting that they do not receive push notification. But sometimes they do receive.

### Reproduce Scenario (including but not limited to)
Not sure, as I cannot reproduce it on the device I'm having.

#### Steps to Reproduce 
Not sure, as I cannot reproduce it on the device I'm having.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
ANDROID: Mostly Pixel users are reporting this issue + Other phones with Android >= 8.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung, LG, Google Pixel etc

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.1.0
    cordova platform version android          6.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.1.3

**Comment by macdonst** [comment] 2018-09-18 08:46
@razam217 sorry but I need more information here as I can't reproduce the issue.

**Comment by razam217** [comment] 2018-09-27 09:58
Unfortunately I'm also not able to reproduce this issue, but customers are reporting this issue. :(

**Comment by macdonst** [comment] 2018-09-27 20:01
@razam217 we are at an impasse then. Neither one of us can reproduce the issue and you don't have any logs so I'm not sure what I can do here. I'm going to close the issue but please re-open if you have more information.

My only suggestion is to have users experiencing the problem remove and re-install the app.

**Closed by macdonst** 2018-09-27 20:01 UTC
Labels: android, can't reproduce
