### ISSUE TITLE
how to work in background ? 

### ISSUE THREAD

**Issue by Jinjos** [phonegap/phonegap-plugin-push#249] opened 2015-10-20 21:52 UTC
Hello,

I built an android (cordova) app, 
I am trying to handle an event of notification in the background, when user didn't click the notification message,
For some reason, data is not received until user clicks the notification.
not even when user is online.

The only way I can get to use notification in the background without user clicks on the notification is if I send a json without the notification structure(without message and title but only regular data).
Since I doubt the way to send it would be to send push twice - one for data and one for notification, I guess there's another way ... 

I didn't find anywhere to handle this kind of event, could you please help understanding with handler do I need to put ?

Thank you

**Comment by fredgalvao** [comment] 2015-10-20 23:00
You're probably looking for the feature described in https://github.com/phonegap/phonegap-plugin-push/issues/93, which unfortunately isn't available yet. The proposal is there, and in a few other related issues, so you can always +1 them so that @macdonst knows what to prioritize on future releases.

**If** that's indeed the case, and this is a duplicate of #93 and it's related issues, **please close this issue**.

**Comment by manikumarkv** [comment] 2015-10-21 11:47
+1

**Comment by macdonst** [comment] 2015-10-21 14:14
Dupe of #93 which I've started working on.

**Closed by macdonst** 2015-10-21 14:14 UTC
