### ISSUE TITLE
GoogleCloudMessaging error

### ISSUE THREAD

**Issue by furyscript** [phonegap/phonegap-plugin-push#604] opened 2016-02-11 08:24 UTC
When I installed this plugin for my Ionic projects I still have this error when I build apk.
```
/phonegap/push/RegistrationIntentService.java:30: error: cannot find symbol
                    GoogleCloudMessaging.INSTANCE_ID_SCOPE, null);
                                        ^
  symbol:   variable INSTANCE_ID_SCOPE
  location: class GoogleCloudMessaging

```
I have all requirements plugin.

**Comment by macdonst** [comment] 2016-02-11 14:56
@furyscript duplicate of #477 #424. Your Android build environment is not correct.

**Closed by macdonst** 2016-02-11 14:56 UTC
Labels: duplicate

**Comment by furyscript** [comment] 2016-02-11 17:07
With version 1.3.0 works why? @macdonst

**Comment by macdonst** [comment] 2016-02-11 17:47
@furyscript because version 1.3.0 does no use the most up to date version of GoogleCloudMessaging. As of 1.4.x I switched to using gradle for the gcm dependency.

**Comment by furyscript** [comment] 2016-02-12 07:57
Ok thanks for anwser, sorry if I ask... But if I'm using last of version of this plugin, and last version of googleplayservices how can I resolve my issue?? I required both @macdonst

**Comment by macdonst** [comment] 2016-02-12 15:16
@furyscript sorry, are you saying you are using the latest googleplayservices plugin?

**Comment by furyscript** [comment] 2016-02-12 15:24
Yes last version of googleplayservices and last version of this plugin.
If I switch to phonegap-plugin-push 1.3.0 compilation works fine...

**Comment by macdonst** [comment] 2016-02-12 15:28
@furyscript You misunderstood my question. Are you using this plugin?

https://www.npmjs.com/package/cordova-plugin-googleplayservices

**Comment by furyscript** [comment] 2016-02-12 15:32
I think yes, this i my package.json for cordova plugin. I'm using using. @macdonst 
https://gist.github.com/anonymous/d51d0de09cdcb145c1c4

**Comment by macdonst** [comment] 2016-02-12 15:43
@furyscript yeah, don't do that. That is the old way of doing things. In fact the original plugin is deprecated see here:

https://github.com/MobileChromeApps/google-play-services

so you must be using the one from here:

https://github.com/floatinghotpot/google-play-services

this is a really bad idea as you can end up including the jar file twice and screwing up your app, like you are seeing.

Why do you need to use that plugin?

**Comment by furyscript** [comment] 2016-02-12 15:57
is required for `google-admob-sdk`, now I installed playservices plugin from `floatinghotpot` repository but I got an error with `google-admob-sdk` 
```
Failed to install 'com.google.admobsdk':Error: Expected plugin to have ID "cordova-plugin-googleplayservices" but got "com.google.playservices".
```
This is new package.json @macdonst https://gist.github.com/anonymous/521394f9fcfe7c9c235d

**Comment by macdonst** [comment] 2016-02-12 16:05
@furyscript right, so this is not a bug with the phonegap-plugin-push package. You are using some outdated plugins. You should raises issues on those plugins to get them to fix the issues or move to a more up to date admob plugin like:

https://github.com/floatinghotpot/cordova-admob-pro

**Comment by furyscript** [comment] 2016-02-12 16:07
Ok at the moment I remove android admob plugin, but now I have this error : 
```
> Error: more than one library with package name 'com.google.android.gms'
```

**Comment by macdonst** [comment] 2016-02-12 16:13
@furyscript delete your platforms directory and start over.

**Comment by furyscript** [comment] 2016-02-12 16:19
Also not work, I run `ionic state reset` and `ionic remove plaform android, ionic add platform android`

**Comment by nibhatish** [comment] 2016-03-14 09:35
I had the same error. Removing plugin cordova-plugin-googleplayservices solved my issue.

**Comment by furyscript** [comment] 2016-03-14 09:43
But I require `cordova-plugin-googleplayservices`

**Comment by ntkzwane** [comment] 2016-11-10 06:29
Hi @furyscript did you find a resolve? I am experiencing the very same issue and als cannot afford to remove `cordova-plugin-googleplayservices`
