### ISSUE TITLE
Issue with plugin facebook connect

### ISSUE THREAD

**Issue by chooseapp** [phonegap/phonegap-plugin-push#107] opened 2015-09-05 23:38 UTC
Hi there,

when I am building android with this plugin and the phonegap-facebook-plugin, I got this error : 

```
:processReleaseResourceswarning: string 'menu_settings' has no default translation.

:generateReleaseSources
:compileReleaseJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/thibaut/Documents/choose/application/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:preDexRelease
:dexRelease
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexRelease'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/usr/local/Cellar/android-sdk/24.3.4/build-tools/23.0.1/dx --dex --output /Users/thibaut/Documents/choose/application/platforms/android/build/intermediates/dex/release --input-list=/Users/thibaut/Documents/choose/application/platforms/android/build/intermediates/tmp/dex/release/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
  		at com.android.dx.command.dexer.Main.run(Main.java:277)
  		at com.android.dx.command.dexer.Main.main(Main.java:245)
  		at com.android.dx.command.Main.main(Main.java:106) 
```
Do you have any idea why I have this ? I tried lots of things but no one worked.

Thanks in advance

**Comment by macdonst** [comment] 2015-09-06 12:31
This is a duplicate of the problem described in issue #51. See the last comment for a potential work around.

**Closed by macdonst** 2015-09-06 12:31 UTC
