### ISSUE TITLE
Is it possible to add badge on Android portion.

### ISSUE THREAD

**Issue by jimior2** [phonegap/phonegap-plugin-push#308] opened 2015-11-05 03:40 UTC
Would it possible to add set badge number like push.setApplicationIconBadgeNumber and support Android portion, I know there's a badge plugin out there called " cordova-plugin-badge", but if this support also that we don't need to install another to do badge.  :+1:

**Comment by fredgalvao** [comment] 2015-11-05 06:05
I'm closing this as a duplicate of https://github.com/phonegap/phonegap-plugin-push/issues/190, you're invited to +1 on that issue so that it gets the desired attention.

**Closed by fredgalvao** 2015-11-05 06:05 UTC

**Comment by jimior2** [comment] 2015-11-05 08:12
@fredgalvao Thanks. +1 already.
