### ISSUE TITLE
Background Notifications on iOS

### ISSUE THREAD

**Issue by alexislg2** [phonegap/phonegap-plugin-push#109] opened 2015-09-06 20:16 UTC
Hey,
I manage to receive notifications in foreground on iOS perfectly but when I send notification when the app is in not running, I receive it in the status bar but when I open the app, the `push.on('notification'` callback is never called.

Is that normal behaviour?

On Android it is called with `data.additionalData.foreground` set to `false`.

**Comment by alexislg2** [comment] 2015-09-06 20:25
Is that the same issue as this one?
https://github.com/phonegap/phonegap-plugin-push/issues/93

**Comment by macdonst** [comment] 2015-09-07 01:14
Closing as duplicate of #93

**Comment by slorber** [comment] 2015-09-07 09:43
@macdonst on android when we receive a notification and the app is in background, when clicking on the notification in the statusbar it opens the app and then the notification callback is run.

Isn't something we can expect for iOS too?

I think #93 is talking about receiving the notification without even putting the application in foreground no?

**Comment by alexislg2** [comment] 2015-09-07 09:54
I was indeed talking about running the callback when the user starts the app from the notification status bar on iOS

There is clearly not the same behaviour on Android (callback is called with foreground option set to true) and on iOS (callback never called)

**Comment by slorber** [comment] 2015-09-07 11:05
@alexislg2 you mean callback has foreground=false no?

@macdonst I think is the [2nd case described here](https://github.com/phonegap/phonegap-plugin-push/issues/93#issuecomment-138254852).

I also expect the behavior to be the same for Android and iOS in this case (however don't know if this is possible at all).

When receiving an iOS notification while being in background, when opening the notification, the callback should rather be fired otherwise we don't have any way to trigger code on our app.

**Comment by alexislg2** [comment] 2015-09-07 19:37
@slorber yeah right sorry for the mistake. 

It was working properly on the deprecated PushPlugin https://github.com/phonegap-build/PushPlugin

**Comment by macdonst** [comment] 2015-09-11 15:10
@alexislg2 okay, I've re-opened this. The iOS code is based off of the old PushPlugin so I'm wondering what the diff is.

**Comment by ledfusion** [comment] 2015-09-14 23:18
+1 here
iOS will launch the app, but push.on('notification', function(notification){...}) will not fire.
I may have to roll back to the old plugin, if there is no fix for that

**Comment by alexislg2** [comment] 2015-09-16 19:35
Fixed for me with the commit https://github.com/phonegap/phonegap-plugin-push/commit/9f354861440a6a929504b7cbed06ed1d37758757

**Comment by slorber** [comment] 2015-09-18 10:03
Related: https://github.com/phonegap/phonegap-plugin-push/issues/117

**Comment by macdonst** [comment] 2015-10-26 20:21
Closing as it appears to be fixed by #117

**Closed by macdonst** 2015-10-26 20:21 UTC
Labels: enhancement, retest
