### ISSUE TITLE
App crashes on pushNotification.init

### ISSUE THREAD

**Issue by InvalidC** [phonegap/phonegap-plugin-push#1058] opened 2016-07-07 11:33 UTC
I am not sure if this is the same error as #1051
 
### Expected Behaviour
 To work.
### Actual Behaviour
  **The app crashes whenever I init on the 1.6.3 version**
07-07 07:32:20.253 19285 19321 E AndroidRuntime: java.lang.IncompatibleClassChangeError: The method 'java.io.File android.support.v4.content.ContextCompat.getNoBackupFilesDir(android.content.Context)' was expected to be of type virtual but instead was found to be of type direct (declaration of 'com.google.android.gms.iid.zzd' appears in /data/app/com.ionicframework.simple539694-1/base.apk)
07-07 07:32:20.253 19285 19321 E AndroidRuntime:        at com.google.android.gms.iid.zzd.zzdL(Unknown Source)
07-07 07:32:20.253 19285 19321 E AndroidRuntime:        at com.google.android.gms.iid.zzd.<init>(Unknown Source)
07-07 07:32:20.253 19285 19321 E AndroidRuntime:        at com.google.android.gms.iid.zzd.<init>(Unknown Source)
07-07 07:32:20.253 19285 19321 E AndroidRuntime:        at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
07-07 07:32:20.253 19285 19321 E AndroidRuntime:        at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
07-07 07:32:20.253 19285 19321 E AndroidRuntime:        at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:73)
07-07 07:32:20.253 19285 19321 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-07 07:32:20.253 19285 19321 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-07 07:32:20.253 19285 19321 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
07-07 07:32:20.260   673   758 W ActivityManager:   Force finishing activity com.ionicframework.simple539694/.MainActivity
07-07 07:32:20.429   673   682 I art     : Background partial concurrent mark sweep GC freed 23070(2029KB) AllocSpace objects, 47(940KB) LOS objects, 20% free, 15MB/19MB, paused 1.417ms total 133.280ms
07-07 07:32:20.432  1120  1120 D ShieldTech_Services: Starting service
07-07 07:32:20.433 19285 19285 W cr_AwContents: WebView.destroy() called while WebView is still attached to window.
07-07 07:32:20.436  1120  1120 D RSMouse : mFeatureEnabled=true  mPackageEnabled=true
07-07 07:32:20.449   673  4222 I OpenGLRenderer: Initialized EGL, version 1.4
07-07 07:32:20.538 19285 19285 W cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 19285
07-07 07:32:20.539 19285 19285 D cr_Ime  : [InputMethodManagerWrapper.java:59] isActive: false
07-07 07:32:20.540 19285 19285 D cr_Ime  : [InputMethodManagerWrapper.java:59] isActive: false
07-07 07:32:20.550 19285 19285 E ActivityThread: Activity com.ionicframework.simple539694.MainActivity has leaked ServiceConnection com.nvidia.ControllerMapper.MapperClient$ServiceClient$1@4364e0b that was originally bound here
07-07 07:32:20.550 19285 19285 E ActivityThread: android.app.ServiceConnectionLeaked: Activity com.ionicframework.simple539694.MainActivity has leaked ServiceConnection com.nvidia.ControllerMapper.MapperClient$ServiceClient$1@4364e0b that was originally bound here
07-07 07:32:20.550 19285 19285 E ActivityThread:        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1092)
07-07 07:32:20.550 19285 19285 E ActivityThread:        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:986)
07-07 07:32:20.550 19285 19285 E ActivityThread:        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1305)
07-07 07:32:20.550 19285 19285 E ActivityThread:        at android.app.ContextImpl.bindService(ContextImpl.java:1288)
07-07 07:32:20.550 19285 19285 E ActivityThread:        at android.content.ContextWrapper.bindService(ContextWrapper.java:604)
07-07 07:32:20.550 19285 19285 E ActivityThread:        at android.content.ContextWrapper.bindService(ContextWrapper.java:604)
07-07 07:32:20.550 19285 19285 E ActivityThread:        at com.nvidia.ControllerMapper.MapperClient$ServiceClient.connect(MapperClient.java:821)
07-07 07:32:20.550 19285 19285 E ActivityThread:        at com.nvidia.ControllerMapper.MapperClient.<init>(MapperClient.java:108)
07-07 07:32:20.550 19285 19285 E ActivityThread:        at android.view.ViewRootImpl.handleWindowActivated(ViewRootImpl.java:905)
07-07 07:32:20.550 19285 19285 E ActivityThread:        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3620)
07-07 07:32:20.550 19285 19285 E ActivityThread:        at android.os.Handler.dispatchMessage(Handler.java:104)
07-07 07:32:20.550 19285 19285 E ActivityThread:        at android.os.Looper.loop(Looper.java:148)
07-07 07:32:20.550 19285 19285 E ActivityThread:        at android.app.ActivityThread.main(ActivityThread.java:5460)
07-07 07:32:20.550 19285 19285 E ActivityThread:        at java.lang.reflect.Method.invoke(Native Method)
07-07 07:32:20.550 19285 19285 E ActivityThread:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-07 07:32:20.550 19285 19285 E ActivityThread:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-07 07:32:20.565   673   683 W AppOps  : Finishing op nesting under-run: uid 1000 pkg com.nvidia.ControllerMapper code 24 time=1463766363812 duration=46437 nesting=0

**on 1.6.4 I get a build error** 
Required by:
         :android:unspecified > com.android.support:support-v13:23.1.1
   > Could not find com.android.support:support-v4:23.4.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         https://jcenter.bintray.com/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         https://jcenter.bintray.com/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         file:/C:/veg/client/platforms/android/libs/support-v4-23.4.0.jar
         file:/C:/veg/client/platforms/android/libs/support-v4.jar
         file:/C:/Users/martine/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         file:/C:/Users/martine/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         file:/C:/Users/martine/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         file:/C:/Users/martine/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
     Required by:
         :android:unspecified > com.google.android.gms:play-services-gcm:8.3.0 > com.google.android.gms:play-services-base:8.3.0 > com.google.android.gms:play-services-basement:8.3.0

**Comment by macdonst** [comment] 2016-07-07 12:29
@InvalidC nope but it is a duplicate of #909. Long story short, Google screwed up. You'll need to update to the latest version of Google Play Services which is why version 1.7.3 of this plugin requires 9.0.2 or greater.

**Closed by macdonst** 2016-07-07 12:29 UTC
Labels: duplicate
