### ISSUE TITLE
Android FC with latest version 1.7.1

### ISSUE THREAD

**Issue by eduboxgithub** [phonegap/phonegap-plugin-push#1006] opened 2016-06-20 17:56 UTC
### Actual Behaviour
The app force close on android when the plugin is used.

### Reproduce Scenario (including but not limited to)
Update to latest version 1.7.1.

#### Steps to Reproduce 
Add version 1.7.0 - app not fc when the plugin is used
Remove version 1.7.1
Add version 1.7.1 - app fc when the plugin is used

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.4.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Wiko Rainbow

#### Cordova CLI version and cordova platform version
Cordova 6.1.1
Android 5.1.1

#### Plugin version
1.7.1

**Comment by macdonst** [comment] 2016-06-20 17:57
@eduboxgithub please reproduce the problem running `adb logcat` so I can see the force close error.

**Comment by meticoeus** [comment] 2016-06-27 16:40
Same problem. Not getting any logcat output from crash.

### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 5.0.1

### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Samsung

### Cordova CLI version and cordova platform version

Cordova 5.2.0
Android 4.1.1

### Plugin version

1.7.2

**Comment by macdonst** [comment] 2016-06-27 17:31
@meticoeus that's impossible. If the app crashes there will be a stack trace. Also, you are not giving me a reproduction scenario here so it's really hard to debug your problem.

**Comment by meticoeus** [comment] 2016-06-27 20:53
Same reproduction scenario as the original post. Update from 1.7.0 to 1.7.1 or 1.7.2.

**Comment by macdonst** [comment] 2016-06-28 01:56
@meticoeus if the Android crash dialog pops up then once you click OK there will be a stack trace generated. Also, I'm not sure what you are doing to reproduce the issue. Is you code calling `init` or `hasPermisson`? Give me something to go on here.

**Comment by eduboxgithub** [comment] 2016-07-01 16:29
Hello,

Sorry for the delay. I was trying to get the logcat error crash as requested, when I noticed I had some Android SDK updates pending. The SDK versions installed on my machine are:

> Android SDK Tools: 25.1.7
> Android SDK Platform-tools 24
> 
> API 22 SDK Platform 2
> 
> Android Support Repository 33
> Android Support Library 23.2.1

After the update I changed the plugin version to 1.7.2 and the crash was gone. 

Does this make sense?
Does the plugin have any specific dependencies with the updated sdks?

@meticoeus do you have any pending sdk updates?

**Comment by macdonst** [comment] 2016-07-01 16:35
@eduboxgithub Yes, this makes complete sense. I suspect this is the same root cause as #909 and it has been fixed with an update from Google.

**Closed by macdonst** 2016-07-01 16:35 UTC
Labels: android

**Comment by meticoeus** [comment] 2016-07-01 16:38
I am using Phonegap Build service to perform builds so I wouldn't be surprised if that is the case.

**Comment by macdonst** [comment] 2016-07-01 16:39
@meticoeus as asked the build team to update the Android build boxes yesterday. Today is a national holiday in Canada so it may not happen immediately.

**Comment by meticoeus** [comment] 2016-07-01 17:06
When they update I'll try to build again with 1.7.2 and see if that fixes it. If not, I'll look for the cause more aggressively.
