### ISSUE TITLE
Application crashes on push.init() in android

### ISSUE THREAD

**Issue by mail4sheik** [phonegap/phonegap-plugin-push#2319] opened 2018-04-16 17:27 UTC
**### Expected Behaviour**
Application get initialized and register itself giving back the key

**### Actual Behaviour**
Application crashes on on doing init 

**### Reproduce Scenario (including but not limited to)**
Just initialize the plugin. It was working good before two days
Application will crash when reaching,
    // wait at least one process tick to allow event subscriptions
    setTimeout(function() {
        exec(success, fail, 'PushNotification', 'init', [options]);
    }, 10); 
=>
 var msgs = nativeApiProvider.get().exec(bridgeSecret, service, action, callbackId, argsJson); . 

I use remote injection plugin to inject code into a remote content url.

**#### Steps to Reproduce** 
Call push.init

**#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)**
Android 8.0 oreo,  Android 5.X lollipop

**#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)**
MI A1,
Samsung note 3

**#### Cordova CLI version and cordova platform version**

    cordova --version                                   8.0.0
    cordova platform version android                 6.3.0

**#### Plugin version**

    cordova plugin version | grep phonegap-plugin-push   1.10.7 and above

#### Sample Push Data Payload

**#### Sample Code that illustrates the problem**
         var push = PushNotification.init({
             "android": {
                 "senderID": "XXXXXXXXXXXX"
             }

         });
**#### Logs taken while reproducing problem**
04-16 22:36:30.459 5942-6707/? W/zygote64: Class android.support.v4.util.SimpleArrayMap failed lock verification and will run slower.
                                           
                                           --------- beginning of crash
04-16 22:36:30.465 5942-6707/? E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-3
                                                 Process: com.ziplogix.zipForm, PID: 5942
                                                 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/util/zzx;
                                                     at com.google.android.gms.iid.zzaf.<init>(Unknown Source:58)
                                                     at com.google.android.gms.iid.zzaf.<init>(Unknown Source:6)
                                                     at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source:68)
                                                     at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source:4)
                                                     at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:73)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                     at java.lang.Thread.run(Thread.java:764)
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.util.zzx" on path: DexPathList[[zip file "/data/app/com.ziplogix.zipForm-YM7iDNrY3Cq3_Ar71Ld8aQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.ziplogix.zipForm-YM7iDNrY3Cq3_Ar71Ld8aQ==/lib/arm64, /system/lib64, /system/vendor/lib64]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                     at com.google.android.gms.iid.zzaf.<init>(Unknown Source:58) 
                                                     at com.google.android.gms.iid.zzaf.<init>(Unknown Source:6) 
                                                     at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source:68) 
                                                     at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source:4) 
                                                     at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:73) 
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                     at java.lang.Thread.run(Thread.java:764) 
                                                 
                                                 
                                                 --------- beginning of system
04-16 22:36:30.470 1409-6023/? W/ActivityManager:   Force finishing activity com.ziplogix.zipForm/.MainActivity

**Comment by macdonst** [comment] 2018-04-16 18:16
@mail4sheik you said the plugin was working two days ago. What has changed?

**Comment by DamilolaJegede** [comment] 2018-04-17 05:12
+1

When I connect to debug in Chrome, I see `PushNotification not defined`.

**Comment by mail4sheik** [comment] 2018-04-17 07:05
@macdonst  I was working to handle clicks from tray notification which wasn't delivered to the app properly. Only change I remember is altered "singleTask" to "singleTop" for "AndroidLaunchMode". That too  rolled back now. 
I used to get same bug before, when I changed cordova android version to 6.3.0, it started working. Now again same issue. 

@DamilolaJegede PushNotification should be defined, perhaps plugin is not installed properly or make sure you try it after deviceready triggered.

**Comment by mail4sheik** [comment] 2018-04-17 09:35
https://stackoverflow.com/questions/32088984/java-lang-noclassdeffounderror-failed-resolution-of-lcom-google-android-gms-co

I think there is something to do with gradle configuration, these are my dependencies,
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
    }
// PLUGIN GRADLE EXTENSIONS START
apply from: "cordova-plugin-safariviewcontroller/zipForm-SafariViewController-java18.gradle"
apply from: "phonegap-plugin-push/zipForm-push.gradle"
// PLUGIN GRADLE EXTENSIONS END
dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    debugCompile(project(path: "CordovaLib", configuration: "debug"))
    releaseCompile(project(path: "CordovaLib", configuration: "release"))
    compile "com.android.support:support-v4:24.1.1+"
    compile "com.google.android.gms:play-services-auth:+"
    compile "com.google.android.gms:play-services-identity:+"
    compile "com.android.support:customtabs:23.2.0"
    compile "com.android.support:support-v13:23+"
    compile "com.google.android.gms:play-services-gcm:12+"
    compile "me.leolin:ShortcutBadger:1.1.14@aar"
    // SUB-PROJECT DEPENDENCIES END
}

**Comment by michaelhodgins** [comment] 2018-04-17 12:02
I'm getting this on 1.10.7 and 1.11.0. I'm not sure what to do to resolve it.

**Comment by michaelhodgins** [comment] 2018-04-17 14:13
Okay, changing `cordova.system.library.8=com.google.android.gms:play-services-gcm:12+` to `cordova.system.library.8=com.google.android.gms:play-services-gcm:15.0.0` in my project.properties file as least fixes the crash caused by calling `PushNotification.init()`. I haven't tested further yet.

**Comment by DamilolaJegede** [comment] 2018-04-17 16:04
I’m using PhoneGap Build. It’s been working before now so it’s not something new I’m doing. Works great on iOS so it’s definitely not an installation issue. I’m using PGB CLI 8.0.0

**Comment by mail4sheik** [comment] 2018-04-17 17:49
If I change "  <framework src="com.google.android.gms:play-services-gcm:12+"/>" to "  <framework src="com.google.android.gms:play-services-gcm:+"/>"  it works. Not sure which version has the right dependency.

**Comment by macdonst** [comment] 2018-04-17 18:57
@DamilolaJegede yeah, but what version of the plugin are you using? what version of cordova-android?

**Comment by macdonst** [comment] 2018-04-17 19:03
@mail4sheik pretty sure your issue is fixed by this PR: https://github.com/phonegap/phonegap-plugin-push/pull/2320 which means I will release a new v1.x shortly.

**Closed** 2018-04-17 19:03 UTC
Labels: android, question

**Comment by macdonst** [comment] 2018-04-18 02:25
@mail4sheik try 1.11.1 that I released today.

**Comment by DamilolaJegede** [comment] 2018-04-18 05:31
@macdonst I'm using cordova-android 7.0.0

**Comment by mail4sheik** [comment] 2018-04-18 15:06
@macdonst Thanks a lot. Updated to 1.11.1 and it is working great.

**Comment by macdonst** [comment] 2018-04-18 15:07
@DamilolaJegede right so if you are using the latest version of the plugin it requires cordova-android 7.1.0.

**Comment by mail4sheik** [comment] 2018-04-18 15:15
"However, you should all upgrade to 2.x as the benefits include 1) FCM support as GCM is deprecated and 2) being able to set the FCM version from the CLI or config.xml so you can easily match these dependent versions. At least it's easier than having to modify the project.properties file which can be overwritten by cordova build android"

I understand, since server side code ready for GCM, we didn't upgrade. Switching to FCM might involve a lot of extra work for server side developers. That is why still sticking on to the 1.x version. If I could make a choice again, will switch to 2.x. Thanks.

**Comment by macdonst** [comment] 2018-04-18 15:26
@mail4sheik the server side changes are minimal.

**Comment by mail4sheik** [comment] 2018-04-18 15:33
Okay, I'll request this to the developers. Thanks again.

**Comment by jcesarmobile** [comment] 2018-04-18 15:57
Also, Google has deprecated GCM and will remove support in less than a year, so you should migrate as soon as possible
