### ISSUE TITLE
push.on('notification')  not triggered - Ionic

### ISSUE THREAD

**Issue by aishahismail** [phonegap/phonegap-plugin-push#808] opened 2016-04-14 02:31 UTC
I'm using Android only.
### Expected Behaviour

When I received new notification, then click it in task bar to open the app, then push.on('notification') should be fired.
### Actual Behaviour

When I received new notification, then click it in task bar to open the app, then push.on('notification') not fired.
### Reproduce Scenario (including but not limited to)

Once the app open, I called this code first:

```
 var push = PushNotification.init({
       "android": {
           "senderID": "XXXXXXXXXXX",
           "sound": "true",
           "vibrate": "true"
       },
       "ios": {
           "alert": "true",
           "badge": "true",
           "sound": "true"
        },
        "windows": {}
})

push.on('notification', function (data) {
     alert('You Got New Notification');
 })
```

It should alert 'You Got New Notification' but it didn't. I tried to push notification again while the app is already launch/open/run, then magically the app able to alert 'You Got New Notification'. 
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android Version and device model:
1. Android  5.0.2 (Xiomi Redmi Note 3)
2. Android  4.4.2 (Lenovo K910L)
3. Android 4.1.2 (Samsung GT-I9070)
#### Cordova CLI version and cordova platform version

```
cordova CLI                                      #5.4.1                                  
cordova platform version android     #5.0.0
```
#### Plugin version

```
cordova plugin version | grep phonegap-plugin-push   #1.6.2
```

Thanks.

**Comment by macdonst** [comment] 2016-04-15 02:23
@aishahismail what payload did you send?

**Comment by yesnoj** [comment] 2016-04-18 09:16
use content-available : 1 in the payload for the notification, it will works 👍

**Comment by zareone** [comment] 2016-05-05 14:03
Hi everybody!

I'm trying to accomplish the same as the original poster. 

I've already tried the content-available flag in the payload, but it doesn't work. According to the [GCM API ](https://developers.google.com/cloud-messaging/http-server-ref#downstream-http-messages-json) docs, the flag is for waking-up the app on notification on iOS devices (this is the default behavior for Android).

The thing is, the app goes to the foreground when you tap the notification (no matter what the value of content-available is), but the callback registered on notification doesn't get invoked. 

Any ideas?

Thanks in advance.

**Comment by chitcode** [comment] 2016-06-26 06:07
I have also exactly same issue. Any solution to the problem ?

**Comment by macdonst** [comment] 2016-06-26 22:49
@zareone @chitcode same as what I asked @aishahismail what payload did you send?

**Comment by RalfGe81** [comment] 2016-09-01 12:25
i have the same problem as zareone. When i touch the message on android, the  push.on('notification') will called. On IOS nothing happened. Anyone an Idea?

Here is my code:

Client:

`onDeviceReady: function () {
        var push = PushNotification.init({
            "android": {
                "senderID": "45362031342",
                "vibration": true,
                "sound": true,
                "badge": true,
                "forceShow": true
            },
            "ios": {
                "alert": true,
                "sound": true,
                "badge": true,
                "clearBadge": "true",
                "categories": {
                    "tradingmessage": {
                        "yes": {
                            "callback": "app.accept", "title": "lesen", "foreground": true, "destructive": false
                        },
                        "no": {
                            "callback": "app.reject", "title": "verwerfen", "foreground": false, "destructive": false
                        }
                    }
                }
            },
            "windows": {}
        });

        app.accept = function(data) {
            navigator.notification.alert(data.message);

            var $mainViewDiv = $('#mainViewDiv');
            $mainViewDiv.injector().get('$location').path("/article/" + data.additionalData.artikle_id);
            $mainViewDiv.scope().$apply();

            push.finish(function() {
                console.log('accept callback finished');
            }, function() {
                console.log('accept callback failed');
            }, data.additionalData.notId);
        };

        push.on('registration', function (data) {
            console.log("registration event");
            angular.element($('#PushControllerLi')).scope().registerDeviceRequest(data.registrationId);
            console.log(JSON.stringify(data));
        });

        push.on('notification', function (data) {
            console.log("notification event");
            console.log(window.device.platform);
            console.log(JSON.stringify(data));

            if (
                (undefined != data.additionalData.coldstart && false == data.additionalData.coldstart)
                || window.device.platform !== 'Android'
            ) {
                navigator.notification.alert(data.message);

                var $mainViewDiv = $('#mainViewDiv');
                $mainViewDiv.injector().get('$location').path("/article/" + data.additionalData.artikle_id);
                $mainViewDiv.scope().$apply();
            }

            push.finish(function () {
                console.log('finish successfully called');
            });
        });

        push.on('error', function (e) {
            console.log("push error", e);
        });
    }`

Server PHP:

`$body = array(
            'aps' => array(
                'badge' => 1,
                'alert' => array('title' => $jForm[self::JFORM][self::TITLE],
                    'body' => $jForm[self::JFORM][self::MESSAGE],
                ),
                'sound' => 'default',
                'artikel_id' => 120,
                "content-available" => 1,
                "category" => "tradingmessage",
            ),
            "notId" => 1,
        );`

**Comment by RalfGe81** [comment] 2016-09-01 14:47
After ralfge$ cordova platform remove ios and ralfge$ cordova platform add ios it works.... .

**Comment by leandroh** [comment] 2016-11-25 19:20
I got this problem too.

**Platform and Version**

- Android 6.0 (Motorola Moto G - 3rd gen)

**Cordova CLI version and cordova platform version**

- cordova CLI 6.4.0
- cordova platform version android # 6.0.0

**Plugin version**

- phonegap-plugin-push 1.9.0 "PushPlugin"

**Comment by phoenixstudio** [comment] 2016-12-09 04:57
Is there any solution with this problem?
I'm having the same problem too.
The problem is the push.on('notification')  not triggered once the app is opened, so any data/object sent via gcm, cannot be received.

**Comment by manojrejinthala** [comment] 2017-01-30 11:02
Hi i am also facing same problem.
@aishahismail  did you find any solutions for this problem

**Comment by hnakhuva** [comment] 2017-02-14 14:14
I'm also facing same problem.. any solution to this?? @aishahismail @leandroh @ihr-it-projekt @zareone

**Comment by ihr-it-projekt** [comment] 2017-02-15 19:01
Sorry, in my case remove and add IOS was helpful.

**Comment by amanchinu** [comment] 2017-03-03 15:40
Hi, I'm also having the same issue.
I found my solution in the phonegap doc https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

the third solution works for me.
Hope this help.

**Comment by aishahismail** [comment] 2017-03-16 12:51
Sorry for the late reply, I'm just the front end developer, I thought this problem is coming from my side but unfortunately it comes from back end. What I'm understand from my back end guy, they said its happen because of the payload value.

**Comment by anjali14garg** [comment] 2017-05-03 13:57
Hello All,
I am also facing this issue. I am using ionic 1. Please can anyone help. Can any of you provide me the running php code for push notification of gcm

**Comment by anjali14garg** [comment] 2017-05-19 14:22
Any Updates.

**Comment by anjali14garg** [comment] 2017-05-22 06:04
Any Updates.

**Comment by macdonst** [comment] 2017-06-28 19:26
Closing, original reporter claims his problem was an issue on the back end.

**Closed by macdonst** 2017-06-28 19:26 UTC
Labels: android, question

**Comment by rahulFortunekit** [comment] 2018-03-19 13:15
I am having same issue while i am clicking notification from tray push.on('notification') does not called.

this is my server log

/Push_FCMService: onMessage - from: 241821265499
D/Push_FCMService: normalize extras
D/Push_FCMService: key = updatedAt
D/Push_FCMService: replace key updatedAt with updatedAt
D/Push_FCMService: key = action
D/Push_FCMService: replace key action with action
D/Push_FCMService: key = _id
D/Push_FCMService: replace key _id with _id
D/Push_FCMService: key = body
D/Push_FCMService: replace key body with message
D/Push_FCMService: no locale found for key = message, error Value Debugging of type java.lang.String cannot be converted to JSONObject
D/Push_FCMService: key = type
D/Push_FCMService: replace key type with type
D/Push_FCMService: key = board
D/Push_FCMService: replace key board with board
D/Push_FCMService: key = sound
D/Push_FCMService: replace key sound with sound
D/Push_FCMService: key = state
D/Push_FCMService: replace key state with state
D/Push_FCMService: key = title
D/Push_FCMService: replace key title with title
D/Push_FCMService: no locale found for key = title, error Value Society of type java.lang.String cannot be converted to JSONObject
D/Push_FCMService: key = createdAt
D/Push_FCMService: replace key createdAt with createdAt
D/Push_FCMService: background
D/Push_FCMService: message =[Debugging App :pawan]
D/Push_FCMService: title =[Society Board :]
D/Push_FCMService: contentAvailable =[null]
D/Push_FCMService: forceStart =[null]
D/Push_FCMService: create notification
E/Push_FCMService: Number format exception - Error parsing notId: null
D/Push_FCMService: stored icon=null
D/Push_FCMService: stored iconColor=null
D/Push_FCMService: stored sound=true
D/Push_FCMService: stored vibrate=true
D/Push_FCMService: no icon resource found - using application icon
D/Push_FCMService: create actions: with in-line
D/MobiComPushReceiver: Received notification
D/Push_HandlerActivity: not id = 0
V/FA: onActivityCreated
V/Push_HandlerActivity: onCreate
D/Push_HandlerActivity: callback = null
D/Push_HandlerActivity: dismissed = false
D/Push_Plugin: convert extras to json
D/Push_Plugin: key = updatedAt
D/Push_Plugin: key = action
D/Push_Plugin: key = actionCallback
D/Push_Plugin: key = _id
D/Push_Plugin: key = type
D/Push_Plugin: key = board
D/Push_Plugin: key = sound
D/Push_Plugin: key = state
D/Push_Plugin: key = title
D/Push_Plugin: key = dismissed
D/Push_Plugin: key = createdAt
D/Push_Plugin: key = message
D/Push_Plugin: key = coldstart
D/Push_Plugin: key = foreground
V/Push_Plugin: extrasToJSON: {"sound":"default","title":"Society Board :","message":"Debugging App :pawan","additionalData":{"updatedAt":"2018-03-19T12:51:36.527Z","action":"newSocietyBoard","_id":"5aafb2582c270740bc550eec","type":"society","board":{"createdAt":"2018-03-19T12:51:36.056Z","society":"5a941654f0e9966ae4ef707b","__v":0,"description":"aaaaaaaaaa","_id":"5aafb2582c270740bc550ee6","message":"Debugging App","updatedAt":"2018-03-19T12:51:36.056Z","sentBy":"pawan","status":true},"state":"societyBoard","dismissed":false,"createdAt":"2018-03-19T12:51:36.527Z","coldstart":false,"foreground":false}}
D/Push_HandlerActivity: bringToForeground = true
D/Push_HandlerActivity: isPushPluginActive = true
D/Push_HandlerActivity: don't want main activity
D/CordovaActivity: Started the activity.
