### ISSUE TITLE
Big picture not showing in nextbit OS

### ISSUE THREAD

**Issue by pavankumarkatakam** [phonegap/phonegap-plugin-push#1801] opened 2017-06-20 07:32 UTC
### Expected Behaviour
Show the picture if expanded when style is set to "PICTURE".
### Actual Behaviour
Expanding the notification but it is showing full white rather than showing a picture.
### Reproduce Scenario (including but not limited to)
This is only happening for nextbit OS mobile device is nextbit robin running the android 7.1.1
#### Steps to Reproduce 
Sending the below payload to the nextbit robin device

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.1.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
nextbit
#### Cordova CLI version and cordova platform version

    cordova --version: 5.0.0
    cordova platform version android : 5.1.1                   

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push : 1.5.3

#### Sample Push Data Payload
```
{
  "title":"sample",
  "body":"sample",
  "style":"picture",
   "picture:":"https://www.elivio.com/assets/elivio/img/banners/10.png"
}
```

Attaching the image that looks like in the robin device
![screenshot_20170620-124629](https://user-images.githubusercontent.com/6078669/27321628-81cb814e-55b8-11e7-83c3-74a90f69d63b.png)

For the same payload it is working fine in other devices like moto g3 , honor running android 7 etc.

Extra information is , in the robin devices for other apps are working with picture style

**Comment by macdonst** [comment] 2017-06-20 17:04
@pavankumarkatakam not sure if I'll be able to fix it as I don't have access to nextbit device. Can you try to reproduce while running `adb logcat | grep Push`?

**Comment by pavankumarkatakam** [comment] 2017-06-21 04:52
Hi @macdonst, Surely I will share you the details of logcat today. More information on the issue is it is not working in devices
 1. Obi SF1 running 5.0.2
 2. Nexus 6p running 7.1.2

**Comment by macdonst** [comment] 2017-06-26 23:07
@pavankumarkatakam any update on this? I can't reproduce it.

**Comment by pavankumarkatakam** [comment] 2017-06-27 05:47
Hi, I can confirm that the payload is correct since it is working in other devices and the image is showing. More info about is the same payload is not able to show image sometimes and showing sometimes i have attached the images please check
![noimage](https://user-images.githubusercontent.com/6078669/27572510-2178e558-5b2a-11e7-960c-de6aaab636b9.jpeg)
![image](https://user-images.githubusercontent.com/6078669/27572519-261c50e0-5b2a-11e7-9f93-fe96aeb340c3.jpeg)

Is there any effect depending on image format, battery, and the internet for showing push notification.

**Comment by macdonst** [comment] 2017-06-27 11:38
@pavankumarkatakam I can only speculate without logs. The Nextbit may just have a bug with regards to picture messages or there could be some program running on the Nextbit preventing the download of the image, etc.

**Comment by pavankumarkatakam** [comment] 2017-06-27 11:49
Facing this issue in another device of my own brother it is **Oneplus 3** running 7.1.1 . Today I sent 10 push notification to this device but only one-time image is not showing.

**Comment by macdonst** [comment] 2017-06-27 11:53
@pavankumarkatakam I feel for you but I can't do much without some logs to tell me what is going on. I do have a OnePlus device here that I can't reproduce the problem on.

**Comment by pavankumarkatakam** [comment] 2017-06-27 11:55
Ok then I will send logs related to Oneplus3 when the image is not showing.

**Comment by sk16** [comment] 2017-07-21 09:15
Issue is reproducing in moto c + as well as in one plus 3, android 7 , when the devices are in sleep mode , for more than 30 minutes.

**Comment by pavankumarkatakam** [comment] 2017-07-21 09:24
Thanks @sk16 , Im actually unable to reproduce it but now i got it if the mobile is in sleep mode then img not noting but after than it is showing.

**Comment by sk16** [comment] 2017-07-22 10:18
[push4.txt](https://github.com/phonegap/phonegap-plugin-push/files/1167273/push4.txt)

Here is android logs . Please check . I have send two push notification . In first Push notification , image did'nt work properly . But it came in second push notification . 

Steps to Reproduce

1. Put device into sleep for more than 30 minutes 
2. Send push notification.

Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 7.0.0 . Reproducible only in android 7 . 

(Android) What device vendor (e.g. Samsung, HTC, Sony...)

Moto c+ , one plus 3

Sample payload :

{
    "default": "Enter default message here",
    "GCM": "{\"data\":{\"notId\": 5,\"priority\": 1,\"message\":\"The internet is built on cat pictures\",\"title\":\"On Android if you want your on('notification') event handler to be called when your app is in the background it is relatively simple.\",\"image\": \"www/styles/images/app_icon_180.png\",\"delay_while_idle\": \"false\",\"link\": \"profile\",\"type\": \"0\",\"summaryText\": \"The internet is built on cat pictures\",\"style\": \"picture\",\"picture\": \"https://learnyst.s3.amazonaws.com/assets/schools/1247/resources/pushMessage/images/login_screen_bg_mjl2q9.png\"}}"
}

**Comment by sk16** [comment] 2017-07-26 07:33
@pavankumarkatakam  can u tell me issue is reproducing with images with http or https ? I am not able to reproduce the issue with http images.

**Comment by pavankumarkatakam** [comment] 2017-07-26 07:45
Still, im not able to reproduce but all the images im using is https because if using s3 to host my all images.

**Comment by macdonst** [comment] 2017-08-18 15:52
@sk16 there's not much I can do if the HttpUrlConnection times out.

**Comment by sk16** [comment] 2017-08-18 15:55
Can we retry (exp backoff) if it times out

**Comment by macdonst** [comment] 2017-11-27 21:18
Closing, can't reproduce.

**Closed by macdonst** 2017-11-27 21:18 UTC
Labels: android, can't reproduce, question
