### ISSUE TITLE
Uncaught ReferenceError: cordova is not defined     at constructor.handler [as _handler] (Scanner.js?_dc=1485160444021:35)

### ISSUE THREAD

**Issue by Teenashrivastava** [phonegap/phonegap-plugin-push#1543] opened 2017-01-23 08:46 UTC
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by jcesarmobile** [comment] 2017-01-23 10:59
Duplicate of https://github.com/phonegap/phonegap-plugin-push/issues/1542

**Closed by jcesarmobile** 2017-01-23 10:59 UTC
