### ISSUE TITLE
Registering on iOS sometimes crashes app

### ISSUE THREAD

**Issue by barryvdh** [phonegap/phonegap-plugin-push#512] opened 2016-01-14 22:21 UTC
My iOS got rejected twice for the same reason, for crashing after logging in and registering push. The crash logs seem to indicate that the error happens with `Dispatch queue: com.apple.UNSNotificationRegistrarConnection`. Specific crash happened on iPad with iOS 9.2

Below is the part that I assume is useful:
```
Incident Identifier: BAC37D3B-0C65-4BAC-980A-xx
CrashReporter Key:   xx
Hardware Model:      xxx
Process:             xxx [4071]
Path:                /private/var/mobile/Containers/Bundle/Application/xx/xxx.app/xxx
Identifier:          nl.xxx.app
Version:             2 (1.3.5)
Code Type:           ARM-64 (Native)
Parent Process:      launchd [1]

Date/Time:           2016-01-14 12:44:27.27 -0800
Launch Time:         2016-01-14 12:44:14.14 -0800
OS Version:          iOS 9.2 (13C75)
Report Version:      105

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
Triggered by Thread:  3

Filtered syslog:
None found

Global Trace Buffer (reverse chronological seconds):
0.386990     CFNetwork                 	0x0000000183bc4708 TCP Conn 0x126c1bcd0 started
0.387382     CFNetwork                 	0x0000000183bc4708 TCP Conn 0x126ce06e0 started
2.396147     CFNetwork                 	0x0000000183b2184c TCP Conn 0x126e17190 SSL Handshake DONE
2.568379     CFNetwork                 	0x0000000183b2175c TCP Conn 0x126e17190 starting SSL negotiation
2.568670     CFNetwork                 	0x0000000183bc3104 TCP Conn 0x126e17190 complete. fd: 20, err: 0
2.568990     CFNetwork                 	0x0000000183bc4630 TCP Conn 0x126e17190 event 1. err: 0
2.734247     CFNetwork                 	0x0000000183bc4708 TCP Conn 0x126e17190 started
2.747107     CFNetwork                 	0x0000000183c0bb04 NSURLConnection finished with error - code -1004
2.747173     CFNetwork                 	0x0000000183bd7bd0 HTTP load failed (error code: -1004 [1:61])
2.747688     CFNetwork                 	0x0000000183bc340c TCP Conn 0x126d60c50 Failed : error 0:61 [61]
2.747688     CFNetwork                 	0x0000000183bc3104 TCP Conn 0x126d60c50 complete. fd: -1, err: 61



Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0:
0   libsystem_kernel.dylib        	0x00000001830d14bc 0x1830d0000 + 5308
1   libsystem_kernel.dylib        	0x00000001830d1338 0x1830d0000 + 4920
2   CoreFoundation                	0x0000000183500ac0 0x183424000 + 903872
3   CoreFoundation                	0x00000001834fe7c4 0x183424000 + 894916
4   CoreFoundation                	0x000000018342d680 0x183424000 + 38528
5   GraphicsServices              	0x000000018493c088 0x184930000 + 49288
6   UIKit                         	0x00000001882a4d90 0x188228000 + 511376
7   xxx                       	0x00000001000c9bf0 0x1000c4000 + 23536
8   libdyld.dylib                 	0x0000000182fce8b8 0x182fcc000 + 10424

Thread 1 name:  Dispatch queue: com.apple.NSURLSession-work
Thread 1:
0   CFNetwork                     	0x0000000183b08508 0x183af0000 + 99592
1   CFNetwork                     	0x0000000183b08508 0x183af0000 + 99592
2   CFNetwork                     	0x0000000183b9164c 0x183af0000 + 661068
3   CFNetwork                     	0x0000000183c098b4 0x183af0000 + 1153204
4   libdispatch.dylib             	0x0000000182f9d630 0x182f9c000 + 5680
5   libdispatch.dylib             	0x0000000182f9d5f0 0x182f9c000 + 5616
6   libdispatch.dylib             	0x0000000182fa9634 0x182f9c000 + 54836
7   libdispatch.dylib             	0x0000000182fa10f4 0x182f9c000 + 20724
8   libdispatch.dylib             	0x0000000182fab504 0x182f9c000 + 62724
9   libdispatch.dylib             	0x0000000182fab224 0x182f9c000 + 61988
10  libsystem_pthread.dylib       	0x00000001831b1470 0x1831b0000 + 5232
11  libsystem_pthread.dylib       	0x00000001831b1020 0x1831b0000 + 4128

Thread 2 name:  Dispatch queue: com.apple.libdispatch-manager
Thread 2:
0   libsystem_kernel.dylib        	0x00000001830ed4fc 0x1830d0000 + 120060
1   libdispatch.dylib             	0x0000000182fb094c 0x182f9c000 + 84300
2   libdispatch.dylib             	0x0000000182f9f7bc 0x182f9c000 + 14268

Thread 3 name:  Dispatch queue: com.apple.UNSNotificationRegistrarConnection
Thread 3 Crashed:
0   libobjc.A.dylib               	0x0000000182bc9bdc 0x182bb0000 + 105436
1   UserNotificationServices      	0x0000000184b14b5c 0x184b10000 + 19292
2   libsystem_blocks.dylib        	0x0000000182ff98e8 0x182ff8000 + 6376
3   libdispatch.dylib             	0x0000000182f9d5f0 0x182f9c000 + 5616
4   libdispatch.dylib             	0x0000000182fa9634 0x182f9c000 + 54836
5   libdispatch.dylib             	0x0000000182fa10f4 0x182f9c000 + 20724
6   libdispatch.dylib             	0x0000000182f9d5f0 0x182f9c000 + 5616
7   libdispatch.dylib             	0x0000000182faba88 0x182f9c000 + 64136
8   libdispatch.dylib             	0x0000000182fab224 0x182f9c000 + 61988
9   libsystem_pthread.dylib       	0x00000001831b1470 0x1831b0000 + 5232
10  libsystem_pthread.dylib       	0x00000001831b1020 0x1831b0000 + 4128

Thread 4 name:  com.apple.NSURLConnectionLoader
Thread 4:
0   libsystem_kernel.dylib        	0x00000001830d14bc 0x1830d0000 + 5308
1   libsystem_kernel.dylib        	0x00000001830d1338 0x1830d0000 + 4920
2   CoreFoundation                	0x0000000183500ac0 0x183424000 + 903872
3   CoreFoundation                	0x00000001834fe7c4 0x183424000 + 894916
4   CoreFoundation                	0x000000018342d680 0x183424000 + 38528
5   CFNetwork                     	0x0000000183b9d434 0x183af0000 + 709684
6   Foundation                    	0x0000000183f0bc40 0x183e18000 + 998464
7   libsystem_pthread.dylib       	0x00000001831b3b28 0x1831b0000 + 15144
8   libsystem_pthread.dylib       	0x00000001831b3a8c 0x1831b0000 + 14988
9   libsystem_pthread.dylib       	0x00000001831b1028 0x1831b0000 + 4136

etc etc.
```

This was using the latest version (at the time): v1.5.2 with Cordova 5.4

The error is hard to reproduce and only seems to occur on the first time the app is run. Re-registering on a second run doesn't give the same error.

Plugin list:
```
cordova-plugin-crosswalk-webview 1.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-geolocation 1.0.1 "Geolocation"
cordova-plugin-inappbrowser 1.1.1 "InAppBrowser"
cordova-plugin-whitelist 1.2.0 "Whitelist"
phonegap-plugin-push 1.5.2 "PushPlugin"
```

I run the initialise function for the Push notification after loggin them in with Sattelizer, and send the notification id to the API service

```
init: function(){

                // If already registered, no need to redo
                if (token) {
                    return;
                }

                document.addEventListener("deviceready", function() {

                    push = window.PushNotification.init({
                            "android": {
                                "senderID": "xxx",
                                "icon": "ic_stat_name",
                                "iconColor": '#ffffdb31'
                            },
                            "ios": {},
                            "windows": {}
                    });

                    push.on('registration', onRegistration);

                    push.on('notification', onNotification);

                    push.on('error', function(e){
                        errorService.alert(e.message);
                    });

                }, false);
            },
```

```
 var onRegistration = function(data){

            var type = 'ios';
            if (isAndroid()) {
                type = 'android';
            }

            token =  data.registrationId;
            apiService.post('/notification/register', {type: type, token: token})
                .error(function (e) {
                    errorService.alert(e.message);
                });
        }
```

Do you have any ideas what could be causing this?

**Comment by barryvdh** [comment] 2016-01-18 14:41
@macdonst Any idea how I can debug this to provide you with more information?

**Comment by barryvdh** [comment] 2016-01-18 16:11
This is the debug log from Cordova. It might seem to indicate I'm calling the register twice, which could create a race condition?

```
2016-01-18 17:05:18.707 MyApp[4731:4449903] [CDVTimer][TotalPluginStartup] 36.330998ms
2016-01-18 17:05:19.050 MyApp[4731:4449903] active
2016-01-18 17:05:19.053 MyApp[4731:4449903] PushPlugin skip clear badge
2016-01-18 17:05:19.635 MyApp[4731:4449903] Resetting plugins due to page load.
2016-01-18 17:05:22.364 MyApp[4731:4449903] Finished load of: file:///var/mobile/Containers/Bundle/Application/62773076-421F-49C4-B24B-1B8C85C75B4E/xxx.app/www/app.html#/login
2016-01-18 17:05:24.917 MyApp[4731:4449903] THREAD WARNING: ['InAppBrowser'] took '131.325684' ms. Plugin should use a background thread.
2016-01-18 17:05:38.403 MyApp[4731:4449903] webView:didFailLoadWithError - -1004: Could not connect to the server.
2016-01-18 17:05:40.419 MyApp[4731:4450087] Push Plugin register called
2016-01-18 17:05:40.419 MyApp[4731:4450019] Push Plugin register called
2016-01-18 17:05:40.419 MyApp[4731:4450087] PushPlugin.register: setting badge to false
2016-01-18 17:05:40.419 MyApp[4731:4450019] PushPlugin.register: setting badge to false
2016-01-18 17:05:40.419 MyApp[4731:4450087] PushPlugin.register: clear badge is set to 0
2016-01-18 17:05:40.419 MyApp[4731:4450019] PushPlugin.register: clear badge is set to 0
2016-01-18 17:05:40.419 MyApp[4731:4450087] PushPlugin.register: better button setup
2016-01-18 17:05:40.419 MyApp[4731:4450019] PushPlugin.register: better button setup
2016-01-18 17:05:40.421 MyApp[4731:4450087] GCM Sender ID (null)
2016-01-18 17:05:40.422 MyApp[4731:4450087] Using APNS Notification
2016-01-18 17:05:40.423 MyApp[4731:4450019] GCM Sender ID (null)
2016-01-18 17:05:40.423 MyApp[4731:4450019] Using APNS Notification
(lldb) *crashes here*
```

**Comment by barryvdh** [comment] 2016-01-18 16:38
Okay I've added a check to prevent init from running twice (unless it's unregistered), so this can be probably closed as a faulty implementation.

But it could be useful to prevent the plugin from registering twice, even in this case. Or at least, not make it crash.

My use-case was that this happens in multiple places, because it's only run after login, and already logged in users have a different starting route..

**Comment by macdonst** [comment] 2016-02-03 01:56
@barryvdh I'm having a really hard time reproducing the crash. I think I can guard against it but I'm loath to call it fixed without a test. The only thing I haven't tried is adding crosswalk to the project which I will do next.

**Comment by macdonst** [comment] 2016-03-03 19:08
@barryvdh What version of Cordova-iOS were/are you using?

**Comment by macdonst** [comment] 2016-03-09 00:19
I'm pretty sure this was caused by a bug in cordova iOS. Closing for now.

**Closed by macdonst** 2016-03-09 00:19 UTC
Labels: bug, ios
