### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by SteveKelseyMocapay** [phonegap/phonegap-plugin-push#205] opened 2015-10-05 18:21 UTC
I am getting this error when trying to build android:

:compileDebugJava
/Users/skelsey/Desktop/development/workspace/MobileApp/mtn/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:483: error: cannot find symbol
            mBuilder.setColor(iconColor);
                    ^
  symbol:   method setColor(int)
  location: variable mBuilder of type Builder

**Comment by fredgalvao** [comment] 2015-10-05 20:01
This is a duplicate of https://github.com/phonegap/phonegap-plugin-push/issues/51, please check the solutions there and let us know if you've managed to solve it.

**Comment by macdonst** [comment] 2015-10-06 01:03
@SteveKelseyMocapay check out the section on compiling. https://github.com/phonegap/phonegap-plugin-push#compiling You may have an older version of the support library.

**Comment by SteveKelseyMocapay** [comment] 2015-10-06 15:08
Managed to solve it. Had to delete the android-support-v4.jar that was in my platform/android/lib folder. 

Thanks for the help. Closing this issue.

**Closed** 2015-10-06 15:08 UTC
