### ISSUE TITLE
Notification cannot get when the app is not run background

### ISSUE THREAD

**Issue by jianhao1203** [phonegap/phonegap-plugin-push#729] opened 2016-03-21 09:41 UTC
### Expected Behaviour
Notification can be get no matter the app is run / not run in background or foreground

### Actual Behaviour
Notification cannot be get if the app is being killed at background.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Mi 4i

#### Cordova CLI version and cordova platform version

    cordova --version                                     6.0.0
    cordova platform version android                    android 5.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push    (phonegap-plugin-push 1.6.0)

**Comment by jianhao1203** [comment] 2016-03-21 09:43
I faced the problem that notification cannot be get when the app is not running background/foreground. Is there any solution to solve this issue? thanks

**Comment by macdonst** [comment] 2016-03-21 20:56
@jianhao1203 when your app is in the background do you see the notification in the notification tray? What is a sample payload you send?

**Comment by fredgalvao** [comment] 2016-03-21 23:28
> Notification cannot be get if the app is being killed at background.

He wants the plugin to wake up the app code if it's killed through the "alt-tab". It's a duplicate.

**Comment by jianhao1203** [comment] 2016-03-22 00:35
@macdonst , when the app still running background(not killed off), the notification still can be get.
![screenshot_2016-03-22-08-29-48_com miui home](https://cloud.githubusercontent.com/assets/12949783/13938409/93a32316-f008-11e5-94c3-d5efbd88a06c.png)
![screenshot_2016-03-22-08-29-56_com miui home](https://cloud.githubusercontent.com/assets/12949783/13938674/ab5ae0e8-f008-11e5-8746-bc276f051ac9.png)


However, after I end the apps, the notification will never get anymore even through after that I reopened the app.

![screenshot_2016-03-22-08-30-17_com miui home](https://cloud.githubusercontent.com/assets/12949783/13938694/c84fe0ae-f008-11e5-97b6-9aedcf871d12.png)


Is that anyway that I can overcome this as this denied the purpose of push notification if required the user to run the app in background in order to receive push notification, thanks lot.

**Comment by jianhao1203** [comment] 2016-03-22 00:36
@fredgalvao , is this issue duplicated? I saw the issues #93 that stated already solved but it still happen when I try it yesterday, hope u can give me some suggestions to overcome this issues, thanks.

**Comment by jianhao1203** [comment] 2016-03-22 00:40
@macdonst , here is the code i implement, is there any missed out? I using plugin version 1.6.0.

`document.addEventListener("deviceready", onDeviceReady, false);
            var menuStatus;
			
            function onDeviceReady() {
                document.addEventListener("backbutton", onBackKeyDown, false);

				var push = PushNotification.init({ "android": {"senderID": "263977057230"},
				"ios": {"alert": "true", "badge": "true", "sound": "true"}, "windows": {} } );

				push.on('registration', function(data) {
				console.log(data.registrationId);
				//alert("lai");
				alert(data.registrationId);
				
				});

				push.on('notification', function(data) {
				console.log(data.message);
				alert(data.title+" Message: " +data.message);
				// data.title,
				// data.count,
				// data.sound,
				// data.image,
				// data.additionalData
				});

				push.on('error', function(e) {
				console.log(e.message);
				});
            }
            `

**Comment by PaoloMessina** [comment] 2016-03-22 12:10
+1 i think that the app must receive the push when the app work in foreground, in background and when is killed.

**Comment by macdonst** [comment] 2016-03-22 12:15
@jianhao1203 alright, this is a duplicate of #707. I've tested this on multiple Android phones and cannot reproduce the issue. Please add some details to #707 like the phone you are using, Mi 4i, Android version, etc.

**Closed by macdonst** 2016-03-22 12:15 UTC
Labels: android, duplicate
