### ISSUE TITLE
ios javascript not fired when in background, using latest plugin and WKWebView

### ISSUE THREAD

**Issue by JeremyColton** [phonegap/phonegap-plugin-push#540] opened 2016-01-24 11:39 UTC
Hi,
I am using the latest ios platform and plugins:
ios@4.0.1
phonegap-plugin-push 1.5.2 "PushPlugin"
cordova-plugin-wkwebview-engine 1.0.1 "Cordova WKWebView Engine"

My PushNotication.init() config is:
{
alert: "true",
badge: "true",
sound: "true"
}

I have set "Background Modes" to "Remote notifications" in my XCode project (ios 9.2). My app is configured for APN and my server sends "content-available:1" in the payload.  AppDelegate+notification.m didReceiveRemoteNotification:fetchCompletionHandler see this JSON is ok too.

When my app is in the foreground, my javascript is fired from the APN - OK.

But, when in the background OR when the phone is sleeping, when a notifcation is received by the phone I see the following debug in XCode:
2016-01-24 11:45:34.503 SUp_iOS_PG401[6172:2325268] didReceiveNotification with fetchCompletionHandler
2016-01-24 11:45:38.504 SUp_iOS_PG401[6172:2325268] app in-active
2016-01-24 11:45:41.429 SUp_iOS_PG401[6172:2325268] this should be a silent push
2016-01-24 11:45:43.403 SUp_iOS_PG401[6172:2325268] Notification received
2016-01-24 11:45:43.404 SUp_iOS_PG401[6172:2325268] Push Plugin key: badge
2016-01-24 11:45:43.404 SUp_iOS_PG401[6172:2325268] Push Plugin key: sound
2016-01-24 11:45:43.404 SUp_iOS_PG401[6172:2325268] Push Plugin key: content-available

The alert is shown. But my javascript callback is not called! Any ideas why not?

**Comment by vbresults** [comment] 2016-01-31 05:15
@macdonst Using cordova-plugin-wkwebview-engine it's not even prompting to allow push notifications.

**Comment by vbresults** [comment] 2016-02-01 12:11
@macdonst Scratch what I said, I was using an old cordova.js and didn't include the wkwebview JS either.  It's working fine now.

**Comment by macdonst** [comment] 2016-02-02 17:47
@JeremyColton I can't reproduce this at all. Can you provide a more detailed reproduction scenario?

**Comment by macdonst** [comment] 2016-02-04 15:08
I'm closing this for now as I can't reproduce it. Please re-open with a detailed reproduction scenario.

**Closed by macdonst** 2016-02-04 15:08 UTC
Labels: ios

**Comment by johnrobertcobbold** [comment] 2016-03-03 02:56
@macdonst @JeremyColton 
Because of this : https://issues.apache.org/jira/plugins/servlet/mobile#issue/CB-10657 ?

@macdonst when you say you can't reproduce this at all. Are you using wkWebView ?

**Comment by vbresults** [comment] 2016-03-13 02:17
@macdonst @JeremyColton This appears to be a WKWebView plugin issue, there's nothing to indicate it's something to do with the push plugin
