### ISSUE TITLE
Quick reply in Android and ios

### ISSUE THREAD

**Issue by vermapratyush** [phonegap/phonegap-plugin-push#1081] opened 2016-07-13 14:23 UTC
### Expected Behaviour
Implement quick reply directly from the lock screen or the notification shade

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
AndroidN and iOS

Is there a way to implement QuickReply in the notification using this plugin?

**Comment by macdonst** [comment] 2016-07-13 16:08
@vermapratyush duplicate of #683

Not implemented yet but I'm keen to work on this feature. Please go give that issue a 👍

**Closed by macdonst** 2016-07-13 16:08 UTC
Labels: duplicate
