### ISSUE TITLE
PushNotification.init is undefined on ios with plugin 2.1

### ISSUE THREAD

**Issue by rentalhost** [phonegap/phonegap-plugin-push#2043] opened 2017-10-30 15:47 UTC
### Expected Behaviour

`PushNotification.init()` should works as expected (be available).

### Actual Behaviour

`PushNotification.init is undefined`

### Reproduce Scenario

It works with plugin 2.0, but fails with 2.1. Only for iOS. I am registering via APNS. Android works fine in any version. I am working with `deviceisready` event.

#### Steps to Reproduce 

```js
const pushNotification = window['PushNotification'].init({
    android: {
        icon:      'notification',
        iconColor: '#007CAA'
    },
    ios:     {
        alert: 'true',
        badge: 'true',
        sound: 'true'
    }
});
```

#### Platform and Version

iOS 10.1.1 (14B100)
Model ME499BZ/A (iPhone 5C)
via Phonegap Build

#### Cordova CLI version and cordova platform version

    cordova --version = 7.0.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push = 2.1.0

**Comment by macdonst** [comment] 2017-10-30 19:42
@rentalhost duplicate of #2034 

https://github.com/phonegap/phonegap-plugin-push/issues/2034#issuecomment-340065191

**Closed by macdonst** 2017-10-30 19:42 UTC
Labels: duplicate
