### ISSUE TITLE
Failed to get Plugin in 1.9.1

### ISSUE THREAD

**Issue by debugerr** [phonegap/phonegap-plugin-push#1463] opened 2016-12-14 17:24 UTC
I already reported the same issue previously, where I wasn't aware of the changed CLI min version requirement (#1343). However, PGB has updated and cli-6.4.0 should work as far as I understand the version requirement. I see the same issue:

Expected Behaviour

I can access window["PushNotification"] after device ready fired.

Actual Behaviour

window["PushNotification"] is always undefined

Steps to Reproduce

Install 1.9.1 as a plugin (I use PhoneGap build for that)
Install the app on the device
check the window["PushNotification"] after deviceready fired

Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 10.1.1

Cordova CLI version and cordova platform version

cordova platform version ios 4.3.0
phonegap: cli-6.4.0

Plugin version

1.9.1

**Comment by fredgalvao** [comment] 2016-12-14 18:43
Do you have any logs from PGB showing any installation/build error?

**Comment by macdonst** [comment] 2016-12-14 19:49
@debugerr yeah, it's not that easy. Updates need to be done to support Cocoapods, etc. That's why I document it is not supported for 1.9.0+

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md#phonegap-build-support

**Comment by debugerr** [comment] 2016-12-14 22:02
Thanks for the update and sorry for not seeing the updated PGB specific documentation.

There is another issue on PGB with building iOS and the notification plugin (https://forums.adobe.com/message/9200149#9200149). It's a bit a mess at the moment.

**Comment by frederikbosch** [comment] 2016-12-15 18:13
@macdonst I understand. Updates need to be done. But at the moment there is - to my understanding - no way to get push running. Version 1.8.4 has iOS problems and version 1.9.x cannot be used with PGB. That leaves users at nothing. Hope the issue can be resolved.

**Comment by frederikbosch** [comment] 2016-12-16 08:25
For those who want to build with PGB see [my comment here](https://github.com/phonegap/phonegap-plugin-push/issues/1408#issuecomment-267541802).

**Comment by macdonst** [comment] 2016-12-16 16:11
@debugerr @frederikbosch the PGB team did some upgrades yesterday. Please give it a try and report back if the issue is now fixed.

**Comment by debugerr** [comment] 2016-12-16 16:44
@macdonst The changes they made was to fix the problem with the entitlement file that caused it to fail on recent iOS build (https://github.com/phonegap/build/issues/485#issuecomment-267489163). Unfortunately the problem with the Cocoapods and building 1.9x on PGB has not been resolved.

**Comment by macdonst** [comment] 2016-12-19 14:44
@debugerr the Cocoapods issue should have been fixed awhile ago. They are running a pod sync twice a day in order to stay up to date on the build machines.

**Comment by cagb80** [comment] 2017-01-01 07:23
I solved this problem.
1. Uninstall Pod Pre Release, you will need only CocoaPod 1.1.1
2. Create the Cordova Project
3. Add the iOs Platform, latest one.
4. Add the plugin, even the error.
5. Go to platforms/ios folder and run the command pod install
6. If you get an error of Nanaimo, uninstall all Nanaimo: sudo gem uninstall Nanaimo, select All Nanaimo versions 
7. Reintal Nanaimo sudo gem install nanaimo
8. Go to your Cordova folder and build your project
9. Say thank you :P

**Closed** 2017-04-03 23:00 UTC
Labels: docs, pgb
