### ISSUE TITLE
Question: v1.6.2 - GCM Sender ID - Runtime argument

### ISSUE THREAD

**Issue by cjpete** [phonegap/phonegap-plugin-push#839] opened 2016-04-26 10:33 UTC
Currently I keep the GCM Sender ID in a configuration file which is used to compile the config.xml file (e.g. to get Bundle ID, User Agent header, package version). The values in this configuration file are also injected into a JavaScript file accessible in the web view - so that it can be passed to the PushNotification.init method.

In the latest version of the plugin (1.6.2 at the time of writing this), there is now a required runtime argument `--variable SENDER_ID="XYZ"`, presumably to remove the need to supply the Sender ID in the JavaScript layer.

Firstly, I'm interested in why the plugin is built in this way? Is it in order to protect the security of the Sender ID - rather than to embed it in the web view code?

Secondly, can you recommend an approach for putting in the runtime argument dynamically at the point of compiling the cordova application? I'm thinking of specifying a config.xml <preference> to hold the value, which could be used in some kind of pre-build hook, but I would like to hear your opinion!

**Comment by macdonst** [comment] 2016-04-26 12:04
@cjpete the sender ID needs to be added to a strings.xml file on Android to prevent a warning from the GCM sub-service and on iOS it needs to be added to a pList file. Those things can't happen unless the CLI already knows about the value at build time. In the 2.0.0 release I will remove the need to add the sender ID in the JS file.

Um, why don't you just do this:

```
<plugin name="phonegap-plugin-push">
    <variable name="SENDER_ID" value="XXXXXXX" />
</plugin>
```

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md

**Comment by bluejamesbond** [comment] 2016-04-27 02:49
@macdonst Does this plugin need the Google App ID which is in the Google Service-Info.plist?

**Comment by macdonst** [comment] 2016-04-27 13:45
@bluejamesbond yes, that is what the SENDER_ID is, the Google App ID.

**Comment by bluejamesbond** [comment] 2016-04-27 18:46
@macdonst When I downloaded the Google Plist file, I see a GCM_SENDER_ID and a GOOGLE_APP_ID. The Google App ID is of the form "1:XXX:ios:YYY" while the GCM_SENDER_ID is just a large number. I am still confused where I need to store these values. Can you please elaborate?

**Comment by richmartin** [comment] 2016-06-19 17:28
Requiring this at plugin installation time is bad because it means you cannot build your app for different sender ids. This is commonly done for e.g. testing builds where you want your test server to publish messages using one sender id and not spam all of your real users.

This issue is biting me right now and I'm messing about trying to install the plugin with a bogus id of something like "99999999999999999999" and then having a build hook that does sed -ie 's/99999999999999999999/<REAL_SENDER_ID>/' running in after_prepare. Very painful. Very hacky. :-(

**Comment by macdonst** [comment] 2016-06-20 02:24
@richmartin yeah, I know it sucks but as I mentioned in [the above comment](https://github.com/phonegap/phonegap-plugin-push/issues/839#issuecomment-214718275) it needs to be there for Google to read it not to throw a warning if you are using GCM. When everyone moves to FCM it gets even worse as you can't specify the SENDER_ID at run time anymore as it will absolutely need to be built into the xml files at compile time.

**Comment by briananderson1222** [comment] 2016-08-08 20:20
@macdonst Is the syntax `param` or `variable`? I've seen it flip flop. I currently am using the `param` syntax and am getting the following when trying to restore the plugin

```
Fetching plugin "phonegap-plugin-push@1.8.1" via npm
Failed to restore plugin "phonegap-plugin-push" from config.xml. You might need to try adding it again. Error: Variable(s) missing (use: --variable SENDER_ID=value).
```

**Comment by samzilverberg** [comment] 2016-08-10 20:52
>>the sender ID needs to be added to a strings.xml file on Android to prevent a warning from the GCM sub-service and on iOS it needs to be added to a pList file

this just got me curious as to what kind of warning it is and why.
after some digging around in plugin.xml history i found out the issue that is the root cause to adding sender_Id as install param:
https://github.com/phonegap/phonegap-plugin-push/issues/492

@macdonst it believe it would be really useful if the addition of sender_id & perhaps this issue would be mentioned in the changes log

**Comment by macdonst** [comment] 2016-08-16 20:27
@samzilverberg it will all be documented when we switch to FCM which will not include the senderID in the options to the init method.

**Comment by macdonst** [comment] 2017-06-28 19:35
Closing as v2.0.0/FCM require the sender ID to be in a json file Google can read.

**Closed by macdonst** 2017-06-28 19:35 UTC
Labels: question
