### ISSUE TITLE
Error Permission name C2D_MESSAGE is not unique on release android

### ISSUE THREAD

**Issue by Alexintosh** [phonegap/phonegap-plugin-push#481] opened 2016-01-07 15:22 UTC
I'm getting this error when I build for release android.

If I remove the plugin everything is working fine, any ideas?

Cordova version 5.4.0

![screen shot 2016-01-07 at 15 21 45](https://cloud.githubusercontent.com/assets/776519/12174083/67bb0b60-b552-11e5-8459-4e2276ad1f49.png)

**Comment by macdonst** [comment] 2016-01-07 15:29
Did you uninstall the debug version of your app first?

**Comment by Alexintosh** [comment] 2016-01-07 15:38
Hi @macdonst 
What do you mean for unistall? 
I'm just building with cordova build --release android

**Comment by macdonst** [comment] 2016-01-07 16:03
@Alexintosh I can't reproduce this. What version of the plugin are you using?

**Comment by Alexintosh** [comment] 2016-01-07 16:22
I'm using version 1.5.1
I'm trying to understand what's going on, I'll keep you updated.

**Comment by macdonst** [comment] 2016-01-07 16:33
@Alexintosh I'd try clearing out the platforms and plugins directory and starting clean.

**Comment by Zeychiel** [comment] 2016-01-13 13:10
Hi,
I encountered the same error. Clearing out platforms and plugins did'nt work, the only workaround is...to disable phonegap-plugin-push.
My environment is brand new, sdk, plugin and cordova are last versions.

**Comment by VinceJou** [comment] 2016-01-13 13:13
Hi,
I encountered the same error. Clearing out platforms and plugins did'nt work, the only workaround is...to disable phonegap-plugin-push.
My environment is brand new, sdk, plugin and cordova are last versions.

**Comment by macdonst** [comment] 2016-01-13 15:02
@VinceJou do you use any other plugins that may be adding C2D_MESSAGE?

**Comment by Alexintosh** [comment] 2016-01-13 15:56
For some reason I had some hardcoded permissions in the Manifest, once cleaning those it worked.

**Comment by VinceJou** [comment] 2016-01-14 08:36
@macdonst Yes, I have another application using it

**Comment by FerryDewe** [comment] 2016-01-15 07:16
My solution, is to remove the duplicate plugin.
In my case it was, between this com.phonegap.plugins.PushPlugin or phonegap-plugin-push
Run this before the release, will remove the double permission in the Manifest
> cordova plugin rm com.phonegap.plugins.PushPlugin

**Comment by macdonst** [comment] 2016-01-15 18:44
@VinceJou right, you can only have that in the AndroidManifest.xml once. What is the other plugin you are using?

**Comment by VinceJou** [comment] 2016-01-27 15:02
@macdonst Hi, sorry for the delay...the other application using it is ms-azure-mobile-engagement.
By now, the problem has been fixed by deactivating PushPlugin, but...I need it back :D
In plugin.xml, we have :
- for azme :
<uses-permission android:name="$PACKAGE_NAME.permission.C2D_MESSAGE"/>
<permission android:name="$PACKAGE_NAME.permission.C2D_MESSAGE" android:protectionLevel="signature"/>

- for pushPlugin :
<permission android:name="${applicationId}.permission.C2D_MESSAGE" android:protectionLevel="signature" />
<uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />

**Comment by macdonst** [comment] 2016-01-27 15:16
@VinceJou just confirming this is the plugin:

https://github.com/Azure/azure-mobile-engagement-cordova

I'll start to look into it but in the mean time you can manually remove that line from the AndroidManifest.xml file and build in Android Studio.

**Comment by VinceJou** [comment] 2016-01-27 15:25
@macdonst yes, this seems to be the one. Thanks,

**Comment by VinceJou** [comment] 2016-02-02 15:19
Hi @macdonst , any news on the subject ?

**Comment by shawns582** [comment] 2016-02-17 05:52
I have this same issue with just phonegap-plugin-push installed.  Any way to resolve it?   I notice that the C2D_message permission is in AndroidManifest.xml, plugins/phonegap-plugin-push/plugin.xml, and platforms/android/android.json.

Is this the right setup?  thanks.

**Comment by VinceJou** [comment] 2016-02-18 15:42
Hi shawns,
No news on the subject from @macdonst in a while, the problem still occurs.
As you have only one plugin causing the bug, have you tried clearing out the platforms and plugins directory and starting clean ?

**Comment by macdonst** [comment] 2016-02-29 18:36
It looks like two plugins were adding the permission in using different methods. This caused plugman to add the permission in twice. I've now matched the way the azure plugin was doing things. It's not necessarily any better but at least both plugins can co-exist now.

**Comment by Zeychiel** [comment] 2016-03-04 15:35
Great job, it works like a charm.
Thanks for helping !

**Comment by VinceJou** [comment] 2016-03-04 15:36
Great job, it works like a charm.
Thanks for helping !

**Comment by Zeychiel** [comment] 2016-04-28 11:22
Hi @macdonst,
Issue is back with 1.6.3, the plugin.xml is nowagain: 
`<permission android:name="${applicationId}.permission.C2D_MESSAGE" android:protectionLevel="signature" />`

**Comment by VinceJou** [comment] 2016-04-28 11:24
Hi @macdonst,
Issue is back with 1.6.3, the plugin.xml is nowagain: 
<permission android:name="${applicationId}.permission.C2D_MESSAGE" android:protectionLevel="signature" />

**Comment by macdonst** [comment] 2016-04-28 12:11
@VinceJou are you using the Azure plugin? I had to revert the previous change as two released apps couldn't use phonega-plugin-push.

**Comment by VinceJou** [comment] 2016-04-28 12:19
Yes, I still use it 😄 
This was just a warning that this issue can re-occur and can be solved by using the version 1.6.2 of this plugin; which seems absolutely acceptable to me until the next major release !

**Comment by macdonst** [comment] 2016-04-28 12:21
@VinceJou yeah, I knew one of the issues would come back but I didn't have a chance to find out which one it was. I will have to work with MS to fix.

**Comment by macdonst** [comment] 2016-04-28 12:27
@VinceJou I'm gonna have to send them a PR once I can test a fix. Luckily we know people at MS.

**Comment by VinceJou** [comment] 2016-04-28 12:30
@macdonst I wish you good luck on that ! Do you have any idea why they use $PACKAGE_NAME instead of ${applicationId} ?

**Comment by macdonst** [comment] 2016-04-28 13:15
@VinceJou probably a pre-gradle affectation.

**Comment by macdonst** [comment] 2016-04-28 14:09
I opened a PR with MS https://github.com/Azure/azure-mobile-engagement-cordova/pull/24

**Comment by VinceJou** [comment] 2016-04-28 14:19
Great, thanks.
Their bot seems nice.

**Comment by macdonst** [comment] 2016-04-29 02:32
@VinceJou my PR got merged. 

https://github.com/Azure/azure-mobile-engagement-cordova/commit/88156e86487e3493d0e37b72beda4d7232d07627

Can you give you app a try with both plugins and let me know if it works. If it does, just close this issue actually.

**Comment by VinceJou** [comment] 2016-05-02 08:48
Hi @macdonst 
Thanks for the quick action.
The new version of Azme is not yet available via Npm ; as I left the project I'll tell the new guy in charge to test it as soon as it is available and reopen the ticket if any problem occurs.

**Comment by macdonst** [comment] 2016-05-02 10:44
@VinceJou odd, there should be a close button next to comment button. Regardless, I will close for now and you can re-open if it doesn't work. If the new guy wants to test now then he can just add the plugin directly from it's github url as that will grab the latest code.

**Closed** 2016-05-02 10:44 UTC
Labels: android, bug
