### ISSUE TITLE
'com.google.android.gms' conflict with cordova-plugin-analytics-adid

### ISSUE THREAD

**Issue by darigon** [phonegap/phonegap-plugin-push#371] opened 2015-11-23 14:55 UTC
I am getting a conflict with com.google.android.gms when using this plugin with cordova-plugin-analytics-adid.

```
Execution failed for task ':processDebugResources'.
> Error: more than one library with package name 'com.google.android.gms'
```

Any assistance here as I need to use Push Notifications as well as use the ADID data.

**Comment by macdonst** [comment] 2015-11-23 15:23
@darigon it looks like the cordova-plugin-analytics-adid is depending on cordova-plugin-analytics which is in turn depending on cordova-google-play-services. The cordova-google-play-services is deprecated because plugins should be using framework tags to specify requirements for things like Google Play Services.

Can you confirm that https://github.com/appfeel/analytics-google-adid is the correct plugin repository as I will send them a PR on how to do it right.

**Comment by macdonst** [comment] 2015-11-23 18:28
Actually, I'm pretty sure this is a duplicate of #283 and I've already sent a PR to that repo to fix the issue.

**Closed by macdonst** 2015-11-23 18:28 UTC
Labels: duplicate

**Comment by degaray** [comment] 2017-06-08 22:26
I am having this issue again. I upgraded to Cordova 7.0.1 and the Android 7.1.1 SDK API 25
