### ISSUE TITLE
Fixed push.on('notification') issue on IOS 11.1

### ISSUE THREAD

**Issue by aliwaqassi** [phonegap/phonegap-plugin-push#1993] opened 2017-10-03 11:34 UTC
Dont need to update push plugin if you are using previous version of plugin.
This is not plugin issue , this is IOS 11.1 version issue, when i update my OS version 11.1 to 11.2 , on('notification') works
Thanks

**Comment by macdonst** [comment] 2017-10-04 16:41
Duplicate of #1977 which I've added a note about in the docs.

**Closed by macdonst** 2017-10-04 16:41 UTC
Labels: duplicate
