### ISSUE TITLE
cordova build error on iOS (Along with google plus plugin)

### ISSUE THREAD

**Issue by jyothisraj** [phonegap/phonegap-plugin-push#646] opened 2016-02-24 10:05 UTC
### Actual Behaviour
Build fails when adding the push plugin (https://github.com/phonegap/phonegap-plugin-push) along with google plus plugin.(https://github.com/EddyVerbruggen/cordova-plugin-googleplus)

Cordova able to generate build if we remove one of the plugin.

#### Steps to Reproduce 
1. $ cordova create hello com.example.hello HelloWorld
2. $ cd hello
3. $ cordova platform add iOS
4. $ cordova plugin add cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=myreversedclientid
5. $ cordova build ios (build success)
6. $ cordova plugin add phonegap-plugin-push
7. $ cordova build ios --(build failed)

Kindly please help as soon as possible.

**Comment by macdonst** [comment] 2016-02-24 10:26
@jyothisraj duplicate of #449

**Closed by macdonst** 2016-02-24 10:26 UTC
Labels: duplicate
