### ISSUE TITLE
AVD Android 7.0 (API 24)- Failed to received notification from GCM

### ISSUE THREAD

**Issue by devshisiyani** [phonegap/phonegap-plugin-push#1242] opened 2016-09-25 22:18 UTC
### Expected -  should have received push  notification from GCM - API 24(Android 7.0) 
Same code work on other android version API 23(Android 6.0) 

### Reproduce Scenario (including but not limited to)
Sent notification  from web site to the device via the GCM. The GCM accepts the request ok.
Wait on the Android 7.0 (AVD) . Nothing received.

#### Steps to Reproduce 
Run up the same code that works on android version API 23(Android 6.0). Repeat on API 24(Android 7.0)

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.3.1
    cordova platform version android                     5.2.2

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   : 1.8.2

#### Sample Push Data Payload
standard payload.

**Comment by macdonst** [comment] 2016-09-26 14:14
@devshisiyani are you running this on an Android 7 device or emulator?

**Comment by hereiam133** [comment] 2016-09-26 15:38
I am also having the same issue, On a Nexus 5x running Android 7 no notifications are ever delivered to the device for any cordova apps using this plugin

**Comment by andreszs** [comment] 2016-09-26 20:09
And what is the complete JSON response from the GCM server?

**Comment by atgillette** [comment] 2016-09-26 21:57
I'm getting reports of the same issue for Android 7.

**Comment by devshisiyani** [comment] 2016-09-26 22:07
I am running  Android 7 on emulator AVD. I don't see any JSON response from GCM in the debug window using "Andriod Studio".  The initial registration request works. I am get the registrationId returned. When I send the notification from my PHP web server,  the request is accepted by the GCM on. So the registrationId  looks good and is recognized by GCM. 

This works fine with Android 6 on the emulator AVD.

**Comment by macdonst** [comment] 2016-09-26 22:46
@devshisiyani depending on how you setup your emulator it may or may not have Google Play Services installed. Without this package from Google GCM will not work. Please make sure the library is installed.

**Comment by hereiam133** [comment] 2016-09-27 11:55
I will have our backend lead pull the response back from GCM as soon as he gets in. But the issue is that its working on everything other than Android 7.

**Comment by hereiam133** [comment] 2016-09-27 12:30
So we have retested push notifications again this morning and without us changing any code or doing any deploys they are now working again on Android 7.
Could it have been some weird GCM issue that only affected Android 7 for a few days?

**Comment by macdonst** [comment] 2016-09-27 14:15
@hereiam133 ¯\_(ツ)_/¯ I wish I knew.

I'm going to close this bug for now as I can't reproduce it on my Android 7 phone and the originator was trying to get things to work on an emulator. If it pops back up again please re-open with some logs.

**Closed by macdonst** 2016-09-27 14:15 UTC
Labels: android, can't reproduce, question

**Comment by atgillette** [comment] 2016-10-05 17:24
Question,
So API 24 is needed to get notification working for Android 7?  Once I download that and rebuild the apk file, my app should receive notifications on Android 7?

**Comment by macdonst** [comment] 2016-10-05 23:08
@atgillette API level 24 is not required for Android N support as earlier versions of the plugin will still work but if you want the latest version of the push plugin I used some Android N apis for the new action buttons. So it's always best to compile your app with the latest Android sdk anyway.

**Comment by atgillette** [comment] 2016-10-06 00:57
@macdonst,
My Android 7 customer is not getting push notifications.   I was using API 23, but I pushed a build out that was compiled with 24.  All previous versions of Android are still getting notifications.
