### ISSUE TITLE
Using the framework syntax to embed libraries via gradle?

### ISSUE THREAD

**Issue by hobbysoldat** [phonegap/phonegap-plugin-push#113] opened 2015-09-07 13:53 UTC
Hello, the new cordova supports the framework syntax, where you can pull in dependencies via Gradle, instead of hard coding them and uploading jars, that might result in dependency conflicts.

Is there a specific reason why this plugin does not use the new syntax, or may I try to provide a pull request?

An Example of the new, though a little bit undocumented syntax:

`    <framework src="com.google.android.gms:play-services-analytics:+" />`

An example where you can see it being used in the plugin.xml
https://github.com/danwilson/google-analytics-plugin/blob/master/plugin.xml

**Comment by macdonst** [comment] 2015-09-07 13:56
Duplicate of Issue #51

**Closed by macdonst** 2015-09-07 13:56 UTC
