### ISSUE TITLE
[Android] on('notification') question

### ISSUE THREAD

**Issue by flexbed** [phonegap/phonegap-plugin-push#901] opened 2016-05-19 12:47 UTC
I don't know if this is the right place for this, but as I find other issue responses useful, I thought that I can get a proper answer here.
The plugin works fine for me, I'm getting the notifications both with the app running on backgroud and when its _"fully closed"_ (i.e. holding down the back button and clearing the app from the list of recent apps), but in the second case the `on('notification')` is not executed when the push is received, only when the notificación is tapped. Is this the expected behaviour?
In the first case, its executed when the push arrives and then again when the notification is tapped, which seems ok for me.

__tl;dr__ Is there a way to make the `on('notification')` run with the app _"fully closed"_?

Thanks in advance.

P.S.: My __data__ payload looks like this:
 ```JSON
{
     "content-available" : "1",
     "title" : "Cool notification",
     "message" : "Nice and easy",
     "type" : "new-message",
     "message_id" : "123",
     "conversation_id" : "456"
  }
```
Last three are custom data for our app.

**Comment by macdonst** [comment] 2016-05-20 09:52
@flexbed currently when you kill the app there is no way to call the `on('notification')` manager of the app because the webview to run the JS is not loaded in memory. This is a duplicate of #158 so I'm going to close this issue, feel free to comment on the other issue. I hope to get some time to figure it out soon.

**Closed by macdonst** 2016-05-20 09:52 UTC

**Comment by flexbed** [comment] 2016-05-20 13:45
@macdonst thank you for the quick reply. 
Sorry about the duplicate, I must have overlooked it when I go through the issues.
