### ISSUE TITLE
registrationID is not received in IOS

### ISSUE THREAD

**Issue by baron92** [phonegap/phonegap-plugin-push#956] opened 2016-06-02 14:18 UTC
Hi!
I'm trying to receive push notifications . Everything works fine on Android , but iOS registration is not successful . The function push.on('registration') does not receive the token IOS.

### Expected Behaviour
       Don't receive registrationID in IOS

### Actual Behaviour
       registrationID received from registration callback in Android
       registrationID don't received from registration callback in IOS.

#### Platform and Version
      Android 5.0
      IOS 6.1.3

#### What device vendor
      Samsung Note 3
      Iphone 3gs

#### Cordova CLI version
    cordova --version   5.1.1

#### Plugin version
    grep phonegap-plugin-push   1.4.3

#### Sample Code that illustrates the problem
       var push = PushNotification.init({
               android: {
        	      senderID: "XXXXXXXX"
    	       },
	        ios: {
		     alert: "true",
		     badge: "true",
		     sound: "true"
              }
     });

    push.on('registration', function(data) {
    	 alert(data.registrationId);
         localStorage.setItem("token", data.registrationId);
    });

    push.on('notification', function(data) {
	 alert(data.title+' msg: '+data.message);
    });

    push.on('error', function(e) {
    	alert("ERROR: " + e.message);
    });

**Comment by macdonst** [comment] 2016-06-02 14:25
@baron92 did you setup your certificates correctly? Can you run in Xcode so we can see the logs?

**Comment by baron92** [comment] 2016-06-02 14:54
@macdonst I configured the development certificates and enabled push notifications. 
I am using Intel XDK in windows. I have developer certificate and provisioning profile with enabled Push Notifications in the identifiers APP.

**Comment by macdonst** [comment] 2016-06-02 15:05
@baron92 I'm going to mark this as a duplicate of #926 where @tony-- from Intel does a great write up on what is required.

**Closed by macdonst** 2016-06-02 15:05 UTC
Labels: duplicate, intelXDK, ios
