### ISSUE TITLE
Unable to get two notifications as data in "push.on('notification', function (data) {"

### ISSUE THREAD

**Issue by pallaviMN** [phonegap/phonegap-plugin-push#552] opened 2016-01-29 07:04 UTC
Hi Team,

When the app is in background, we get status bar notification. In order to show more than one notification in status bar, we are using inbox stacking kind of push from server side. But when i tried to tap that status bar notification i get only one object in "data" of "push.on('notification', function (data) {". Only last one received. But in status bar notification both are seen.

**Comment by nuclearsagar** [comment] 2016-01-29 13:43
Hello Team,

I am struggling for the same issue since last 10 days.
I can see from logcat that variable "extras" has both the notifications stored, but I am not able to access those in js.

When I set "content-available = 1", I can go inside push.on("notification", function(data){}), although app was in background when notification arrived. But here I get only last notification in data.

**Comment by nuclearsagar** [comment] 2016-01-29 13:44
@pallaviMN  can you share what all things have you tried?

**Comment by pallaviMN** [comment] 2016-01-29 15:30
@nuclearsagar , i am not native android developer. So didnt try any changes in the android code. And moreover in Netbeans i am unable to debug the code. So asked for help with the team

**Comment by pallaviMN** [comment] 2016-01-29 15:35
@nuclearsagar Have you changed any code inside GCMIntentService.java files? I am not storing any notification data in the DB. We are using ionic+angularjs.

**Comment by macdonst** [comment] 2016-01-29 16:56
This is a duplicate of #314 please go vote up that issue and add comments.

**Closed by macdonst** 2016-01-29 16:56 UTC
Labels: duplicate
