### ISSUE TITLE
App crashed on receive notification - Andriod

### ISSUE THREAD

**Issue by sangeethkumarsg** [phonegap/phonegap-plugin-push#2144] opened 2018-01-12 13:12 UTC
### Expected Behaviour
If app is in foreground, if it receive notification, it should show the notification

### Actual Behaviour
When I send notification, I am getting success in my server. But on App, the app is getting crashed
#### Steps to Reproduce 
Install plugin
Register for push notification
Send push notification to the app.
Getting alert that App has been crashed

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Nexus 5 and Redmi Mi 4A
#### Cordova CLI version and cordova platform version
cordova version : 7.0.1
cordova platform version android 6.2.3

#### Plugin version

  phonegap-plugin-push 2.0.0 "PushPlugin"

#### Sample Push Data Payload
$msg1 = array(
			"data" => array(
				"title"=> "Test Notification",
				"body" => "This offer expires at 11:30 or whatever",
				"notId" => 12,
				),
			"title" => "Notification",
			"body" => "body of notification"
		);
	$fields = array
			(
				'to'		=> $registrationIds,
				'notification'	=> $msg1
			);

#### Sample Code that illustrates the problem
java.lang.NoSuchMethodError: No static method zzJU()Lcom/google/firebase/iid/zzq; in class Lcom/google/firebase/iid/zzq; or its super classes (declaration of 'com.google.firebase.iid.zzq' appears in /data/app/com.xxxx.xxx-2/base.apk)
    at com.google.firebase.messaging.FirebaseMessagingService.zzn(Unknown Source)
    at com.google.firebase.iid.zzb.onStartCommand(Unknown Source)
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3043)
    at android.app.ActivityThread.access$2300(ActivityThread.java:153)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:5523)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

#### Logs taken while reproducing problem
adb logcat gives

java.lang.NoSuchMethodError: No static method zzJU()Lcom/google/firebase/iid/zzq; in class Lcom/google/firebase/iid/zzq; or its super classes (declaration of 'com.google.firebase.iid.zzq' appears in /data/app/com.xxx.xxx-2/base.apk)
    at com.google.firebase.messaging.FirebaseMessagingService.zzn(Unknown Source)
    at com.google.firebase.iid.zzb.onStartCommand(Unknown Source)
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3043)
    at android.app.ActivityThread.access$2300(ActivityThread.java:153)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:5523)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

Available plugins

cordova-custom-config 2.0.3 "cordova-custom-config"
cordova-plugin-admobpro-firebase 2.29.23 "AdMob Plugin Pro"
cordova-plugin-apprate 1.1.7 "AppRate"
cordova-plugin-camera 2.3.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-extension 1.5.3 "Cordova Plugin Extension"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-file 4.1.1 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-geolocation 2.3.0 "Geolocation"
cordova-plugin-globalization 1.0.7 "Globalization"
cordova-plugin-googlemaps 1.4.5 "cordova-googlemaps-plugin"
cordova-plugin-inappbrowser 2.0.1 "InAppBrowser"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 1.0.1 "StatusBar"
cordova-plugin-whitelist 1.0.0 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-plugin-x-toast 2.3.2 "Toast"
cordova.plugins.diagnostic 3.1.7 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 1.0.9 "Keyboard"
phonegap-plugin-barcodescanner 6.0.8 "BarcodeScanner"
phonegap-plugin-push 2.0.0 "PushPlugin"

**Comment by macdonst** [comment] 2018-01-12 21:23
@sangeethkumarsg please update the version of Play Services running on your device and retest. Let me know how it goes.

**Comment by sangeethkumarsg** [comment] 2018-01-13 08:36
@macdonst ,
I am using the latest version of google play services. Here is the screenshots.

![screenshot_2018-01-13-14-01-56-269_com android settings](https://user-images.githubusercontent.com/15649495/34904378-9d68404a-f86a-11e7-9172-0c52bf07195f.png)
![screenshot_2018-01-13-14-01-50-296_com android vending](https://user-images.githubusercontent.com/15649495/34904379-9e989f32-f86a-11e7-99c7-374e8fc882e3.png)

Note : Also how can I say to the end user to update the Play Services because my app is crashing ? It will hamper the user experience.

**Comment by macdonst** [comment] 2018-01-15 02:33
@sangeethkumarsg what version of FCM are you building with?

**Comment by sangeethkumarsg** [comment] 2018-01-16 05:46
@macdonst ,
These are the entries in my project.properties file.

target=android-25
android.library.reference.1=CordovaLib
cordova.system.library.1=com.android.support:support-v4:+
cordova.system.library.2=com.android.support:appcompat-v7:+
cordova.system.library.3=com.android.support:support-v4:24.1.1+
cordova.system.library.4=com.facebook.android:facebook-android-sdk:4.14.+
cordova.system.library.5=com.google.android.gms:play-services-maps:11.+
cordova.system.library.6=com.google.android.gms:play-services-location:11.+
cordova.system.library.7=com.android.support:support-v4:24.1.1+
cordova.gradle.include.1=phonegap-plugin-barcodescanner/th-barcodescanner.gradle
cordova.system.library.8=com.android.support:support-v13:25.1.0
cordova.system.library.9=me.leolin:ShortcutBadger:1.1.17@aar
cordova.system.library.10=com.google.firebase:firebase-messaging:11.0.1
cordova.gradle.include.2=phonegap-plugin-push/th-push.gradle
cordova.system.library.11=com.google.firebase:firebase-ads:+

**Comment by wambele** [comment] 2018-01-23 05:43
Am also receiving the same issue but for me on foreground the plugin work perfect but when the app is in the background (but not killed even) when notification is received and start vibrating and sounding with no notification in the tray just sound in the background, the i get the error saying "Unfortunately appname has stopped" or "unfortunately system ui has stopped" and it wont start till a restart the phone again 


Android v 5.1 kitkat,
DEVICE tecno j8,
PGB Cordova CLI 7.1.0,
Cordoca android 6.3.0,
Plugin version 2.1.2

Help please it now a 3rd week struggling for it

**Comment by wambele** [comment] 2018-02-07 15:23
I have updates everything google play services to 11.9.75 
Plugin v2.1.3 and cli 7.1.0 with android 6.3.0
At least now system ui does not crash but when app in background app crashes
content-available to 1 is available in payload
Help please my customers are getting troubled of this behaviour what else should i do?

**Comment by wambele** [comment] 2018-02-07 15:24
App crashes immediatelly after receiving push notification on background mode

**Comment by macdonst** [comment] 2018-02-07 15:48
@sangeethkumarsg please update to 2.1.3 and re-test.

@wambele I need to see the stack trace of your crash to help and the payload you send to the device.

**Comment by wambele** [comment] 2018-02-07 16:05
@macdonst am working on it

**Comment by wambele** [comment] 2018-02-07 16:05
Ok @macdonst am working on it

**Comment by wambele** [comment] 2018-02-08 16:53
$registrationIds = array($to);
	$notification = array (
		'title' => $title,
	    'body' => $message,
        "vibrate"=> "1",
        "sound"=> "default",
        "badge"=> "0", 
        "content-available" => "1"
	);
		$data = array (
		'title' => $title,
	    'body' => $message,
        "vibrate"=> "1",
        "sound"=> "default",
        "badge"=> "0", 
        "content-available" => "1"
	);

	$fields = array(
	    'registration_ids' => $registrationIds,
		'data'=> $data,
		'notification'=>$notification
	);

**Comment by wambele** [comment] 2018-02-09 11:21
hello any response on the data? @macdonst

**Comment by JustasKuizinas** [comment] 2018-02-09 18:15
I am running
phonegap-plugin-push": 2.1.3
cordova version : 8
cordova platform version android 6.4.3

![screenshot_2018-02-09-20-13-39-039_com miui bugreport](https://user-images.githubusercontent.com/5862640/36042863-f4bc301a-0dd5-11e8-96a8-4a4f34025824.png)

**Comment by Creawebs** [comment] 2018-02-10 01:54
My app crashes with the same error message on adb logcat as @JustasKuizinas everytime I get a push message.

**Comment by Creawebs** [comment] 2018-02-10 02:36
I can confirm the same problem with latest version
phonegap-plugin-push 2.1.3 "PushPlugin"
ionic push@4.5.3

Tested on Android O device

: 1.19.1
ionic (Ionic CLI) : 3.19.1

global packages:

cordova (Cordova CLI) : 8.0.0

local packages:

@ionic/app-scripts : 3.1.8
Cordova Platforms  : android 7.0.0
Ionic Framework    : ionic-angular 3.9.2

System:

Android SDK Tools : 25.2.5
Node              : v8.9.3
npm               : 5.6.0
OS                : Windows 10

Logcat:
02-09 20:26:12.849 4572 4572 I zygote64: Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.RemoteMessage>: java.lang.IncompatibleClassChangeError: Superclass com.google.android.gms.internal.zzbej of com.google.firebase.messaging.RemoteMessage is declared final (declaration of 'com.google.firebase.messaging.RemoteMessage' appears in /data/app/io.ionic.starter-6sRYi3Y_743H1NUTW__38Q==/base.apk:classes2.dex)

Further down:

02-09 20:26:12.867  4572  4572 D AndroidRuntime: Shutting down VM
02-09 20:26:12.869  4572  4572 E AndroidRuntime: FATAL EXCEPTION: main
02-09 20:26:12.869  4572  4572 E AndroidRuntime: Process: io.ionic.starter, PID: 4572
02-09 20:26:12.869  4572  4572 E AndroidRuntime: java.lang.NoSuchMethodError: No static method zzchl()Lcom/google/firebase/iid/zzaa; in class Lcom/google/firebase/iid/zzaa; or its super classes (declaration of 'com.google.firebase.iid.zzaa' appears in /data/app/io.ionic.starter-6sRYi3Y_743H1NUTW__38Q==/base.apk:classes2.dex)
02-09 20:26:12.869  4572  4572 E AndroidRuntime:        at com.google.firebase.messaging.FirebaseMessagingService.zzp(Unknown Source:0)
02-09 20:26:12.869  4572  4572 E AndroidRuntime:        at com.google.firebase.iid.zzb.onStartCommand(Unknown Source:13)
02-09 20:26:12.869  4572  4572 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3544)
02-09 20:26:12.869  4572  4572 E AndroidRuntime:        at android.app.ActivityThread.-wrap20(Unknown Source:0)
02-09 20:26:12.869  4572  4572 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
02-09 20:26:12.869  4572  4572 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:105)
02-09 20:26:12.869  4572  4572 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:251)
02-09 20:26:12.869  4572  4572 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6563)
02-09 20:26:12.869  4572  4572 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-09 20:26:12.869  4572  4572 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
02-09 20:26:12.869  4572  4572 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Tested on a fresh new app.

@macdonst

**Comment by macdonst** [comment] 2018-02-12 15:39
This is a duplicate of #2129. Please try the suggested work around: https://github.com/phonegap/phonegap-plugin-push/issues/2129#issuecomment-357669732

and comment on #2129 to let me know that it works.

**Closed by macdonst** 2018-02-12 15:39 UTC
Labels: android, duplicate, question
