### ISSUE TITLE
Closed App is not getting Push Data after initialization

### ISSUE THREAD

**Issue by TimWeyand** [phonegap/phonegap-plugin-push#55] opened 2015-08-05 07:12 UTC
Hi,
i just found a usability issue.

If the User is exiting the App and getting a Push afterwards, the PushPlugin is still registering the Push but is not returning the Data to the App.

Aug  5 09:04:04 Tims-iPhone6 OK[7443] <Warning>: Notification received
Aug  5 09:04:04 Tims-iPhone6 OK[7443] <Warning>: Push Plugin key: alert
Aug  5 09:04:04 Tims-iPhone6 OK[7443] <Warning>: Invalid callback id received by sendPluginResult

It would be great, to read PushData received after the initalization of the App.

Thanks for your work on this plugin! :)

Best,
Tim

**Comment by TimWeyand** [comment] 2015-08-05 07:14
Sorry for the Duplication https://github.com/phonegap/phonegap-plugin-push/issues/50

**Comment by berndartmueller** [comment] 2015-09-05 13:07
I have exaclty the same problem, even using version 1.0.1. Does this plugin even work with iOS? How to fix this or which version should I use?

Thanks!

**Comment by macdonst** [comment] 2015-09-06 12:39
Closing as duplicate of #50

**Closed** 2015-10-28 16:36 UTC
