### ISSUE TITLE
Clear Notifications on Android

### ISSUE THREAD

**Issue by Nilos** [phonegap/phonegap-plugin-push#894] opened 2016-05-17 14:59 UTC
Hi everyone,
I would like to clear notifications on android, even if my app is not in the background.
Is there a way to do that?

Use case: Chat.
My user receives a message, as a push, reads it on another device and I would like the push to be removed then.

**Comment by macdonst** [comment] 2016-05-20 09:30
Closing as duplicate of #346.

**Closed by macdonst** 2016-05-20 09:30 UTC
Labels: android, duplicate
