### ISSUE TITLE
Click the push in notification center doesnt bring to foreground the app

### ISSUE THREAD

**Issue by jarnaiz** [phonegap/phonegap-plugin-push#2403] opened 2018-06-05 15:40 UTC
### Expected Behaviour
Open the app when push notification is clicked in notification center and bring to foreground the app

### Actual Behaviour
App doesn't open when is in background mode, but the on 'notification' event is triggered.
The app works well if the app is closed or if it is in foreground.

### Reproduce Scenario (including but not limited to)
Trigger notification with given payloads and the app is in background mode

#### Steps to Reproduce 
Step 1: Open app and set in background mode
Step 2: Trigger notification
Step 3: Click on it in the notification center

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 8.0.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Xiaomi M1A1

#### Cordova CLI version and cordova platform version
```cordova --version```  8.0.0
```cordova platform version android``` 7.1.0

#### Plugin version

```cordova plugin version | grep phonegap-plugin-push```  2.2.3

#### Sample Push Data Payload
send by http FCM
```
     {
           registration_ids: ['adsasdas'],
            priority: 'high',
            content_available: false, // tested with true too
            data: {
                title: 'A short string describing the purpose of the notification',
                message: 'The text of the alert message', // "body" can be used as alias, is converted to "message"
                // localization of message is possible
                count: 5, // set the badge notification count at app icon
                sound: 'default', // play default sound ... or "soundname", see [Android Sound](#sound) section
                //notId: 1, // unique ID for the message, used for grouping, see below
                'content-available': '1', // tested with 0 too
                custom_key1: 'value1',
                click_action: "https://www.google.es",
                custom_key2: 'value2',
            }
        }
```

#### Logs taken while reproducing problem
```
06-05 17:06:53.911  2410  4273 E ActivityTrigger: activityResumeTrigger: not whiteListedes.upplication.android637/es.upplication.android637.MainActivity/75
06-05 17:07:15.377  2410 12434 I ActivityManager: START u0 {flg=0x24000000 cmp=es.upplication.android637/com.adobe.phonegap.push.PushHandlerActivity (has extras)} from uid 10130
06-05 17:07:15.377  2410 12434 W ActivityManager: startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { flg=0x24000000 cmp=es.upplication.android637/com.adobe.phonegap.push.PushHandlerActivity (has extras) }
06-05 17:07:15.381   549   549 E ANDR-IOP: IOP HAL: Received pkg_name = es.upplication.android637 pid = -1
06-05 17:07:15.387  2410 12434 D ActivityTrigger: activityStartTrigger: Activity is Triggerred in full screen ApplicationInfo{eabdd0c es.upplication.android637}
06-05 17:07:15.387  2410 12434 E ActivityTrigger: activityStartTrigger: not whiteListedes.upplication.android637/com.adobe.phonegap.push.PushHandlerActivity/75
06-05 17:07:15.388  2410 12434 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{eabdd0c es.upplication.android637} is now in focus and seems to be in full-screen mode
06-05 17:07:15.388  2410 12434 E ActivityTrigger: activityResumeTrigger: not whiteListedes.upplication.android637/com.adobe.phonegap.push.PushHandlerActivity/75
06-05 17:07:15.393  2410 12434 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{eabdd0c es.upplication.android637} is now in focus and seems to be in full-screen mode
06-05 17:07:15.393  2410 12434 E ActivityTrigger: activityResumeTrigger: not whiteListedes.upplication.android637/com.adobe.phonegap.push.PushHandlerActivity/75
```

**Comment by macdonst** [comment] 2018-06-05 16:08
@jarnaiz in your AndroidManifest.xml file what is the value of `android:launchMode`?

**Comment by jarnaiz** [comment] 2018-06-06 09:07
Hello @macdonst 
I set the value to: `singleInstance` to solve this issue: https://github.com/nordnet/cordova-universal-links-plugin/issues/37

But maybe I can change to `singleTask`

**Comment by macdonst** [comment] 2018-06-06 13:02
@jarnaiz yeah, the root cause of your problem is that your launch mode is not set to `standard` or `singleTop`. Both `singleTask` and `singleInstance` are special cases and not recommended for most applications.

You can read up more about it at:

https://developer.android.com/guide/topics/manifest/activity-element#lmode
https://developer.android.com/guide/components/activities/tasks-and-back-stack

I'm going to close this issue as it is not a problem with the plugin but with the way the universal links one sets up your app.

**Closed by macdonst** 2018-06-06 13:02 UTC
Labels: android, question

**Comment by jarnaiz** [comment] 2018-06-07 12:16
Thanks for the feedback and the docs.
I tested the APK and it works without any troubles
