### ISSUE TITLE
CODE_SIGN_ENTITLEMENTS missing Xcode 8

### ISSUE THREAD

**Issue by kaynz** [phonegap/phonegap-plugin-push#1256] opened 2016-09-30 10:59 UTC
Hi,

with the newest OSX and iOS I need to manually enable APNS in Xcode. I think there were some breaking changes and this plugin needs to be adjusted.

I'm using latest cordova, platform and phonegap-plugin-push versions.

Xcode looks like this after platform add:

![xcode](https://cloud.githubusercontent.com/assets/12952835/18989625/430a9686-870d-11e6-9b17-8da03f860e7c.png)

And if I switch it to ON, Xcode adds some lines to this file:

project.pbxproj:

```
SystemCapabilities = {
							com.apple.Push = {
								enabled = 1;
							};
						};

[...]

CODE_SIGN_ENTITLEMENTS = myApp/myApp.entitlements;
```

After switching to ON the plugin works as expected.

**Comment by jcesarmobile** [comment] 2016-09-30 11:10
Duplicate of https://github.com/phonegap/phonegap-plugin-push/issues/1154

**Closed by jcesarmobile** 2016-09-30 11:10 UTC
