### ISSUE TITLE
Incompatibility with cordova-plugin-googlemaps

### ISSUE THREAD

**Issue by noam1610** [phonegap/phonegap-plugin-push#1330] opened 2016-10-31 13:34 UTC
### Actual Behaviour
Hello,
When both  cordova-plugin-googlemaps and phonegap-plugin-push are used in the app's, the app crash just after the slash screen appear.

#### Platform and Version
"android": "5.2.2"

#### Device used
Asus Zenfone 2 and Sony experia M2

#### Cordova CLI version and cordova platform version

    cordova --version  6.3.0
    cordova platform version android "android": "5.2.2"

#### Plugin version

    phonegap-plugin-push  1.8.3
    cordova-plugin-googlemaps 1.3.9

The code I run :
```javascript
 var options = {
            android: {
                'senderID': '330401114899',
                // 'icon': 'images/app/logo.png',
                // 'iconColor': 'rgb(235, 102, 41)',
                'vibrate': true,
                'sound': true,
                'forceShow': true
            }
        };

        var push = PushNotification.init(options);

        push.on('registration', function(data) {
            console.log('----  ---- registration ---- ---- ', data);
            console.log('$window', $window);
        });

        push.on('notification', function(data) {
            console.log(data.message);
            console.log(data.title);
            console.log(data.count);
            console.log(data.sound);
            console.log(data.image);
            console.log(data.additionalData);
        });
```

What's more, If I remove the cordova-plugin-googlemaps plugin, The app runs fine.
Thank you,

**Comment by macdonst** [comment] 2016-10-31 13:56
@noam1610 same root cause as #1325. The resolution will be in the upcoming 1.9.0 release which will use Cocoapods to include the GCM libraries. Then the two plugins will be able to include the same libs without this error.

**Comment by noam1610** [comment] 2016-10-31 14:14
Thank you !

**Comment by hungca** [comment] 2016-11-01 08:09
I have got this issue too after I upgrade push plugin to version 1.8.3/1.8.4.
It doesn't happen with push plugin version 1.8.2

**Comment by macdonst** [comment] 2016-11-01 19:36
@noam1610 can you make sure you have [CocoaPods installed](https://guides.cocoapods.org/using/getting-started.html) then try the latest code from master to see if your bug is resolved. If it isn't I may need to actually send a PR to cordova-plugin-googlemaps.

**Comment by noam1610** [comment] 2016-11-02 12:33
I don't use cocoapods.
I will try ..

**Comment by noam1610** [comment] 2016-11-02 13:02
Thank you,
It seems to work...

**Closed** 2016-11-02 19:59 UTC
Labels: ios
