### ISSUE TITLE
[ANDROID] on('notification') isn't trigged when app is in background or closed - ionic 2

### ISSUE THREAD

**Issue by lionalex** [phonegap/phonegap-plugin-push#1506] opened 2017-01-05 20:08 UTC
### Expected Behaviour
When I send a push notification and the APP is already opened, show an alert modal with the text of notification. The notification fire "on('notification')" and "**data.additionalData.foreground**" is **true**, "**data.additionalData.coldstart**" is **false**

When I send a push notification and the APP is in background or closed, show the message in android notify. If I tap this notification, open the APP and show the same alert modal with the text of the push notification that fire "on('notification')" and "**data.additionalData.foreground**" is **false**, "**data.additionalData.coldstart**" is **true**

### Actual Behaviour
When I send a push notification and the APP is active, that's all right.
When I send a push notification and the APP is in background, I receive the notification, but it open only the APP without fire "on('notification')" or any other function.
When I send a push notification and the APP is in closed, I don't receive any message.

#### Steps to Reproduce 
Build android: `ionic build android`
Copy APK in my device to debug
Start app on my device
Send notification with my PHP script
Open notification on my device
Go to device HOME (app in background)
Send notification with my PHP script
Close my App on device
Send notification with my PHP script

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
 Android 6.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Asus Zenfone 2

#### Cordova CLI version and cordova platform version

  `cordova --version` 6.4.0
  `cordova platform version android` 6.0.0

#### Plugin version

    `cordova plugin version | grep phonegap-plugin-push`  1.9.2

#### Sample Push Data Payload
**in PHP**
```
$url = 'https://fcm.googleapis.com/fcm/send';

$fields = array (
		"to" => "/topics/appAndroid",
		"priority" => "high",
		"time_to_live"	=> 120, 
		"content_available"=> true,
		"content-available" => 1,
		'data' => array (
				"message" => "messaggio",
		),
		"notification" => array(
				"title" => "Titolo notifica",
				"text" => "Testo notifica",
				"sound" => "default",
				"icon" => "myicon",
		),
);
$fields = json_encode ( $fields );

$headers = array (
		'Authorization: key=' . "AAAAesRC....C2Q", //firebase server key
		'Content-Type: application/json'
);

$ch = curl_init ();
curl_setopt ( $ch, CURLOPT_URL, $url );
curl_setopt ( $ch, CURLOPT_POST, true );
curl_setopt ( $ch, CURLOPT_HTTPHEADER, $headers );
curl_setopt ( $ch, CURLOPT_RETURNTRANSFER, true );
curl_setopt ( $ch, CURLOPT_POSTFIELDS, $fields );

$result = curl_exec ( $ch );
var_dump($result);
curl_close ( $ch );
```

#### Sample Code that illustrates the problem
**in app.component.ts**
```
this.platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      let push = Push.init({
        android: {
          senderID: "123456",
          topics: ["appAndroid"],
          clearNotifications: "true"
        },
        ios: {
          senderID: "123456",
          alert: "true",
          badge: false,
          sound: "true",
          topics: ["appIos"]
        },
        windows: {}
      });

      push.on('registration', (data) => {
        //TODO - send device token to server
      });

      push.on('notification', (data) => {

        alert(JSON.stringify(data));

        if (data.additionalData.foreground) {

          let confirmAlert = this.alertCtrl.create({
            title: 'Nuova notifica',
            message: data.message,
            buttons: [{
              text: 'Ignora',
              role: 'cancel'
            }, {
              text: 'Visualizza',
              handler: () => {
                alert("redirect app aperta");
              }
            }]
          });
          confirmAlert.present();
        } else {
         if (data.additionalData.coldstart)
         {
          alert("Push notification clicked app closed");
         }
         else
         {
          alert("Push notification clicked app background");
          }
        }
      });
      push.on('error', (e) => {
        console.log(e.message);
      });
    });
```

#### Logs taken while reproducing problem
N/A because I don't know how to see console logs generated from app builds on device

**Comment by lionalex** [comment] 2017-01-06 10:12
I've fixed the notification when app is in background with sended this push:

```
$fields = array (
		"to" => "/topics/appAndroid",
		"time_to_live"	=> 10, //secondi
		'data' => array (
				"title"	=> "title data",
				"message" => "messaggio bello",
				"priority" => "high",
				"force-start" => 1,
				"sound" => "default",
				"icon" => "icon",
		),
		/*
		"notification" => array(
				"title" => "Titolo notifica",
				"text" => "Testo notifica",
				"sound" => "default",
				"icon" => "myicon",
		),

);
```

But I don't resolve when the app is CLOSED!!! Who can help me?

**Comment by peterterbe** [comment] 2017-01-06 10:36
I have the same problem. The app gets only activated when clicking on the notification but the notification callback of push doesn't called. I have logcat running and that shows the same:
- When the app is in foreground, many logs came in from PushPlugin according to the message sent to the device.
- When it is in the background, nothing shows up in logcat. None from PushPlugin, none from the registered notification callback which should immediately write into the console. Nothing connected even if I don't filter logcat.

**Comment by lionalex** [comment] 2017-01-06 11:01
With ADB LOGCAT, when the app is closed, I think this is the error:

`W GCM-DMM : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.ionicframework.app383196 (has extras) }`

How can I resolve?

**Comment by peterterbe** [comment] 2017-01-06 13:51
Okay, for me it was caused by Firebase Test Console but I don't know how. If I send messages by node-gcm everything is working. I have dumped the incoming messages to logcat to see the difference between the two message and the only difference is that the collapse_key property contains the apk name when sending from Firebase and contains the "do_not_collapse" string when sending from node-gcm. What does this mean?

**Comment by macdonst** [comment] 2017-01-06 15:21
@lionalex I can't reproduce this one. If I send a message to my app when the app is closed (i.e not running) the app starts and the `on('notification')` handler is called correctly. It would really help if you reproduced the issue while running `adb logcat` to see if the PushPlugin gets the event and fires the JS code. It may be firing the event before the handler is setup in your app but that is just a guess based on my gut.

@peterterbe the problem with the Firebase Test Console is that it doesn't put anything in the `data` section of the push payload. Without that it will not invoke the `onMessageReceived` method in the push plugin. I really hate the way Google has that architected but I can't change it. That's why I've tried to document liberally to use the `data` section of the push payload.

**Comment by peterterbe** [comment] 2017-01-06 15:45
@macdonst I don't really understand the difference between GCM and Firebase but the backend developer will use the Firebase API to send messages to my app. This means that it won't work either? Shall I tell him to use GCM instead? Or is it just the Firebase Test Console and there won't be problem with real messages sent through the API?

**Comment by macdonst** [comment] 2017-01-06 16:03
@peterterbe if you are using 1.x version of the plugin use GCM. If you are using 2.x version use FCM. Regardless of GCM/FCM the contents of the payload matter. This link from Google makes the point better:

https://firebase.google.com/docs/cloud-messaging/android/receive#handling_messages

So when the app is in the foreground no matter what is in the payload the `onMessageReceived` method gets called and the plugin can fire the JS event.

When the app is in the background and you send a push this is where the payload really matters. If your payload is:

```
{
  "notification": {
    "title": "my title",
    "body": "my body"
  }
}
```

the plugin will never have the `onMessageReceived` method called so there will be no JS event. But if your payload is:

```
{
  "data": {
    "title": "my title",
    "body": "my body"
  }
}
```

then everything works like it should. 

What I was trying to say in my earlier message is when you send a test message from Firebase console it doesn't put anything in `data` so it seems like the plugin doesn't work correctly.

**Comment by lionalex** [comment] 2017-01-07 00:02
@macdonst thanks for your reply. 
Can you post your JSON example that send using POST variables at this url "https://fcm.googleapis.com/fcm/send" for open your app closed ?

I try with only "data", then only "notification" and with both, but the log cat give me always this error:

```
W/BroadcastQueue: Reject to launch app .../10174 for broadcast: App Op 63
W GCM-DMM : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.ionicframework.app383196 (has extras) }
```

**Comment by peterterbe** [comment] 2017-01-07 10:29
@macdonst Thank you for your answers!
@lionalex Sorry for disturbing your thread.

**Comment by lionalex** [comment] 2017-01-07 16:23
@peterterbe no problem ;)

**Comment by lionalex** [comment] 2017-01-07 16:33
I think my problem is related with the device.
I try the same APK with other 2 device (wiko highway pure and stonex dante) and I've not any error. I receive the push notification also when the app is closed.
So, why in my Asus Zenfone 2 I've this problem?

**Comment by macdonst** [comment] 2017-01-08 21:13
@lionalex no idea. What version of Play Services do you have installed on the Asus Zenphone 2?

**Comment by lionalex** [comment] 2017-01-09 09:30
Google Play Services v. 10.0.84

Is possible I must insert some authorization in the android manifest ?

**Comment by onlydave** [comment] 2017-01-24 14:49
Experiencing the same issues but on **ionic 1**

Works fine with the app is in the foreground but background or closed nothing comes up from `adb logcat | grep PushPlugin` except the registration stuff when you tap the notification from closed

If the app receive the notification while the app is in the foreground.
Then kill the app.
Then tap the notification.
The app will open and `on('notification')` will run.

So works if the app is in the foreground when you **receive** it. Doesn't matter what state the app is in when you **tap** it.

Device: Nexus 5x
Android Version: 7.1.1

**Comment by peterterbe** [comment] 2017-01-24 14:56
@onlydave Where do you send your notifications from? As @macdonst [stated before](https://github.com/phonegap/phonegap-plugin-push/issues/1506#issuecomment-270935780) the structure of the notification what matters and GCM and FCM structures are different. Do you send notifications from Firebase Test Console?

**Comment by onlydave** [comment] 2017-01-24 16:47
@peterterbe I'm sending them from GCM. First I was using pubnub then changed to sending them directly to the device using node-gcm. Using version 1.9.2 of phonegap-plugin-push and tried downgrading to 1.9.0 at one point too

**Comment by onlydave** [comment] 2017-01-25 11:15
Fix for me was to remove the notification block from my payload... Even though we're using GCM it doesn't work if we use both data and notification. Is this because of updates to GCM and Firebase or android sdk? We've been using that dataset for a year... Thanks Google.

**Comment by deklarnuvek** [comment] 2017-02-02 22:03
Exactly what happens. onlydave is correct. I thought this could be another plugin causing the issue but it is not. Background app is not called foreword on a data push.

**Comment by Avishaidev** [comment] 2017-02-13 11:11
Any solution???
Same problem

**Comment by deklarnuvek** [comment] 2017-02-13 13:18
Yeah, just switch over to Cordova-FCM. It doesn't have as many features, and is broken in other ways - but it does work.

**Comment by harishintimetec** [comment] 2017-02-19 03:27
I have the same issue with FCM. I am not getting notification when app is closed in device. I mean when app is removed from memory in Android device, no notification arrived. 

Can I switch to old plugin(1.6.x) with GCM? That was working with all the scenarios.

**Comment by onlydave** [comment] 2017-02-20 16:43
What we're doing is using https://github.com/napolitano/cordova-plugin-intent to pick up the background intents. Been a few weeks now so this isn't very fresh in my mind but I think that's all we do

**Comment by chcaru** [comment] 2017-02-26 05:37
Same issue here. 

Using plugin version 1.9.4 and FCM.

Using this payload:
```
{
    "priority": "high",
    "notification": {
        "title": "test title",
	"body": "test body",
	"message": "test message",
	"sound": "default"
    },
    "data": {
	"title": "test title",
	"body": "test body",
	"message": "test message",
	"info": "test info",
	"content-available": "1",
	"content_available": "1",
	"sound": "default"
    }
}
```

1. When the application is open, the on('notification') is received. 
2. If the app is either in the background of closed, then on('notification') is not called when the app is restored.

**Comment by harishintimetec** [comment] 2017-02-26 09:40
I got the solution with latest plugin. 

In Android case, Payload should be:

{"data":{"title":"Push Notification","body":"All the content are in Data Object!","color":"#014D81","sound":"default","notId":"324234","content-available": "1"},"priority":"high","registration_ids":[""]}

Whatever params you want to add, you can add in **data** object. We need to sent **notId** always different otherwise notification will club in notification bar. Only latest will be appear there. 

I have tested with my app. It's working fine.

**Comment by fredgalvao** [comment] 2017-02-27 01:51
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

**Comment by NasserAlmanji** [comment] 2017-03-14 13:36
@macdonst 

When the app is in the background and you send a push this is where the payload really matters. If your payload is:

```
{
  "notification": {
    "title": "my title",
    "body": "my body"
  }
}
```
the plugin will never have the onMessageReceived method called so there will be no JS event. But if your payload is:
```
{
  "data": {
    "title": "my title",
    "body": "my body"
  }
}
```

**This made a difference**

**Comment by macdonst** [comment] 2017-03-14 13:51
Folks, read the payload docs: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

Use `data` payloads not `notification` payloads.

**Closed by macdonst** 2017-03-14 13:51 UTC
Labels: android, can't reproduce, question

**Comment by vishal-bluesys** [comment] 2017-07-12 09:11
@harishintimetec
I downgraded the plugin version to 1.6.4 but still facing the same problem

**Comment by josechristym** [comment] 2017-08-31 13:46
Do anyone have solution for this issue? I have integrated push and on clicking the push when app is in background or not active state. Please help me with solution.

**Comment by eibz91** [comment] 2017-09-07 00:08
Hi i have the same problem my notificationReceived is not fire when return from background, this is my json

{
    "message_id": null,
    "registration_ids": ["d_nptiWAiDU:APA91bEk8ZWacI4yGv5948ZMRcipvIM-Nb1aDTx3_JYo29DOrZxwvwyp9jlBLpI9k3crXup57OgdiZgTXn81v-pHr5DFzM_j05kBYA-y_5gLM9pr5VEIhrkoB4vXL-ZTE1tk1m5WD-1x"],
    "to": null,
    "collapse_key": "",
    "data": {
        "msg": "hola from postman",
        "title": "Yobin",
        "body": "hola from postman",
        "sound": "default",
        "visibility": 1,
        "surveyID": "ewtawgreg - gragrag - rgarhthgbad",
        "notId": 10
    },
    "notification": {
        "title": "Yobin",
        "body": "hola from postman",
        "soundname": "default",
        "sound": "default"
    },
    "delay_while_idle": null,
    "time_to_live": null,
    "dry_run": null,
    "NotificationKey": null,
    "restricted_package_name": null,
    "content_available": null,
    "priority": null
}

is there something that i am missing in this json


thank for your time !

**Comment by Bistaff** [comment] 2018-04-06 18:55
Hi all, any news?

**Comment by fredgalvao** [comment] 2018-04-06 19:33
@Bistaff News on what? The issue has been closed for over a year now.
