### ISSUE TITLE
iOS: Not processing data when app is killed

### ISSUE THREAD

**Issue by dylanvdmerwe** [phonegap/phonegap-plugin-push#826] opened 2016-04-22 06:06 UTC
### Actual Behaviour
On iOS, what is happening is that when an app is killed and a push notification with `content-available: 1` is received the following can occur:

1. The user opens the app by pressing the notification. 
2. The user opens the app by pressing the app icon. 

In both these instances, the on('notification') event does not fire immediately as soon as the push is received. 
In scenario 1, the event fires when the app is opened. However this is problematic as if more than one notification is received, only one will ever be processed.
In scenario 2, no data is ever processed by the app.

### Expected Behaviour
For an app that has been completely killed and is not in memory. When a push notification with `content-available: 1` is received:

First prize would be for the on('notification') event to immediately fire in the background. But if this is not possible:

1. The user opens the app by pressing the notification. All the notifications received should have been queued and are now processed in JavaScript now that the app is open and running.
2. The user opens the app by pressing the app icon. All notifications received should have been queued and are now processed in JavaScript now that the app is open and running. 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 9.3.1

#### What device vendor (e.g. Samsung, HTC, Sony...)
iPhone 6s

#### Cordova CLI version and cordova platform version
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
OS: Mac OS El Capitan
Node Version: v5.10.1
ios 4.1.1

#### Plugin version

1.6.2

#### Sample Code that illustrates the problem
See my [repo](https://github.com/dylanvdmerwe/pushtest) that I have put together for testing the various scenarios.

**Comment by macdonst** [comment] 2016-04-22 14:51
@dylanvdmerwe this is a great write up of the problem but I'm going to mark it as a duplicate of #158.

**Closed** 2016-04-22 14:52 UTC
Labels: duplicate
