### ISSUE TITLE
Push Notifications work on iPhone but not iPad

### ISSUE THREAD

**Issue by jvjvjv** [phonegap/phonegap-plugin-push#222] opened 2015-10-13 15:11 UTC
Here's something I don't get, and hopefully you can help out. I'm working with someone else on a project and he is using [PushSharp](https://github.com/Redth/PushSharp) to send the notifications. I am using this plugin on the devices side.

We've tested extensively to make sure we have everything working. I have a couple of Android devices the thing works fine on. Perfectly dandy! And notifications also work perfectly on my iPhone 5 (iOS 7.1) and iPhone 6 (iOS 9.0.2).

But my iPad Air would never get the notifications. I tested on 9.0.1 and 9.0.2, but still nothing. I'm not sure that code snippets would help, as neither the notification appears in my notification tray, nor does `NSLog(@"didReceiveNotification");` ever happen when the app is open.

I'm at a bit of a loss, if you can help me out.

**Comment by bottasergio** [comment] 2015-10-13 22:51
Similar to https://github.com/phonegap/phonegap-plugin-push/issues/216

**Comment by macdonst** [comment] 2015-10-14 00:07
@jvjvjv marking as duplicate of #216. Apparently I need to go buy and iPad Air or something.

**Closed by macdonst** 2015-10-14 00:07 UTC
Labels: duplicate
