### ISSUE TITLE
No iOS Action Buttons with GCM Service and Phonegap build

### ISSUE THREAD

**Issue by ahlidap** [phonegap/phonegap-plugin-push#536] opened 2016-01-22 16:44 UTC
Hi,

I'm having problems in getting action Buttons to work with my push on iOS.
I'm not able to get my action buttons on notification. I don't know how to give you a good debug, as I'm building on Phonegap Build, and action buttons in push are intended to be displayed while not on the app, so Safari Debugging doesn't work.

My init is:
```
pushNotification = PushNotification.init({
    ios: {
        senderID: GOOGLE_PROJECT_ID,
        alert: true,
        sound: true,
        gcmSandbox: true,
        "categories": {
            "invite": {
                "yes": {
                    "callback": "pushOpenPlace", "title": "Open Place", "foreground": true, "destructive": false
                }
            }
        }
    }
});
```

and my json:
```
{
    "to": "device:REGID",
    "content_available" : true,
    "notification": {
         "body": "olee",
         "title": "This is a GCM  Message!",
         "category": "invite"
     }
}
```

Push is successfully received and shows title and message.
Am I doing anything wrong?

iPhone 5S
Version: 8.4(12H143)

**Comment by macdonst** [comment] 2016-01-24 01:19
@ahlidap Did you slide your finger from the right edge of the push to the left to expose the buttons?

**Comment by ahlidap** [comment] 2016-01-25 13:40
@macdonst Hi,
yes I did it.

I've attached two screenshots, one of the notification area (after swiping down from top of screen) and one at the lock screen, both after push to the left.

If there is any other way to provide you good logs, as I'm using PGB, please tell me and I'll do it asap.



![image 1](https://cloud.githubusercontent.com/assets/5701091/12552262/92e55588-c368-11e5-9854-6276569a2def.png)
![image](https://cloud.githubusercontent.com/assets/5701091/12552263/92e65da2-c368-11e5-9dcd-dddf7bab7558.png)

**Comment by ahlidap** [comment] 2016-01-25 14:52
@macdonst ,

I see a "strange behaviour" on how aditionalData is handled on my iOS app.

This example of payload (making some tests with additional data to display when app is opened):

```
{
    "to": "gcm:idhere",
    "content_available" : true,
    "notification": {
      "placeId": 37,
      "image": "http://gintonico.com/content/uploads/2015/03/fontenova.jpg",
      "title": "Fonte Nova Esplanada",
      "style": "picture",
      "picture": "http://media5.letsbonus.com/products/285000/285006/14014409744462-0-1700x690.jpg",
      "body": "olee",
      "title": "This is a GCM  Message!",
      "category": "invite"
     }
}
```

produces this Json Object is JS:

```
{
	"title": "This is a GCM  Message!",
	"additionalData": {
		"foreground": true,
		"gcm.notification.style": "picture",
		"gcm.message_id": "0:1453732341584882%390facf6390facf6",
		"gcm.notification.placeId": "37",
		"gcm.notification.category": "invite",
		"gcm.notification.image": "http://gintonico.com/content/uploads/2015/03/fontenova.jpg",
		"gcm.notification.picture": "http://media5.letsbonus.com/products/285000/285006/14014409744462-0-1700x690.jpg",
		"content-available": "1"
	},
	"message": "olee"
}
```

Could this be the problem?
```
gcm.notification.category
```

If the plugin expects for a ```additionalData.category``` it may fail, I think.

**Comment by macdonst** [comment] 2016-01-28 18:22
@ahlidap yup, that seems to be the root cause of this issue. I need to spend some time to see if we can support action buttons when using GCM on iOS.

**Comment by macdonst** [comment] 2016-02-04 14:59
@ahlidap yeah, I confirmed that action buttons are not supported in GCM on iOS. If you want action buttons on iOS you'll need to send via APNS.

**Comment by ahlidap** [comment] 2016-02-29 18:23
@macdonst 

sorry for replying again to this topic but is there anything that you could implement to support this, or is this really impossible due to some Google GCM Restrictions, letting as the only option to user native APNS service?

Sorry, but I don't know if I should take you last post as definitive and impossible to implement or not.


Regards,

**Comment by macdonst** [comment] 2016-02-29 18:49
@ahlidap not supported right now but possible in a future release.

**Comment by macdonst** [comment] 2016-02-29 18:50
Didn't realize I accidentally close it weeks ago.

**Comment by ahlidap** [comment] 2016-03-01 09:29
> Didn't realize I accidentally close it weeks ago.

As you closed the issue and removed it from 1.6.0 milestone I thought it was impossible due to GCM Service.
Just for the record, any hint on when could this be available for PGB?

Anyway, with the release of 1.6.0 with the boolean coldstart working on iOS will be useful for sure :)

**Comment by macdonst** [comment] 2016-03-01 16:09
@ahlidap I had to cut some features from 1.6 so I can get this out.

**Comment by raymondjacobson** [comment] 2016-04-07 04:54
See this!
http://stackoverflow.com/questions/34173367/ios-notification-only-showing-cross-button-not-showing-category-using-gcm

**Comment by ahlidap** [comment] 2016-04-07 09:36
Awesome!
This really works! 

Well, did'n put the callback to work cause I don't have time right now, but buttons are there!!


Many thanks!

**Closed** 2016-04-11 16:59 UTC
Labels: docs, feature, ios
