### ISSUE TITLE
Android build fails when using com.cmackay.plugins.googleanalytics@1.0.2

### ISSUE THREAD

**Issue by jvjvjv** [phonegap/phonegap-plugin-push#1879] opened 2017-07-30 20:05 UTC
This issue should be deleted, as my issue is with com.mackay.plugins.googleanalytics plugin. Current build errors out with the message below. Warning to users until this is updated, you may run into the same headache I had.

```
Error: /Development/Projects/PluginCompatTest/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.0.1.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

I'll close the ticket once I see the offending plugin updated, if this post is still up.

**Comment by jvjvjv** [comment] 2017-07-30 20:22
**NB:** this issue occurs when you are using the new 2.0.0 branches. I see it on @2.0.0-rc5.

**Comment by jvjvjv** [comment] 2017-07-30 20:29
**NB:** and dan wilson's google analytics plugin, too. 😞

**Comment by jvjvjv** [comment] 2017-07-30 22:45
Oh dear. It's like I'm having a conversation with myself in this issue, instead of just letting others talk. I'm wondering, is it every other plugin that this doesn't seem to work with that's a problem? Or is it this plugin that doesn't play nice with the others, that's the problem? I think this is a question to pose both to the community as well as this plugin's authors. Who should fix the problem?

**Comment by macdonst** [comment] 2017-08-01 03:30
@jvjvjv this is a duplicate of #1718. The problem is the application of the:

`apply plugin: com.google.gms.googleservices.GoogleServicesPlugin`

which forces everyone to use the same version of google libraries.

**Closed by macdonst** 2017-08-01 03:30 UTC
