### ISSUE TITLE
[Android][Build] Error during building app in cordova cli

### ISSUE THREAD

**Issue by Xwalk-Company** [phonegap/phonegap-plugin-push#855] opened 2016-05-02 17:14 UTC
Hi guys, i have a problem during building an android app in cli
Here the details.

#### Cordova CLI version and cordova platform version and plugin version

![plugin](https://cloud.githubusercontent.com/assets/9979292/14961310/3cf53840-1099-11e6-9dae-053ca581482f.png)

#### ERROR

![error](https://cloud.githubusercontent.com/assets/9979292/14961318/40f5ca18-1099-11e6-8d67-f051170f689f.png)

**Comment by macdonst** [comment] 2016-05-02 17:38
@Xwalk-Company this is a duplicate of #51, you need to update your Android libs as detailed in: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#compilation

**Closed by macdonst** 2016-05-02 17:38 UTC
