### ISSUE TITLE
Got this Crash via Crashlytics

### ISSUE THREAD

**Issue by hobbysoldat** [phonegap/phonegap-plugin-push#214] opened 2015-10-09 12:12 UTC
http://crashes.to/s/147b326f823

Any Idea what I could do against it? I mean more than wrapping it in a try/catch block ... error is in pushContext.sendPluginResult(pluginResult);

    public static void sendEvent(JSONObject _json) {
        PluginResult pluginResult = new PluginResult(PluginResult.Status.OK, _json);
        pluginResult.setKeepCallback(true);

        pushContext.sendPluginResult(pluginResult);

    }

java.lang.NullPointerException
       at com.adobe.phonegap.push.PushPlugin.sendEvent(PushPlugin.java:121)
       at com.adobe.phonegap.push.GCMIntentService.onRegistered(GCMIntentService.java:68)
       at com.google.android.gcm.GCMBaseIntentService.handleRegistration(GCMBaseIntentService.java:296)
       at com.google.android.gcm.GCMBaseIntentService.onHandleIntent(GCMBaseIntentService.java:197)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by macdonst** [comment] 2015-10-10 23:15
@hobbysoldat what version of the plugin are you using? The line numbers don't match up with the current master.

**Comment by macdonst** [comment] 2015-10-12 16:54
@hobbysoldat this is actually a duplicate of #144 so I'm going to close it. Please comment on that issue. Also, I checked in code for version 1.3.0 that should guard against this problem.

**Closed by macdonst** 2015-10-12 16:54 UTC
Labels: duplicate

**Comment by hobbysoldat** [comment] 2015-10-12 23:58
Had some customizations ... but basic code in question was the same. Might make a pull request for these customizations ... e.G. another logo for older android versions.

**Comment by macdonst** [comment] 2015-10-13 00:35
@hobbysoldat yeah, please send the PR.
