### ISSUE TITLE
Remove registrationId and senderId from sharedPrefs on unregister

### ISSUE THREAD

**Issue by kentmw** [phonegap/phonegap-plugin-push#294] opened 2015-11-02 22:40 UTC
I'm suggesting we add the following to PushPlugin.java at line 127.
```
SharedPreferences sharedPref = getApplicationContext().getSharedPreferences(COM_ADOBE_PHONEGAP_PUSH, Context.MODE_PRIVATE);
SharedPreferences.Editor editor = sharedPref.edit();
editor.remove(REGISTRATION_ID);
editor.remove(SENDER_ID);
editor.commit();
```
Without this, if you unregister and then initialize, it will return an old registrationId not associated with any instanceId. You'll be in a weird state that the application will think it's registered but it's not. That's due to this logical block on register:
```
if ("".equals(savedSenderID) && "".equals(savedRegID)) {
  token = InstanceID.getInstance(getApplicationContext()).getToken(senderID, GCM);
}
 // new sender ID, re-register
else if (!savedSenderID.equals(senderID)) {
  token = InstanceID.getInstance(getApplicationContext()).getToken(senderID, GCM);
}
// use the saved one
else {
  token = sharedPref.getString(REGISTRATION_ID, "");
}
```
I'm adding this to my fork because some strange reason, I'm getting an emtpy string "" for a registrationId upon initialization of the plugin (See #295). Regardless, my work around is to unregister if I didn't receive an actual registrationId and then re-register. However, without the code above, it will just fallback to old, outdated registrationId - in my case an empty string.

**Comment by macdonst** [comment] 2015-11-02 22:57
@kentmw it's a duplicate of #291 which I'm already working on.

**Closed** 2015-11-02 22:57 UTC
Labels: duplicate

**Comment by kentmw** [comment] 2015-11-02 22:59
@macdonst, seriously just saw that issue moments after typing all this up...
