### ISSUE TITLE
On('registration') calling twice in IOS devices 

### ISSUE THREAD

**Issue by Bhargavi-N** [phonegap/phonegap-plugin-push#2096] opened 2017-12-12 10:37 UTC
### Expected Behaviour
push.on('registration') calling twice in IOS device
expecting to call after clicking on allow option in native popup

### Actual Behaviour
push.on('registration') calling twice in IOS device
One call after init
second call after clicking on native allow popup

### Reproduce Scenario (including but not limited to)
every time 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
in different IOS  devices 5s, 6, 6s, 6s Plus, 7, 10
IOS versions :  10.1, 10.2 , 11.1, 11.2

#### Cordova CLI version and cordova platform version
"cordova-ios": "~4.5.1",
 "cordova-lib": "^7.1.0",

#### Plugin version
cordova plugin version | grep phonegap-plugin-push   # e.g. 2.1.2

**Comment by macdonst** [comment] 2017-12-12 14:59
Looks like a duplicate of #1438 which I can't reproduce.

**Closed by macdonst** 2017-12-12 14:59 UTC
Labels: duplicate
