### ISSUE TITLE
IOS Can't get push notifications on ios10

### ISSUE THREAD

**Issue by pe1o2pl** [phonegap/phonegap-plugin-push#2145] opened 2018-01-12 14:27 UTC
I can't get push notifications on devices with ios10, on ios11 works fine. 
My Deployment Target: 10.0, devices: universal

```
 ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:
    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : ios 4.5.3
    Ionic Framework    : ionic-angular 3.9.2

System:
    ios-deploy : 1.9.2 
    ios-sim    : 5.0.13 
    Node       : v6.10.0
    npm        : 3.10.10 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

phonegap-plugin-push 2.1.0 "PushPlugin"
```

**Comment by macdonst** [comment] 2018-01-12 21:19
@pe1o2pl I can't reproduce this as my test device running iOS 10 is working fine. Can you a) please fill out the issue template and ping me to re-open this issue and b) grab some logs from Xcode as they are usually quite informative.

Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Closed by macdonst** 2018-01-12 21:19 UTC
Labels: can't reproduce, invalid, ios, question
