### ISSUE TITLE
Error trying to remove the plugin

### ISSUE THREAD

**Issue by sebrojas14** [phonegap/phonegap-plugin-push#19] opened 2015-06-19 00:18 UTC
This happen when I try to remove the plugin from my app (I think you miss to rename some things, the cli is looking at com.phonegap.plugins.PushPlugin, when the plugin folder is called phonegap-plugin-push)

E:\LocalDocs\Iridian\PilotoAutomatico\PilotoAutomaticoConductoresCLI>cordova plu
gin rm phonegap-plugin-push
Uninstalling phonegap-plugin-push from android
Removing "phonegap-plugin-push"
Error: ENOENT, no such file or directory 'E:\LocalDocs\Iridian\PilotoAutomatico\
PilotoAutomaticoConductoresCLI\plugins\com.phonegap.plugins.PushPlugin\plugin.xm
l'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at Object.module.exports.parseElementtreeSync (C:\Users\DELL\AppData\Roaming
\npm\node_modules\cordova\node_modules\cordova-lib\src\util\xml-helpers.js:118:2
7)
    at new PluginInfo (C:\Users\DELL\AppData\Roaming\npm\node_modules\cordova\no
de_modules\cordova-lib\src\PluginInfo.js:320:37)
    at PluginInfoProvider.get (C:\Users\DELL\AppData\Roaming\npm\node_modules\co
rdova\node_modules\cordova-lib\src\PluginInfoProvider.js:35:32)
    at C:\Users\DELL\AppData\Roaming\npm\node_modules\cordova\node_modules\cordo
va-lib\src\plugman\util\dependencies.js:42:49
    at Array.forEach (native)
    at Object.module.exports.package.generateDependencyInfo (C:\Users\DELL\AppDa
ta\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\de
pendencies.js:38:45)
    at C:\Users\DELL\AppData\Roaming\npm\node_modules\cordova\node_modules\cordo
va-lib\src\plugman\uninstall.js:166:37
    at Array.forEach (native)

**Comment by macdonst** [comment] 2015-06-19 17:38
@sebrojas14 I can't reproduce this. Is it possible you installed the plugin before the plugin name was changed to `phonegap-plugin-push`?

Try creating a new project and add/rm the plugin, then let me know.

**Comment by sebrojas14** [comment] 2015-06-19 18:31
My project has the previous plugin installed. I uninstall it, the I instlla the new plugin, and then when I try to uninstall the new plugin I got that error. Finally I removed the plugin manually. Maybe was something messed up in the way. If not happen with a new project maybe we can close this.

**Comment by macdonst** [comment] 2015-06-22 14:56
Yeah, I'm going to close this as it should not happen going forward with the package ID consistently being `phonegap-plugin-push` going forward.

**Closed by macdonst** 2015-06-22 14:56 UTC

**Comment by RenateM** [comment] 2016-11-22 14:43
Hi

I also had the above mentioned issue after updating to the newest version of this plugin. I can't remove it now. Recreating my project is not an option. 

How do I go about manually removing the plugin?

Kind regards

**Comment by belkashehaj** [comment] 2017-07-07 10:38
@sebrojas how can i remove plugin manually?
