### ISSUE TITLE
impossible to install the phonegap-plugin-push Error 

### ISSUE THREAD

**Issue by eros2187** [phonegap/phonegap-plugin-push#130] opened 2015-09-14 07:43 UTC
![error](https://cloud.githubusercontent.com/assets/5880552/9844588/b19a5b3e-5ac4-11e5-878f-8322bc1fbd0b.jpg)

this morning and you can not install the plug error up to Seasons last night everything worked !!
it's possible thanks Solve??
joseph greetings

**Comment by caipigott** [comment] 2015-09-14 09:18
Hi,

i also can't install the plugin anymore. In order to get the new funtion for LED i removed the pluging and tried to add it again using "cordova plugin add https://github.com/phonegap/phonegap-plugin-push" but i get the following error:

Error: Does not appear to be an xcode project, no xcode project file in C:\Users
\xxxxxx\yyyyyy\platforms\android

xcode is for IOs, right? I'm using windows and with the update last wednesday everything was fine. Now i can't build anymore as i always get the xcode-error.

Greetings,
Caipigott

**Comment by eros2187** [comment] 2015-09-14 09:23
in fact until yesterday evening everything worked !! ? this morning are unable to fill and can Solve thanks

**Comment by macdonst** [comment] 2015-09-14 12:51
@eros2187 one of the changes checked in yesterday was the move to Gradle. If you are having problems with the current master than add the 1.2.3 version to your project.  How exactly are you building the app as I don't recognize the screen shot you posted.

@caipigott it looks like you typed the plugin add command in the wrong directory.

**Comment by eros2187** [comment] 2015-09-14 13:12
use intel XDK and chart using url
  https://github.com/phonegap/phonegap-plugin-push.git
id: PhoneGap-plugin-push

give me compile error
  there a direct link to 1.2.3?

**Comment by caipigott** [comment] 2015-09-14 13:15
Hi,

thanks for your reply.
I used the same directory i always used, and so far it always worked. But if it was the wrong the wrong directory, why i can't build anymore?

Here is my list of plugins:

[ 'de.appplant.cordova.plugin.email-composer',
  'org.apache.cordova.device',
  'org.apache.cordova.dialogs',
  'org.apache.cordova.file',
  'org.apache.cordova.file-transfer',
  'org.apache.cordova.inappbrowser',
  'org.apache.cordova.statusbar',
  'org.apache.cordova.vibration',
  'phonegap-plugin-push',
  'uk.co.whiteoctober.cordova.appversion' ]

Trying to remove the phonegap-plugin-push leads again to the same error:

C:\Users\xxxx\yyyy>cordova plugins rm phonegap-plugin-push
Uninstalling phonegap-plugin-push from android
Error: Does not appear to be an xcode project, no xcode project file in C:\Users
\xxxxr\yyyy\platforms\android

The same problems (xcode error) i faced using the depricated plugin at https://github.com/phonegap-build/PushPlugin, which was the reason i started to use this one.

Greetings,
Caipigott

**Comment by eros2187** [comment] 2015-09-14 13:23
I compiled the plugin solved by putting this link:
https://github.com/phonegap/phonegap-plugin-push.git#1.2.3
id: PhoneGap-plugin-push

please try thanks to me now compiles without errors
![senza titolo 1](https://cloud.githubusercontent.com/assets/5880552/9850685/7d6c3cbc-5af4-11e5-9360-39efe6b39318.jpg)

**Comment by macdonst** [comment] 2015-09-14 13:27
@eros2187 Yeah, I don't use the Intel XDK to compile apps. It appears one of two things:

1) They do not support gradle
2) You need to do something to add the `com.android.support:support-v13:22+` framework to your app.

**Comment by eros2187** [comment] 2015-09-14 13:29
I compiled the plugin solved by putting this link:
https://github.com/phonegap/phonegap-plugin-push.git#1.2.3
id: PhoneGap-plugin-push

**Comment by macdonst** [comment] 2015-09-14 13:32
@caipigott What version of PhoneGap/Cordova are you using?

**Comment by caipigott** [comment] 2015-09-14 13:33
When i call "cordova -version"
i get 3.4.1-0.1.0

That's what you meant?

**Comment by macdonst** [comment] 2015-09-14 13:37
@caipigott Yeah, that is what I mean and that is a super old version. If you can reproduce with Cordova 5.0 or greater please re-open this issue.

**Closed by macdonst** 2015-09-14 13:37 UTC

**Comment by eros2187** [comment] 2015-09-14 13:42
4.1.2

**Comment by caipigott** [comment] 2015-09-14 13:45
Oh, ok, sry !
But how can i update to 5 or higher? For example to the latest version, and do all my plugins still work after that?

**Comment by eros2187** [comment] 2015-09-14 13:45
ok you have to use 5.0 cordova
Exit When new version plugin to  with data.additionalData working ?

**Comment by macdonst** [comment] 2015-09-15 15:36
@caipigott just install the cordova 5 cli from github. You can read my blog post on updating plugins.

http://simonmacdonald.blogspot.ca/2015/06/including-plugins-with-cordova-command.html

@eros2187 soonish, I need to tag a release and do a blog post sometime this week.
