### ISSUE TITLE
Compatible to FCM 

### ISSUE THREAD

**Issue by joshiparthin** [phonegap/phonegap-plugin-push#931] opened 2016-05-26 11:44 UTC
This link in google developers says people using GCM should upgrade to FCM (Firebase Cloud Messaging).. https://developers.google.com/cloud-messaging/

will this cordova plugin be compatible to FCM ?

**Comment by macdonst** [comment] 2016-05-26 12:20
Duplicate of #929

**Closed by macdonst** 2016-05-26 12:20 UTC
Labels: duplicate
