### ISSUE TITLE
App with phonegap-plugin-push 2.0.0 android crashes when a message is sent

### ISSUE THREAD

**Issue by bhatnagaranilb** [phonegap/phonegap-plugin-push#2360] opened 2018-05-07 15:07 UTC
### Expected Behaviour
- App should not crash when app is open and a notification is sent.
- Tray should show notification when app is in background and a notification is sent.

### Actual Behaviour
- App crashes (Unfortunately this app has stopped working) when app is open and a notification is sent.
- Tray does not show notification when app is in background and a notification is sent.

### Reproduce Scenario (including but not limited to)
As listed above

#### Steps to Reproduce 
As listed above

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Micromax Q412

#### Cordova CLI version and cordova platform version

Phonegap CLI 7.0.1, Android 6.2.3

#### Plugin version
2.0.0

#### Sample Push Data Payload
   'data'=> {
        'title'	=> "Hello World",
	'body' 	=> "Did you practice today?"
   }

#### Sample Code that illustrates the problem
config.xml is---
```
<platform name="android">
    <resource-file src="google-services.json" target="/google-services.json" />
</platform>

<plugin name="cordova-plugin-device" spec="2.0.2" source="npm" />   
<plugin name="phonegap-plugin-push" spec="2.0.0" source="npm">
    <variable name="SENDER_ID" value="1:XXXXXXXX:android:YYYYYYY" />
</plugin>

```

Javascript code has:
```
function onDeviceReady() 
{
    registerForFCMPushNotifications();
    //... more code
}

function registerForFCMPushNotifications()
{
    var notificationObj = PushNotification.init({
        android: {
            senderID: "XXXXXXXXX",
            badge: "true",
            sound: "true",
            vibrate: "true",
            topics: ["all"],
            forceShow: "false"
        },
        ios: {
        },
        windows: {}
    });

    notificationObj.on('registration', function(data) {alert('Id='+data.registrationId);});
    notificationObj.on('notification', function(data) {alert("Got notification");});
    notificationObj.on('error', function(e) {alert( e.message );});
}
```

**Comment by macdonst** [comment] 2018-05-07 15:45
@bhatnagaranilb try making your `config.xml` look like this:

```
<platform name="android">
    <resource-file src="google-services.json" target="google-services.json" />
</platform>

<plugin name="cordova-plugin-device" spec="2.0.2" source="npm" />   
<plugin name="phonegap-plugin-push" spec="2.0.0" source="npm" />
```

If that doesn't work, then run `adb logcat` while reproducing the issue so we can see the stack trace of the crash.

**Comment by bhatnagaranilb** [comment] 2018-05-08 07:50
Updated config.xml as @macdonst suggested. Still crashed.
Changed senderID in javascript to just a number (gcm style), still crashed.
Changed senderID in javascript to 1:XXXXXXX:android:YYYYYY (fcm style). Still crashed.

Unfortunately my device is showing offline in adb despite trying many solutions available on Stacktrace. So no stack trace is available as of now. I am still trying and will paste the trace once available.

**Comment by bhatnagaranilb** [comment] 2018-05-08 08:17
@macdonst my PlayStore is up-to-date too.

**Comment by cyberundertakor** [comment] 2018-05-08 11:03
+1 Same Here
1) On old devices(< Android 7) app crashed
2)On new deviced(>Android 7), the error states "App has stopped working"

**Comment by macdonst** [comment] 2018-05-08 13:50
@bhatnagaranilb what other plugins are you using? I think another plugin using play services is conflicting with this one.

**Comment by bhatnagaranilb** [comment] 2018-05-08 22:47
@macdonst  here is the complete list of plugins I am using in my **phonegap build** app.
I am using admob plugin. Please see list below.

 ```
   <preference name="phonegap-version" value="cli-7.0.1" />	

    <platform name="android">
        <resource-file src="google-services.json" target="google-services.json" />
    </platform>
    	

    <gap:plugin name="cordova-plugin-whitelist" source="npm" version="1" />
    <allow-navigation href="http://xx.yy.com/*" /> 
    
    <plugin name="cordova-plugin-x-toast" spec="2.6.2" source="npm" />
    <plugin name="cordova-plugin-insomnia" spec="4.3.0" source="npm" />		
    <plugin name="cordova-plugin-texttospeech" spec="0.1.1" source="npm" />		
    <plugin name="cordova-plugin-speechrecognition" spec="1.2.0" source="npm" />
    <plugin name="cordova-plugin-device" spec="2.0.2" source="npm" />	
    <plugin name="phonegap-plugin-push" spec="2.0.0" source="npm" />	
    <plugin name="cordova-plugin-admobpro-firebase" spec="2.31.5" source="npm"/>
    <preference name="permissions" value="none"/>   
```

**Comment by macdonst** [comment] 2018-05-09 02:46
@bhatnagaranilb yeah, it's `cordova-plugin-admobpro-firebase` causing the issue. In it's `plugin.xml` it requires:

```
<framework src="com.google.android.gms:play-services-ads:+" />
```

So it picks up the latest Play Services where this plugin uses 11.6.2 by default but you can set it in `config.xml`. 

It would be great if @floatinghotpot could adopt a way of setting the Play Services version like this plugin.

**Comment by bhatnagaranilb** [comment] 2018-05-09 05:13
@macdonst @floatinghotpot - so, as of now, there is no way to use phonegap-plugin-push and cordova-plugin-admobpro-firebase together in an app?

**Comment by bhatnagaranilb** [comment] 2018-05-11 05:41
@macdonst - see my previous comment, and kindly advice.

**Comment by macdonst** [comment] 2018-05-11 16:37
Since the fix is in a different plugin I'm going to close this issue.

**Closed by macdonst** 2018-05-11 16:37 UTC
Labels: android, question
