### ISSUE TITLE
Android badge count 

### ISSUE THREAD

**Issue by barryvdh** [phonegap/phonegap-plugin-push#622] opened 2016-02-16 09:04 UTC
Android badge count is not supported by default, but is does appear to be somewhat standardised.

One method is using https://github.com/leolin310148/ShortcutBadger/ to off-load setting the badges, but it seems that the most popular phones use `android.intent.action.BADGE_COUNT_UPDATE` to set the badge. Example from [DefaultBadger](https://github.com/leolin310148/ShortcutBadger/blob/master/ShortcutBadger/src/main/java/me/leolin/shortcutbadger/impl/DefaultBadger.java):

```java
private static final String INTENT_ACTION = "android.intent.action.BADGE_COUNT_UPDATE";
private static final String INTENT_EXTRA_BADGE_COUNT = "badge_count";
private static final String INTENT_EXTRA_PACKAGENAME = "badge_count_package_name";
private static final String INTENT_EXTRA_ACTIVITY_NAME = "badge_count_class_name";

public void executeBadge(Context context, ComponentName componentName, int badgeCount) throws ShortcutBadgeException {
   Intent intent = new Intent(INTENT_ACTION);
   intent.putExtra(INTENT_EXTRA_BADGE_COUNT, badgeCount);
   intent.putExtra(INTENT_EXTRA_PACKAGENAME, componentName.getPackageName());
   intent.putExtra(INTENT_EXTRA_ACTIVITY_NAME, componentName.getClassName());
   context.sendBroadcast(intent);
}
```

Would it be possible to implement `push.setApplicationIconBadgeNumber()`, using this intent?

**Comment by macdonst** [comment] 2016-04-12 14:01
@barryvdh marking as duplicate of #190 but working on merging #624 into branch v1.7.x right now.

**Closed by macdonst** 2016-04-12 14:01 UTC
Labels: android, duplicate

**Comment by YaroslavG** [comment] 2016-04-26 15:23
hi macdonst,
Where I can find v1.7.x ?

**Comment by macdonst** [comment] 2016-04-26 15:26
@YaroslavG it is a branch of this github repo. Not released to NPM yet.

**Comment by YaroslavG** [comment] 2016-04-26 15:30
can I use it and will work android badge?

**Comment by barryvdh** [comment] 2016-04-26 15:36
Yes, you can also require a branch by adding the git repo als plugin, with #v1.7.x appended

**Comment by YaroslavG** [comment] 2016-04-26 15:37
ok, thanks

**Comment by YaroslavG** [comment] 2016-04-28 09:07
macdonst,
Hi, I can install plugin from your branch or I need change files in plugin?
