### ISSUE TITLE
Google Play Services r41

### ISSUE THREAD

**Issue by tgensol** [phonegap/phonegap-plugin-push#1776] opened 2017-06-08 15:27 UTC
### Actual Behaviour

The new Google play services (revision 41) is breaking the build on Android (for the version 1.10.4, I did not try the new 2.0)

```
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/zzc;
```

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android

#### Cordova CLI version and cordova platform version

    cordova 7.0.1,  android 6.2.3

#### Plugin version

  1.10.4

####

To solve this, changing in the plugin.xml, the version of the play-services-gcm with : 

 `<framework src="com.google.android.gms:play-services-gcm:11.0+"/>`

Maybe this will cause more issue ? 
At least, the build should then work properly

**Comment by fredgalvao** [comment] 2017-06-08 17:24
Closing this as a duplicate of https://github.com/phonegap/phonegap-plugin-push/issues/1772.

**Closed by fredgalvao** 2017-06-08 17:24 UTC
