### ISSUE TITLE
Failed to install 'phonegap-plugin-push':undefined Error: Version should contain only numbers and dots

### ISSUE THREAD

**Issue by SepuWeb** [phonegap/phonegap-plugin-push#1465] opened 2016-12-14 22:43 UTC
Hi,
when I execute command "cordova platforms add ios" return this error:

iOS project created with cordova-ios@4.3.1
Installing "cordova-plugin-admobpro" for ios
Installing "cordova-plugin-extension" for ios
Installing "cordova-plugin-app-version" for ios
Installing "cordova-plugin-console" for ios
Installing "cordova-plugin-datepicker" for ios
Installing "cordova-plugin-device" for ios
Installing "cordova-plugin-dialogs" for ios
Installing "cordova-plugin-email-composer" for ios
Dependent plugin "cordova-plugin-extension" already installed on ios.
Installing "cordova-plugin-geolocation" for ios
Installing "cordova-plugin-inappbrowser" for ios
Installing "cordova-plugin-splashscreen" for ios
Installing "cordova-plugin-statusbar" for ios
Installing "cordova-plugin-whitelist" for ios
Installing "cordova-plugin-winstore-jscompat" for ios
Installing "cordova-plugin-x-toast" for ios
Installing "cordova-sqlite-storage" for ios
installing external dependencies via npm
npm install of external dependencies ok
Installing "ionic-plugin-keyboard" for ios
Installing "phonegap-plugin-push" for ios
**Failed to install 'phonegap-plugin-push':undefined
Error: Version should contain only numbers and dots**

this is my configuration:

cordova-plugin-admobpro 2.25.0 "AdMob Plugin Pro"
cordova-plugin-app-version 0.1.8 "AppVersion"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-datepicker 0.9.2 "DatePicker"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-email-composer 0.8.3 "EmailComposer"
cordova-plugin-extension 1.5.1 "Cordova Plugin Extension"
cordova-plugin-geolocation 2.1.0 "Geolocation"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-splashscreen 3.1.0 "Splashscreen"
cordova-plugin-statusbar 2.1.1 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-plugin-winstore-jscompat 0.0.1 "Windows Compatibility"
cordova-plugin-x-toast 2.5.2 "Toast"
cordova-sqlite-storage 1.5.1 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 1.0.8 "Keyboard"
**phonegap-plugin-push 1.9.2 "PushPlugin"**

cordova: 6.4.0
cocoadpods: 1.2.0.beta.1

Thank you.

**Comment by macdonst** [comment] 2016-12-15 15:45
@SepuWeb how do you install the push plugin? What does it look like in your config.xml?

**Comment by SepuWeb** [comment] 2016-12-15 18:09
I execute the following command:

cordova plugin add https://github.com/phonegap/phonegap-plugin-push --variable SENDER_ID="11111111111"

**Comment by cookys** [comment] 2016-12-16 12:30
@SepuWeb check you cocoapods installation. I fixed this with
 **sudo gem install -n /usr/local/bin cocoapods**

**Comment by SepuWeb** [comment] 2016-12-16 22:29
Hi cookys, when I execute `sudo gem install -n /usr/local/bin cocoapods` return me:

> Successfully installed cocoapods-1.1.1
> Parsing documentation for cocoapods-1.1.1
> 1 gem installed

after I run `cordova platforms rm ios` and after `cordova platforms add ios`

but return:

**Failed to install 'phonegap-plugin-push':undefined
Error: Version should contain only numbers and dots**

**Comment by macdonst** [comment] 2016-12-19 14:42
@SepuWeb I can't reproduce this. I need better steps in order to figure out how you got to this point.

**Comment by SepuWeb** [comment] 2016-12-19 22:06
Hi macdonst and thank you,
for my app I need push notifications, so I follow the guide and execute the command to install this plugin in my ionic project.

First of all I execute the command:

`cordova plugin add https://github.com/phonegap/phonegap-plugin-push --variable SENDER_ID="11111111111"`

after I run `cordova platforms rm ios` and after `cordova platforms add ios`

nothing else.

have I to do other things?

**Comment by vreen** [comment] 2016-12-20 09:49
I try to implement push notifications for my ionic2 app on my mac and have the exact same situation here.

I am willing to provide any information to help you figure out what's going on.

Sascha

**Comment by pavel-matarevic** [comment] 2016-12-20 11:08
I have same problem:

`cordova plugin add phonegap-plugin-push`
`Installing "phonegap-plugin-push" for android`
`ANDROID_HOME=/Users/pavel/Library/Android/sdk`
`JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home`
`Subproject Path: CordovaLib`
`Starting a new Gradle Daemon for this build (subsequent builds will be faster).`
`Incremental java compilation is an incubating feature.`
`:clean`
`:CordovaLib:clean`
``
`BUILD SUCCESSFUL`
``
`Total time: 10.067 secs`
`Subproject Path: CordovaLib`
`Installing "phonegap-plugin-push" for browser`
`Error loading cordova-browser`
`Installing "phonegap-plugin-push" for ios`
`Failed to install 'phonegap-plugin-push':undefined`
`Error: Version should contain only numbers and dots`

pod --version
`1.2.0.beta.1`

cordova -v
`6.4.0`

cordova platform -l
`Installed platforms:`
`  android 6.0.0`
`  browser 4.1.0`
`  ios 4.3.1`
`Available platforms:`
`  amazon-fireos ~3.6.3 (deprecated)`
`  blackberry10 ~3.8.0`
`  firefoxos ~3.6.3`
`  osx ~4.0.1`
`  webos ~3.7.0`

**Comment by nphyatt** [comment] 2016-12-20 17:18
I was able to fix by using cocoapods:1.1.1

```bash
sudo gem install -n /usr/local/bin cocoapods:1.1.1
sudo gem unistall -n /usr/local/bin cocoapods # uninstall 1.2.0.beta.1
pod --version # 1.1.1
rm -rf platforms plugins
cordova platform add ios
```

**Comment by marcos1490** [comment] 2016-12-20 20:58
As @nphyatt mentioned the fix is to have cocoapods v 1.1.1 installed. It's actually on the [requirements](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation-requirements)

**Comment by macdonst** [comment] 2017-01-03 14:16
Closing this as the community agrees that it is a cocoapods 1.1.1 requirement issue.

**Closed by macdonst** 2017-01-03 14:16 UTC
Labels: can't reproduce, ios, question

**Comment by ssbDeveloper-SG** [comment] 2017-02-08 03:11
Sorry if this sounds stupid I'm really new to this but I encountered this problem as well on my windows 10.

![cocoapods error](https://cloud.githubusercontent.com/assets/24999384/22722037/36b1d3ec-edef-11e6-81af-689c57dc41a8.jpg)

Working on VS2015 and deploying the app to an ios device via remotebuild.
Correct me if I'm wrong but all the solutions using sudo gem to install cocoapods are commands to be run in the Terminal of a mac. 
How can I solve this on Windows. 
Any Pointers and guidance will be much appreciated thank u in advance.

**Comment by miche-atucha** [comment] 2017-02-15 19:47
@ssbDeveloper-SG watch the warning : **Applications for platform iOS can not be built on this OS - win32**.
u cannot build iOS platform on windows platform.

**Comment by kaynz** [comment] 2017-02-17 13:48
@macdonst Why's there no information in the readme about this requirement?

**Comment by fredgalvao** [comment] 2017-02-17 17:36
That's not a requirement of this plugin, it's a requirement of cordova. If you create an empty cordova project on windows, add android and ios platforms, and try to do any of these  `clean, compile, build` you'll get an error.

Thus, plugins that affect the compile step like push do, will not work on a windows environment. iOS platform projects can only be built on macOS environments.

**Comment by gnhub** [comment] 2017-06-03 08:17
I thing it should permission issues, I have tried, Please Visit, [Issue1342](https://github.com/phonegap/phonegap-plugin-push/issues/1342).

Thanks.

**Comment by VitorHFLopes** [comment] 2017-07-24 22:47
@kaynz it's here https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation-requirements

**Comment by Zorgatone** [comment] 2017-09-26 15:23
Same issue here,

removed old phonegap-plugin-push, installed cocoa pods and added new phonegap-plugin-push then when adding ios platform:

```
Using cordova-fetch for cordova-ios@~4.4.0


Adding ios project...


Creating Cordova project for the iOS platform:

	Path: platforms/ios

	Package: com.myapp.myapp
	Name: Myapp


iOS project created with cordova-ios@4.4.0


Installing "cordova-plugin-compat" for ios


Installing "cordova-plugin-console" for ios

Installing "cordova-plugin-crosswalk-webview" for ios



        After much discussion and analysis of the market, we have decided to discontinue support for Android 4.0 (ICS) in Crosswalk starting with version 20.

        So the minSdkVersion of Cordova project is configured to 16 by default.



Installing "cordova-plugin-device" for ios


Installing "cordova-plugin-dialogs" for ios

Installing "cordova-plugin-file" for ios



The Android Persistent storage location now defaults to "Internal". Please check this plugins README to see if you application needs any changes in its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation" value="Compatibility" />"

to config.xml in order for the application to find previously stored files.




Installing "cordova-plugin-geolocation" for ios

Plugin dependency "cordova-plugin-compat@1.2.0" already fetched, using that version.


Dependent plugin "cordova-plugin-compat" already installed on ios.

Installing "cordova-plugin-inappbrowser" for ios

Installing "cordova-plugin-network-information" for ios

Installing "cordova-plugin-splashscreen" for ios


Installing "cordova-plugin-statusbar" for ios

Installing "cordova-plugin-whitelist" for ios


Installing "cordova-plugin-wkwebview-engine" for ios

Installing "cordova-plugin-x-toast" for ios


Installing "ionic-plugin-keyboard" for ios


Installing "phonegap-plugin-push" for ios

Failed to install 'phonegap-plugin-push': undefined

Error: Version should contain only numbers and dots
```

**Comment by Zorgatone** [comment] 2017-09-26 15:25
I have cocoapods version 1.4.0.beta.1 installed with `sudo gem install cocoapods` on macOS Sierra 0.12.6

**Comment by Zorgatone** [comment] 2017-09-26 15:27
Basically I have to downgrade to cocoapods 1.1.1??

**Comment by Zorgatone** [comment] 2017-09-26 15:48
Ok, removed cocoapods and reinstalled version 1.1.1 (instead of 1.4.0.beta.1) and it worked

**Comment by bhumin3i** [comment] 2018-01-30 09:38
@nphyatt 

after run 
$cordova platform add ios

ERROR : 

Discovered plugin "phonegap-plugin-push" in config.xml. Adding it to the project

Installing "phonegap-plugin-push" for ios

Failed to install 'phonegap-plugin-push': undefined

Failed to restore plugin "phonegap-plugin-push" from config.xml. You might need to try adding it again. Error: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /Users/rac/Desktop/Bhumin/RTI/blankRTI/node_modules/.bin in PATH, mode 040777
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as root. (CLAide::Help)

Usage:

    $ pod COMMAND

      CocoaPods, the Cocoa library package manager.

Commands:

    + cache      Manipulate the CocoaPods cache
    + env        Display pod environment
    + init       Generate a Podfile for the current directory
    + install    Install project dependencies according to versions from a
                 Podfile.lock
    + ipc        Inter-process communication
    + lib        Develop pods
    + list       List pods
    + outdated   Show outdated project dependencies
    + repo       Manage spec-repositories
    + setup      Setup the CocoaPods environment
    + spec       Manage pod specs
    + update     Update outdated project dependencies and create new Podfile.lock

Options:

    --silent     Show nothing
    --version    Show the version of the tool
    --verbose    Show more debugging information
    --no-ansi    Show output without ANSI codes
    --help       Show help banner of specified command
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:47:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:23:in `load'
	from /usr/local/bin/pod:23:in `<main>'

Discovered plugin "cordova-plugin-geolocation" in config.xml. Adding it to the project

Installing "cordova-plugin-geolocation" for ios

Adding cordova-plugin-geolocation to package.json

Saved plugin info for "cordova-plugin-geolocation" to config.xml

--save flag or autosave detected
Saving ios@~4.5.4 into config.xml file ...
[ERROR] Exception:
