### ISSUE TITLE
Background actions - Android

### ISSUE THREAD

**Issue by Maximvdw** [phonegap/phonegap-plugin-push#734] opened 2016-03-21 19:49 UTC
Dear,

I created a push notification before with two action buttons (lets say "yes" and "no"). They worked
and still do work fine in 1.6. The app opens in the foreground and the callbacks get executed.

However with 1.6 I wanted to do this in the background so I can also use it on android wear. The application remains in the background but the callback does not get executed. Only when I manually start the application the callback that has been stored is executed.

The push plugin is initialized when the device is ready. I tried this on android 5.1 ,6.0 on both a OnePlus One, OnePlus Two, Samsung Galaxy s7e and Samsung Galaxy s3 mini

Versions:
phonegap cordova --version = 6.0.0
phonegap platform version android = 4.1.1
push plugin version = 1.6.0

The callbacks are "app.yes" and "app.no" (as test) and are defined in the app object also containing the initialize method.

log on receiving the notification:

```
03-21 20:45:11.522 28925-28949/? D/PushPlugin_GCMIntentService: onMessage - from: 978275104094
03-21 20:45:11.526 28925-28949/? D/PushPlugin_GCMIntentService: normalize extras
03-21 20:45:11.527 28925-28949/? D/PushPlugin_GCMIntentService: key = actions
03-21 20:45:11.528 28925-28949/? D/PushPlugin_GCMIntentService: replace key actions with actions
03-21 20:45:11.528 28925-28949/? D/PushPlugin_GCMIntentService: key = data
03-21 20:45:11.528 28925-28949/? D/PushPlugin_GCMIntentService: extracting nested message data from key = data
03-21 20:45:11.528 28925-28949/? D/PushPlugin_GCMIntentService: replace key data with data
03-21 20:45:11.528 28925-28949/? D/PushPlugin_GCMIntentService: key = notId
03-21 20:45:11.528 28925-28949/? D/PushPlugin_GCMIntentService: replace key notId with notId
03-21 20:45:11.529 28925-28949/? D/PushPlugin_GCMIntentService: key = title
03-21 20:45:11.529 28925-28949/? D/PushPlugin_GCMIntentService: replace key title with title
03-21 20:45:11.529 28925-28949/? D/PushPlugin_GCMIntentService: key = message
03-21 20:45:11.529 28925-28949/? D/PushPlugin_GCMIntentService: replace key message with message
03-21 20:45:11.529 28925-28949/? D/PushPlugin_GCMIntentService: key = collapse_key
03-21 20:45:11.529 28925-28949/? D/PushPlugin_GCMIntentService: replace key collapse_key with collapse_key
03-21 20:45:11.530 28925-28949/? D/PushPlugin_GCMIntentService: background
03-21 20:45:11.530 28925-28949/? D/PushPlugin_GCMIntentService: message =[Entrance request at Test reader Maxim]
03-21 20:45:11.530 28925-28949/? D/PushPlugin_GCMIntentService: title =[eIDIO Entrance request]
03-21 20:45:11.530 28925-28949/? D/PushPlugin_GCMIntentService: contentAvailable =[null]
03-21 20:45:11.530 28925-28949/? D/PushPlugin_GCMIntentService: create notification
03-21 20:45:11.540 28925-28949/? D/PushPlugin_GCMIntentService: stored icon=logonotification
03-21 20:45:11.541 28925-28949/? D/PushPlugin_GCMIntentService: stored iconColor=null
03-21 20:45:11.541 28925-28949/? D/PushPlugin_GCMIntentService: stored sound=true
03-21 20:45:11.541 28925-28949/? D/PushPlugin_GCMIntentService: stored vibrate=true
03-21 20:45:11.541 28925-28949/? D/PushPlugin_GCMIntentService: using icon from plugin options
03-21 20:45:11.543 28925-28949/? D/PushPlugin_GCMIntentService: create actions
03-21 20:45:11.543 28925-28949/? D/PushPlugin_GCMIntentService: adding action
03-21 20:45:11.543 28925-28949/? D/PushPlugin_GCMIntentService: adding callback = app.allowEntrance
03-21 20:45:11.573 28925-28949/? D/PushPlugin_GCMIntentService: adding action
03-21 20:45:11.573 28925-28949/? D/PushPlugin_GCMIntentService: adding callback = app.denyEntrance
```

log on clicking "allow"

```
03-21 20:47:37.802 28925-28925/? D/PushPlugin_BackgroundActionButtonHandler: BackgroundActionButtonHandler = Bundle[mParcelledData.dataSize=992]
03-21 20:47:37.802 28925-28925/? D/PushPlugin_BackgroundActionButtonHandler: not id = 1
03-21 20:47:37.804 28925-28925/? V/PushPlugin: sendExtras: caching extras to send at a later time.
```

after that nothing happens (the code doesn't get executed until I actually open the app)

Regards,
Maxim

**Comment by macdonst** [comment] 2016-03-21 21:03
@Maximvdw can you send me an example of the push payload you send to the device?

**Comment by Maximvdw** [comment] 2016-03-23 16:39
sry for the late reaction:

    {
       "data":{
          "message":"Give access to X",
          "title":"Access request",
          "notId":1,
          "actions":[
             {
                "icon":"ic_allowentrance",
                "title":"Allow",
                "callback":"app.allowEntrance",
                "foreground":false
             },
             {
                "icon":"ic_denyentrance",
                "title":"Deny",
                "callback":"app.denyEntrance",
                "foreground":false
             }
          ]
       }
    }

**Comment by macdonst** [comment] 2016-04-03 00:49
@Maximvdw by chance has the app been killed? As long as I don't kill the app in the task launcher this should work.

**Comment by Maximvdw** [comment] 2016-04-04 09:53
@macdonst the app is indeed killed, so sorry if I missed this in the description: but does it mean that it won't do anything (nor start the app) when the app is killed but the notification shows up? Would there be any way to somehow allow this to work even when the app is killed.

Again sorry if this was something in the description that I missed

**Comment by Maximvdw** [comment] 2016-04-04 09:53
oeps accidentally clicked closed (my bad)

**Comment by macdonst** [comment] 2016-04-04 12:21
@Maximvdw yeah, this is the same root cause as #158. If you kill the app then the webview is unloaded and there is nothing to run the JS code in the background. That's why the action only runs once the app is started. If you are okay I'm going to mark this issue as a duplicate of #158 and you can add your comments on that issue. 

I need to figure out a way to restart the webview without bringing the app to the foreground to fix this.

**Comment by marcoziegaus** [comment] 2016-04-05 14:38
@macdonst I've followed the various threads on this core problem and to me it seems like #158 is the "main" issue. However, I want to post a suggestion here as you laid out some details on the problems here, too.

I found [this](https://github.com/christocracy/push-cordova-plugin/blob/master/src/android/PushHandlerActivity.java#L34) (restarting the MainActivity if the WebView is not started) somewhere, maybe you could utilise a similar approach?

**Closed** 2018-06-10 05:33 UTC
Labels: android, question, wontfix
