### ISSUE TITLE
Support different push servers (Android)

### ISSUE THREAD

**Issue by jacobfunch** [phonegap/phonegap-plugin-push#245] opened 2015-10-20 12:03 UTC
**This should be helpful for people who don't receive push notifications on Android.**

It seems that this plugin expects either MESSAGE or TITLE key in the Push object for Android. However some hosted push servers, such as Parse.com don't use 'message'. They use 'alert'.

To fix this go ahead and change MESSAGE to ALERT (or whatever your push server uses) in *GCMIntentService.java*. For example:
```
String message = extras.getString(MESSAGE); --> String message = extras.getString(ALERT);
```

**Suggestion:** let's add an easy configuration to change this instead of editing the source code.

**Comment by macdonst** [comment] 2015-10-20 14:12
@jacobfunch this is a duplicate of #147 which will be fixed once 1.4.0 comes out so there will be no need to modify the Java code.

**Closed** 2015-10-20 14:14 UTC
