### ISSUE TITLE
Notification with app closed/background

### ISSUE THREAD

**Issue by gmittica** [phonegap/phonegap-plugin-push#771] opened 2016-04-01 12:20 UTC
### Expected Behaviour

Receive notification on Android with app closed/background

### Actual Behaviour

No notifications are received if on the device (for example Xiaomi Mi4c, Asus ZenPhone...) the app is not manually added to "apps list available for autorun" in security center.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
5.0+

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Xiaomi Mi4c, Asus ZenPhone, Samsung S5...

 phonegap-plugin-push   2.4.0

### Expected Behaviour

Receive notification on Android with app closed/background

### Actual Behaviour

No notifications are received if on the device (for example Xiaomi Mi4c, Asus ZenPhone...) the app is not manually added to "apps list available for autorun" in security center.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
5.0+

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Xiaomi Mi4c, Asus ZenPhone, Samsung S5...

 phonegap-plugin-push   2.4.0

#### Sample Push Data Payload
```
{
	"registration_ids": ["token-1"],
	"data": {
		"message": "the message",
		"title": "title",
		"subtitle": "title",
		"tickerText": "title",
		"vibrate": 1,
		"sound": 1,
		"largeIcon": "large_icon",
		"smallIcon": "small_icon",
                "content-available": "1"
	}
}
```

**Comment by macdonst** [comment] 2016-04-01 12:45
@gmittica I'm pretty sure this is a duplicate of #707. Also, where did you get version 2.4.0 of this plugin because we are only up to version 1.6.1. Are you sure you aren't using https://github.com/phonegap-build/PushPlugin which is not the same plugin.

**Comment by dhirajb1989** [comment] 2016-04-04 14:52
I am facing the same problem with Mi4i ..... Until and unless I don't go to Security>Permissions>Autostart and add the app to autostart the notification does not come.... I even tried to get all the correct SDK's . Can we hope for a fix for this in future .

**Closed** 2016-04-08 17:47 UTC
Labels: android, duplicate
