### ISSUE TITLE
Opt-out of CocoaPod

### ISSUE THREAD

**Issue by ippeiukai** [phonegap/phonegap-plugin-push#1555] opened 2017-01-29 12:23 UTC
### Expected Behaviour

One can build iOS app that uses phonegap-plugin-push without CocoaPod. CocoaPod should not be needed if the app uses APN on iOS app.
 
### Actual Behaviour

iOS app that uses phonegap-plugin-push does not work if CocoaPod is not present on the build environment. (Plugin fails to get installed. Either build stops there or the app builds without phonegap-plugin-push in it.)

### Reproduce Scenario (including but not limited to)

We use Ionic Cloud. Everything is working with phonegap-plugin-push at 1.8.x, but not with 1.9.x.
The server does not have CocoaPod, and is out of reach of us customers.
The resulting .ipa archive is missing phonegap-plugin-push plugin within the bundle.

#### Steps to Reproduce 

0. Upgrade any app that uses phonegap-plugin-push 1.8.x to use 1.9.x.
0. Have your CI server build your app as usual.
0. Launch the resulting app to find that the plugin is missing.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

N/A
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

N/A
#### Cordova CLI version and cordova platform version

Cordova CLI version on our CI server (Ionic Cloud) is unknown.

Following platforms are specified in config.xml:
```
    <engine name="ios" spec="4.3.1" />
    <engine name="android" spec="6.1.2" />
    <engine name="browser" spec="4.1.0" />
```
#### Plugin version

working:
```
    <plugin name="phonegap-plugin-push" source="npm" spec="1.8.4">
        <variable name="SENDER_ID" value="[FILTERED]" />
    </plugin>
```
not working:
```
    <plugin name="phonegap-plugin-push" source="npm" spec="1.9.2">
        <variable name="SENDER_ID" value="[FILTERED]" />
    </plugin>
```
#### Sample Push Data Payload

N/A
#### Sample Code that illustrates the problem

N/A
#### Logs taken while reproducing problem

N/A

**Comment by macdonst** [comment] 2017-01-29 19:25
@ippeiukai yup, that would be great if there was some way to conditionally included the CocoaPods but I don't know of a way to do it right now. Have you asked Ionic Cloud to include CocoaPods? That's what the PG Build team did.

**Comment by Defcon0** [comment] 2017-04-05 23:10
+1

**Comment by macdonst** [comment] 2017-06-27 16:29
Dupe of #1419

**Closed by macdonst** 2017-06-27 16:29 UTC
Labels: enhancement, ionic, ios
