### ISSUE TITLE
The "notification" event is not fired on iOS 9.0.2

### ISSUE THREAD

**Issue by smanuel** [phonegap/phonegap-plugin-push#200] opened 2015-10-04 15:54 UTC
Hi,

The notification is received successfully on the phone. When I tap on it the [AppDelegate.didReceiveRemoteNotification](https://github.com/phonegap/phonegap-plugin-push/blob/master/src/ios/AppDelegate%2Bnotification.m#L65) method is called successfully but the app state is inactive and the notification is saved for later.
Immediately after that, the [applicationDidBecomeActive](https://github.com/phonegap/phonegap-plugin-push/blob/master/src/ios/AppDelegate%2Bnotification.m#L85) method is called which does

```objective-c
    [pushHandler performSelectorOnMainThread:@selector(notificationReceived) withObject:pushHandler waitUntilDone:NO];
```
but the [PushPlugin.notificationReceived](https://github.com/phonegap/phonegap-plugin-push/blob/master/src/ios/PushPlugin.m#L187) method is never called and the "notification" event on the javascript side is never fired.

Any ideas on how I could eventually fix this?
Thanks in advance for your help.

- Silvio

**Comment by macdonst** [comment] 2015-10-11 05:30
@smanuel I downgraded one of my devices to iOS 9.0.2 and I cannot reproduce this issue.

**Comment by lordamon** [comment] 2015-10-12 11:22
i have the same problem too in ios 9.0.2

**Comment by chumstech** [comment] 2015-10-12 13:09
i have a same problem too in iOS devices greater then 9.0

**Comment by smanuel** [comment] 2015-10-12 14:07
@macdonst The problem was in some changes I had done at a totally different place but which resulted in the above mentioned behavior. Reverted all the changes and everything works as expected.
Sorry for the false alarm.

**Comment by chumstech** [comment] 2015-10-12 14:09
@smanuel can you please tell us how we can fix this issue?
becasue at my side there is no notification at devices above 9.0 but devices 8.0 working fine.

**Comment by macdonst** [comment] 2015-10-12 16:20
Closed as per @smanuel

**Closed by macdonst** 2015-10-12 16:20 UTC
Labels: bug
