### ISSUE TITLE
The notification is shown on the ios10 in foreground mode

### ISSUE THREAD

**Issue by extempl** [phonegap/phonegap-plugin-push#1765] opened 2017-06-05 23:51 UTC
### Expected Behaviour
According to readme, it should not be shown while the app is in foreground.

### Actual Behaviour
It is shown on the top.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
IOS 10.3.2
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iPhone 6 (NG4R2LL/A)

#### Cordova CLI version and cordova platform version
cordova version 6.5.0
cordova platform version 4.3.1

#### Plugin version
1.10.4

#### Sample Push Data Payload
Was not set.
#### Sample Code that illustrates the problem
I've used https://github.com/node-apn/node-apn
with something like this:

    var apnProvider = new apn.Provider({token: {key, keyId, teamId}, production}) // values are ommitted
    var notification = new apn.Notification();
    notification.topic = '%topic%'
    notification.alert = 'someTitle' // with `body` same behavior
    apnProvider.send(notification, deviceToken)

#### Logs taken while reproducing problem
Just nothing.

#### code used to initialize the plugin
 (Coffeescript)

    pnOptions =
      android:
        senderID: 'some'
        icon: 'transparent_icon'
      ios:
        alert: 'true'
        badge: 'true'
        clearBadge: 'true'
        sound: 'true'
        categories:
          default:
            yes:
              callback: "pnController.accept"
              title: "Accept"
              foreground: true
              destructive: false
            no:
              callback: "pnController.reject"
              title: "Reject"
              foreground: false
              destructive: true

    PushNotification.init pnOptions

**Comment by fredgalvao** [comment] 2017-06-06 01:42
You did not provide any of the following needed information to reproduce, debug, fix and test your issue:
- example payload used to send the notification
- code used to initialize the plugin
- logs taken from xcode during the reproduction of your issue.

All of those fields/sections are described in the github issue template as needed, and it is literally impossible to even try to help you without them.

![image](https://cloud.githubusercontent.com/assets/616464/26810147/24d515be-4a40-11e7-8976-4313d366b907.png)

**Comment by extempl** [comment] 2017-06-06 18:37
@fredgalvao updated the initial message. 
As you can see, actually, nothing was added. Everything is like almost default setup with minimum payload (just title). That doesn't mean that this does not happens for different payload, I just simplified it.

**Comment by extempl** [comment] 2017-06-06 18:38
Btw, when I catched the issue, I had older version, is like `1.9.4`.

**Comment by extempl** [comment] 2017-06-06 18:40
And, btw2 - it does not shown on the android, but there is also different service for sending notifications.

**Comment by fredgalvao** [comment] 2017-06-06 18:50
@macdonst Can you take a look?

**Comment by extempl** [comment] 2017-06-06 20:38
Found the issue. 
The plugin `de.appplant.cordova.plugin.local-notification` was installed beside of the current one.

**Comment by extempl** [comment] 2017-06-06 20:43
So we have two issues here:
- plugins conflict
- Actuality of the `The message is not displayed in the devices notification center as that is not normal behaviour for Android or iOS.` statement. So if it shows notification while app is active, maybe *it is* normal behaviour for iOS?

**Comment by macdonst** [comment] 2017-06-06 23:37
@extempl no, it's not normal behaviour for the notification to show up while the app is in the foreground. In fact it wasn't even possible until iOS 10.

Do you need to use `de.appplant.cordova.plugin.local-notification`?

**Comment by extempl** [comment] 2017-06-07 00:17
@macdonst 
> In fact it wasn't even possible until iOS 10
That's what I mean, so this is the default behaviour on the iOS10+, is that correct? 

> Do you need to use `de.appplant.cordova.plugin.local-notification`?
I need local notifications, so yes, this is the only plugin I found.
Are they can't be compatible one with other?

**Comment by macdonst** [comment] 2017-06-07 14:18
@extempl no, it's not the default behaviour to show a notification when the app is in the foreground even in iOS10+.

I'll have to see if I can make some time to check into the other plugin. The other plugin I started working on is https://github.com/phonegap/phonegap-plugin-local-notification but it is iOS10 only right now and I didn't implement the force show on iOS https://github.com/phonegap/phonegap-plugin-local-notification/issues/8 yet.

**Comment by extempl** [comment] 2017-06-07 20:42
@macdonst 
> but it is iOS10 only right now
 right now is a perfect timing to make it popular, as the plugin mentioned by me does not fully supports ios10, it has like a branch for it which is still in dev state.

**Comment by jcesarmobile** [comment] 2017-06-15 14:32
can you show your on notification code?

**Comment by extempl** [comment] 2017-06-15 16:37
@jcesarmobile does not matters.
`push.on('notification', function (data) {alert(data)})` for example. Have you checked the comments above?

**Comment by macdonst** [comment] 2017-06-16 12:26
@extempl I'm not even sure what you issue is now. Can you restate what the problem is?

**Comment by extempl** [comment] 2017-06-16 17:14
@macdonst After I set off the local notification plugin I mentioned before - all works fine. Right now I do not have any issues. Later I'll probably will use your plugin for local notifications.
But, still, if there is any problem with plugins incompatibility - it should be fixed or noted explicitly that they are not compatible.

**Comment by extempl** [comment] 2017-06-16 17:17
So, the problem was in that when you have installed current plugin for PN and `de.appplant.cordova.plugin.local-notification` for LN - PN plugin onNotification handler was not fired and the notification appeared on the top of the screen while the app is in the foreground mode. So probably it was done by the system default config or the another plugin, I do not know.

**Comment by drbeermann** [comment] 2017-06-16 17:50
FWIW, I'm seeing this exact problem right now as well.

**Comment by LlamaloX** [comment] 2017-09-07 17:34
Was this solved in any way? I am having the same problem with the notification bar appearing in foreground

**Comment by macdonst** [comment] 2017-09-12 23:45
Closing as the original issue was solved by removing the local notification plugin.

**Closed by macdonst** 2017-09-12 23:45 UTC
Labels: ios
