### ISSUE TITLE
Notification icon showing as phonegap on iphone 6+

### ISSUE THREAD

**Issue by lavarith** [phonegap/phonegap-plugin-push#863] opened 2016-05-04 15:41 UTC
### Expected Behaviour

For all iPhone's I've tested except for iphone 6+, the notification icon appears as the application icon. 
### Actual Behaviour

However, on an iphone 6+, it shows as the phonegap icon. I've tested an iphone 5, 5S, and 6 and it shows correctly.
### Reproduce Scenario (including but not limited to)

My config.xml includes the following related to icons, ios, and the plugin:

```
    <plugin name="phonegap-plugin-push" source="npm" spec="1.6.3">
        <param name="SENDER_ID" value="launch-money" />
    </plugin>
    <icon src="icon.png" />
    <icon platform="android" gap:qualifier="ldpi" src="res/icon/android/icon-36-ldpi.png" />
    <icon platform="android" gap:qualifier="mdpi" src="res/icon/android/icon-48-mdpi.png" />
    <icon platform="android" gap:qualifier="hdpi" src="res/icon/android/icon-72-hdpi.png" />
    <icon platform="android" gap:qualifier="xhdpi" src="res/icon/android/icon-96-xhdpi.png" />
    <platform name="ios">
        <!-- iOS 7.0 -->
        <!-- iPhone 6 / 6+ -->
        <icon height="180" src="res/icon/ios/icon-60-3x.png" width="180" />
        <!-- iPhone / iPod Touch  -->
        <icon height="60" src="res/icon/ios/icon-60.png" width="60" />
        <icon height="120" src="res/icon/ios/icon-60-2x.png" width="120" />
        <!-- Settings Icon -->
        <icon height="76" src="res/icon/ios/icon-76.png" width="76" />
        <icon height="152" src="res/icon/ios/icon-76-2x.png" width="152" />
        <!-- Spotlight Icon -->
        <icon height="40" src="res/icon/ios/icon-40.png" width="40" />
        <icon height="80" src="res/icon/ios/icon-40-2x.png" width="80" />
        <!-- iOS 6.1 -->
        <!-- iPhone / iPod Touch -->
        <icon height="57" src="res/icon/ios/icon-57.png" width="57" />
        <icon height="114" src="res/icon/ios/icon-57-2x.png" width="114" />
        <!-- iPad -->
        <icon height="72" src="res/icon/ios/icon-72.png" width="72" />
        <icon height="144" src="res/icon/ios/icon-72-2x.png" width="144" />
        <!-- iPhone Spotlight and Settings Icon -->
        <icon height="29" src="res/icon/ios/icon-29.png" width="29" />
        <icon height="58" src="res/icon/ios/icon-29-2x.png" width="58" />
        <!-- iPad Spotlight and Settings Icon -->
        <icon height="50" src="res/icon/ios/icon-50.png" width="50" />
        <icon height="100" src="res/icon/ios/icon-50-2x.png" width="100" />        
        <!-- iPhone and iPod touch -->
        <splash height="480" src="res/screen/ios/screen-iphone-portrait.png" width="320" />
        <splash height="960" src="res/screen/ios/screen-iphone-portrait-2x.png" width="640" />
        <!-- iPhone 5 / iPod Touch (5th Generation) -->
        <splash height="1136" src="res/screen/ios/screen-iphone-portrait-568h-2x.png" width="640" />
        <splash height="640" src="res/screen/ios/screen-iphone-landscape-568h-2x.png" width="1136" />
        <!-- iPhone 6 -->
        <splash height="1334" src="res/screen/ios/screen-iphone-portrait-667h-2x.png" width="750" />
        <splash height="2208" src="res/screen/ios/screen-iphone-portrait-736h-3x.png" width="1242" />
        <splash height="1242" src="res/screen/ios/screen-iphone-landscape-736h-3x.png" width="2208" />
        <!-- iPad -->
        <splash height="1024" src="res/screen/ios/screen-ipad-portrait.png" width="768" />
        <splash height="768" src="res/screen/ios/screen-ipad-landscape.png" width="1024" />
        <!-- Retina iPad -->
        <splash height="2048" src="res/screen/ios/screen-ipad-retina-portrait.png" width="1536" />
        <splash height="1536" src="res/screen/ios/screen-ipad-retina-landscape.png" width="2048" />
    </platform>
```

Let me know if you need any other information.

**Comment by lavarith** [comment] 2016-05-05 01:17
It's worth noting that on a previous phonegap build, I had to copy the icon files to the root directory to get the upload to Apple to work. I haven't copied all the remaining files. Is it possible that the 180px icon isn't being utilized?

**Comment by lavarith** [comment] 2016-05-05 01:42
I didn't copy the 180 px icon to the root directory because there wasn't an error or warning.

**Comment by macdonst** [comment] 2016-05-26 17:31
@lavarith did you get this sorted out? On my iPhone 6+ it does show up with the correct icon but I'm not sure about going through PGB.

**Comment by lavarith** [comment] 2016-05-26 18:20
No I didn't. It only shows correctly on the apple watch (which I assume is showing the phone icon).

**Comment by oscarabilleira** [comment] 2016-06-22 19:20
The same problem here...  in iphone6+ and cli-6.1.0 in phonegap build, phonegap icon is show

**Comment by vtellez** [comment] 2016-06-23 18:22
I am using this icons and splash screens in my config.xml, icons are displaying ok in all devices:

```
<!-- icons -->
        <icon src="res/theme/iOS/Resources/icons/Icon.png" width="57" height="57" />
        <icon src="res/theme/iOS/Resources/icons/Icon-72.png" width="72" height="72" />
        <icon src="res/theme/iOS/Resources/icons/Icon@2x.png" width="114" height="114" />
        <icon src="res/theme/iOS/Resources/icons/Icon-72@2x.png" width="144" height="144" />
        <icon src="res/theme/iOS/Resources/icons/Icon-76.png" width="76" height="76"/>
        <icon src="res/theme/iOS/Resources/icons/Icon-120.png" width="120" height="120"/>
        <icon src="res/theme/iOS/Resources/icons/Icon-152.png" width="152" height="152"/>
        <icon src="res/theme/iOS/Resources/icons/Icon-180@3x.png" width="180" height="180" />
        <icon src="res/theme/iOS/Resources/icons/Icon-60.png" width="60" height="60" />
        <icon src="res/theme/iOS/Resources/icons/Icon-120.png" width="120" height="120" />
        <icon src="res/theme/iOS/Resources/icons/Icon-76.png" width="76" height="76" />
        <icon src="res/theme/iOS/Resources/icons/Icon-152.png" width="152" height="152" />
        <icon src="res/theme/iOS/Resources/icons/Icon-29.png" width="29" height="29" />
        <icon src="res/theme/iOS/Resources/icons/Icon-58.png" width="58" height="58" />
        <icon src="res/theme/iOS/Resources/icons/Icon-40.png" width="40" height="40" />
        <icon src="res/theme/iOS/Resources/icons/Icon-80.png" width="80" height="80" />
        <!-- Splash -->
        <splash src="res/theme/iOS/Resources/splash/Default-iphone.png" platform="ios" width="320" height="480" />
        <splash src="res/theme/iOS/Resources/splash/Default@2x-iphone_640x960.png" platform="ios" width="640" height="960" />
        <splash src="res/theme/iOS/Resources/splash/Default-568h@2x-iphone_640x1136.png" platform="ios" width="640" height="1136" />
        <splash src="res/theme/iOS/Resources/splash/Default-750@2x-iphone6-portrait_750x1334.png" platform="ios" width="750" height="1334" />
        <splash src="res/theme/iOS/Resources/splash/Default-1242@3x-iphone6s-portrait_1242x2208.png" platform="ios" width="1242" height="2208" />
        <splash src="res/theme/iOS/Resources/splash/Default-Portrait-ipad_768x1024.png" platform="ios" width="768" height="1024" />
        <splash src="res/theme/iOS/Resources/splash/Default-Portrait@2x-ipad_1536x2048.png" platform="ios" width="1536" height="2048" />
        <splash src="res/theme/iOS/Resources/splash/Default-1242@3x-iphone6s-landscape_2208x1242.png" platform="ios" width="2208" height="1242" />
        <splash src="res/theme/iOS/Resources/splash/Default-Landscape-ipad_1024x748.png" platform="ios" width="1024" height="768" />
        <splash src="res/theme/iOS/Resources/splash/Default-Landscape@2x-ipad_2048x1536.png.png" platform="ios" width="2048" height="1536" />
```

**Comment by oscarabilleira** [comment] 2016-06-23 21:29
vtellez are you using  cli-6.1.0 version?

**Comment by vtellez** [comment] 2016-06-24 08:21
Yes, I am using cli-6.1.0 version

**Comment by oscarabilleira** [comment] 2016-06-24 09:45
Thanks I will try to use the exact names for files like you... Are you using version 1.7.1 of this plugin?

**Comment by vtellez** [comment] 2016-06-24 09:50
Yes, the last version of this plugin. This is my config.xml declaration:  

```
  <gap:plugin name="phonegap-plugin-push" source="npm">
        <param name="SENDER_ID" value="xxxx" />
    </gap:plugin>
```

**Comment by oscarabilleira** [comment] 2016-06-24 09:52
Thanks again... I think that the problem is here

  <icon src="images_ios/icons/ios/Icon-72@2x.png"   platform="ios" width="144" height="144" />

In my config.xml file is not present this icon... I will try if this solve the problem

**Comment by dagmawim** [comment] 2016-08-26 13:20
@oscarabilleira did you ever find the fix for this issue?

**Comment by dagmawim** [comment] 2016-09-09 18:56
@sergioaok The issue for us was a missing 86 X 87 icon. I think it was the Icon-29@3x.png. Hopefully, this helps

**Comment by sergioaok** [comment] 2016-09-09 18:58
@dagmawim thank you so much! You are amazing!

**Comment by postersw** [comment] 2017-03-22 16:45
Did you ever get PhoneGap Build to pick up the 180x180 icon for IOS (AppIcon60x60@3x)?  
Using PGB with CLI 6.5.0, that icon always shows up as ALL BLACK in the .ipa file that PGB generates, even though it shows correctly (as a small map) in the www/res/icon/ios  folder
![image](https://cloud.githubusercontent.com/assets/16981508/24209549/d9fc2fec-0ee3-11e7-9b0c-306d079a2327.png)

In my config.xml I have 
` <icon src="www/res/icon/ios/icon-180.png"    width="180" height="180" />`
All my other 19 IOS icons show up correctly. 

To see the contents of the .ipa file, download it to your machine, change ipa to zip, and unzip it.  The build icons are under /Payload/appname.app/:
![image](https://cloud.githubusercontent.com/assets/16981508/24209389/521bd9b0-0ee3-11e7-8dea-5472b4d3c5e2.png)

**Comment by macdonst** [comment] 2017-06-28 19:38
the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.

**Closed by macdonst** 2017-06-28 19:38 UTC
Labels: ios, pgb
