### ISSUE TITLE
Unable to build android after updating to 1.4.0

### ISSUE THREAD

**Issue by satyapriya** [phonegap/phonegap-plugin-push#276] opened 2015-10-29 08:32 UTC
After updating to 1.4.0, Android build is breaking.

Below is my environment setup:
Android-support-library: 23.1
Android-support-repository: 24
Google-play-services: 27
Google-repository-version: 22
Android SDK tools: 24.4.1
Android SDK platform-tools: 23.0.1

Error screenshots

![screen shot 2015-10-29 at 1 45 26 pm](https://cloud.githubusercontent.com/assets/2866401/10813361/9fbcb120-7e44-11e5-9e43-ead9298a613d.png)
![screen shot 2015-10-29 at 1 45 08 pm](https://cloud.githubusercontent.com/assets/2866401/10813374/b75ee208-7e44-11e5-936e-925e7f338167.png)

**Comment by bau720123** [comment] 2015-10-29 08:35
hi @satyapriya 
the same as me
https://github.com/phonegap/phonegap-plugin-push/issues/273

maybe you can leave some message in my post

**Comment by affinionmobile** [comment] 2015-10-29 12:43
Exactly the same error for me.

**Comment by macdonst** [comment] 2015-10-29 14:04
Duplicate of #273 please comment on that issue.

**Closed by macdonst** 2015-10-29 14:04 UTC
Labels: duplicate
