### ISSUE TITLE
Cordova and PGB will all build fail that only in Android (1.4.0 version)

### ISSUE THREAD

**Issue by bau720123** [phonegap/phonegap-plugin-push#273] opened 2015-10-28 16:14 UTC
hi @macdonst 
I am using 1.4.0 version from npm
well...
Cordova and PGB will build fail that only in Android (1.4.0 version) (PGB cli-5.2.0 gradle，Cordova 5.3.3)

this is the PGB log
![pgb](https://cloud.githubusercontent.com/assets/5110085/10794833/cde91d0e-7dd1-11e5-990b-13abfbadb87e.jpg)

this is the Cordova log
![cordova](https://cloud.githubusercontent.com/assets/5110085/10794832/cde6543e-7dd1-11e5-94c4-fa259b207974.jpg)

**Comment by macdonst** [comment] 2015-10-28 16:24
@bau720123 this is a multi dex issue. What other plugins are you using as two of them are including Google Play Services.

**Comment by karser** [comment] 2015-10-28 16:33
I can confirm this issue. This exception throws even without other plugins installed.

**Comment by karser** [comment] 2015-10-28 16:38
As a workaround:
```
cordova plugin add phonegap-plugin-push@1.3.0
```

**Comment by QuentinFchx** [comment] 2015-10-28 16:38
+1 I had to downgrade too !

**Comment by macdonst** [comment] 2015-10-28 16:57
Can someone send me a link to a git repository with a simple app that reproduces this problem on PGB? I have uploaded my test app and it does build. Using the following preferences:

```
    <gap:plugin name="phonegap-plugin-push" source="npm" version="1.4.0"/>
    <preference name="android-minSdkVersion" value="14" /> 
    <preference name="android-build-tool" value="gradle" />
```

**Comment by bau720123** [comment] 2015-10-29 02:14
hi @macdonst 
I finally know what the problem is
it is the "cordova-plugin-googleplus" plugin problem
https://www.npmjs.com/package/cordova-plugin-googleplus

when in 1.3.0，we can use it together
but when in 1.4.0，it seem some conflict
```
<gap:plugin name="cordova-plugin-googleplus" source="npm" version="4.0.3">
 <param name="REVERSED_CLIENT_ID" value="your REVERSED_CLIENT_ID" />
</gap:plugin>
```

**Comment by macdonst** [comment] 2015-10-29 14:28
@bau720123 Yeah, I think you should open an issue for @EddyVerbruggen on the plugin. He's including a dependent plugin that pulls in Google Play Services but we should be using frameworks instead of dependent plugins. Based upon my reading of the plugin.xml for that plugin he's already aware but he could re-test on PGB.

@karser @QuentinFchx Do you have a different reproduction scenario than @bau720123? As I said, I uploaded a project to PGB and it built fine.

**Comment by EddyVerbruggen** [comment] 2015-10-29 14:32
@macdonst Exactly, I reverted back to the dependent framework last August because of a few issues related to failing PGB builds. Probably folks using an older Cordova version not supporting Gradle. I could swap them in again and ask users to upgrade their Cordova if needed. It's such a pain these Android dependencies. Especially on cloud build services..

**Comment by macdonst** [comment] 2015-10-29 14:35
@EddyVerbruggen yeah, it's a PITA. I think if you test again with PGB it now supports Gradle and the build using frameworks should work.

**Comment by karser** [comment] 2015-10-29 17:37
@macdonst I don't have cordova-plugin-googleplus installed.
In fact, phonegap-plugin-push@1.3.0 is working in my app.

**Comment by macdonst** [comment] 2015-10-29 18:17
@karser I understand but I need more info in order to debug your issue. Are you also seeing the same error as @bau720123? If so can you search your project to see if gcm.jar is still hanging around? That could cause the Dex issue.

**Comment by bau720123** [comment] 2015-10-30 02:47
hi @karser 
I know 1.3.0 is working in your app，but the issue is talking about "1.4.0"
well...if you are using 1.4.0 version
please use the Temporary way to solve the problem until maybe @EddyVerbruggen solve the issue
```
cordova plugin rm cordova-plugin-googleplus
cordova plugin rm cordova-plugin-googleplayservices
```
and rebuild it，Android will build success again

**Comment by karser** [comment] 2015-10-30 10:15
cordova plugin rm cordova-plugin-googleplus
Plugin "cordova-plugin-googleplus" is not present in the project. Converting value to "nl.x-services.plugins.googleplus" and trying again.
Plugin "cordova-plugin-googleplus" is not present in the project. See `cordova plugin list`.
➜  Observe git:(ionic) cordova plugin rm cordova-plugin-googleplayservices
Plugin "cordova-plugin-googleplayservices" is not present in the project. Converting value to "com.google.playservices" and trying again.
Plugin "cordova-plugin-googleplayservices" is not present in the project. See `cordova plugin list`.
➜  Observe git:(ionic) find ./**/gcm.jar
./platforms/android/libs/gcm.jar
./plugins/phonegap-plugin-push/src/android/libs/gcm.jar

**Comment by macdonst** [comment] 2015-10-30 14:02
@karser it appears when you upgraded to 1.4.0 that the gcm.jar was left around in the platforms directory. Remove the `./platforms/android/libs/gcm.jar`file and rebuild. You shouldn't get the double dex issue anymore. Let me know if that resolves it.

**Comment by karser** [comment] 2015-10-30 14:42
@macdonst you are right, it conflicts with another custom plugin.

**Comment by macdonst** [comment] 2015-10-30 14:52
@karser so your issue is resolved and I can close this?

**Closed** 2015-11-02 09:48 UTC
Labels: pgb, question

**Comment by bau720123** [comment] 2015-11-02 09:51
hi @macdonst
because this issue is not "phonegap-plugin-push" issue
so...close it first until maybe @EddyVerbruggen release a new version and I will try again at that moment
