### ISSUE TITLE
[Android 5.0] Notifications not getting through when app is not running

### ISSUE THREAD

**Issue by s4lesman** [phonegap/phonegap-plugin-push#748] opened 2016-03-23 16:15 UTC
### Expected Behaviour
 Showing a notification on the system panel.

### Actual Behaviour

   When the app is not running and I send a push notification through GCM, it gets to the phone but its rejected on logcat. Nothing happens.

#### Steps to Reproduce 

 force close the app and send a push notification on GCM.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
  Android 5.0
  Zenfone 2  ZE551ML (stock rom)

#### Cordova CLI version and cordova platform version

    cordova                              6.0.0
    platform android                     5.1.1

#### Plugin version

    phonegap-plugin-push  1.6.0

#### Sample Code that illustrates the problem

My server side GCM generation code (using gcm-node and coffeescript):

```
  sender = new gcm.Sender(settings.gcm.API_KEY)
  message = new gcm.Message()
  message.addData 'title', 'testing'
  message.addData 'message', 'some test msg'
  message.addData 'content-available', 1
  message.addData 'priority', 2
  receivers =
    registrationTokens: [...]
  sender.send message, receivers, callback
```
#### Logs taken while reproducing problem

```
I/GCM     (19955): GCM message com.app.test.mobile 0:1458748156761978%e60cf8f4f9fd7ecd
W/BroadcastQueue(  673): Reject to launch app com.app.test.mobile/10241 for broadcast: App Op 48
W/GCM-DMM (19955): broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.app.test.mobile (has extras) }

```

**Comment by macdonst** [comment] 2016-03-23 16:23
@s4lesman I believe it to be a duplicate of #158. Please add details to that issue.

**Closed by macdonst** 2016-03-23 16:23 UTC
Labels: duplicate
