### ISSUE TITLE
Error: Plugin PushPlugin failed to install.

### ISSUE THREAD

**Issue by ajinkyamarathe** [phonegap/phonegap-plugin-push#210] opened 2015-10-07 15:10 UTC
I got solution on deprecated plugins(PushPlugin). which works for me but 

i use this new(phonegap-plugin-push) i found this error.

cordova plugin add  link of  https://github.com/phonegap/phonegap-plugin-push#1.3.0

**Comment by macdonst** [comment] 2015-10-08 16:50
@ajinkyamarathe I don't understand what your problem is, please add more details.

**Comment by denistrofimov** [comment] 2015-10-08 19:22
```
Error during processing of action! Attempting to revert...
Failed to install 'phonegap-plugin-push':TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:439:13)
    at module.exports.framework.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:121:31)
    at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:72:25)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:591:20)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:340:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
```

**Comment by fredgalvao** [comment] 2015-10-08 20:26
Duplicate of https://github.com/phonegap/phonegap-plugin-push/issues/186. This is not a plugin error, but a cordova error. +1's are welcome [here](https://issues.apache.org/jira/browse/CB-9270).

**Closed by fredgalvao** 2015-10-08 20:26 UTC
