### ISSUE TITLE
Missing TypeScript definition for browser-Platform

### ISSUE THREAD

**Issue by wolfmarcel** [phonegap/phonegap-plugin-push#1841] opened 2017-07-07 16:34 UTC
### Expected Behaviour

.init method accept android,iOS,windows AND browser

### Actual Behaviour

only android, iOS and windows is possible

### Reproduce Scenario (including but not limited to)

Using index.d.ts for TypeScript-Support

#### Steps to Reproduce 

Try to call .init function

#### Platform and Version 

Browser

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
not needed

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.0.1
    cordova platform version android                     6.2.3

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.0.0 rc-5

#### Sample Code that illustrates the problem
let push = PushNotification.init({
      android: {
      },
      browser: {
        pushServiceURL: 'http://push.api.phonegap.com/v1/push'
      },
      ios: {
        alert: "true",
        badge: true,
        sound: 'false'
      },
      windows: {}
    });
#### Logs taken while reproducing problem

Argument of type '{ android: {}; browser: { pushServiceURL: string; }; ios: { alert: "true"; badge: true; sound: "f...' is not assignable to parameter of type 'InitOptions'. Object literal may only specify known properties, and 'browser' does not exist in type 'InitOptions'

**Comment by fredgalvao** [comment] 2017-07-07 19:50
We need to update that part too in the `.d.ts`. This is part/duplicate of #1536 (with helpfull details, thank you). Help is welcome ;).

**Closed by fredgalvao** 2017-07-07 19:50 UTC

**Comment by wolfmarcel** [comment] 2017-07-07 20:07
Thank you fredgalvao. Do you know a workaround how to get Push-Notifications working in browser till the TypeScript-Support is added for the new API  ?

**Comment by fredgalvao** [comment] 2017-07-07 20:12
Not really. If you're using typescript and weak object restrictions are in place (which seems like they are), then you either need to add it yourself, or wait until me or anyone else have the time to update/sync the type definitions.

Maybe (I can't test it right now) this will work:
```ts
let push = PushNotification.init(<PhonegapPluginPush.InitOptions>{
    android: {},
    browser: {
        pushServiceURL: 'http://push.api.phonegap.com/v1/push'
    },
    ios: {
        alert: "true",
        badge: true,
        sound: 'false'
    },
    windows: {}
});
```

**Comment by wolfmarcel** [comment] 2017-07-07 20:45
Thank you, unfortunately that didn't work (error: :Type '{ android: {}; browser: { pushServiceURL: string; }; ios: { alert: "true"; badge: true; sound: " cannot be converted to type 'InitOptions')
I will try to work on the TypeDefinition but I never did this before. If i find a solution I will contribute to this repo.
