### ISSUE TITLE
Custom notification sound in background mode?

### ISSUE THREAD

**Issue by sebrojas14** [phonegap/phonegap-plugin-push#17] opened 2015-06-18 23:56 UTC
Why I can't the app play a custom sound with the notification when is in background? I'm sending the sound name in the notification...I neither can make this to work in the previous version of the plugin.

I have beep.wav in my www folder. For Android I'm sending 'soundname': 'beep.wav' in the payload, and 'sound': 'beep.wav' for iOS

My code:

App:

    var push = PushNotification.init({
        "android": {
            "senderID": "..."//I put here my GCM senrder id
        },
        "ios": {}
    });

    push.on('registration', function(data) {
        // data.registrationId
        registerNotificationToken(data.registrationId, (window.device.platform == 'android' || device.platform == 'Android') ? 'Android' : 'iOS');
    });

    push.on('notification', function(data) {
        // data.message,
        // data.title,
        // data.count,
        // data.sound,
        // data.additionalData
        if (isLogedIn()) {
            
            if (window.device.platform == 'android' || device.platform == 'Android') {
                
                // if this flag is set, this notification happened while we were in the foreground.
                // you might want to play a sound to get the user's attention, throw up a dialog, etc.
                if ( data.additionalData.foreground )
                {
                    var my_media = new Media("/android_asset/www/" + data.sound);
                    my_media.play();
    
                    alertify.confirm('<p><strong>' + data.title + '</strong><p/><p>' + data.message + '</p><p>¿Desea verlo?</p>', function () {
    
                        location.hash = 'available-services\\' + data.additionalData.id;
                    });
                }
                // otherwise we were launched because the user touched a notification in the notification tray.
                else {   
                    //If app wasn't runing
                    if ( e.coldstart ) {
    
                        serviceId = data.additionalData.id;
                    }
                    else {
    
                        location.hash = 'available-services\\' + data.additionalData.id;
                    }
                }
            }
            else {
                
                if ( data.additionalData.alert ) {
                    
                    //do something with the push message. This function is fired when push message is received or if user clicks on the tile.
                    if (data.additionalData.foreground == 1) {
                        
                        alertify.confirm('<p><strong>' + data.title+ '</strong><p/><p>' + data.message + '</p><p>¿Desea verlo?</p>', function () {
                                         
                            location.hash = 'available-services\\' + data.additionalData.id;
                        });
                    }
                    else {
                        
                        location.hash = 'available-services\\' + data.additionalData.id;
                    }
                }
            
                if ( data.sound ) {
                    
                    //play notification sound. Ignore when app is in foreground.
                    var snd = new Media(data.sound);
                    snd.play();
                }
            }
        }

**Comment by sebrojas14** [comment] 2015-06-19 17:09
Anyone had the opportunity to test it? It's a bug or it's possible I'm doing something wrong?

**Comment by macdonst** [comment] 2015-07-01 01:49
@sebrojas14 root cause of the issue is sounds in the assets folder are private to the app and not accessible from the notification service.

**Comment by macdonst** [comment] 2015-07-01 02:44
@sebrojas14 So, I've been working on this a bit tonight. The sound file will need to get copied from the asset/www folder to the res/raw folder on Android in order to work. I will look at creating a hook for this soon and test on iOS as well.

**Comment by sebrojas14** [comment] 2015-07-01 13:28
I'm glad to know it, please let me know if you need anything, test on Andorid for example

**Comment by macdonst** [comment] 2015-07-02 19:52
@sebrojas14 if you pull the latest from this github repo then you can test. You have to put the sound file in the `platforms/android/res/raw` directory and when you send the push just use it's name, omit the extension.

**Comment by sebrojas14** [comment] 2015-07-03 03:18
I tried it but doesn't work. I put the beep.wav file in platforms/android/res/raw if I look into the apk file is in it. In the payload I sent 'soundname': 'beep'. Missing something?

**Comment by macdonst** [comment] 2015-07-06 15:18
@sebrojas14 sorry, did you pull from the issue17 branch?

**Comment by sebrojas14** [comment] 2015-07-06 17:15
Nooo, my bad. This afternoon I'm gonna try again, I need it so bad. What about iOS?

**Comment by macdonst** [comment] 2015-07-06 18:49
@sebrojas14 No, my bad. I forgot to mention the branch. I took a look at iOS and it _should_ work but I need to double check where the sound should be packaged on iOS.

**Comment by sebrojas14** [comment] 2015-07-06 18:51
Ok, let me know

**Comment by sebrojas14** [comment] 2015-07-07 06:01
It works on Android (OnePLus One, OxygenOS, Android 5.0.2, using a .wav audio)!! But the sound starts and starts again like half a second later (so is cropped and then it plays all). And in foreground is worst, starts over and over again

**Comment by sebrojas14** [comment] 2015-07-07 19:24
I'm gonna used in an app besides that. Please let me know when you know something about iOS

**Comment by macdonst** [comment] 2015-07-08 15:32
@sebrojas14 I'm testing on a Nexus 5 and Nexus 6 running Android 5.1.1 and can't reproduce.

**Comment by sebrojas14** [comment] 2015-07-16 22:31
What about iOS?

**Comment by macdonst** [comment] 2015-07-24 03:57
@sebrojas14 swinging back around to iOS tomorrow :)

**Comment by macdonst** [comment] 2015-07-24 20:59
@sebrojas14 I got a chance to test this and it works. If I do the following to generate a proper sound:

`afconvert /System/Library/Sounds/Submarine.aiff ~/Desktop/sub.caf -d ima4 -f caff -v`

and put the resulting `sub.caf` in the root of my Xcode project then send the following push:

```
{
    "aps": {
        "alert": "test sub", 
        "sound": "sub.caf"
    }
}
```

I hear the correct sound.

See this link for more info: https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/IPhoneOSClientImp.html#//apple_ref/doc/uid/TP40008194-CH103-SW6

**Comment by macdonst** [comment] 2015-07-24 21:56
Merged the fix

**Closed by macdonst** 2015-07-24 21:56 UTC
Labels: bug

**Comment by alexislg2** [comment] 2015-09-10 04:05
What do you mean "put the resulting sub.caf in the root of my Xcode project". In the directory /platforms/ios/ ? or /platforms/ios/project_name/ ? Or inside the xcode project tree? 

Documentation is not so clear about it, neither about if we have to pass `sound.mp3` or `sound` as a payload. I'll make a PR for the doc if I got a chance to make it work!

**Comment by macdonst** [comment] 2015-09-10 15:16
@alexislg2 It would be `/platforms/ios`. If you see the above comment you are supposed to supply an extension. Also, .mp3 may not work. Check the https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/IPhoneOSClientImp.html#//apple_ref/doc/uid/TP40008194-CH103-SW6 link for information on what file types iOS supports.

**Comment by alexislg2** [comment] 2015-09-11 05:52
Thanks. In fact what I didn't get was that I have to drag and drop the file
inside the Xcode project
It's working now

**Comment by dbadb** [comment] 2016-09-19 18:19
Here we are in Sep 2016 and this issue raises its ugly head again :-)

I have working files residing here: "www/snd/beep.caf".  I'm referencing these files from the APN  server with the same relative path in the notification payload.  These work on IOS 9 but not on IOS 10.0.1 (from the same build!).  Either its a new behavior triggered by compat layers in IOS 10 or its a bug in IOS 10.   Here's a thread: http://stackoverflow.com/questions/39400703/ios10-custom-push-notification-sound-not-playing.  My impression is that it's not as straightforward as the answer suggests.  That is,  the claim there is that it's an xcode 8 bug.

I'm not confident that the relative path references should be expected to work or fail (though they work on iOS 9)  and welcome any thoughts/comments on this matter.,

**Comment by abdohossam5** [comment] 2016-09-24 14:05
same issue here with ios 10

Using version 1.8.2 of the plugin and testing on iphone 6s. sound was working fine on ios 9 and even on ios 10 when running the app using cordova run ios. The issue only occurs when running with xcode not sure about the store version yet.
