### ISSUE TITLE
Migrate to Firebase Cloud Messaging

### ISSUE THREAD

**Issue by macdonst** [phonegap/phonegap-plugin-push#929] opened 2016-05-25 14:04 UTC
Google is moving from GCM to FCM and this plugin should follow suit. 

https://developers.google.com/cloud-messaging/android/android-migrate-fcm

I may end up supporting a 1.x and 2.x stream where the 2.x stream is FCM as it will be awhile before everyone can update to using FCM.

**Comment by skyprimer** [comment] 2016-05-26 12:50
Great.! we are following the topic...

**Comment by getqd** [comment] 2016-05-26 17:42
Same. Looking forward to integrating FCM into our apps!

**Comment by Maximvdw** [comment] 2016-05-27 19:57
+1

**Comment by lorenzob-incomedia** [comment] 2016-05-31 06:38
+1

**Comment by raphaguasta** [comment] 2016-06-02 04:46
Great!! Thanks for this!

**Comment by JeremyColton** [comment] 2016-06-02 08:00
FCM makes iOS APNS obsolete since FCM is reliable and free?

**Comment by sn0w** [comment] 2016-06-03 10:58
+1

Any ETA on this?

**Comment by zishon89us** [comment] 2016-06-06 16:19
+1

waiting for it , http://stackoverflow.com/questions/37653251/firebase-cloud-messaging-with-ionic-app/

**Comment by lukebpowell** [comment] 2016-06-06 16:33
+1

**Comment by srikantk** [comment] 2016-06-07 06:43
+1

**Comment by vasanthns** [comment] 2016-06-07 13:26
+1 following..

**Comment by lurainsin** [comment] 2016-06-08 07:16
+1
I'm looking forward to use FCM in my new app!

**Comment by kumpanen** [comment] 2016-06-08 08:12
+1

**Comment by MaximKipot** [comment] 2016-06-08 09:18
+1. 
really excited about that!

**Comment by JeremyColton** [comment] 2016-06-08 10:15
Please stop adding "+1" - you are spamming everyone!  Just click the "subscribe" button on the right-hand-side!

**Comment by GitFr33** [comment] 2016-06-09 20:12
I am just getting started with push notifications. Would you advise going ahead and setting up GCM and migrating later, or waiting until FCM is supported?

**Comment by GrzegorzWarzecha** [comment] 2016-06-13 14:12
+100!

**Comment by ktzanettis** [comment] 2016-06-14 08:17
Anyone know when this issue will be committed?

**Comment by jcesarmobile** [comment] 2016-06-14 08:39
When? once it's ready

**Comment by macdonst** [comment] 2016-06-14 12:39
@ktzanettis you can always help out by testing the v2.0.x branch or submitting a PR.

**Comment by glasset** [comment] 2016-06-27 06:56
I have tested on v2.0.x(07fa81) currently works fine (tested only fcm feature), if something bad happen i will report

**Comment by stephan-nordnes-eriksen** [comment] 2016-06-28 07:09
@glasset Great to hear! I would like to try it out and help if possible. Is the setup any different than gcm?

**Comment by glasset** [comment] 2016-06-28 18:18
@stephan-nordnes-eriksen yes same as gcm setup.

**Comment by neosekar** [comment] 2016-06-29 11:48
how to install the v2.0.x using cordova command ?

**Comment by glasset** [comment] 2016-06-29 12:19
`cordova plugin add https://github.com/phonegap/phonegap-plugin-push\\#b451b55134f716fcf172ec51d8fcfa2e4e6c32d1`   

`b451b55134f716fcf172ec51d8fcfa2e4e6c32d1` is the last commit on v2.0.x

**Comment by neosekar** [comment] 2016-06-29 13:06
If i run this command , i got the error like

**error: Failed to fetch plugin https://github.com/phonegap/phonegap-plugin-push\ via git.
Either there is a connection problems, or plugin spec is incorrect:
	Error: git: Command failed with exit code 128 Error output:
Cloning into '/tmp/git/1467205453431'...
fatal: unable to access 'https://github.com/phonegap/phonegap-plugin-push\/': The requested URL returned error: 400**

**Comment by neosekar** [comment] 2016-06-29 13:19
It is my mistake i just removed the slash before **#** sysmbol now  it works

**Comment by pleivac** [comment] 2016-06-29 16:04
The way I installed this was `cordova plugin add https://github.com/phonegap/phonegap-plugin-push.git#v2.0.x --variable SENDER_ID="XXXXXXXXX"`.

**Comment by wilsonpinto360** [comment] 2016-06-29 16:13
Meanwhile there is a great fcm notifications implementation that it's working, [cordova-plugin-fcm](https://github.com/fechanique/cordova-plugin-fcm) by @fechanique

**Comment by neosekar** [comment] 2016-06-30 09:59
cordova-plugin-fcm is build failed . it shows,
**> Could not find com.google.firebase:firebase-core:9.0.0.**

**Comment by neosekar** [comment] 2016-06-30 10:03
pushv2.0.x is working in android but in ios it shows **invalidRegistration** error

**Comment by wilsonpinto360** [comment] 2016-06-30 10:08
@neosekar [https://www.npmjs.com/package/cordova-plugin-fcm](https://www.npmjs.com/package/cordova-plugin-fcm) check **Android compilation details** and **iOS compilation details**

**Comment by skyprimer** [comment] 2016-06-30 13:13
What is the exact git url for config.xml to test it v2.0 via Phonegap Build?

**Comment by lukebpowell** [comment] 2016-07-05 22:42
@skyprimer this commit works for both iOS and Android.  Make sure to add your SENDER_ID.  
From the command line:
`cordova plugin add https://github.com/phonegap/phonegap-plugin-push#07fa81b7a3a62400915ac70b9a24a802465a6f95 --variable SENDER_ID="XXXXXXX"`

Or add this to your config.xml file, then rebuild your ios and android builds:
`<plugin name="phonegap-plugin-push" spec="https://github.com/phonegap/phonegap-plugin-push#07fa81b7a3a62400915ac70b9a24a802465a6f95">`
  `<variable name="SENDER_ID" value="XXXXXXX" />`
`</plugin>`

**Comment by neosekar** [comment] 2016-07-06 04:40
Is it implemented for ios ?

**Comment by skyprimer** [comment] 2016-07-06 08:38
I've already tried that with sender ID strange but today i got no error on IOS. Android has errors on build..

**Comment by pierreNeck** [comment] 2016-07-06 15:34
I have this error with Ionic+crosswalk, with the version @lukebpowell 

:transformClassesWithDexForArmv7Debug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/FirebaseException;
 FAILED

BUILD FAILED

Total time: 50.554 secs
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForArmv7Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_73\bin\java.exe'' finished with non-zero exit value 2

**Comment by stephan-nordnes-eriksen** [comment] 2016-07-07 13:41
@pierreNeck: You probably have a mismatch with the google play services version and the firebase version. If you have google play services v31 you need firebase 9.2.0. 

Google play services you can find in your sdk manager. Firebase version you find in your app in `build.gradle`

**Comment by rezozo** [comment] 2016-07-21 20:10
+1

**Comment by escolhatecnologia** [comment] 2016-07-23 17:42
+1

**Comment by jcesarmobile** [comment] 2016-07-23 18:28
please, don´t +1, github added the reactions so you can +1 with the thumbs up instead of writing a comment

BTW, you can test v.2.0.x branch of the plugin that has FCM support, but it's untested, so if you install it and give feedback will be more helpful that +1s

**Comment by ktzanettis** [comment] 2016-08-26 13:37
I have downloaded the latest commit and trying to make my android project to receive notifications using FCM. The FCM registration token is produced but the notification is not sent. Is there any use of the SENDER_ID used with GCM? I noticed this line in the PushPlugin: token = FirebaseInstanceId.getInstance().getToken(senderID,FCM);

Thank you

**Comment by jcesarmobile** [comment] 2016-08-29 15:22
Yes, the SENDER_ID is still used with FCM. Not sure if it changes if you migrate an existing GCM project to be a FCM project, can you check your firebase console?

**Comment by Telemakhos** [comment] 2016-09-30 11:28
Who's testing the 2.0 branch and what are the thoughts about stability? it'd be great to have some feedback.. =)

**Comment by wparad** [comment] 2016-10-01 16:32
I've been using this for GCM on android and ios (sending through AWS).  The documentation on send GCM is really bad, so it was pretty confusing.  If you want I can share some quirks.  I have it working for the most part.  The biggest problem is that if I don't init and register the plugin early enough, then I don't receive coldstart or background notifications on android (on confirmed on ios).

**Comment by edtiley** [comment] 2016-10-04 01:18
My wasn't that responsive!

Never mind, I won't ask anything again

**Comment by dannywillems** [comment] 2016-10-10 11:15
Any new about the migration? I don't see any new commits on branch `v2.0.x` or `FCM`.

**Comment by Telemakhos** [comment] 2016-10-10 16:53
@dannywillems looks like the development has stalled.. In our case we've switched to this other [FCM plugin](https://github.com/fechanique/cordova-plugin-fcm) which is gaining momentum now and works for us...

**Comment by dannywillems** [comment] 2016-10-11 09:15
@Telemakhos Thanks for your comment. We hesitated to migrate to this plugin.

**Comment by jcesarmobile** [comment] 2016-10-13 08:53
I was asked by mail about the FCM status, so I'm answering here too mostly the same:

I don't use FCM on any real project, so it's hard for me to find real issues while using it. 
Last time I worked on it, I was able to receive push from FCM on both iOS and Android.

People is not opening issues about `v2.0.x` branch, so that can mean that it has no issues or people is not using it. 
I don't think `v2.0.x` is perfect and it has probably issues, but if I don't see the issues I can't fix them. 
So, if it has issues but they are not reported it's because people is not using it.

What can you do? 
Test `v.2.0.x` and report issues so we can fix them
If you don't want to test it, you can switch to another plugin like the one mentioned on previous messages, but at least if you find issues on it, report them.

**Comment by dannywillems** [comment] 2016-10-13 09:15
@jcesarmobile Thanks for your answer!

**Comment by dannywillems** [comment] 2016-10-13 09:21
@jcesarmobile Do you think it's possible to rebase `v.2.0.x` branch with the master branch? I think it would help people to know FCM is WIP and get all fixes since June.
It's a great job, thanks.

**Comment by dannywillems** [comment] 2016-10-13 14:03
@jcesarmobile It seems it doesn't work for iOS for me. I created a project in the firebase console and add an Android and iOS application. I downloaded `GoogleService-Info.plist` and put it in the root project (in XCode). No error appears in XCode, no error from Google response but no notification appears on iOS.

For Android it's working, even if I didn't add `google-services.json` in the Android project.

**Comment by jcesarmobile** [comment] 2016-10-13 14:10
You have to put the `GoogleService-Info.plist` on the root of the Cordova project, not on the Xcode project. It will be copied with the hook https://github.com/phonegap/phonegap-plugin-push/blob/v2.0.x/plugin.xml#L135

**Comment by dannywillems** [comment] 2016-10-13 14:54
@jcesarmobile It's the same problem. No notification appear on iOS.

I use the firebase console, not the google console to upload the file. It's OK no?

**Comment by jcesarmobile** [comment] 2016-10-13 15:19
Yes, you have to use firebase console
Did you pass senderID on the iOS init?
I think it's better if you create a new issue sharing some code and telling you are using v2.0.x branch

**Comment by dannywillems** [comment] 2016-10-13 16:26
@jcesarmobile See #1287

**Comment by loredanAdrian** [comment] 2016-10-24 18:13
Any help [1315](https://github.com/phonegap/phonegap-plugin-push/issues/1315) ?

**Comment by grapemix** [comment] 2016-10-27 06:28
@jcesarmobile 
If you want a beta tester, we can help. When we tried to install the plugin via `ionic plugin add https://github.com/phonegap/phonegap-plugin-push#v2.0.x --variable SENDER_ID=API_KEY` and compile via `ionic run android` 

we got:

Dex: Error converting bytecode to dex:

Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)

        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)

        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
        at com.android.dx.command.dexer.Main.run(Main.java:246)

        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)
    

:transformClassesWithDexForArmv7Debug FAILED



FAILURE: Build failed with an exception.



* What went wrong:

Execution failed for task ':transformClassesWithDexForArmv7Debug'.

> 
com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-7-openjdk-amd64/bin/java'' finished with non-zero exit value 2


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
 option to get more log output.


BUILD FAILED

Total time: 32.874 secs

Error: /PROJ_ROOT/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
        at com.android.dx.command.dexer.Main.run(Main.java:246)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)
    

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForArmv7Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-7-openjdk-amd64/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

For iOS, we imagine there will be a lot of problem too.

So, any ideas?

**Comment by zhkuskov** [comment] 2016-10-27 07:57
Hi, please help me: where get the Sender_id in Firebase console? Is it the Api_Key? Thanks! And sorry for my english

**Comment by zhkuskov** [comment] 2016-10-27 08:41
i found sender_id in fcm - just number of project
plugin installed on android 6 and initialized correctly

**Comment by zhkuskov** [comment] 2016-10-27 08:45
tried to send msg from firebase console - its worked! thank you:)

**Comment by zhkuskov** [comment] 2016-10-27 10:46
Hi,
on Android 6: Sound does not work when you receive a message and does not work vibration

**Comment by zhkuskov** [comment] 2016-10-27 10:51
Here is the text of the log to the previous my post:

10-27 13:46:59.664 20050 20050 I chromium: [INFO:CONSOLE(66)] "Uncaught TypeError: push.hasPermission is not a function", source: file:///android_asset/www/js/my-app.js (66)
10-27 13:46:59.674 20050 20136 V PushPlugin: execute: action=init
10-27 13:46:59.677 20050 21622 V PushPlugin: execute: data=[{"android":{"senderID":"735464285637","sound":"true","vibrate":"true","forceShow":"true"},"browser":{"pushServiceURL":"http:\/\/push.api.phonegap.com\/v1\/push"},"ios":{"alert":"true","badge":"true","sound":"true"},"windows":{}}]
10-27 13:46:59.677 20050 21622 V PushPlugin: execute: jo={"senderID":"735464285637","sound":"true","vibrate":"true","forceShow":"true"}
10-27 13:46:59.677 20050 21622 V PushPlugin: execute: senderID=735464285637
10-27 13:46:59.680 20050 21622 V PushPlugin: onRegistered: {"registrationId":"ezQpQZhTeMU:APA91bHX1hm_RNRdvbUr1yC9U-OG_oTaU8vynG0XylGI-WQfUfJpkzltpMsc8ILewksONFEJSIIZKglQjc0w20cwkjC07h9zs0dvukRPgQFa62UrFlzWNJxxngDkIRYw"}
10-27 13:46:59.684 20050 21622 D PushPlugin: no icon option
10-27 13:46:59.684 20050 21622 D PushPlugin: no iconColor option

**Comment by zhkuskov** [comment] 2016-10-27 17:09
not working subscription to a topic:

10-27 20:05:37.571 15664 15664 I chromium: [INFO:CONSOLE(74)] "Uncaught TypeError: push.subscribe is not a function", source: file:///android_asset/www/js/my-app.js (74)

**Comment by zhkuskov** [comment] 2016-10-27 19:18
sound and vibration work - I tested out firebase console. There sound turned off by default. When a message is sent from the server - it works

**Comment by MELAS007** [comment] 2016-11-05 23:50
HI,

I just run and found this issues...

```
:transformClassesWithDexForDebug
 FAILED



FAILURE: Build failed with an exception.



* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/FirebaseException;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


BUILD FAILED

Total time: 1 mins 46.168 secs

Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/FirebaseException;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```
i don't knoow what i missed?

any help will be appreciated!

**Comment by jcesarmobile** [comment] 2016-11-06 00:10
are you using any other plugin that uses firebase?

**Comment by MELAS007** [comment] 2016-11-06 00:20
jcesarmobile - no, i don't...

**Comment by wparad** [comment] 2016-11-06 06:54
@Melase007 please move your debug files to a gistp

The problem is that all the google libs must be the same version.  Cherk your jar lib dilectory (you are just search for the jars in the diroctory structure) and make sure all the google anes are the same.

You absolutely are using other google libs, based on the plugin list you showed.  The solution is to update your build-extras.gradle file to force the correct versions of those libraries.

**Comment by MELAS007** [comment] 2016-11-06 07:09
@wparad - Could you tell me how to move on gistp?

**Comment by MELAS007** [comment] 2016-11-06 09:10
@wparad - Where is the build-extras.gradle path? i can't find it. how did you get jars' list?

**Comment by wparad** [comment] 2016-11-06 09:21
Correction, that would be gist.

**Comment by MELAS007** [comment] 2016-11-06 09:30
@wparad - Sorry i use ionic frameworks! how can i do it ?

**Comment by wparad** [comment] 2016-11-06 09:45
and in cordova the build-extra.gradle is a custom file you create which has
to be put in the `platforms/android` directory.  I copy it in with a hook.
I have an example of one:
https://github.com/wparad/cordova-angular-example/blob/master/hooks/copy_gradle.js

To find all the jar files in a directory (recursive) I ran this:
```
find . -iname "*.jar"
```

**Comment by wparad** [comment] 2016-11-06 09:47
the framework you are using shouldn't matter, at the end of the day there will be some jar files pulled into your app.  I'm not sure if iconic has a gradle addition strategy, but first finding the contention and then fixing it is important.  Although that isn't something that can be resolved by this plugin.  You can follow my instructions to find the contention, but resolving it will be another matter.  Posting on the iconic forums would probably be the next step.

**Comment by MELAS007** [comment] 2016-11-06 10:04
@wparad - it update to 9.4.0 but unfortunately it stopped on :mergeDebugResources
it doesn't continue!!:( is it normal?

**Comment by MELAS007** [comment] 2016-11-06 11:05
@wparad - i deleted and build platform again then i did with build-extras.gradle...
i run it then it gave me another errors in below:


```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.pro                                                                                                                cess.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.                                                                                                                DexException: Multiple dex files define Lcom/google/ads/AdRequest$ErrorCode;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug                                                                                                                 option to get more log output.


BUILD FAILED

Total time: 1 mins 49.915 secs

Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.pro                                                                                                                cess.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.                                                                                                                DexException: Multiple dex files define Lcom/google/ads/AdRequest$ErrorCode;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug                                                                                                                 option to get more log output.

```

and my jars:

```
./platforms/android/build/intermediates/exploded-aar/android/CordovaLib/unspecif                                                                                                                ied/debug/jars/classes.jar
./platforms/android/build/intermediates/exploded-aar/com.android.support/support                                                                                                                -v13/23.4.0/jars/classes.jar
./platforms/android/build/intermediates/exploded-aar/com.android.support/support                                                                                                                -v13/23.4.0/jars/libs/internal_impl-23.4.0.jar
./platforms/android/build/intermediates/exploded-aar/com.android.support/support                                                                                                                -v4/23.4.0/jars/classes.jar
./platforms/android/build/intermediates/exploded-aar/com.android.support/support                                                                                                                -v4/23.4.0/jars/libs/internal_impl-23.4.0.jar
./platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play                                                                                                                -services-ads/9.4.0/jars/classes.jar
./platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play                                                                                                                -services-ads-lite/9.4.0/jars/classes.jar
./platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play                                                                                                                -services-analytics/9.4.0/jars/classes.jar
./platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play                                                                                                                -services-analytics-impl/9.4.0/jars/classes.jar
./platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play                                                                                                                -services-base/9.4.0/jars/classes.jar
./platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play                                                                                                                -services-basement/9.4.0/jars/classes.jar
./platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play                                                                                                                -services-clearcut/9.4.0/jars/classes.jar
./platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play                                                                                                                -services-gass/9.4.0/jars/classes.jar
./platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play                                                                                                                -services-tasks/9.4.0/jars/classes.jar
./platforms/android/build/intermediates/exploded-aar/com.google.firebase/firebas                                                                                                                e-common/9.4.0/jars/classes.jar
./platforms/android/build/intermediates/exploded-aar/com.google.firebase/firebas                                                                                                                e-iid/9.4.0/jars/classes.jar
./platforms/android/build/intermediates/exploded-aar/com.google.firebase/firebas                                                                                                                e-messaging/9.4.0/jars/classes.jar
./platforms/android/build/intermediates/exploded-aar/me.leolin/ShortcutBadger/1.                                                                                                                1.4/jars/classes.jar
./platforms/android/build/intermediates/pre-dexed/debug/com.android.support-supp                                                                                                                ort-v13-23.4.0_2cc5a1d29e4a6e36d04a1662961037366652aeef.jar
./platforms/android/build/intermediates/pre-dexed/debug/com.android.support-supp                                                                                                                ort-v4-23.4.0_cbaa808c9d859b1f826ab23dabb09f2f3ead5588.jar
./platforms/android/build/intermediates/pre-dexed/debug/com.google.android.gms-p                                                                                                                lay-services-ads-9.4.0_e30caa246363a48205654b7f087c488cab2372c0.jar
./platforms/android/build/intermediates/pre-dexed/debug/com.google.android.gms-p                                                                                                                lay-services-ads-lite-9.4.0_bf86e49ee0eb0b41bfd8ac538f841b9f1651be10.jar
./platforms/android/build/intermediates/pre-dexed/debug/com.google.android.gms-p                                                                                                                lay-services-analytics-9.4.0_26934e7148c3f9b671f993eb2a9a900d03ac7933.jar
./platforms/android/build/intermediates/pre-dexed/debug/com.google.android.gms-p                                                                                                                lay-services-analytics-impl-9.4.0_c46d36a6b2adb22029349bb2b4c185c2987f4508.jar
./platforms/android/build/intermediates/pre-dexed/debug/com.google.android.gms-p                                                                                                                lay-services-base-9.4.0_98a49072ba61c4aadf3d6f1c6bed0bd5f69f65e5.jar
./platforms/android/build/intermediates/pre-dexed/debug/com.google.android.gms-p                                                                                                                lay-services-basement-9.4.0_8c93b6a79dad86778d13bcc4a87e3802ec1a3ae1.jar
./platforms/android/build/intermediates/pre-dexed/debug/com.google.android.gms-p                                                                                                                lay-services-clearcut-9.4.0_d4b23aa151b49741d33c7daec602c026b97d02f7.jar
./platforms/android/build/intermediates/pre-dexed/debug/com.google.android.gms-p                                                                                                                lay-services-gass-9.4.0_4b607b5dd9e923892ed2ec927886e360053908d2.jar
./platforms/android/build/intermediates/pre-dexed/debug/com.google.android.gms-p                                                                                                                lay-services-tasks-9.4.0_8db92cb246397141ef97074a93b5a3bfadeb1847.jar
./platforms/android/build/intermediates/pre-dexed/debug/com.google.firebase-fire                                                                                                                base-common-9.4.0_2e260d15a98c17d5973b5d7e2350e180043b1966.jar
./platforms/android/build/intermediates/pre-dexed/debug/com.google.firebase-fire                                                                                                                base-iid-9.4.0_003018b91f7ac39d2218e27bddaa445a3b340de8.jar
./platforms/android/build/intermediates/pre-dexed/debug/com.google.firebase-fire                                                                                                                base-messaging-9.4.0_9c2278708cfb19a7e639a54a11545a1f86419762.jar
./platforms/android/build/intermediates/pre-dexed/debug/cordova-generic-ad_cfbb0                                                                                                                5bf62d9e03950d06f1106a94c4e6509eb46.jar
./platforms/android/build/intermediates/pre-dexed/debug/CordovaLib-unspecified-d                                                                                                                ebug_ba725996bb03c6b768c81e9d9524c5af1f2120c4.jar
./platforms/android/build/intermediates/pre-dexed/debug/debug_78e949d248b7f5236e                                                                                                                9372d2175566cd5c0af1b2.jar
./platforms/android/build/intermediates/pre-dexed/debug/google-play-services_a6d                                                                                                                d384903a38718f1d1e7030e9622df5113dc4d.jar
./platforms/android/build/intermediates/pre-dexed/debug/internal_impl-23.4.0_5e8                                                                                                                887f05ecaa6027b5041ecfb6bafc79ebc3e5c.jar
./platforms/android/build/intermediates/pre-dexed/debug/internal_impl-23.4.0_d73                                                                                                                75e7b70e8e8160186dc7c4790794967841bf9.jar
./platforms/android/build/intermediates/pre-dexed/debug/me.leolin-ShortcutBadger                                                                                                                -1.1.4_7c07cf83a4918b68335a22d00110197ac750b95d.jar
./platforms/android/build/intermediates/pre-dexed/debug/support-annotations-23.4                                                                                                                .0_e0f831b58169b0028caddb502c00decf24a567ef.jar
./platforms/android/CordovaLib/build/intermediates/bundles/debug/classes.jar
./platforms/android/CordovaLib/build/intermediates/bundles/release/classes.jar
./platforms/android/gradle/wrapper/gradle-wrapper.jar
./platforms/android/libs/cordova-generic-ad.jar
./platforms/android/libs/google-play-services.jar
./plugins/cordova-plugin-extension/src/android/cordova-generic-ad.jar
./plugins/cordova-plugin-googleplayservices/google-play-services.jar

```

**Comment by wparad** [comment] 2016-11-06 12:54
If I had to guess the problem is that you have both of these:
* ./platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play-services-ads/9.4.0/jars/classes.jar pulled in by `cordova-plugin-admobpro`
* ./platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play-services-ads-lite/9.4.0/jars/classes.jar pulled in by unknown`

Try removing the plugins one at a time (and cleaning the /platforms/android/build/ directory), to find the plugins which conflict.  You can also try expliciting excluding the lite version from your build by updating the gradle file.

Also remove `cordova-plugin-googleplayservices` that shouldn't be included by you directly.

As this is an issue with the ads' dependency and not with this specific version of this plugin, would you be able to open a new issue if the problem persists after the following the above steps?

**Comment by MELAS007** [comment] 2016-11-06 14:31
@wparad - If i am correct, i will delete admobpro, analyticsm google play services then remove platforms and re-build platform right?

**Comment by MELAS007** [comment] 2016-11-07 08:37
@wparad - I restart a new project it works, i got the registrationID but when i send notification from FCM it doesn't appear on my device... do you know why?

**Comment by Assylkhan** [comment] 2017-01-04 09:49
Hi MELAS007. Did you solve the issue? I am in the same situation.

**Comment by TheRealKira** [comment] 2017-01-24 00:49
@Assylkhan make sure the package name of your app matches the one in FCM, I had that issue and didn't realize it matters to FCM.

**Comment by sam2x** [comment] 2017-03-20 16:07
Hey, any ETA on this ? is firebase-analytics API supported on the 2.x branch ? Otherwise, will it be integrated with the 2.x version ? 

And, has anyone succeeded using phonegap-plugin-push with [firebase-analytics](https://github.com/chemerisuk/cordova-plugin-firebase-analytics) plugin ? I cant use both due to a conflict with the google_map_id referenced twice...

**Comment by jonas-m-** [comment] 2017-04-25 13:51
@sam2x I have. First, in Firebase console, you need to import your existing GCM project, not create a new one. 

Then in cordova's config.xml paste your Firebase app id into the SENDER_ID variable of push plugin, like so:
```xml
<plugin name="phonegap-plugin-push" spec="~1.10.0">
    <variable name="SENDER_ID" value="1:956432534015:android:df201d13e7261425" />
</plugin>
```

And when you init:
```javascript
PushNotification.init({
    android: {
        senderID: 956432534015
    }
});
```

Then it works

**Comment by fredgalvao** [comment] 2017-04-25 17:52
@jonas-m- Is that something that could be added to the docs? Seems like a valuable drop of knowledge.

**Comment by jonas-m-** [comment] 2017-04-25 18:10
@fredgalvao Yep, I think it could be :)

**Comment by fredgalvao** [comment] 2017-04-25 18:15
@jonas-m- Would you mind creating a PR for that?

**Comment by jonas-m-** [comment] 2017-04-25 18:16
@fredgalvao Sure, will do

**Comment by marcRDZ** [comment] 2017-06-06 15:11
Hi all
Any news on this issue? Currently, the notifications come when the app is in background but without firing 'onNotification' event. I try the workaround suggested by jonas-m- with no success.
Other features work very well. Coungratulations for your work.
Any suggestions are welcome, thanks for all

**Closed** 2017-09-06 20:07 UTC
Labels: discussion, feature
