### ISSUE TITLE
iOS building error

### ISSUE THREAD

**Issue by lessadiogo** [phonegap/phonegap-plugin-push#504] opened 2016-01-14 12:15 UTC
Hi, when trying to build the app on android, it runs perfectly.

But when trying to build same on iOS, it returns error while linking. I've updated my Xcode to 7.2, I've also disabled bitcode, and my Cordova version is 5.3.1.

I tried remove the push plugin and the app runs. Re-adding and removing googleplus plugin, it also runs. Looks like there's some conflict with both together, but I'm not sure. I spent few hours trying to fix it, without success. Paste latest lines of building log below. Hope someone can help.

**[...]
    /Users/danielarditti/Desktop/myappfolder/platforms/ios/My App/Plugins/phonegap-plugin-push/GCM/Libraries/libGTMSessionFetcher_full.a(GTMReadMonitorInputStream.o)
    My App/Plugins/cordova-plugin-googleplus/GoogleSignIn.framework/GoogleSignIn(GTMReadMonitorInputStream.o)
ld: 276 duplicate symbols for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Showing first 200 warnings only**

Thanks,
Diogo

**Comment by macdonst** [comment] 2016-01-14 13:57
@lessadiogo does your build work if you only include the push plugin? What googleplus plugin are you using?

**Comment by lluismnd** [comment] 2016-01-14 15:34
Same error. I try to do this:

http://stackoverflow.com/questions/30848208/new-warnings-in-ios9

But not results yet :(

**Comment by lessadiogo** [comment] 2016-01-14 16:15
@macdonst I'm using cordova-plugin-googleplus by Eddy Verbruggen. Yes, if I include only push plugin, the build works.

**Comment by macdonst** [comment] 2016-01-14 21:43
Duplicate of #449

**Closed by macdonst** 2016-01-14 21:43 UTC
Labels: duplicate, ios

**Comment by lessadiogo** [comment] 2016-01-15 12:20
@macdonst, thanks for your time.
