### ISSUE TITLE
clang: error: -fobjc-weak is not supported on the current deployment target

### ISSUE THREAD

**Issue by sebj54** [phonegap/phonegap-plugin-push#2183] opened 2018-02-02 14:48 UTC
### Expected Behaviour
Build success 

### Actual Behaviour
Build failed for iOS 😢 

```
CompileC /Users/sebas/Library/Developer/Xcode/DerivedData/Pharmacap-dzqvgmbzyeemwxczaqhkhklhixpw/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/nanopb.build/Objects-normal/armv7/nanopb-dummy.o Target\ Support\ Files/nanopb/nanopb-dummy.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/sebas/Sites/evrard-client/platforms/ios/Pods
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -fobjc-arc -fobjc-weak -fmodules -fmodules-cache-path=/Users/sebas/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/sebas/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DPOD_CONFIGURATION_DEBUG=1 -DDEBUG=1 -DCOCOAPODS=1 -DPOD_CONFIGURATION_DEBUG=1 -DDEBUG=1 -DPB_FIELD_32BIT=1 -DPB_NO_PACKED_STRUCTS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=4.3 -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wunguarded-availability -fembed-bitcode-marker -index-store-path /Users/sebas/Library/Developer/Xcode/DerivedData/Pharmacap-dzqvgmbzyeemwxczaqhkhklhixpw/Index/DataStore -iquote /Users/sebas/Library/Developer/Xcode/DerivedData/Pharmacap-dzqvgmbzyeemwxczaqhkhklhixpw/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/nanopb.build/nanopb-generated-files.hmap -I/Users/sebas/Library/Developer/Xcode/DerivedData/Pharmacap-dzqvgmbzyeemwxczaqhkhklhixpw/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/nanopb.build/nanopb-own-target-headers.hmap -I/Users/sebas/Library/Developer/Xcode/DerivedData/Pharmacap-dzqvgmbzyeemwxczaqhkhklhixpw/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/nanopb.build/nanopb-all-target-headers.hmap -iquote /Users/sebas/Library/Developer/Xcode/DerivedData/Pharmacap-dzqvgmbzyeemwxczaqhkhklhixpw/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/nanopb.build/nanopb-project-headers.hmap -I/Users/sebas/Library/Developer/Xcode/DerivedData/Pharmacap-dzqvgmbzyeemwxczaqhkhklhixpw/Build/Products/Debug-iphoneos/nanopb/include -I/Users/sebas/Sites/evrard-client/platforms/ios/Pods/Headers/Private -I/Users/sebas/Sites/evrard-client/platforms/ios/Pods/Headers/Private/nanopb -I/Users/sebas/Sites/evrard-client/platforms/ios/Pods/Headers/Public -I/Users/sebas/Sites/evrard-client/platforms/ios/Pods/Headers/Public/FirebaseAnalytics -I/Users/sebas/Sites/evrard-client/platforms/ios/Pods/Headers/Public/FirebaseCore -I/Users/sebas/Sites/evrard-client/platforms/ios/Pods/Headers/Public/FirebaseInstanceID -I/Users/sebas/Sites/evrard-client/platforms/ios/Pods/Headers/Public/FirebaseMessaging -I/Users/sebas/Sites/evrard-client/platforms/ios/Pods/Headers/Public/GoogleToolboxForMac -I/Users/sebas/Sites/evrard-client/platforms/ios/Pods/Headers/Public/Protobuf -I/Users/sebas/Sites/evrard-client/platforms/ios/Pods/Headers/Public/nanopb -I/Users/sebas/Library/Developer/Xcode/DerivedData/Pharmacap-dzqvgmbzyeemwxczaqhkhklhixpw/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/nanopb.build/DerivedSources/armv7 -I/Users/sebas/Library/Developer/Xcode/DerivedData/Pharmacap-dzqvgmbzyeemwxczaqhkhklhixpw/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/nanopb.build/DerivedSources -F/Users/sebas/Library/Developer/Xcode/DerivedData/Pharmacap-dzqvgmbzyeemwxczaqhkhklhixpw/Build/Products/Debug-iphoneos/nanopb -include /Users/sebas/Sites/evrard-client/platforms/ios/Pods/Target\ Support\ Files/nanopb/nanopb-prefix.pch -MMD -MT dependencies -MF /Users/sebas/Library/Developer/Xcode/DerivedData/Pharmacap-dzqvgmbzyeemwxczaqhkhklhixpw/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/nanopb.build/Objects-normal/armv7/nanopb-dummy.d --serialize-diagnostics /Users/sebas/Library/Developer/Xcode/DerivedData/Pharmacap-dzqvgmbzyeemwxczaqhkhklhixpw/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/nanopb.build/Objects-normal/armv7/nanopb-dummy.dia -c /Users/sebas/Sites/evrard-client/platforms/ios/Pods/Target\ Support\ Files/nanopb/nanopb-dummy.m -o /Users/sebas/Library/Developer/Xcode/DerivedData/Pharmacap-dzqvgmbzyeemwxczaqhkhklhixpw/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/nanopb.build/Objects-normal/armv7/nanopb-dummy.o
```

I added a plugin on another computer for Android platform. I made a git pull on the Mac, removed ios platform and re-added platform in order to make the plugin work. After that, I could not build the app for iOS anymore.
After adding the platform, I had to do a `pod install` and a `pod setup` to make it work. Without that, I had the `Library not found for -lGoogleToolboxForMac` error.

#### Steps to Reproduce 
I really don't know what caused the problem :(

#### Cordova CLI version and cordova platform version
cordova 8.0.0
cordova-ios 4.5.4

I tried to build with every Deployment target listed (from 8.0 to 11.1) but it did not change anything.

#### Plugin version
phonegap-plugin-push 2.1.2 "PushPlugin"

Other plugins: 
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-plugin-appversion 1.0.0 "App Version"
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-whitelist 1.3.3 "Whitelist"

### Additional information
I'm not really used to MacOS, so please be comprehensive!

Thanks for your help!

**Comment by fredgalvao** [comment] 2018-02-02 23:33
I can't see any indication of errors on the logs you pasted. Can you recheck and share the whole build log? Preferably as a file on https://pastebin.com/ so we don't overflow the issue with a monster comment.

**Comment by danilofd** [comment] 2018-02-03 03:22
same error =\

**Comment by misaxi** [comment] 2018-02-03 05:11
Having the same issue here.

cordova 7.1.0
cordova-ios 4.5.4

I'm using ionic.

* Tried to create the application from scratch `ionic start`.
* Then did `ionic cordova build ios` and it was successful.
* After that, I added the plugin `ionic cordova plugin add phonegap-plugin-push`.
* Again, I did `ionic cordova build ios`. But this time it failed with the same issue.

**Comment by misaxi** [comment] 2018-02-03 05:17
Not sure how phonegap-plugin-push depends on nanopb. But seems that's where the issue coming from?

**Comment by misaxi** [comment] 2018-02-03 06:38
> Hmm, nanopb doesn't specify that build option so I assume it's coming from their build configuration.

Quoted from the issue created with nanopb. Not too much info, but hopefully can help isolate the root cause.

**Comment by misaxi** [comment] 2018-02-03 07:14
Here's my complete build log https://pastebin.com/VbNgys6P

**Comment by CureCompanion** [comment] 2018-02-03 16:36
I'm getting this error too.

**Comment by mukulmajmudar** [comment] 2018-02-03 16:37
I'm getting this error too.

**Comment by macdonst** [comment] 2018-02-04 21:02
I can't actually reproduce this one. Anyone have more detailed reproduction notes?

**Comment by sebj54** [comment] 2018-02-05 07:52
I confirm that it works now when I explicitly set the deployment target to 9.0! Thanks for the workaround :)

@macdonst Which logs do you want and where can I find them?

**Comment by macdonst** [comment] 2018-02-05 18:45
@sebj54 I just need a better reproduction scenario. I started a new test app from scratch using the same version of cordova and cordova-ios. Then I set the deployment target as 8, 9, 10 & 11. Couldn't reproduce the issue.

**Comment by sebj54** [comment] 2018-02-05 19:02
@macdonst I have the same error than @misaxi, don't you?
![](https://user-images.githubusercontent.com/767799/35763298-f3e13636-085d-11e8-89aa-7f55e91c8935.png)

It didn't work when I changed the deployment target first because I was editing build settings of my main project. I should have changed the build settings of the nanopb target.
I also have last versions of xcode and cocoapods gem, I don't know it change anything.

Please tell me if I can provide you more context!

**Comment by macdonst** [comment] 2018-02-05 19:06
@sebj54 I do not have the error. I can't reproduce it at all.

**Comment by sebj54** [comment] 2018-02-06 11:36
Okay, so I'll try to provide you more context.

- I don't build the project with `cordova build ios` command line but I run `cordova prepare` instead + run from Xcode.
- Like I said before, I have last versions of MacOS, Xcode and the cocoapods' gem.
- I have the `ld: library not found for -lGoogleToolboxForMac` issue after adding the phonegap-plugin-push plugin. I have to manually run `pod install`.

Regarding that `lGoogleToolboxForMac` issue, everyone is not affected by the problem. I guess it is the same for the current issue. 

Just asking, don't be mad at me if I'm wrong, can the `Deployment target` be set in the podfile or something that this plugin can specify? 
If not, I think we should add a paragraph in `INSTALLATION.md` to inform about this problem that might occurs.

**Comment by joshdholtz** [comment] 2018-02-06 17:35
I am also getting `clang: error: -fobjc-weak is not supported on the current deployment target`. Didn't change anything except removing and re-adding the platform

**Comment by ropmansk** [comment] 2018-02-20 08:22
same issue for me, i got the -lGoogleToolboxForMac error first, then ran pod install so maybe its somehow related.

workaround of setting deployment target of nanopb to 9.0 solved it

**Comment by kilatib** [comment] 2018-03-05 11:52
▸ Compiling GTMNSData+zlib.m
▸ Compiling GoogleToolboxForMac-dummy.m
▸ Compiling GTMLogger.m
▸ Compiling GTMNSData+zlib.m
▸ Building Pods/Protobuf [Release]
▸ Check Dependencies
▸ Compiling Any.pbobjc.m
▸ Compiling Api.pbobjc.m
▸ Building Pods/nanopb [Release]
▸ Check Dependencies
▸ Compiling nanopb-dummy.m

❌  clang: error: -fobjc-weak is not supported on the current deployment target

How can I change  deployment target  if I compile not in xcode?

**Comment by macdonst** [comment] 2018-06-04 15:45
I'm going to close this as I can't reproduce the issue and all new apps have to target iOS 9.0 or later now.

**Closed by macdonst** 2018-06-04 15:45 UTC
Labels: can't reproduce, ios, wontfix
