### ISSUE TITLE
Android crashing when Init

### ISSUE THREAD

**Issue by denkomanceski** [phonegap/phonegap-plugin-push#1037] opened 2016-07-01 21:16 UTC
The plugin worked as expected, and than I tried to use it with another app and same senderId (since the project covers 2 apps). After I tried initializing on the second app both of the apps started crashing. The only thing that I think is relevant in adb logcat is this. Any idea how to resolve this ?

```
07-01 23:14:09.991 19443 19542 E AndroidRuntime: java.lang.IncompatibleClassChangeError: The method 'java.io.File android.support.v4.content.ContextCompat.getNoBackupFilesDir(andr
oid.content.Context)' was expected to be of type virtual but instead was found to be of type direct (declaration of 'com.google.android.gms.iid.zzd' appears in /data/app/mk.vertex
.ginkgorider-2/base.apk)
07-01 23:14:09.991 19443 19542 E AndroidRuntime:        at com.google.android.gms.iid.zzd.zzeb(Unknown Source)
07-01 23:14:09.991 19443 19542 E AndroidRuntime:        at com.google.android.gms.iid.zzd.<init>(Unknown Source)
07-01 23:14:09.991 19443 19542 E AndroidRuntime:        at com.google.android.gms.iid.zzd.<init>(Unknown Source)
07-01 23:14:09.991 19443 19542 E AndroidRuntime:        at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
07-01 23:14:09.991 19443 19542 E AndroidRuntime:        at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
07-01 23:14:09.991 19443 19542 E AndroidRuntime:        at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:75)
07-01 23:14:09.991 19443 19542 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-01 23:14:09.991 19443 19542 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-01 23:14:09.991 19443 19542 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
07-01 23:14:09.992   778   947 W ActivityManager:   Force finishing activity mk.vertex.ginkgorider/.MainActivity


```

**Comment by macdonst** [comment] 2016-07-01 21:25
@denkomanceski this is a duplicate of #909. Long story short Google broke some stuff, then they released a fix. Please update your Android build environment and your devices Google Play Services to the latest releases.

**Closed by macdonst** 2016-07-01 21:25 UTC
Labels: android, duplicate
