### ISSUE TITLE
invalidRegistration on app server when push to iOS

### ISSUE THREAD

**Issue by kascode** [phonegap/phonegap-plugin-push#439] opened 2015-12-18 00:23 UTC
I used [this] (https://developers.google.com/cloud-messaging/ios/certs) instruction on Google Cloud Messaging site to set certificates for APNS. I'm on development phase and set only development certificate in Apple Developer Console. Then I set up phonegap-plugin-push and initialized it in JS like that (on deviceready of course):

```
var pushController = PushNotification.init({
    "android": {
      "senderID": "_",
      "forceShow": true
    },
    "ios": {
      "alert": "true",
      "badge": "true",
      "sound": "true"
    }
  });

pushController.on('registration', function (data) {
  console.log("Push registration", data);
});
```

So when registration is successful I see registration id of the device in console. But when I try to push message from server to registration id of iOS device I get error response with code invalidRegistration. I'm pushing from node.js server with gcm package.

Same setup works great on Android.

**Comment by macdonst** [comment] 2015-12-18 00:48
@kascode what branch are you using because I have not release GCM support for iOS yet.

**Comment by kascode** [comment] 2015-12-18 10:10
@macdonst I use master branch, just installed plugin with cordova cli from git. That's interesting, if GCM for iOS is not supported in this plugin then how do I get registration id? Is it requested from APNS directly?

**Comment by macdonst** [comment] 2015-12-18 13:29
@kascode yes, wait for the 1.5.0 release. Your issue is a duplicate of #115 so I'm closing it.

**Closed by macdonst** 2015-12-18 13:29 UTC
Labels: duplicate
