### ISSUE TITLE
Callbacks for actions buttons.

### ISSUE THREAD

**Issue by uzlov** [phonegap/phonegap-plugin-push#274] opened 2015-10-28 22:31 UTC
Don't executed for any states of app.
Only event "notification". 
Last version (1.4.0)
Or mb question in wrong declaration action callback in js?

**Comment by macdonst** [comment] 2015-10-29 14:11
@uzlov I'm not sure what you are asking here. Please give me a detailed reproduction scenario.

**Comment by uzlov** [comment] 2015-10-29 21:32
I tried to declare in it way
window.callbackName = function (data) {
    console.log(data);
};

and
push.on('callbackName', function(data) {
    console.log(data);
}

Don't executed for both.

**Comment by macdonst** [comment] 2015-10-29 22:29
@uzlov okay, this will only work in Android BTW. The first way you defined the call back would be okay the second will never work. So if you do:

```
window.callbackName = function (data) { 
    console.log(data);
};
```

and send the following JSON to GCM:

```
{
    title:"AUX Scrum",
    message: "Scrum: Daily touchbase @ 10am Please be on time so we can cover everything on the agenda.",
    actions: [
        { icon: "emailGuests", title: "EMAIL GUESTS", callback: "window.callbackName"},
        { icon: "snooze", title: "SNOOZE", callback: "window.callbackName"},
    ]
}
```

your callback should be executed when you click on the button.

**Comment by uzlov** [comment] 2015-10-29 22:47
ok, clear, thx :)

other question:
after click on action button - app opens
but push don't closed - I still have push

*if I click on push - app opens - push closed

bug or how to close push after click on action button?

**Comment by bau720123** [comment] 2015-11-04 07:22
hi @uzlov 
did you solve your problem ? "Callbacks for actions buttons"
because I face the same problem at here
https://github.com/phonegap/phonegap-plugin-push/issues/298

by the way
I am using 1.4.2 version，if you want clear the push any，just set the "clearNotifications" attribute to true
```
var push = PushNotification.init({ "android": {"senderID": "senderid", "sound": "true", "vibrate": "true", "clearNotifications": "true", "forceShow": "true", "icon": "phonegap", "iconColor": "blue"}..... } );
```

**Comment by uzlov** [comment] 2015-11-04 07:34
nope
callback of action don't executed
(*I solved in this way: call action callback(we have name of callback in additional info) from callback for event "notification")

and  - after click on button - app opens but push don't close

**Comment by bau720123** [comment] 2015-11-04 07:57
hi @uzlov 
thanks your reply
but I can't understand what your true meaning about
```
(*I solved in this way: call action callback(we have name of callback in additional info) from callback for event "notification")
```
can you use some code to show your way ?

**Comment by uzlov** [comment] 2015-11-04 08:03
if use your example, will be something like:

$fields = array(
 'registration_ids' => 'my registration_id', 
 'data' => array(
   'title' => 'my title'
   'message' => 'the message',
   'actions' => array(array('icon' => 'emailGuests','title' => 'bottom1','callback' => 'actions_left')),
  )
);

push.on('notification', function(data)
{
          if(undefined != data.additionalData.callback && 'function' == typeof window[data.additionalData.callback])
          {
            window[data.additionalData.callback](data);
          }
});

window.actions_left = function(data) 
{ 
alert("left:" + data);
};

**Comment by bau720123** [comment] 2015-11-04 08:26
thanks @uzlov 
got it
"data.additionalData.callback" is the keypoint

**Comment by stewartmegaw** [comment] 2015-11-04 10:47
Thanks for this.
This should be in the documentation otherwise only way to know is go into the java files.

**Comment by jimior2** [comment] 2015-11-06 03:04
Add to documentation would be nice. +1

**Comment by uzlov** [comment] 2015-11-10 11:08
please check new functionality 
https://github.com/phonegap/phonegap-plugin-push/pull/321

**Comment by cdorner** [comment] 2015-11-28 13:49
I don't think this should be any documentation for this, there is a bug right there, the callback should be called without any magic on our side.

Please check if makes sense, I will submit a pull request for this.

**Comment by macdonst** [comment] 2015-11-30 17:00
@cdorner Well spotted. The `callback` property should be off the main object not `additionalData` but that got messed up somewhere in the Android refactoring. I've merged your PR and will try to get a bug release out today.

**Closed by macdonst** 2015-11-30 17:00 UTC
Labels: bug

**Comment by SiddAjmera** [comment] 2016-03-10 11:10
Hello,

I'm using a MEAN Stack Application where I used DaftMonk's Angular Fullstack Generator. I'm sending the push notification from server side. Where I'm struggling is that I'm not able to figure out where to implement the callbacks. I simply used the Server Side code that is shown [here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons) : 

I just changed the name of the callbacks to `window.approve` and `window.reject`.

But I'm not getting were to implement the `app.emailGuests`, and the `app.snooze` callbacks. Right now, I implemented them in the client/app inside a service named pushnotification. It's code looks like this : 

`'use strict';

angular.module('cbApp')
  .service('pushnotification', function ($q) {
    return {
      registerPushNotification : function(){
        var deferred= $q.defer();
        var androidConfig = {
             "senderID": "463291795017",
             "icon":"logo",
             "iconColor":"blue"
            };
        var push = PushNotification.init({
          android: androidConfig,
          ios: {
            alert: "true",
            badge: true,
            sound: 'false'
          },
          windows: {}
        });
        push.on('registration', function(data) {
          console.log(data.registrationId);
          deferred.resolve(data.registrationId);
        });
        return deferred.promise;
      }

      window.approve = function(data){
        alert("Approve Triggered");
        console.log("Approve Callback Triggred. Here is the Data : ", data);
      }

      window.reject = function(data){
        alert("Reject Triggred");
        console.log("Reject Callback Triggred. Here is the Data : ", data);
      }
    }
});`

But unfortunately the callback isn't getting triggered. What an I doing wrong?

**Comment by ebarault** [comment] 2016-05-14 09:02
please see [this](https://github.com/phonegap/phonegap-plugin-push/issues/884)

**Comment by sumeeranalabs** [comment] 2016-06-17 11:32
Hi ,
can any one help me out ,callback is not working.i am struggled with this issue from a week
where i can call that function in my app,can any one give me detailed explanation.thx  in advance.
