### ISSUE TITLE
Error building app

### ISSUE THREAD

**Issue by caipigott** [phonegap/phonegap-plugin-push#136] opened 2015-09-15 08:45 UTC
Hi,

after adding the latest version of the push plugin my app fails on build.
My Versions:
cordova                            5.3.1
Installed platforms: android 4.1.1

To add the plugin i used: 
cordova plugin add https://github.com/phonegap/phonegap-plugin-push.git#1.2.3 (found this #1.2.3 on a closed issue)

The build fails with this error:
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotat
ion/AnimRes;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:50
2)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.

Any idea what can be the problem?

Thanks for your help,
Caipigott

**Comment by fredgalvao** [comment] 2015-09-15 19:30
This is a duplicate of the issue described at https://github.com/phonegap/phonegap-plugin-push/issues/51

## Details ##
The problem is that versions <= 1.2.3 still use the android-support-v13.jar instead of using the gradle dependency, and it was known to cause issues whenever you had any other plugin or custom code that had another dependency on android-support, which would cause that "multiple dex" issue. It's been solved recently on master (https://github.com/phonegap/phonegap-plugin-push/commit/6b5bebb85c94cca0a734c743b37a50fccc57c8c7), but a stable version hasn't been released yet with the fix, so you might wanna try installing directly from the git url pointing to the master branch. Beware though that it's considered unstable code.
`cordova plugin rm phonegap-plugin-push`
`cordova plugin add https://github.com/phonegap/phonegap-plugin-push.git`

## Workaround ##
Another way to solve it is installing whichever version you have or can, stable or not, and then you do:
1- Delete the android-support-*.jar from /platforms/android/lib/
2- Create a file called `build-extras.gradle` at /platforms/android/ (it should be side-by-side with `build.gradle`) and give it this content:
```groovy
dependencies {
    compile "com.android.support:support-v13:23+"
}
```

The project should then compile successfully (this is how I solved it before the gradle fix), but your mileage may vary.

**Comment by macdonst** [comment] 2015-09-16 04:07
I've already made the switch to gradle build in master and I will be releasing a 1.3.0 later this week.

**Comment by caipigott** [comment] 2015-09-16 08:06
Hi,

thanks a lot for your help.
I guess i will wait for the new release as it will come soon anyway.

Have a nice day,
Caipigott

**Comment by caipigott** [comment] 2015-09-22 08:42
HI,

yesterday i updated to Version 1.3.0 and it works perfect!

Thanks for great work.

Greetings,
Caipigott

**Closed** 2015-09-22 12:38 UTC

**Comment by globexdesigns** [comment] 2015-11-08 05:14
I am having the same error:

```
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
Unknown source file :   at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
Unknown source file :   at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
Unknown source file :   at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
Unknown source file :   at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
Unknown source file :   at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file :   at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file :   at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file :   at com.android.dx.command.Main.main(Main.java:106)

:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_60\bin\java.exe'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

However, I am running version 1.4.2 of the plugin (which is the latest).

Any other suggestions on how to fix this?

**Comment by fredgalvao** [comment] 2015-11-08 10:08
@globexdesigns  Some other plugin on your application is including a .jar of android-support-v4 somewhere, and that's conflicting with what gradle dependencies generate.

[if you're on **unix**] Please run this at the root of your cordova project to try and find it:
`find ./** -name '*.jar'`

There's 2 possible outcomes of that:

 1. A .jar file is found at the `plugins/` AND `platforms/android/` folder, in which case you need to contact the author of said plugin so that he can update it to use gradle dependencies instead of including the jar directly.
 2. A .jar file is found at the `platforms/android/lib` ONLY, and that indicates that a leftover of another plugin or an older version of `phonegap-plugin-push` is present, and you should simply delete it from that folder.
