### ISSUE TITLE
push.on => "registration" will trigger twice times that only in iOS

### ISSUE THREAD

**Issue by bau720123** [phonegap/phonegap-plugin-push#57] opened 2015-08-08 06:39 UTC
according to the "Quick Example"
https://github.com/phonegap/phonegap-plugin-push
I test in Android 4.4.2 and iOS 8.4 that all in real device

when in android，the "registration" behavior only trigger one time
but...
when in ios，the "registration" behavior will trigger twice times

**Comment by macdonst** [comment] 2015-08-09 15:51
@bau720123 Really, I've never seen the registration trigger twice on iOS. Can you put up a gist of the html/js you are using that can reproduce the problem?

**Comment by bau720123** [comment] 2015-08-09 16:10
hi @macdonst 
thanks for your reply
well...the code just like the example code
```
var push = PushNotification.init({ "android": {"senderID": "my_sender_id"},
         "ios": {}, "windows": {} } );

    push.on('registration', function(data) {
        alert(data.registrationId); //it will trigger twice times in iOS 8.4
    });

    push.on('notification', function(data) {
        //not try yet...
    });

    push.on('error', function(e) {
        //not try yet...
    });
```

but I am using PGB (build.phonegap.com) with all official core plugin from NPM

**Comment by macdonst** [comment] 2015-08-11 02:10
@bau720123 I'm running iOS 8.4 on my test device and I can't reproduce this at all. Do you have a link to the github repo you use to test on PGB?

**Comment by bau720123** [comment] 2015-08-11 11:03
hi @macdonst 
problem solved (so strange...)
anyway ~ thanks

**Comment by Mojo90** [comment] 2015-08-31 21:50
@bau720123 
what was your Problem?
Because mine is also called twice or sometimes even 3 times.....
My assumption is that it has to do with this plugin: https://github.com/katzer/cordova-plugin-local-notifications but not sure yet

**Comment by bau720123** [comment] 2015-09-01 05:43
hi @Mojo90 
have you ever use the old "plugin-notification"
https://github.com/phonegap-build/PushPlugin
if yes，remove it，rebuild it，clean the app's cache
and try again...

**Comment by Mojo90** [comment] 2015-09-01 06:22
no unfortunately not :-(. Still investigating...

**Comment by bau720123** [comment] 2015-09-01 08:28
hi @Mojo90 
how about push your full code here

**Comment by Mojo90** [comment] 2015-09-01 15:21
@bau720123  here is a snippet:
initPushService is called from device-ready method.
and then my registerPushAtServer is called twice, 3x or 4x on iOS. I handle it now and do only update devicetoken on parse.com when it changed. but nevertheless it is a strange behavior

function initPushService(){

	var push = PushNotification.init({ 
				"android": {"senderID": "XXXXX"},
         		"ios": {}, 
         		"windows": {} 
         	});

	push.on('registration', function(response) {
 		registerPushAtServer(response);
	});

	push.on('notification', function(data) {
    	handlePushNotification(data)
	});

	push.on('error', function(e) {
    	// e.message
	    console.log("Push Error: " + e);
	});
	
}

it is strange because on android it is only called once.

**Comment by bau720123** [comment] 2015-09-01 15:38
hi @Mojo90 
try to just only use "alert(response)" or "console.log(response)" first
to see if it will work only trigger one time
if will，I think maybe your "registerPushAtServer" problem

**Comment by Mojo90** [comment] 2015-09-01 18:57
thanks @bau720123 
tried it, but same behavior. I really think that it has some problems with the local notifications plugin from katzer. but couldn't figured out yet whats the problem. really these are two good plugins and the notifications plugin has completely stopped working since I installed this Push Plugin here :-(

**Comment by bau720123** [comment] 2015-09-22 02:13
hi @Mojo90 
for now I am facing the same problem ("registration" will trigger twice times that only in iOS)

**Comment by Mojo90** [comment] 2015-09-22 06:43
@bau720123 Are you using Local Notification Plugin as well? Because I think for me it is called twice because I use both plugins. Anyway as mentioned by me it is ok for now because I am only updating sth if Device Token changed otherwise nothing happens...

**Comment by bau720123** [comment] 2015-09-22 06:51
got it
thanks @Mojo90 
I will try delete the "Local Notification" first to see if anything change
feedback later...

**Comment by bau720123** [comment] 2015-09-22 07:52
hi @Mojo90 
just like you said
is the "the "Local Notification" problem
thanks a lot

**Comment by Mojo90** [comment] 2015-09-22 08:26
@bau720123  No problem. If you fixed it please let me know. But at the moment I just ignore...

**Comment by bau720123** [comment] 2015-09-22 08:37
hi @Mojo90 
I notice that the problem is not "Local Notification"
for now I am just using core plugin + push plugin
![push](https://cloud.githubusercontent.com/assets/5110085/10013653/d0d29b4c-6145-11e5-8066-cebc196c8418.jpg)

but still facing same problem that only in Android
when you install your ipa to your ios device

launch it...
first time，the app will ask you if turn on the notification，select yes，after it，trigger only one time

close the app and launch it again...
second time，because first time the app have been ask you before，so...won't ask again，after it， trigger twice time

**Comment by bau720123** [comment] 2015-09-22 12:29
hi @Mojo90 and @macdonst 
according above (PGB 5.2.0 + all latest core plugin + 1.2.3 + all same code)
ipad mini (9.0 13A344) => have twice problem
iphone 6 plus (8.4.1 12H321) => have no twice problem

**Comment by wakeupmh** [comment] 2015-10-01 02:45
Hi @bau720123 , I have tested your code, but in my app it doesn't works, Can you help me ?

**Comment by macdonst** [comment] 2015-10-01 03:02
@bau720123 Yeah, I've been able to reproduce this on an iOS9 device as well.

**Comment by bau720123** [comment] 2015-10-01 03:03
hi @wakeupmh 
is your deviceready trigger ?
please confirm this first

**Comment by bau720123** [comment] 2015-10-01 03:04
thanks @macdonst 
glad to hear that you reproduce this on an iOS9 !!!

**Comment by wakeupmh** [comment] 2015-10-01 03:20
Yes @ bau720123 , I use deviceready trigger , Can I use another way to show an alert with my registration key ?, I just wanna a test with this plugin, because when i called the function it does not show anything to me in app build

**Comment by bau720123** [comment] 2015-10-01 09:14
hi @wakeupmh 
android or ios ?
version ?
are you sure the plugin install correct ?
PGB version ?

**Comment by wakeupmh** [comment] 2015-10-01 11:42
hello @bau720123, In a first moment this app is only for Android  version:4.4.2. I'm using a PGB without interface, directly on Sublime text for example, so I only included this following tag: <gap:plugin name="phonegap-plugin-push" source="npm" /> in my config.xml. I'm using  phonegap/cordova CLI 5.2.

**Comment by bau720123** [comment] 2015-10-01 12:01
hi @wakeupmh 
what tag ?
I can't see it...

**Comment by wakeupmh** [comment] 2015-10-01 12:13
sorry, this tag: gap:plugin name="phonegap-plugin-push" source="npm"

**Comment by bau720123** [comment] 2015-10-01 12:18
hi @wakeupmh 
if you are using PGB (build.phonegap.com)
please use 1.2.3 version for now
```
<gap:plugin name="phonegap-plugin-push" source="npm" version="1.2.3" />
```

and...if you have other question
please reopen a new one
because this article topic is "rigger twice times" problem
thanks

**Comment by fredgalvao** [comment] 2015-10-01 13:00
@bau720123, @wakeupmh   There is not need to specify 1.2.3 for PhonegapBuild anymore. See the [README](https://github.com/phonegap/phonegap-plugin-push#phonegap-build-support).

**Comment by bau720123** [comment] 2015-10-01 13:07
hi @fredgalvao 
I know PGB support gradle build for now
but look at this
http://community.phonegap.com/nitobi/topics/gradle-support-enabled-for-android-builds
I am "ColinBau"

so...I suggest if you are using PGB，1.2.3 version for now

**Comment by fredgalvao** [comment] 2015-10-01 13:13
I see... that's bad news huh.

Well, might as well mention that it's a temporary workaround, so people don't stick with older versions of the plugin unnecessarily.

**Comment by macdonst** [comment] 2015-10-11 00:17
@bau720123 can you test with the code that is currently in master? I've merged PR #215 that fixes the issue with the local notifications plugin and I believe it also takes care of this double registration problem. It removes an unnecessary call to `registerForRemoteNotifications` which could cause the double registration event. Now, I can no longer reproduce the issue.

**Comment by bau720123** [comment] 2015-10-11 03:13
hi @macdonst 
so you want me to readd the plugin again and test with this situation ?
```
cordova plugin add https://github.com/phonegap/phonegap-plugin-push
or
cordova plugin add "phonegap-plugin-push"
```

**Comment by macdonst** [comment] 2015-10-11 03:54
Try the

cordova plugin add https <https://github.com/phonegap/phonegap-plugin-push>
:// <https://github.com/phonegap/phonegap-plugin-push>github.com
<https://github.com/phonegap/phonegap-plugin-push>/
<https://github.com/phonegap/phonegap-plugin-push>phonegap
<https://github.com/phonegap/phonegap-plugin-push>/
<https://github.com/phonegap/phonegap-plugin-push>phonegap-
<https://github.com/phonegap/phonegap-plugin-push>plugin-push
<https://github.com/phonegap/phonegap-plugin-push>

Method as it will get the latest code.

**Comment by bau720123** [comment] 2015-10-12 07:01
hi @macdonst 
the issue seem solved
thanks

**Comment by macdonst** [comment] 2015-10-12 16:22
Closing as per @bau720123

**Closed by macdonst** 2015-10-12 16:22 UTC
Labels: bug

**Comment by 19akash91** [comment] 2016-05-26 06:27
hi @bau720123 sir
i am adding cordova plugin add "phonegap-plugin-push" this plugin but not call registration method and error method plz help me

code is here : 

var push = PushNotification.init({
                      android: {
                          senderID: "*********"
                      },
                      ios: {
                          alert: "true",
                          badge: "true",
                          sound: "true"
                      },
                      windows: {}
                  });
                  //alert("push is : "+push);
               //var push = Scopes.get('push');
          push.on('registration', function(data) {alert("in push registration");
                      device=data.registrationId;
                      localStorage.setItem('device_id',device);
                       alert("device id is : "+localStorage.getItem('device_id'));

         });
           push.on('notification', function(data) {
            });
          push.on('error', function(e) {
                                   // e.message
                                   alert("ErrorCallback "+e.message);
          });
      
     }
