### ISSUE TITLE
push.on('notification') not fired on ios 10

### ISSUE THREAD

**Issue by ajaysaini95700** [phonegap/phonegap-plugin-push#1253] opened 2016-09-28 14:39 UTC
when app is in background and push notification comes and if i click on it then push.oh('notification') does not fire (triger). but it is working fine when app is closed.
i tested it on iphone 5s (ios 10).
for both case it is working fine on android

**Comment by Paul-Lo** [comment] 2016-09-28 16:42
+1
In my ipod version 9.3.5, it works.
However, in my iPhone 5 version 10.0.2, push notification doesn't work any more.

**Comment by macdonst** [comment] 2016-09-28 20:09
This seems to be a duplicate of #1002. You should upgrade to 1.8.2.

**Closed by macdonst** 2016-09-28 20:09 UTC
Labels: duplicate

**Comment by manojrejinthala** [comment] 2017-02-02 11:12
@macdonst i am using 1.8.4 version of push plugin

However, in my iPhone 5 version 10.0.2, push notification doesn't work any more when the app is minimized or in background but it works fine when the device is from cold start
