### ISSUE TITLE
Nothing happens on event 'notification'

### ISSUE THREAD

**Issue by sebastiandanilonr** [phonegap/phonegap-plugin-push#247] opened 2015-10-20 15:14 UTC
Right now i receive the notification on the phone, when i touch the notification the app opens but none of the actions on the 'notification' event function works, my code:

```javascript
function onLoad() {
        document.addEventListener("deviceready", onDeviceReady, false);
    }

    // device APIs are available
    //
    function onDeviceReady() {
        // Now safe to use device APIs
        setTimeout(initializeNotifications(), 2000);
        
}

//-------

function initializeNotifications(){
	try{
		 var push = PushNotification.init({ "android": {"senderID": "..."},
         "ios": {"alert": "true", "badge": "true", "sound": "true"}, "windows": {} } );

		push.on('registration', function(data) {
                  alert("regID = " + data.registrationId);
		
    });

    push.on('notification', function(data) {
     
        alert(JSON.stringify(data));

         showalert(data.message, '' , data.title , 'Recibido');
        
    });

    push.on('error', function(e) {
      
        console.log('push notificacion error: ', e.message);
    });

	}catch(error){
		alert('error init ' + error);
	} 

}
```

**Comment by macdonst** [comment] 2015-10-21 17:21
@sebastiandanilonr it looks like the `push` variable would go out of scope at the end of `initializeNotifications`.

**Comment by macdonst** [comment] 2015-10-28 16:00
@sebastiandanilonr please re-open if you still have the problem on 1.4.0 and can provide a reproduction scenario.

**Closed by macdonst** 2015-10-28 16:00 UTC
