### ISSUE TITLE
Get push notification data when app closed [IOS]

### ISSUE THREAD

**Issue by jedofus** [phonegap/phonegap-plugin-push#917] opened 2016-05-23 14:27 UTC
Hi , I've got a problem ,when i get notification data on ios.
When i push my notification on foreground or background, it call method of pushplugin.m, the method notificationReceived() and the first condition if get a value of notificationMessage and the property of callbackId.The value notificationMessage and the value of callbackId is not null.

But when my app is closed by user and i get my notification,i open my notification by click and i see in the method notificationReceived(),the value of notificationMessage that's ok but the property of callbackId is nill... where is the problem? 

On my JS app, all of functions push (init,register,notification...) is in my function  DeviceReady() of cordova.

**Comment by jedofus** [comment] 2016-05-26 14:11
no idea ??

**Comment by macdonst** [comment] 2016-05-26 14:16
@jedofus I was traveling last week for our yearly conference and haven't had the time to test.

**Comment by jedofus** [comment] 2016-05-26 14:30
ok, I'll wait then ;)

**Comment by macdonst** [comment] 2016-05-26 16:38
Duplicate of #158

**Closed by macdonst** 2016-05-26 16:38 UTC
Labels: ios

**Comment by ominfowave** [comment] 2016-09-10 04:49
#158 issue solved or not ?
