### ISSUE TITLE
How to force plugin to use APNS for iOS when plist is present

### ISSUE THREAD

**Issue by gecko-8** [phonegap/phonegap-plugin-push#2138] opened 2018-01-08 20:50 UTC
I have a project that uses this plugin and the cordova-plugin-firebase-analytics one. The analytics plugin requires that the GoogleService-Info.plist file be present but that seems to make this plugin assume I'm using Firebase for iOS notifications. I'm using APNS for iOS notifications. Is there some way other than removing the plist file to tell the plugin to use APNS? I actually looked into using Firebase for iOS notifications too but we're also using Azure Notification Hubs and I can't figure out how to get it all meshed together (Azure seems to require you to use APNS for iOS).

The attached screenshot shows the registrationType of FCM for the device, which is an iPad.

<img width="1261" alt="screen shot 2018-01-08 at 12 07 48 pm" src="https://user-images.githubusercontent.com/24754972/34691717-bdde2fcc-f47a-11e7-85b5-66b397ce0520.png">

#### Plugin version
2.1.2

**Comment by macdonst** [comment] 2018-01-08 21:46
@gecko-8 duplicate of #1770 and no fix yet but PR's are welcome.

**Closed by macdonst** 2018-01-08 21:46 UTC
Labels: duplicate

**Comment by gecko-8** [comment] 2018-01-08 21:51
Yep, didn't see that ticket but just realized I should be able to disable GCM in the GoogleService-Info.plist.
