### ISSUE TITLE
Icon for android not configurable

### ISSUE THREAD

**Issue by HuebnerITC** [phonegap/phonegap-plugin-push#1286] opened 2016-10-13 12:41 UTC
Hi,

I am working with plugin-push on my app. For android nexus devices the icon in the status bar is completly white when a notification is received. So far so good I already have read a lot about this behavior which goes back to lollipop android release. 
I figured out an alternate icon for my app which is my default app icon but only two colored (black and white) and transparent. When I deliver this new icon replacing my old icon and give it the same name (icon.png) it will be used by plugin push for small-icon like described in reference. This naturally causes in the fact that app icon on homescreen looks black and white too, but here I need a colored icon. So I added the new black and white icon as additional resource to my android asset drawables. Finaly I make it copying all my new icons to the specific resolution drawables in apk file (xxxhdpi, xxhdpi etc....). 

The bug comes now:

When I give another name to icon in plugin-push init it is ignored and still uses the default icon which is white again. I can not change my main app icon because it will look weird on homescreen when its only two colored. What can I do??

I am running Android 6 on a Nexus 6, using cordova 6.3.1 and plugin-push 1.8.2.

```
var push = PushNotification.init({

                android: {
                    senderID: "562254197549",
                    forceShow: false,
                    vibrate: true,
                    clearBadge: true,
                    sound: false,
                    icon: "notification_icon" // icon is used instead why???
                },
                ios: {
                    alert: true,
                    badge: true,
                    clearBadge: true,
                    sound: false
                },
                windows: {}
            });
```

Thanks for your help
Best regards
huebner

**Comment by macdonst** [comment] 2016-10-13 12:46
@HuebnerITC sorry, can you post your icon here?

**Comment by HuebnerITC** [comment] 2016-10-13 12:59
![icon](https://cloud.githubusercontent.com/assets/17268848/19349848/90be67b6-9155-11e6-841a-2f7ee236644c.png)
![notification_icon](https://cloud.githubusercontent.com/assets/17268848/19349849/90d0ba92-9155-11e6-9144-0ae49a903c3b.png)

**Comment by HuebnerITC** [comment] 2016-10-13 13:00
the icon below the blue rwth text is nearly invisible but on status bar you can see it when notification is received

**Comment by HuebnerITC** [comment] 2016-10-13 13:03
that represents example files for xxxhdpi

**Comment by macdonst** [comment] 2016-10-13 13:20
@HuebnerITC right this icon does not follow Android icon guidelines. I've documented what's going on here: [Image docs](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images) which links to the [Android guidelines](https://material.google.com/style/icons.html#).

The icon that you've posted has no transparent pixels so it will always show up as a a white block. If you replace the white pixels with transparent ones you will see your text. However, putting text into an icon like that is a really bad idea as when it is shrunk down for the status bar or notification icon it will be nearly unreadable.

**Comment by HuebnerITC** [comment] 2016-10-14 07:31
Thank you for your quick reply, but nevertheless the icon I posted below the white and blue one works. 
You may see it on the shot I added to this post. My only issue I trap in is that this icon is only used when I replace my default app icon called icon.png in the drawables with the other one I posted below. I like to publish two icons in the drawables. So I might reference the notification_icon.png in push plugins init method. But this do not work. The default icon.png is used instead. Do you have any explanation for that? 
I will shorten the text to RWTH this might take more effect for what an icon should do. Thank you for that. RWTH saddly does not provide an icon for organisation identication. Its always the word RWTH.
![test](https://cloud.githubusercontent.com/assets/17268848/19378929/bcdc51ec-91ef-11e6-9341-44461a74e83a.png)

**Comment by HuebnerITC** [comment] 2016-10-14 07:42
OK I figure it out right now. I need to reference my new icon in payload, offcourse. Then everything worked as expected. But I still do not understand why I can set the icon in init method, when its ignored and the choice is controlled by payload, which is generated on server side...

**Comment by HuebnerITC** [comment] 2016-10-14 09:04
same for iconColor to set a different background for app. When I send it via payload it will be used. Configured in plugin-push init it is not used

**Comment by macdonst** [comment] 2016-10-14 13:38
@HuebnerITC I'm not sure why it isn't working for you either. I tried, can't reproduce your problem. When I use [icon and iconColor](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#android) they work fine. Are you sure the `notification_icon` is showing up in the drawables directory?

Perhaps you can reproduce while running `adb logcat | grep PushPlugin`. Capture the logs from a fresh start.

**Comment by augustoabreu** [comment] 2016-10-20 15:03
Same here @HuebnerITC

**Comment by macdonst** [comment] 2016-10-20 21:37
@augustoabreu take a screen shot of what is not working so I can see.

**Comment by macdonst** [comment] 2016-11-10 16:02
Can't reproduce, no feedback, closing.

**Closed by macdonst** 2016-11-10 16:02 UTC
Labels: android, can't reproduce, question
