### ISSUE TITLE
Uncorrect token returned by FCM on iOS

### ISSUE THREAD

**Issue by FFabiano** [phonegap/phonegap-plugin-push#1839] opened 2017-07-07 10:07 UTC
On iOS we decided to use FCM for push notification service. What happens is that on registration to FCM, Google return an APNs token instead of FCM one. 

So when i try to send a notification to iOS with APNs token through FCM, request returns obviously an error.
The weird thing is that if i try to unregister and then register again, FCM returns a correct token. Notifications sent using the second token are always received correctly on iOS device.
How can i fix this? 

N.B. I assume that token received on first place by FCM is an APNs token, but i may be wrong. I posted token samples below to be clear.

### Expected Behaviour

Receive a correct FCM token on every push.on('registration', function(data) { ... }) call

### Actual Behaviour

Sometimes function push.on('registration', function(data) { ... }) returns an incorrect token for FCM.

Tokens received look like:

```
Token for pushes: 0236c4204712b8ffd7c56b6ab7540c0732o1bd962406d8884656b5fc541a99d2
```
```
Token for pushes: dwBMQ3x5rz4:APA91lOcfhj-Tymfq7o0Tq0lcUsOIuHuZj52oh0bct5IR5oIPumEMgG74p0P0sL43lNE9s0TzTImj0rEsHUcwxoJUmpXUSYBFI6m42O-_uzs1VLym6F2S2hlPs9eshPML6ho70BWOpG0
```

The first token is the one returned on first registration request. The second one is what i receive if i call
```
push.unregister(function() {
		    		...
		    	});
```
and then call registration function again.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
         iOS 7.1.2
#### Plugin version
         1.10.5
#### Sample Code that illustrates the problem
Here is my code:
```
push = PushNotification.init({ //init push service
                android: {
                    senderID: "XXXXXXXXXXX"
                },
                
                ios: {
                    senderID: "XXXXXXXXXXX",
                    alert: true,
                    badge: true,
                    sound: true,
                    fcmSandbox: false
                },
                
                windows: {}
            });

...

 push.on('registration', function(data) { 
	                var registrid = data.registrationId;
	                console.log('Token for pushes: '+ registrid);
	                ...
	            });
...

 this.unregisterPushService = function () {
                    ...
		    	push.unregister(function() {
		    		...
		    	});
    }
```

**Comment by macdonst** [comment] 2017-07-10 01:22
@FFabiano if you are using FCM please use the 2.0.0-rc5 version of the plugin and follow the instructions on how to include the GoogleServices-Info.pList in your project. 

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation-requirements

**Comment by FFabiano** [comment] 2017-07-10 09:32
I tried your solution @macdonst, but i got the following error:
`ReferenceError: PushNotification is not defined`

I'm currently build with build.phonegap.com. I went deeper and i found out that latest versions supported by Phonegap Builder are:

` 
PhoneGap version: cli-6-5-0
` 
` 
iOS Phonegap version: 4.3.1
` 
` 
Android Phonegap version: 6.1.2
`

as pointed out also in official docs: https://build.phonegap.com/current-support
2.0.0-rc5 plugin version is not supported with this configuration at all.
I can't build using local workspace, where i would have more control on cli version for internal deployment reasons.
Is it the only way to fix this? Configuring my app with FCM is fine and works well except for this problem, both on Android and iOS.

**Comment by macdonst** [comment] 2017-07-10 13:53
@FFabiano I've asked the PGB team about current support levels. Those seem old but the problem you are describing does seem to indicate that the project can't install the Push Plugin because it does not meet the required versions.

Looking over your original post again I see you are using iOS7 and the 2.x stream of this plugin drops support for iOS versions before 9 so you probably shouldn't upgrade to 2.x anyway.

I can't reproduce this problem and there is a good chance the issue is with the older version of iOS you are using. Is it possible for you to upgrade to a newer version of iOS?

If you can't you may just have to work around it. If you get a registration ID with a `:` in it you can assume it is a FCM token. If it is missing you can assume it is a APNS token then call unregister/init again to generate the FCM token.

**Comment by mifkys** [comment] 2017-07-12 20:30
Hello. I used v1  of this plugin and my ios app got correct registrationId from FCM but device not receive push notifications. So I install v2 of plugin and try to get corrected regId but I receive APN regId, not FCM. What can be wrong?

Steps:
ionic cordova plugin add phonegap-plugin-push
in plugins/phonegap-plugin-push/plugin.xml add
```
<platform name="ios">
  <resource-file src="GoogleService-Info.plist" />
</platform>
```
in package.json added:
```
"phonegap-plugin-push": {
                "SENDER_ID": "XXX"
            }
```
in config.xml added:
```
<plugin name="phonegap-plugin-push" spec="2.0.0">
        <variable name="SENDER_ID" value="XXX" />
    </plugin>
```
and in app.component.ts added:
```
onst options: PushOptions = {
      ios: {
        senderID: 'XXX',
        alert: 'true',
        badge: false,
        sound: 'true'
      }
    };
    const pushObject: PushObject = this.push.init(options);

    pushObject.on('registration').subscribe((data: any) => {
      console.log('device token -> ' + data.registrationId);
    }, err => {
      console.log('error in device registration:', err);
    });
```

On v1 after this steps I received correct FCM regId but don't receive pushes on device. With v2 I received incorrect regId!

**Comment by mifkys** [comment] 2017-07-13 07:45
I got corrected registrationId after manually add GoogleService-Info.plist to Resources folder in Xcode project tree. But I don receive notification again. In FCM console message has status 'Accepted'.

**Comment by FFabiano** [comment] 2017-07-14 07:49
> @macdonst I can't reproduce this problem and there is a good chance the issue is with the older version of iOS you are using. Is it possible for you to upgrade to a newer version of iOS?

I checked on iPad Mini with 10.3.x iOS version, and everything worked fine. You were right, probably it's my iPhone's iOS old version. 
Thank you very much for the support.

> @macdonst If you can't you may just have to work around it. If you get a registration ID with a : in it you can assume it is a FCM token. If it is missing you can assume it is a APNS token then call unregister/init again to generate the FCM token.

It could be a valid workaround for who can't set min version for his project above iOS 7.x.x or must test on it. Personally i will upgrade everything i have to in order to get things right.

**Comment by macdonst** [comment] 2017-07-14 14:50
@FFabiano okay, I'm going to close this issue then. iOS 7 from the latest info I have is only on 1% of all iOS devices out there and I no longer have a test device capable of running iOS7.

**Closed by macdonst** 2017-07-14 14:50 UTC
Labels: can't reproduce, ios, question

**Comment by Kals5** [comment] 2018-03-16 14:03
Here is my IONIC info

cli packages: (/Users/kaldinsolutions2/.webclipse/nodejs/8.5.0/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0 ios 4.5.2
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2 
    Node       : v8.5.0
    npm        : 5.4.2 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro


Here is code to get FCM token 



const options: PushOptions = {
      android: {
        senderID: '1047615971893'
      },
      ios: {
        alert: 'true',
        badge: 'true',
        sound: 'true'
      },
      windows: {}
    };
    const pushObject: PushObject = this.push.init(options);
    pushObject.on('registration').subscribe((data: any) => {
      console.log('device token -> ' + data.registrationId);
      this.user.token = data.registrationId;
});


it generates like this:
fPUhdRK78aI:APA91bFn3lozqE6MKz3WLWzvaFngquYGEmh_hawoachcFlld-
juxljkacmfm1Qg_VoAIJ4meZK7Nps1of22leZ-vXo3csXUAIA1X26WsBPnjV4Af-DGQMFVh-kN56TCw_

but I want it like this:
ceo4f4bed3b29d94c1386761ed65a1fa68c4a5fd82e7495164ebf445

TIA!!

**Comment by jcesarmobile** [comment] 2018-03-16 14:23
That's a FCM token, if you want/need an APNs token then don't use FCM.

**Comment by Kals5** [comment] 2018-03-16 14:55
how to get that APN token it doesn't available directly like FCM token

**Comment by Kals5** [comment] 2018-03-27 12:46
jcesarmobile Can you please tell how can i get it ?

**Comment by Kals5** [comment] 2018-03-27 12:48
@jcesarmobile Can you please tell how can i get that APN token using my code

**Comment by jcesarmobile** [comment] 2018-03-27 13:01
You can't, if you use FCM, you will get the FCM token, that's it.
