### ISSUE TITLE
Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin'] For input string: "11+"

### ISSUE THREAD

**Issue by Losnen** [phonegap/phonegap-plugin-push#2392] opened 2018-05-28 07:50 UTC
#### Cordova CLI version and cordova platform version

    cordova --version                                   8.0.0
    cordova platform version android          android 7.1.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   phonegap-plugin-push 2.2.3 "PushPlugin"

#### Logs taken while reproducing problem
```
ionic cordova buildandroid --prod --release
Running app-scripts build: --prod --platform android --target cordova
[08:41:30]  build prod started ...
[08:41:31]  clean started ...
[08:41:31]  clean finished in 4 ms
[08:41:31]  copy started ...
[08:41:31]  deeplinks started ...
[08:41:32]  deeplinks finished in 803 ms
[08:41:32]  ngc started ...
Warning: Can't resolve all parameters for AngularFirestore in /Users/samuelramosbarroso/Desktop/move-live-smart-app-movil/node_modules/angularfire2/firestore/index.d.ts: ([object Object], ?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for AngularFirestore in /Users/samuelramosbarroso/Desktop/move-live-smart-app-movil/node_modules/angularfire2/firestore/index.d.ts: ([object Object], ?). This will become an error in Angular v6.x
[08:41:45]  ngc finished in 13.59 s
[08:41:45]  preprocess started ...
[08:41:45]  preprocess finished in less than 1 ms
[08:41:45]  webpack started ...
[08:42:01]  copy finished in 30.68 s
[08:43:14]  webpack finished in 88.61 s
[08:43:14]  uglify started ...
[08:43:14]  sass started ...
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSSfile path or to `undefined` to prevent this warning.
[08:43:16]  sass finished in 1.68 s
[08:43:16]  cleancss started ...
[08:43:18]  cleancss finished in 2.09 s
[08:43:44]  uglify finished in 30.00 s
[08:43:44]  postprocess started ...
[08:43:44]  postprocess finished in 39 ms
[08:43:44]  lint started ...
[08:43:44]  build prod finished in 133.46 s
> cordova build android --release
Error: The "path" argument must be of type string

Android Studio project detected

ANDROID_HOME=/Users/samuelramosbarroso/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home
studio
Subproject Path: CordovaLib
Subproject Path: app
publishNonDefault is deprecated and has no effect anymore. All variants are now published.

Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.

The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.

        at build_8rrdlhzd29yav7l65bfx6rpcq.run(/Users/samuelramosbarroso/Desktop/move-live-smart-app-movil/platforms/android/app/build.gradle:151)


FAILURE: Build failed with an exception.

* Where:
Script '/Users/samuelramosbarroso/Desktop/move-live-smart-app-movil/platforms/android/cordova-support-google-services/movelivesmart-build.gradle' line: 16


* What went wrong:
A problem occurred evaluating project ':app'.
>
Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "11+"


* Try:

Run with
--stacktrace
 option to get the stack trace. Run with
--info
 or
--debug
 option to get more log output.


* Get more help at https://help.gradle.org


BUILD FAILED in 1s

(node:60260) UnhandledPromiseRejectionWarning: Error: /Users/samuelramosbarroso/Desktop/move-live-smart-app-movil/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script '/Users/samuelramosbarroso/Desktop/move-live-smart-app-movil/platforms/android/cordova-support-google-services/movelivesmart-build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "11+"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
    at ChildProcess.whenDone (/Users/samuelramosbarroso/Desktop/move-live-smart-app-movil/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Socket.stream.socket.on (internal/child_process.js:353:11)
    at Socket.emit (events.js:180:13)
    at Pipe._handle.close [as _onclose] (net.js:541:12)
(node:60260) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:60260) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[08:43:51]  lint finished in 7.15 s
```

Someone knows the solution?

**Comment by macdonst** [comment] 2018-05-28 12:43
@Losnen This is a duplicate of #1718.

You need to figure out what plugin is pulling in the 11+ dependency and pin it to a proper version. If you let me know what plugin pulls in that dependency I can help send a PR.

**Closed by macdonst** 2018-05-28 12:43 UTC
Labels: duplicate
