### ISSUE TITLE
oficial push plugin and windows and wp8 compatibility

### ISSUE THREAD

**Issue by eduboxgithub** [phonegap/phonegap-plugin-push#71] opened 2015-08-19 14:58 UTC
Is this the new oficial phonegap plugin for push notifications?

The old one seems lost in time with lot of open issues and no updates:
https://github.com/phonegap-build/PushPlugin

I was using the old one, but at this point I can't use it anymore because is in conflict with other plugins I have installed.

Also a noticed this plugin as "windows" platform and no "wp8". 

Can I target the windows platform and use it with other plugins that don't have yet the "windows" platform and only the "wp8" platform?

**Comment by bau720123** [comment] 2015-08-19 16:13
just like @eduboxgithub said
as same as
https://github.com/phonegap/phonegap-plugin-push/issues/56

**Comment by macdonst** [comment] 2015-08-19 16:21
Closing, duplicate of #56

**Closed by macdonst** 2015-08-19 16:21 UTC
