### ISSUE TITLE
Notification appear on Android when application is closed

### ISSUE THREAD

**Issue by gfreire** [phonegap/phonegap-plugin-push#1894] opened 2017-08-09 12:04 UTC
### Expected Behaviour
Notification appear on Android when application is closed

### Actual Behaviour
Notification appear just when application is open in background

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Asus

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

cordova -> 7.0.1
cordova android -> 6.2.3

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3
 2.0.0
#### Sample Push Data Payload

$data = array("title" => $title, "body" => $message, "" => "1");
$fields = array(
        'to' => $regId,
        'data' => $data,
    );

#### Logs taken while reproducing problem

-------

Probably is just a configuration missing, but I not find it, can someone help me on this...
I try use force-start on payload but not working too...

**Comment by macdonst** [comment] 2017-08-09 15:58
@gfreire  Are you saying the notification does not show up in the notification tray when the app is closed? That is, not running?

**Comment by gfreire** [comment] 2017-08-09 22:08
Yes... the notification just appear when the app is open in background.
If I clean the task manager on android, and send the notification, nothing happens... 

As I say this is weird, and probraly I mess up with configurations... I just need some help to solve this...

PS.: sry for bad english...

**Comment by macdonst** [comment] 2017-08-09 23:56
@gfreire can you run `adb logcat | grep Push` when you are reproducing the problem?

**Comment by gfreire** [comment] 2017-08-11 17:16
Now if I open the app with:
> adb logcat | grep Push

> V/Push_Plugin(24874): execute: action=init
> V/Push_Plugin(24874): execute: data=[{"android":{"image":"icon_notification"},"ios":{"alert":"true","badge":"true","sound":"true"}}]
> V/Push_Plugin(24874): execute: jo={"image":"icon_notification"}
> V/Push_Plugin(24874): execute: senderID=xxx
> V/Push_Plugin(24874): onRegistered: {"registrationId":"dL1ajA3-f...","registrationType":"FCM"}
> D/Push_Plugin(24874): no icon option
> D/Push_Plugin(24874): no iconColor option

Put the application on background, but don't close it on task manager.. And send notification again...

> D/Push_FCMService(24874): onMessage - from: xxx
> D/Push_FCMService(24874): normalize extras
> D/Push_FCMService(24874): key = force-start
> D/Push_FCMService(24874): replace key force-start with force-start
> D/Push_FCMService(24874): key = 
> D/Push_FCMService(24874): replace key  with message
> D/Push_FCMService(24874): no locale found for key = message, error Value 1 of type java.lang.Integer cannot be converted to JSONObject
> D/Push_FCMService(24874): key = body
> D/Push_FCMService(24874): replace key body with message
> D/Push_FCMService(24874): no locale found for key = message, error Value hey of type java.lang.String cannot be converted to JSONObject
> D/Push_FCMService(24874): key = title
> D/Push_FCMService(24874): replace key title with title
> D/Push_FCMService(24874): no locale found for key = title, error Value Jaguariuna of type java.lang.String cannot be converted to JSONObject
> D/Push_FCMService(24874): background
> D/Push_FCMService(24874): message =[hey]
> D/Push_FCMService(24874): title =[Jaguariuna]
> D/Push_FCMService(24874): contentAvailable =[null]
> D/Push_FCMService(24874): forceStart =[true]
> D/Push_FCMService(24874): create notification
> E/Push_FCMService(24874): Number format exception - Error parsing notId: Invalid int: "null"
> D/Push_FCMService(24874): stored icon=null
> D/Push_FCMService(24874): stored iconColor=null
> D/Push_FCMService(24874): stored sound=true
> D/Push_FCMService(24874): stored vibrate=true
> D/Push_FCMService(24874): no icon resource found - using application icon
> D/Push_FCMService(24874): create actions: with in-line

**Comment by gfreire** [comment] 2017-08-11 17:24
And the server always return a success message
`dL1ajA3-f-....
{"multicast_id":7254340635317676916,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1502471684763715%7840d3b2f9fd7ecd"}]}`

**Comment by gfreire** [comment] 2017-08-14 19:07
I still got problem with this issue, can someone help me find the solution.
Thanks in advance

**Comment by macdonst** [comment] 2017-08-14 21:28
@gfreire I can't reproduce this problem at all. I don't have an ASUS device but can you reproduce this on another phone?

**Comment by kirill001** [comment] 2017-08-30 15:20
I have the same problem. Moreover, many features like summaryText, actions, style="inbox" etc aren't working. I can see that data comes to my phone, but it is just ignored. I'm using last version of cordova and this library. Android 6.2, Xiaomi redmi 4. I have no idea how to fix it. Please help!

**Comment by ibrahimAboelsuod** [comment] 2017-10-16 16:14
I have the same issue on a Hisense device. Seems to be this [one](http://docs.telerik.com/platform/knowledge-base/troubleshooting/troubleshooting-cannot-receive-push-notifications-on-android-when-the-app-is-closed).

**Comment by macdonst** [comment] 2017-11-27 21:05
Closing, can't reproduce.

**Closed by macdonst** 2017-11-27 21:05 UTC
Labels: android, can't reproduce, question
