### ISSUE TITLE
Bug - Script 'Desktop/myApp/platforms/android/phonegap-plugin-push/app-push.gradle' line: 38

### ISSUE THREAD

**Issue by HamzaLJ** [phonegap/phonegap-plugin-push#1883] opened 2017-08-02 23:32 UTC
I have an IONIC 3 project, and I am getting the below errors when I install phonegap-plugin-push and try to build the project in Ionic.

### Expected Behaviour

Should build with no error

### Actual Behaviour

It throws the below error:

`✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.
        
[ERROR] An error occurred while running cordova build android (exit code 1):
        
        ANDROID_HOME=/Users/Hamza/Library/Android/sdk
        JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home
        Subproject Path: CordovaLib
        NDK is missing a "platforms" directory.
        If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to
        /Users/Hamza/Library/Android/sdk/ndk-bundle.
        If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this
        warning.
        
        
        FAILURE: Build failed with an exception.
        
        * Where:
        Script '/Users/Hamza/Desktop/myApp/platforms/android/phonegap-plugin-push/app-push.gradle' line: 38
        
        * What went wrong:
        A problem occurred evaluating root project 'android'.
        > Failed to apply plugin [id 'com.google.gms.google-services']
        > For input string: "+"
        
        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
        
        BUILD FAILED
        
        Total time: 1.778 secs
        Error: /Users/Hamza/Desktop/myApp/platforms/android/gradlew: Command failed with exit code 1 Error
        output:
        FAILURE: Build failed with an exception.
        
        * Where:
        Script '/Users/Hamza/Desktop/myApp/platforms/android/phonegap-plugin-push/app-push.gradle' line: 38
        
        * What went wrong:
        A problem occurred evaluating root project 'android'.
        > Failed to apply plugin [id 'com.google.gms.google-services']
        > For input string: "+"
`

#### Steps to Reproduce 

Just install the last version of phonegap-plugin-push rc5 and try to build the android project.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Ionic 3

Android 5, 6, 7

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Emulator
Real device & Samsung S7

#### Cordova CLI version and cordova platform version

    cordova --version   : 7.0.1
    cordova platform version android   :   6.2.3      

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push  :  **2.0.0.rc5**

**Comment by macdonst** [comment] 2017-08-03 02:47
Duplicate of #1718

**Closed by macdonst** 2017-08-03 02:47 UTC
