### ISSUE TITLE
Not receiving notifications on iOS when using an adhoc distribution certificate/provisioning profile

### ISSUE THREAD

**Issue by jcus0006** [phonegap/phonegap-plugin-push#938] opened 2016-05-27 21:54 UTC
### Expected Behaviour

To my knowledge the app should register and also receive notifications with this configuration. Details in 'Reproduce Scenario' section. 

### Actual Behaviour

The app is registering. I can see the registration with the PNS identifier and the Registration ID in Azure. However, when sending push notifications (that are received on same devices using development config) are not received using the distribution (ad-hoc) certificate/provisioning profile.

### Reproduce Scenario (including but not limited to)

I created the certificate and the provisioning profile based on an App Id which has both development and production enabled push notification settings.

First I was trying the App Store distribution provisioning profile (but then I realised that kind of provisioning profile is only suitable for sending to App Store - in fact I wasnt managing to deploy), then I realised I could use Ad-hoc and specify the devices that I was going to deploy on: which I did. I got the .p12 to upload into Azure and uploaded it in Azure. 

Using this configuration, the app deploys and runs properly, the push plugin manages to register and I can see the registration in the Notification Hub on Visual Studio, including the PNS identifier and the registration id.  When sending a push from the backend service I have developed, and even from Azure debug or Visual Studio test send (in notification hub), nothing happens neither when in app and neither when the app is running in the background or closed. 

I was building/deploying via taco remote build but I also tried to upload the app on diawi.com and install it from there; a possible fix which I found online that didn't solve the problem.

My question is: should I be receiving notifications using ad-hoc and the above-mentioned configuration? Is there something that I could be missing? I saw something about .pem files, I also found code that can be done in the terminal that actually creates a pem file; which I did, but have no idea what to do with. Is the pem something I need or is it completely irrelevant? 

Remember that Im managing to work properly (both registering and receiving) using the Development build and development configuration. Please help :)

Please note: I am unsure if this is an issue with the Push Plugin when working with this specific kind of config or a problem with the certificates/provisioning profile itself. I would be able to provide more info if useful to assess my situation.

#### (iOS) What device vendor/type

Apple iPhone 6, Apple iPad 4 (latest versions)

#### Cordova CLI version and cordova platform version

    Cordova 6.2.0

#### Plugin version

    1.6.4

**Comment by raphaguasta** [comment] 2016-06-01 00:03
I have a similar problem. My push notifications works in development, but in production does not work, even with their corrects certificates, the application does not receive the push.

**Comment by jcus0006** [comment] 2016-06-01 08:16
I did not find any help regarding our problem yet @raphaguasta. Let's hope someone gives us some insight in here. There could be a very small detail that we're missing

**Comment by ngystvn90** [comment] 2016-06-02 13:22
have you tried to set gcmSandbox: false for production?

**Comment by raphaguasta** [comment] 2016-06-02 13:46
Hello Guys!

@ngystvn90 I made another submission to store, now with gcmSandbox:false.

I'm waiting for application approval, if works I'll tell you.

Thanks!

**Comment by macdonst** [comment] 2016-06-02 14:31
@raphaguasta yeah, when you are submitting the app to the app store the gcmSandbox must be set to false. If not the app will register with the wrong APNS service.

**Comment by jcus0006** [comment] 2016-06-02 15:13
In my case my problem was not even with an App Store certificate. I was using an ad-hoc certificate (a release certificate which can only be used on pre-registered devices) and I did not want to send it to App Store just yet. Does the same apply regarding the gcmSandbox? Im managing to register but not receive notifications.

**Comment by oussaki** [comment] 2016-06-08 06:02
Hi  guys , 
the registration done successfully an i received the Registration ID in my database 
but when i send a notification i received nothing , 
what should i do , and what is this  gcmSandbox:false is ? 

thank you

**Comment by ngystvn90** [comment] 2016-06-08 06:10
If you are using a development pem file in your backend you should use _gcmSandbox:true_ and you sould send notifications via _ssl://gateway.sandbox.push.apple.com:2195_ . If you are using a production pem file you should build your project with _gcmSandbox:false_ and use _ssl://gateway.push.apple.com:2195_ at your backend. Also if registration is successfull than check if you can connect to APNS, if not then probably your notification certificate isn't correct. I spent almost a week figuring out the right combination for ios notifications...

**Comment by ngystvn90** [comment] 2016-06-08 06:17
I recommend [this ](https://www.raywenderlich.com/123862/push-notifications-tutorial) tutorial for generating the pem file see below **Creating an SSL Certificate and PEM file** and [this ](http://codular.com/sending-ios-push-notifications-with-php)for APNS with PHP

**Comment by oussaki** [comment] 2016-06-08 06:18
@ngystvn90  Im using a production certification i already deploy the app on app store , 
im sending notification using a PHP script in my backend , for android it send very normal , 
i uploaded my pem file to Google GCM , so i think when we use this plugin it send the request to GCM and GCM forward it to APNs , i'll check the links you sent to me , and ill back to you . 
thank you

**Comment by oussaki** [comment] 2016-06-08 07:35
This is my PHP code in the backend 
https://gist.github.com/oussaki/c5dfd0ddef6e8d7a7cc56debe3139146
i don't know maybe i have to change something there .

**Comment by ngystvn90** [comment] 2016-06-08 07:49
I am using APNS for iOS and GCM for android. I never tried to use GCM for iOS...

**Comment by oussaki** [comment] 2016-06-08 08:15
Thank you for help , hope someone came here and give us away of how to do this using GCM .

**Comment by oussaki** [comment] 2016-06-08 09:27
I just noticed that the Regisration ID is different in IOS than android 
for android the ID is a bit shorter like this a63fc3e37407336ed1fc143049209f260745c6e3e029cfe2f45a518d97797433 

and for Android it looks like this one : 
APA91bFuyWfNvxZ94bO0JXJXWOZHVBC3IEayb7TCxYVjh8rIO8jJCAfwXho9DAprWX_Y51IDte7ScMRmFhIaKbqf78mY4xuyygJ3QjZ8lvl1DhgCvaAQYmWPk6cMmzCXUbT8LZMMOwgT

i've tried to send a broadcast notification and i only received the notification in android .

**Comment by ngystvn90** [comment] 2016-06-08 09:35
What are your options for registering to pushnotifications? 
If you are using

`var options = {};
options.ios = {
	alert: true,
	badge: true,
	sound: true,
	gcmSandbox: false,
};`

than you are registering to APNS with iOS

If you are using: 

`var options = {};
options.ios = {
	**senderID: 'xxxxx',**
	alert: true,
	badge: true,
	sound: true,
	gcmSandbox: false,
};`

than you are registering to GCM with iOS.

I am using my first example and the php tutorial for APNS that a linked above.

**Comment by oussaki** [comment] 2016-06-08 10:06
I think i missed to use gcmSandbox: false  in my params .

**Comment by oussaki** [comment] 2016-06-08 10:14
@raphaguasta : Anything new with your submision , are using the same code in your backend to send notifications for both IOS and Android ?

**Comment by Remskei** [comment] 2016-06-08 10:17
I have the same issue. The registration works but no notification appears on iOS. And when I try to add senderID: 'xxxxxxxxx' in ios options, the registration fail.

**Comment by oussaki** [comment] 2016-06-08 10:22
@Remskel : Are u putting gcmSandbox: false ? because in my current configuration i did put gcmSandbox: false and the the senderId was in the configuration and the Regisration event was working 
but not receiving any notification .

**Comment by Remskei** [comment] 2016-06-08 10:34
@oussaki : Yes, I tried but when I add the option senderID: "myId", the registration fail in my database. But when I don't put the senderID, it works...

This is my code :

`item = {};
    var push = PushNotification.init({
        android: {},
        ios: {
            senderID: "xxxxxxxx",
            alert: true,
            badge: true,
            sound: true,
            gcmSandbox: false
        },
        windows: {}
    });

    push.on('registration', function(data) {
        item["registrationID"] = data.registrationId;

        $.post(SERVER + "notification.php", item, function(data) {});
    });`

**Comment by oussaki** [comment] 2016-06-08 10:42
Did you upload the p12 to the GCM ? from the Google Cloud Messaging panel ?

**Comment by Remskei** [comment] 2016-06-08 11:16
@oussaki I forgot it 👍  Now the registration works thank you. But now I've the same issue that you have, no notification appears.

**Comment by Remskei** [comment] 2016-06-08 15:03
@oussaki : Did you find something?

**Comment by oussaki** [comment] 2016-06-08 17:39
No bro , i'm waiting for the approval of my app in play store , to try the new configuration . my xcode 6.4  only deploy directly to under 8 version .

**Comment by raphaguasta** [comment] 2016-06-08 17:57
Guys! @oussaki... My notification works!

I was forgetting the "gcmSandbox: true", and did not request the file on google console.

My summary of everything for you is:

- Request certificates and profiles for production
- Get the configuration file from Google: https://developers.google.com/cloud-messaging/ios/start
- Install and configure the plugin to production
- Include the Google configuration file to your project

Thanks to all of you for your help!

**Comment by oussaki** [comment] 2016-06-08 18:13
@raphaguasta : Congrats !! , Can you please share with us here your php backend and your javascript configuration ? 
and what do you mean by include the google configuration to your project ! how is that

**Comment by raphaguasta** [comment] 2016-06-08 18:23
@oussaki 

My registration in the app:

`var push = PushNotification.init({
        "android": {
          "senderID": 'XXXXX'
        },
        "ios": {
          "senderID": 'XXXXX',
          "alert": "true",
          "badge": "true",
          "sound": "true",
          "gcmSandbox":"false"
      }
    });`

My array to the GCM service is:
`'registration_ids' => $devices,
            'priority' => 'high',
            'notification' => array(
                'title' => $title,
                'body' => $message,
                'priority' => 'high',
                'content-available' => '1'
            )`

About the configuration file, follow the step 2 from this link: [https://developers.google.com/cloud-messaging/ios/start](url), everything is documented on this site!

**Comment by Remskei** [comment] 2016-06-08 19:07
Nice to hear it works 😉. I'll try it tomorrow. You tested on development or production?

**Comment by raphaguasta** [comment] 2016-06-08 19:16
It worked in development AND in production 👍  =)

**Comment by Remskei** [comment] 2016-06-08 19:18
Nice :) Thank you for sharing. I'll try tomorrow.

**Comment by oussaki** [comment] 2016-06-08 19:54
@raphaguasta  Thank you man ,  my javascript configuration is the same like yours 
seems like i missed some fields in the GCM Arrray like ( 'priority' => 'high', 'content-available' => '1' ) Especially content-available . ill try tommorow . thank you

**Comment by oussaki** [comment] 2016-06-09 05:31
@raphaguasta  for ios registration ID's can give an example of an ID you received ? 
is it looks like the ones of android ?

**Comment by oussaki** [comment] 2016-06-09 07:00
Guys maybe this is a dumb question but what version you guys are using ?

**Comment by Remskei** [comment] 2016-06-09 08:22
Hi, for me it's still not working... For the configuration file, did you use CocoaPods ?
@oussaki : For me, ios registration ID's look like Android ones. It looks like this : 

`mnAGYjVW9dI:APA91bGuozAhc8aFAsiDiiwGvgohdENNr-18g2IXghHjgFK-OORJApsr2J8vAU1r8cV_qxm8UyqJH1way7fKSNhAt_yljmsbwgKXEGyChP0V-xTjpoXmZuzcAprPfNUt-u0Lw_aTg3fk`

**Comment by oussaki** [comment] 2016-06-09 08:28
@Remskei  im still having the same issue , my iOS ID's have a length of 64 , the JS configuration is correct also i uploaded the P12 file to GCM , i don't know but maybe because im using the version 1.3 of this plugin ! , @macdonst do you think it's because of using the version 1.3 of this plugin !

**Comment by Remskei** [comment] 2016-06-09 08:42
@oussaki Why you don't try to update? I've just did it and same thing. It's ok on Android but not in iOS...

**Comment by Remskei** [comment] 2016-06-09 13:32
@raphaguasta I think it's not working for me cause of my php function format. Can you share me your php code please?

**Comment by Remskei** [comment] 2016-06-09 14:27
@oussaki Ok I got it working now. It was my php code. I had to use notification instead of data. Now it works on Android and iOS but I have another issue 👍  The ledColor is not working anymore on Android...

`'notification' => array( 'title' => $title, 'body' => $message, 'priority' => 'high', 'content-available' => true`

**Comment by raphaguasta** [comment] 2016-06-10 01:55
@oussaki The Apple registration ID that i receive is like _11characters:140characters_

**Comment by jcus0006** [comment] 2016-06-10 09:49
This was originally my question, however, it has deviated so much from my original problem and I am not sure I can relate with what you are talking about in the thread. First of all, why are you using GCM for iOS? I signed my app with an Apple production certificate, I created the certificates for push notifications which I uploaded into Azure. Like this it has always worked in development mode. However, I couldn't make it work when using an ad-hoc production certificate. What happens is that the iOS devices successfully register every time but I cant receive any notification. In my case, since I am pretty sure that I am only using GCM for Android, I am guessing that the gcmSandbox:false setting would be in vain. BTW, I am developing using Cordova and I have no php backend. Do I still need this .pem file?

**Comment by oussaki** [comment] 2016-06-12 06:33
@raphaguasta Please can you tell me the steps you did after you export that .plist file from GCM ? 
i just put it in the root folder of the project , and i don't know what next to do .

**Comment by raphaguasta** [comment] 2016-06-12 18:43
@oussaki About the .plist from the GCM is just this!

**Comment by oussaki** [comment] 2016-06-13 05:13
@raphaguasta Yes about the .plist , i dont know if this is enough because i've seen that lot of people talks about adding this plist to all targets and i don't know what is exactly that .

**Comment by raphaguasta** [comment] 2016-06-13 13:57
@oussaki I don`t know about this... In my project i just added the file to the root in my xcode and works.

**Comment by jcus0006** [comment] 2016-06-16 12:27
Still have the problem (original post). Not receiving notifications when signing the iOS app with an Adhoc provisioning profile. I dont use GCM for iOS, I use APNS. Im afraid that when signing with the App Store certificate the same will happen. Any help: @macdonst ?

**Comment by macdonst** [comment] 2016-06-16 15:22
@jcus0006 I don't know what to tell you. I can't reproduce the problem but I sympathize with you as the whole Apple certificate process is screwed up.

**Comment by jcus0006** [comment] 2016-06-16 15:30
@macdonst Thanks a lot anyways. Finally, I managed to fix the problem. I recreated the .p12 file, re-uploaded into Azure and it worked. 

What I could have done differently this time round that somehow fixed the problem is this (though not sure how much sense it makes).

In the keychain of my macbook I was creating the .p12 file by exporting the **certificate** and not the **key**. When I tried today, initially, I did the same thing. Thankfully, the Azure portal started giving me an error. What is weird is that last time it seemed to have uploaded the .p12 file successfully into Azure and gave me no error (even if I had created it out of the certificate and not the key).

For someone who might have had a similar problem, the answer in this question could possibly be of help: 
http://stackoverflow.com/questions/23190517/azure-notification-hub-unable-to-upload-p12-for-apn

**Comment by macdonst** [comment] 2016-06-16 16:50
@jcus0006 whelp, I'm glad you were able to fix it. I'm going to close this issue as you as the original reported got it resolved.

**Closed by macdonst** 2016-06-16 16:50 UTC
Labels: ios, question

**Comment by Assylkhan** [comment] 2017-01-04 10:49
Hi @raphaguasta, do you get senderId from GoogleService-info.plist(is it GCM_SENDER_ID field)? When I paste it here "ios": { "senderID": "here"}, I run and get 401 error.

**Comment by jawad-aziz-farhad** [comment] 2017-01-31 12:22
Thanks to @ngystvn90 for his comment and guidance.
I got the solution by changing this Link:
ssl://gateway.sandbox.push.apple.com:2195
to 
ssl://gateway.push.apple.com:2195.

voila... :-)

**Comment by Appuploader** [comment] 2017-07-01 09:56
Share Appuploader tool only need to enter the iOS certificate name, password can quickly apply for iOS certificate. P12 and ..mobileprovision iOS certificate file

But also in the Windows system directly apply for iOS certificate

https://github.com/Appuploader/applicationloader
