### ISSUE TITLE
Background processing with coldstart on iOS

### ISSUE THREAD

**Issue by kukikiloke** [phonegap/phonegap-plugin-push#583] opened 2016-02-05 22:36 UTC
First of all thanks for the great work!

I have a question/request and the scenario is as follows:
I set `content-available: 1` to allow notification callback to be run in background to fetch some data even the user does not click on the push notification but directly launch the app.
There is something I want to do (e.g. go to view ABC) based on whether the user clicks on the notification to launch the app.
As there is no different event being fired on receiving push notification and on clicking on the push notification, I rely on Cordova app **pause** and **resume** events to know if the callback is run in background to achieve that. (little hack)

However, if the app is killed or some equivalent event, the notification callback will be run when the user launches the app and the little hack won't work and the app will always go the view ABC regardless of if the user clicks on the notification.

I'm aware that `coldstart` information has been added on Android recently and this field will always present when the user clicks on the push notification, I can make use of this to differentiate when the user clicks on the push.

Will there be any plan for that to be added on iOS as well?

This is related to https://github.com/phonegap/phonegap-plugin-push/issues/501. If that is solved then we will have means to differentiate between receiving push notification and clicking on push notification.

Thanks again!

**Comment by macdonst** [comment] 2016-02-07 15:10
@kukikiloke so basically you want to know if the app has been started by the push notification on both iOS and Android, so `coldstart`? I'm going to mark this as a duplicate of #501, correct me if that's wrong.

**Comment by macdonst** [comment] 2016-02-08 03:41
I'm going to add `coldstart` to iOS.

**Comment by kukikiloke** [comment] 2016-02-08 04:32
Awesome! Thanks a lot for the great work!

**Closed** 2016-03-09 00:17 UTC
Labels: enhancement, ios
