### ISSUE TITLE
push.on('registration',  not fired in iOs + APNS

### ISSUE THREAD

**Issue by vousys** [phonegap/phonegap-plugin-push#1136] opened 2016-08-02 15:02 UTC
Hi Simon! I gave up with GCM in ios, they're not working for me. 
I'm trying with APNS but the registration event, never gets fire.

Certificate to push in apple sandbox : OK
Pem in server: OK
Device profile to compile and test: OK

Events:
Init:  fires OK
unregister: works fine
registration: never gets call

#### Device 
Ipad ios 9.0.3

#### Cordova CLI version and cordova platform version

    cordova --version                                    cli-6.3.0   (via phonegap build web)
    
#### Plugin version                                    ~1.8.0

This is my config.xml

```
    <preference name="phonegap-version" value="cli-6.3.0" /> 
    <preference name="android-build-tool" value="gradle" />
    <preference name="android-minSDKVersion" value="17" />
    <preference name="android-maxSDKVersion" value="" />
    <preference name="android-targetSdkVersion" value="12" />  
    <preference name="target-device" value="universal" />
    <preference name="deployment-target" value="8" />    
    <preference name="permissions" value="none"/> 
    <preference name="orientation" value="auto" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="fullscreen" value="false" />
    <preference name="android-installLocation" value="auto" />
    <preference name="show-splash-screen-spinner" value="true" />
    <preference name="auto-hide-splash-screen" value="true" />
    <preference name="splash-screen-duration" value="2500" />
    <preference name="exit-on-suspend" value="false" />
    <preference name="load-url-timeout" value="25000" />
    <preference name="EnableViewportScale" value="true" />

    ... some plugins...

   <gap:plugin name="phonegap-plugin-push"  spec="~1.8.0" source="npm">
        <param name="SENDER_ID" value="XXXXX"/>
    </gap:plugin>  
```

in my  onDeviceReady function: 

```
			 push = PushNotification.init({
				"android": {
					senderID: api.gcm_sender_id  // Es el ID del proyecto en la consola de GCM
				},
			    "ios": {
			    	/*senderID: api.gcm_sender_id,  si lo agrego sale por GCM */
			        "sound": true,
			        "alert": true,
			        "badge": true
			    }
			});

	 
 

			push.on('registration', function(data) {
				 alert("registration event");
			});

			push.on('notification', function(data) {
				// data.message,
				// data.title,
				// data.count,
				// data.sound,
				// data.image,
				// data.additionalData

					navigator.notification.alert(
							data.message,         // message
							null,                 // callback
							data.title,           // title
							'Ok'                  // buttonName
					);


					// do something with the push data
					// then call finish to let the OS know we are done
					push.finish(function() {
						 // Do something
					});


			});

			push.on('error', function(e) {

				if (e.code != 7) {
				   modal_errores(e.message);

				}	
				// e.message
			});
```

I've also try compiling with cli-6.1.0 and push plugin version ~1.6.2  but happens the same.
¿what else can I do?

**Comment by macdonst** [comment] 2016-08-02 17:32
@vousys can you run the project in Xcode and collect the logs? They may be able to tell us more.

**Comment by vousys** [comment] 2016-08-02 17:37
no, I don't have it.  :(

can I debug the plugin in other way?


​
Salu2!

Vero | *VOUSYS.com*
<http://www.vousys.com/>

VOUSYS.com Office: Buenos Aires, Argentina | +54.011.4481-3751

http://www.vousys.com     [image: Facebook]
<https://www.facebook.com/vousys> [image: Twitter]
<http://www.twitter.com/vousys> [image: Google Plus]
<https://plus.google.com/u/0/b/111673332818765301661/+Vousys/posts> [image:
Pintrest] <http://www.pinterest.com/vousys/> [image: Skype]
<https://www.vousys.com/> <https://www.vousys.com/exportador>
<http://www.tusfacturas.com.ar/> <http://www.e-xpensas.com/>
<http://www.micampeonato.com/>




2016-08-02 14:32 GMT-03:00 Simon MacDonald <notifications@github.com>:

**Comment by macdonst** [comment] 2016-08-02 17:42
@vousys it seems like it is a problem with the certificate/mobile provisioning. Xcode would actually log these errors.

**Comment by nicolastakashi** [comment] 2016-08-02 18:53
I'v the same issue now!

I'm trying use with APNS but the registration event is never fired

Below is the code that I used

`var push;
        if (device.Platform.isAndroid()) {
          push = window.PushNotification.init({
            android: {
              senderID: "722176105754"
            },
            ios: {
              alert: "true",
              badge: true,
              sound: 'false'
            }
          });
        }

        if (device.Platform.isIOS()) {
          push = window.PushNotification.init({
            ios: {
              alert: "true",
              badge: true,
              sound: 'false'
            }
          });
        }


        push.on('registration', function(data) {
          console.log("Device Token:" + data.registrationId);
        });`

**Comment by aymanstar** [comment] 2016-08-03 03:10
same here , registration: never gets call

**Comment by macdonst** [comment] 2016-08-03 11:58
@nicolastakashi @aymanstar same comment as before, try running the app in Xcode to see what it is complaining about. In 99.45% of these cases it is a problem with certificate/mobile provisioning.

**Comment by eclark887** [comment] 2016-08-04 21:42
I'm having the same issue.

**Comment by DympyDev** [comment] 2016-08-05 07:36
I am also having this issue, I have ensured I have Push enabled for Development and have created a new Development certificate. When I call the init method, this is what I see in my xCode log:

> 2016-08-05 09:32:37.419 Sparta App[1190:1233575] Finished load of: file:///var/containers/Bundle/Application/BB9D689C-4CD1-4BBE-9704-86F8AF2E2A10/Sparta%20App.app/www/index.html
2016-08-05 09:32:37.474 Sparta App[1190:1233628] Push Plugin register called
2016-08-05 09:32:37.474 Sparta App[1190:1233628] PushPlugin.register: setting badge to false
2016-08-05 09:32:37.474 Sparta App[1190:1233628] PushPlugin.register: clear badge is set to 0
2016-08-05 09:32:37.474 Sparta App[1190:1233628] PushPlugin.register: better button setup
2016-08-05 09:32:37.474 Sparta App[1190:1233628] GCM Sender ID (null)
2016-08-05 09:32:37.475 Sparta App[1190:1233628] Using APNS Notification
2016-08-05 09:32:37.486 Sparta App[1190:1233575] Unexpected call to didRegisterForRemoteNotificationsWithDeviceToken, ignoring: <0df31559 eff84231 b69ae998 08e6358b c5934ae5 4c6134b3 3623b6c8 83628ad9>

The registration callback is never fired, so I think it's because of the unexpected call to didRegisterForRemoteNotifications?

**Comment by macdonst** [comment] 2016-08-06 15:47
@DympyDev well that's interesting. Can you share some code on how you got yourself into that situation. You shouldn't really be able to reach it: 

https://github.com/phonegap/phonegap-plugin-push/blob/4cd4ee00e2eb081d0d29d001e580009fba5c341a/src/ios/PushPlugin.m#L353

**Comment by chph63** [comment] 2016-08-08 10:42
Hi,
It was working fine until I renewed my Apple Developer Membership.
Now it doesn't register even if xCode log seems to do it.
2016-08-08 11:30:43.859 Pizza Royers[282:25608] Apache Cordova native platform version 3.9.2 is starting.
2016-08-08 11:30:46.949 Pizza Royers[282:25608] active
2016-08-08 11:30:46.950 Pizza Royers[282:25608] PushPlugin skip clear badge
2016-08-08 11:30:47.230 Pizza Royers[282:25608] Resetting plugins due to page load.
2016-08-08 11:30:47.728 Pizza Royers[282:25608] Finished load of: file:///var/mobile/Containers/Bundle/Application/28F4BB93-71D3-4B2B-AAD3-5464F97EC87E/Pizza%20Royers.app/www/index.html
2016-08-08 11:30:48.443 Pizza Royers[282:25683] Push Plugin register called
2016-08-08 11:30:48.443 Pizza Royers[282:25683] PushPlugin.register: setting badge to false
2016-08-08 11:30:48.444 Pizza Royers[282:25683] PushPlugin.register: clear badge is set to 0
2016-08-08 11:30:48.444 Pizza Royers[282:25683] PushPlugin.register: better button setup
2016-08-08 11:30:48.444 Pizza Royers[282:25683] GCM Sender ID (null)
2016-08-08 11:30:48.444 Pizza Royers[282:25683] Using APNS Notification
2016-08-08 11:30:48.466 Pizza Royers[282:25608] Push Plugin register success: <94d991d1 f0c25025 efda256e 11bb7736 dd267465 d67b78a9 c012d38b 5dfccf15>

What I am doing wrong?

Thank you for your cooperation

**Comment by DympyDev** [comment] 2016-08-08 10:50
@macdonst
I'm using ES6 in combination with Babel, along with Angular 1.5.x (not sure which specific version).
My code basically looks like this (gist link, because the comment won't format the code correctly): https://gist.github.com/DympyDev/d6230eb3d4cc24f9620603f45b184faf

I'm trying to use APNS, not GCM, and the main target right now is iOS. We have had working applications (fully native) with our own push server, and from what I can see the provisioning profiles are set up correctly.

**Comment by janthonyeconomist** [comment] 2016-08-08 18:35
I think I may be experiencing a similar problem.  If I uninstall the app and rebuild, the on('registration') callback will fire exactly once; however, it won't fire on subsequent opening of the app and the off('registration') won't fire either.

Is this the intended behavior?  ... so I would have to store the registrationId permanently or forever lose it?  What happens if I want to allow the user to unsubscribe to push notifications?

**Comment by vousys** [comment] 2016-08-11 12:35
Hi @macdonst! could you find, any fix to this issue?

**Comment by janthonyeconomist** [comment] 2016-08-11 12:41
I was wrong about it not firing on subsequent opening; however, it still seems the case that after you off('registration'), and the re- on('registration'), the registration event handler is not fired.  I got around this by storing the registrationId on the client side, so even if the registration callback does not fire, I can still resend the registrationId to my notifications server.

**Comment by vousys** [comment] 2016-08-11 12:57
mmm but if it never gets fire, you won't recive any notification, or am I
wrong?


​
Salu2!

Vero | *VOUSYS.com*
<http://www.vousys.com/>

VOUSYS.com Office: Buenos Aires, Argentina | +54.011.4481-3751

http://www.vousys.com     [image: Facebook]
<https://www.facebook.com/vousys> [image: Twitter]
<http://www.twitter.com/vousys> [image: Google Plus]
<https://plus.google.com/u/0/b/111673332818765301661/+Vousys/posts> [image:
Pintrest] <http://www.pinterest.com/vousys/> [image: Skype]
<https://www.vousys.com/> <https://www.vousys.com/exportador>
<http://www.tusfacturas.com.ar/> <http://www.e-xpensas.com/>
<http://www.micampeonato.com/>




2016-08-11 9:41 GMT-03:00 Judah Anthony <notifications@github.com>:

**Comment by janthonyeconomist** [comment] 2016-08-11 13:29
That's where I think my bug is slightly different than yours.  Mine does initially fire; just not subsequently.

**Comment by an-rahulpandey** [comment] 2016-08-18 12:22
Having the same issue with the current version of the plugin on iOS 9.3.1. 
push.on('registration', regData) never get called, not able to get the device token because of it.

This is the log from Xcode - 

```
2016-06-29 17:20:50.894 Demo[301:26671] createNotificationChecker
2016-06-29 17:20:50.894 Demo[301:26671] not coldstart
2016-06-29 17:20:50.915 Demo[301:26671] active
2016-06-29 17:20:50.916 Demo[301:26671] PushPlugin skip clear badge
2016-06-29 17:20:51.486 Demo[301:26671] Resetting plugins due to page load.
2016-06-29 17:21:11.339 Demo[301:26877] void SendDelegateMessage(NSInvocation *): delegate (webView:runJavaScriptAlertPanelWithMessage:initiatedByFrame:) failed to return after waiting 10 seconds. main run loop mode: kCFRunLoopDefaultMode
2016-06-29 17:21:12.415 Demo[301:26671] Finished load of: file:///var/containers/Bundle/Application/12D4824C-D04D-4060-A6B2-6B320E7A5D97/Demo.app/www/index.html#/start
2016-06-29 17:21:13.040 Demo[301:26859] Push Plugin register called
2016-06-29 17:21:13.040 Demo[301:26859] PushPlugin.register: setting badge to false
2016-06-29 17:21:13.041 Demo[301:26859] PushPlugin.register: clear badge is set to 0
2016-06-29 17:21:13.041 Demo[301:26859] PushPlugin.register: better button setup
2016-06-29 17:21:13.042 Demo[301:26859] GCM Sender ID (null)
2016-06-29 17:21:13.043 Demo[301:26859] Using APNS Notification
2016-06-29 17:21:15.432 Demo[301:26671] active
2016-06-29 17:21:15.432 Demo[301:26671] PushPlugin skip clear badge
```

**Comment by an-rahulpandey** [comment] 2016-08-19 07:27
Has anyone able to solve it? 
I am trying to make it work on my iPhone since last two days.

**Comment by vousys** [comment] 2016-08-19 11:22
no, it's not working for me


​
Salu2!

Vero | *VOUSYS.com*
<http://www.vousys.com/>

VOUSYS.com Office: Buenos Aires, Argentina | +54.011.4481-3751

http://www.vousys.com     [image: Facebook]
<https://www.facebook.com/vousys> [image: Twitter]
<http://www.twitter.com/vousys> [image: Google Plus]
<https://plus.google.com/u/0/b/111673332818765301661/+Vousys/posts> [image:
Pintrest] <http://www.pinterest.com/vousys/> [image: Skype]
<https://www.vousys.com/> <https://www.vousys.com/exportador>
<http://www.tusfacturas.com.ar/> <http://www.e-xpensas.com/>
<http://www.micampeonato.com/>




2016-08-19 4:27 GMT-03:00 Rahul Pandey <notifications@github.com>:

**Comment by an-rahulpandey** [comment] 2016-08-19 11:47
Hope @macdonst can help us here. I just ended up recreating all the certificates, but still not getting the token. I am using APNS.

**Comment by vousys** [comment] 2016-08-19 13:32
I regenerate all the certificates but never gets fire the registration
event.
Also happens to me in android.

All of us are using   plugin name="phonegap-plugin-push"  spec="~1.8.0"
 and phonegap-version"  ="cli-6.3.0  ??


​
Salu2!

Vero | *VOUSYS.com*
<http://www.vousys.com/>

VOUSYS.com Office: Buenos Aires, Argentina | +54.011.4481-3751

http://www.vousys.com     [image: Facebook]
<https://www.facebook.com/vousys> [image: Twitter]
<http://www.twitter.com/vousys> [image: Google Plus]
<https://plus.google.com/u/0/b/111673332818765301661/+Vousys/posts> [image:
Pintrest] <http://www.pinterest.com/vousys/> [image: Skype]
<https://www.vousys.com/> <https://www.vousys.com/exportador>
<http://www.tusfacturas.com.ar/> <http://www.e-xpensas.com/>
<http://www.micampeonato.com/>




2016-08-19 8:47 GMT-03:00 Rahul Pandey <notifications@github.com>:

**Comment by vousys** [comment] 2016-08-19 13:56
GUYS ! I've FIXED    :)

I removed the  spec="~1.8.0"  from the config.xml  , then I regenerated all
the certificates (sandbox, production and  APNS for production & sandbox).
I change this line from the code (note the " "  in the "true" )

var push = PushNotification.init({
   android: {
       senderID: config.gcm_sender_id
   },

   ios: {
       alert: "true",
       badge: "true",
       sound: "true"
   }
});

I recompile it and is registering in both platforms: android and iOs

and is working   :)






​
Salu2!

Vero | *VOUSYS.com*
<http://www.vousys.com/>

VOUSYS.com Office: Buenos Aires, Argentina | +54.011.4481-3751

http://www.vousys.com     [image: Facebook]
<https://www.facebook.com/vousys> [image: Twitter]
<http://www.twitter.com/vousys> [image: Google Plus]
<https://plus.google.com/u/0/b/111673332818765301661/+Vousys/posts> [image:
Pintrest] <http://www.pinterest.com/vousys/> [image: Skype]
<https://www.vousys.com/> <https://www.vousys.com/exportador>
<http://www.tusfacturas.com.ar/> <http://www.e-xpensas.com/>
<http://www.micampeonato.com/>




2016-08-19 10:31 GMT-03:00 Vero de VOUSYS.com <vosorio@vousys.com>:

**Comment by an-rahulpandey** [comment] 2016-08-19 14:45
@vousys Are you using Xcode to build and run your project or doing via cli?
Also did you generated the certificates from Xcode or manually from developer member center?

**Comment by vousys** [comment] 2016-08-19 14:49
Hi Rahul.
I use phonegap build website to compile it.
I generate the certificates via developer member center.


​
Salu2!

Vero | *VOUSYS.com*
<http://www.vousys.com/>

VOUSYS.com Office: Buenos Aires, Argentina | +54.011.4481-3751

http://www.vousys.com     [image: Facebook]
<https://www.facebook.com/vousys> [image: Twitter]
<http://www.twitter.com/vousys> [image: Google Plus]
<https://plus.google.com/u/0/b/111673332818765301661/+Vousys/posts> [image:
Pintrest] <http://www.pinterest.com/vousys/> [image: Skype]
<https://www.vousys.com/> <https://www.vousys.com/exportador>
<http://www.tusfacturas.com.ar/> <http://www.e-xpensas.com/>
<http://www.micampeonato.com/>




2016-08-19 11:45 GMT-03:00 Rahul Pandey <notifications@github.com>:

**Comment by an-rahulpandey** [comment] 2016-08-19 14:54
Oh! I think the issue might be related to Certificates, but the provision profile show the push environment when opened. But I have already generated the certificates around three times, don't know what else may be causing this issue. Totally blank now.

**Comment by vousys** [comment] 2016-08-19 15:02
I regenerate them incluiding the csr file and works.
Be carefull, I could get the "registration" event and the registration ID
fine, but APNS never send me the notification...


​
Salu2!

Vero | *VOUSYS.com*
<http://www.vousys.com/>

VOUSYS.com Office: Buenos Aires, Argentina | +54.011.4481-3751

http://www.vousys.com     [image: Facebook]
<https://www.facebook.com/vousys> [image: Twitter]
<http://www.twitter.com/vousys> [image: Google Plus]
<https://plus.google.com/u/0/b/111673332818765301661/+Vousys/posts> [image:
Pintrest] <http://www.pinterest.com/vousys/> [image: Skype]
<https://www.vousys.com/> <https://www.vousys.com/exportador>
<http://www.tusfacturas.com.ar/> <http://www.e-xpensas.com/>
<http://www.micampeonato.com/>




2016-08-19 11:54 GMT-03:00 Rahul Pandey <notifications@github.com>:

**Comment by janthonyeconomist** [comment] 2016-08-25 15:06
This may be a silly question, but are you listening for the incoming on('notification')?  It seems to me the the registration callback does not fire unless you are also listing for the notification.

**Comment by vousys** [comment] 2016-08-25 15:34
Yes, of course.


​
Salu2!

Vero | *VOUSYS.com*
<http://www.vousys.com/>

VOUSYS.com Office: Buenos Aires, Argentina | +54.011.4481-3751

http://www.vousys.com     [image: Facebook]
<https://www.facebook.com/vousys> [image: Twitter]
<http://www.twitter.com/vousys> [image: Google Plus]
<https://plus.google.com/u/0/b/111673332818765301661/+Vousys/posts> [image:
Pintrest] <http://www.pinterest.com/vousys/> [image: Skype]
<https://www.vousys.com/> <https://www.vousys.com/exportador>
<http://www.tusfacturas.com.ar/> <http://www.e-xpensas.com/>
<http://www.micampeonato.com/>




2016-08-25 12:06 GMT-03:00 Judah Anthony <notifications@github.com>:

**Comment by an-rahulpandey** [comment] 2016-08-26 11:30
@vousys What is your server setup for sending push notifications?
I got it working by creating the certificates from scratch in private browsing mode. Now I am able to receive the notifications on both development as well as production certificate.

**Comment by vousys** [comment] 2016-08-26 18:54
Hi Rahul, I don't understand you fine..
 We send via stream_socket  to APNs


​
Salu2!

Vero | *VOUSYS.com*
<http://www.vousys.com/>

VOUSYS.com Office: Buenos Aires, Argentina | +54.011.4481-3751

http://www.vousys.com     [image: Facebook]
<https://www.facebook.com/vousys> [image: Twitter]
<http://www.twitter.com/vousys> [image: Google Plus]
<https://plus.google.com/u/0/b/111673332818765301661/+Vousys/posts> [image:
Pintrest] <http://www.pinterest.com/vousys/> [image: Skype]
<https://www.vousys.com/> <https://www.vousys.com/exportador>
<http://www.tusfacturas.com.ar/> <http://www.e-xpensas.com/>
<http://www.micampeonato.com/>




2016-08-26 8:30 GMT-03:00 Rahul Pandey <notifications@github.com>:

**Comment by macdonst** [comment] 2016-08-29 01:56
@janthonyeconomist your's is not actually a bug. When you call `off` what you are doing removing the event listener for `registration` or `notification`. When you call `on` you are registered another listener but it doesn't cause the event to fire again. It's the `init` method that requests a registration ID.

**Comment by macdonst** [comment] 2016-08-29 01:56
Closing as the original reporter resolved the issue.

**Closed by macdonst** 2016-08-29 01:56 UTC
Labels: ios, question

**Comment by IgnazioSammarco** [comment] 2017-01-31 07:52
Hi, I have the same issue. How can I debug my app. Is there any log file from plugin ? Where Can I find it ?

**Comment by srameshr** [comment] 2017-02-10 05:21
```
MYAPP[5768:5249983] Push Plugin register called
2017-02-10 10:48:08.596 MYAPP[5768:5249983] PushPlugin.register: setting badge to false
2017-02-10 10:48:08.596 MYAPP[5768:5249983] PushPlugin.register: clear badge is set to 0
2017-02-10 10:48:08.597 MYAPP[5768:5249983] PushPlugin.register: better button setup
2017-02-10 10:48:08.602 MYAPP[5768:5249983] GCM Sender ID 42377729696
2017-02-10 10:48:08.602 MYAPP[5768:5249983] Using GCM Notification
2017-02-10 10:48:08.618 MYAPP[5768:5248876] Push Plugin register failed
2017-02-10 10:48:43.756 MYAPP[5768:5248876] active
2017-02-10 10:48:43.757 MYAPP[5768:5248876] PushPlugin skip clear badge
```

But my emulator as well as an actual device fails to register for push

**Comment by an-rahulpandey** [comment] 2017-02-10 06:12
@srameshr emulator will not be able to register for push only device can. You are using GCM Notification for iOS too?

**Comment by srameshr** [comment] 2017-02-10 07:31
@an-rahulpandey I know that. I have also mentioned that <b>"an actual device"</b> fails to register for push notifications. This happens only on IOS. I added new profiles and certificates but no luck.

**Comment by an-rahulpandey** [comment] 2017-02-10 07:34
You are using GCM Notifications for iOS also?

**Comment by srameshr** [comment] 2017-02-10 08:14
@an-rahulpandey Yes. 

Here is the JSON I am sending to IOS devices
```
{
  "data": {
    "extra": {
      "url": ""
    },
    "notId": 12234
  },
  "notification": {
  	"title": "",
    "message": ""
  },
  "to": ""
}
```

**Comment by srameshr** [comment] 2017-02-11 13:56
@an-rahulpandey Can you let me know the json that you are sending for IOS devices, so that 
1. Notification is shown on shade
2. ```.on('notification')``` callback is called.

**Comment by an-rahulpandey** [comment] 2017-02-13 14:11
Do you mean the payload data?

**Comment by srameshr** [comment] 2017-02-13 15:01
Yes the payload

**Comment by srameshr** [comment] 2017-02-13 15:11
@an-rahulpandey I noticed you mentioned certificates created in incognito mode. What about that? Should I recreate my certificates? I am still unable to get push notification id for an IOS device.

**Comment by an-rahulpandey** [comment] 2017-02-14 13:50
```
{
    "title":"Test",
    "message":"Rahul sent you a message.",
    "additionalData":
             {
                 "summaryText":"There are %n% notifications",
                 "style":"inbox",
                 "google.message_id":"0:14870%f38b4b35f9fd7ecd",
                "coldstart":false,
                "collapse_key":"do_not_collapse",
                "foreground":false
            }
}
```

Yes please try recreating the certificates. I was having account issues because of multiple accounts linked to same id. So I did incognito to avoid any confusion.

**Comment by srameshr** [comment] 2017-02-14 14:37
@an-rahulpandey I did not get this? I read that ```title``` and ```body``` should be under ```notification```. FYI I am using GCM.

**Comment by an-rahulpandey** [comment] 2017-02-14 15:03
@srameshr I have pasted the output of Android Notification, I do not have one for iOS right now. Why dont you try with APNS first and see if it works properly or not.

**Comment by srameshr** [comment] 2017-02-14 15:08
@an-rahulpandey  @macdonst  I am able to deliver push notifications to IOS devices as well as see them under the shade. But the ```.on('notification')``` handler is not called. Here is the JSON that I am sending via GCM.
```
{
  "data": {
    "title": "",
    "message": "",
    "image": "",
    "extra": {
      "url": ""
    }
  },
  "to": "device-id",
  "notification": {
    title: "",
    body: ""
  }
}
```

**Comment by arunagiritm** [comment] 2017-09-14 08:05
Had the same issue,on registration even not working. I did the following to resolve

- Attached the registration script to the index.html and found the registration event working.
- On investigation found, the SENDER_ID in the config.xml is registered with the default value
-  changed the SENDER_ID in the config.xml and tried with my previous code (this time removing script from index.html)
VOILA - it worked.
