### ISSUE TITLE
PushNotification.init blocked the main thread 

### ISSUE THREAD

**Issue by deluxeuo** [phonegap/phonegap-plugin-push#169] opened 2015-09-26 21:19 UTC
Hello friends
I'm trying to use the example of pushplugin the repository.
when running it appears this error on my logcat
thus not showing my key

09-26 17:41:16.850: D/CordovaNetworkManager(2016): Connection Type: 3g
09-26 17:41:16.850: D/CordovaNetworkManager(2016): Connection Extra Info: epc.tmobile.com
09-26 17:41:16.860: V/PushPlugin(2016): execute: action=init
09-26 17:41:16.860: V/PushPlugin(2016): execute: data=[{"android":{"senderID":"1111"},"ios":{"alert":"true","badge":"true","sound":"true"},"windows":{}}]
09-26 17:41:16.860: V/PushPlugin(2016): execute: jo={"senderID":"1111"}
09-26 17:41:16.860: V/PushPlugin(2016): execute: senderID=1111
09-26 17:41:16.860: D/GCMRegistrar(2016): resetting backoff for br.com.xxx
09-26 17:41:16.860: V/GCMRegistrar(2016): Registering app br.com.xxx of senders 1111
09-26 17:41:16.900: D/PushPlugin(2016): no icon option
09-26 17:41:16.900: D/PushPlugin(2016): no iconColor option
09-26 17:41:16.900: W/PluginManager(2016): THREAD WARNING: exec() call to PushNotification.init blocked the main thread for 40ms. Plugin should use CordovaInterface.getThreadPool().

**Comment by fredgalvao** [comment] 2015-09-27 22:29
That is not an error, it's just a performance warning. It should **not** prevent you from receiving your registrationId on the proper callback. If you're not receiving it, the problem is elsewhere.

**Comment by deluxeuo** [comment] 2015-09-27 22:34
I understand ..

Good is working directly on the device.

Can you help me with other questions

in the documentation, there is several manerias to modify the push.
but in all examples as aplicalos

for example

Additionally, each push can include a large icon Which is used to personalize each push. The location of the image may one of three types.

The first is the drawables folder in your app. This JSON sent from GCM:

{
     title: "Large Icon"
     message: "Loaded from drawables folder"
     image: "twitter"
}


Where do I put this code


{
     title: "Large Icon"
     message: "Loaded from drawables folder"
     image: "twitter"
}

**Comment by macdonst** [comment] 2015-09-28 14:56
Pushed a fix to remove the warning in version 1.4.0.

**Comment by fredgalvao** [comment] 2015-09-28 19:48
@macdonst I'm pretty sure his logs come from an Android version of an app, so your fix only solves one side of the warning (the ios side).

**Comment by macdonst** [comment] 2015-09-29 01:29
@fredgalvao lol, you are so right.

**Comment by macdonst** [comment] 2015-09-29 17:31
Fixed on Android now too.

**Closed by macdonst** 2015-09-29 17:31 UTC
Labels: enhancement
