### ISSUE TITLE
How to get data on didReceiveNotification Background Process 

### ISSUE THREAD

**Issue by silasakk** [phonegap/phonegap-plugin-push#198] opened 2015-10-04 06:57 UTC
this background
2015-10-04 13:49:43.284 MaskOA[1591:376661] didReceiveNotification
2015-10-04 13:49:46.633 MaskOA[1591:376661] didReceiveNotification

i want call function when didReceiveNotification on background 

this foreground
2015-10-04 13:54:58.122 MaskOA[1591:376661] Notification received
2015-10-04 13:54:58.122 MaskOA[1591:376661] Push Plugin key: alert
2015-10-04 13:54:58.122 MaskOA[1591:376661] Push Plugin key: sound
2015-10-04 13:54:58.123 MaskOA[1591:376661] Push Plugin key: content-available

```
push.on('notification', function (data) {
                // data.message,
                // data.title,
                // data.count,
                // data.sound,
                // data.image,
                // data.additionalData
                //console.log('xxx');

});
```

**Comment by macdonst** [comment] 2015-10-05 02:21
@silasakk Do you mean you want the `notification` even to be fired when your app is in the background?

**Comment by silasakk** [comment] 2015-10-05 02:22
@macdonst  yes

**Comment by macdonst** [comment] 2015-10-05 02:25
@silasakk duplicate of issue #93 please +1 that thread.

**Closed by macdonst** 2015-10-05 02:25 UTC
