### ISSUE TITLE
invalid registration number on IOS

### ISSUE THREAD

**Issue by clembou590** [phonegap/phonegap-plugin-push#833] opened 2016-04-24 20:54 UTC
### Expected Behaviour

registration ID should always have the same length.
### Actual Behaviour

ON IOS 7,1,1. (iphone 4s)

```
 var pushService = PushNotification.init({
                        android: {
                            senderID: tindrive_anrdoid_sender_id
                        },
                        ios: {
                            senderID: tindrive_ios_sender_id,
                            gcmSandbox: true,
                            alert: "true",
                            badge: "true",
                            sound: "true"
                        },
                        windows: {}
                    });
```

when I install app and launch it for the first time I receive the following registration ID:
"luE0jC7ja7w:APA91bHjVRljQFxTds1Tpbfz5UK6aJzQcKHuIwrJujKufbu62IpYp75mUbqOUdVSpo3QdTq_0F6VuG__Mlk8Wz3zny-RNg98U-Zr9WqkDLls24fHpAKIXHMlJzRai72T2xCsrcuO14yJ"

I send a notification from a java app through the end point:
https://gcm-http.googleapis.com/gcm/send
(because I am using GCM sandbox).

I send a notification:
{
  "to": "luE0jC7ja7w:APA91bHjVRljQFxTds1Tpbfz5UK6aJzQcKHuIwrJujKufbu62IpYp75mUbqOUdVSpo3QdTq_0F6VuG__Mlk8Wz3zny-RNg98U-Zr9WqkDLls24fHpAKIXHMlJzRai72T2xCsrcuO14yJ",
  "notification": {
    "title": "hello title",
    "body": "great match!",
    "td": "2"
  }
}

the notification is displayed on the IPHONE
--> everything is fine.

I uninstall the app, reinstall it (without changing the code)
but then the registration ID received is:
a34aaa2ecdf981c42bfa1b07fe2ed8fbeaccdf5c04e2a0de716a26d61fe19aff

**this registration ID is invalid!** (when used the notication is not received on the iphone)
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

ON IOS 7,1,1. (iphone 4s)
#### Cordova CLI version and cordova platform version

```
cordova --version                                    5,4,1
cordova platform version IOS                   3.9.2
```
#### Plugin version

```
cordova plugin version | grep phonegap-plugin-push   1.5.3
```

**Comment by macdonst** [comment] 2016-04-25 12:23
@clembou590 I'd be interested to see the logs when you startup the app the second time after you uninstall.

**Comment by clembou590** [comment] 2016-04-26 19:53
here are the traces I got from xcode. (is there any way to get it whithout launching the app from xcode?)
Tell me if there is anything I can provide that might help you figure out the problem


2016-04-26 21:42:50.846 tindrive[176:60b] Apache Cordova native platform version 3.9.2 is starting.
2016-04-26 21:42:50.855 tindrive[176:60b] Multi-tasking -> Device: YES, App: YES
2016-04-26 21:42:50.875 tindrive[176:60b] Unlimited access to network resources
2016-04-26 21:42:51.227 tindrive[176:60b] [CDVTimer][splashscreen] 157.179952ms
2016-04-26 21:42:51.265 tindrive[176:60b] [CDVTimer][statusbar] 34.859002ms
2016-04-26 21:42:51.269 tindrive[176:60b] [CDVTimer][keyboard] 1.343966ms
2016-04-26 21:42:51.272 tindrive[176:60b] [CDVTimer][TotalPluginStartup] 201.851010ms
2016-04-26 21:42:51.341 tindrive[176:60b] active
2016-04-26 21:42:51.344 tindrive[176:60b] PushPlugin skip clear badge
2016-04-26 21:42:52.463 tindrive[176:60b] Resetting plugins due to page load.
2016-04-26 21:42:54.642 tindrive[176:60b] Finished load of: file:///var/mobile/Applications/FE2A2CF5-71CA-41E6-B76C-AA4DD8D58BA6/tindrive.app/www/index.html#/initializing
2016-04-26 21:42:55.989 tindrive[176:60b] THREAD WARNING: ['Device'] took '18.797119' ms. Plugin should use a background thread.
2016-04-26 21:42:56.105 tindrive[176:60b] THREAD WARNING: ['Globalization'] took '20.402832' ms. Plugin should use a background thread.
2016-04-26 21:42:56.156 tindrive[176:60b] Bluetooth state changed: State unknown, update imminent.
2016-04-26 21:42:56.162 tindrive[176:60b] Location Services is enabled
2016-04-26 21:42:56.186 tindrive[176:60b] THREAD WARNING: ['StatusBar'] took '16.331055' ms. Plugin should use a background thread.
2016-04-26 21:42:56.190 tindrive[176:60b] Location authorization status changed to: not_determined
2016-04-26 21:42:56.196 tindrive[176:60b] isOnEmulator false
2016-04-26 21:42:56.221 tindrive[176:60b] THREAD WARNING: ['Console'] took '25.911133' ms. Plugin should use a background thread.
2016-04-26 21:42:56.225 tindrive[176:60b] isOnBrowser false
2016-04-26 21:42:56.229 tindrive[176:60b] trying to hide splashscreen
2016-04-26 21:42:56.232 tindrive[176:60b] WARN: missing gmapsReady
2016-04-26 21:42:56.236 tindrive[176:60b] WARN: missing isGeolocationEnabled
2016-04-26 21:42:56.240 tindrive[176:60b] WARN: missing isPushNotificationAuthorized
2016-04-26 21:42:56.244 tindrive[176:60b] WARN: missing clientVersionChecked
2016-04-26 21:42:56.249 tindrive[176:60b] WARN: missing isUserLanguageretrieved
2016-04-26 21:42:56.253 tindrive[176:60b] trying to register to push
2016-04-26 21:42:56.256 tindrive[176:60b] starting geolocation loop
2016-04-26 21:42:56.259 tindrive[176:60b] detected language fr-FR
2016-04-26 21:42:56.263 tindrive[176:60b] WARN: missing gmapsReady
2016-04-26 21:42:56.266 tindrive[176:60b] WARN: missing isGeolocationEnabled
2016-04-26 21:42:56.269 tindrive[176:60b] WARN: missing isPushNotificationAuthorized
2016-04-26 21:42:56.273 tindrive[176:60b] WARN: missing clientVersionChecked
2016-04-26 21:42:56.282 tindrive[176:60b] is location enabled = true
2016-04-26 21:42:56.292 tindrive[176:60b] Location authorization status is: not_determined
2016-04-26 21:42:56.301 tindrive[176:60b] THREAD WARNING: ['Diagnostic'] took '13.306152' ms. Plugin should use a background thread.
2016-04-26 21:42:56.307 tindrive[176:60b] satus is not_determined
2016-04-26 21:42:56.350 tindrive[176:60b] THREAD WARNING: ['Geolocation'] took '37.221924' ms. Plugin should use a background thread.
2016-04-26 21:42:56.354 tindrive[176:60b] Bluetooth state changed: The platform doesn't support Bluetooth Low Energy.
2016-04-26 21:42:57.229 tindrive[176:60b] THREAD WARNING: ['PushNotification'] took '23.302002' ms. Plugin should use a background thread.
2016-04-26 21:42:57.232 tindrive[176:60b] push autorization = true
2016-04-26 21:42:57.233 tindrive[176:60b] WARN: missing gmapsReady
2016-04-26 21:42:57.235 tindrive[176:60b] WARN: missing isGeolocationEnabled
2016-04-26 21:42:57.237 tindrive[176:60b] WARN: missing clientVersionChecked
2016-04-26 21:42:57.265 tindrive[176:1303] Push Plugin register called
2016-04-26 21:42:57.274 tindrive[176:1303] PushPlugin.register: setting badge to false
2016-04-26 21:42:57.278 tindrive[176:1303] PushPlugin.register: clear badge is set to 0
2016-04-26 21:42:57.281 tindrive[176:1303] PushPlugin.register: better button setup
2016-04-26 21:42:57.296 tindrive[176:60b] Push Plugin register success: <a34aaa2e cdf981c4 2bfa1b07 fe2ed8fb eaccdf5c 04e2a0de 716a26d6 1fe19aff>
2016-04-26 21:42:57.414 tindrive[176:1303] GCM Sender ID 131950293070
2016-04-26 21:42:57.418 tindrive[176:1303] Using GCM Notification
2016-04-26 21:42:57.421 tindrive[176:1303] Using GCM Sandbox
2016-04-26 21:42:57.808 tindrive[176:60b] on push registration is called 1
2016-04-26 21:42:57.812 tindrive[176:60b] registrationId done1
2016-04-26 21:42:57.814 tindrive[176:60b] registration init done successfully :a34aaa2ecdf981c42bfa1b07fe2ed8fbeaccdf5c04e2a0de716a26d61fe19aff
2016-04-26 21:42:57.824 tindrive[176:60b] WARN: missing gmapsReady
2016-04-26 21:42:57.827 tindrive[176:60b] WARN: missing isGeolocationEnabled
2016-04-26 21:42:57.830 tindrive[176:60b] WARN: missing clientVersionChecked
2016-04-26 21:42:57.878 tindrive[176:60b] WARN: missing gmapsReady
2016-04-26 21:42:57.881 tindrive[176:60b] WARN: missing isGeolocationEnabled
2016-04-26 21:42:58.068 tindrive[176:60b] gmaps script downloaded successfully
2016-04-26 21:42:58.071 tindrive[176:60b] WARN: missing isGeolocationEnabled
2016-04-26 21:43:04.335 tindrive[176:60b] WARN: Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
2016-04-26 21:44:50.815 tindrive[176:60b] Location authorization status changed to: authorized_always
2016-04-26 21:44:51.019 tindrive[176:60b] THREAD WARNING: ['Geolocation'] took '106.671875' ms. Plugin should use a background thread.
2016-04-26 21:44:51.023 tindrive[176:60b] active
2016-04-26 21:44:51.024 tindrive[176:60b] PushPlugin skip clear badge
2016-04-26 21:44:51.070 tindrive[176:60b] THREAD WARNING: ['Geolocation'] took '37.425049' ms. Plugin should use a background thread.
2016-04-26 21:44:52.578 tindrive[176:60b] leaving initializing view

**Comment by clembou590** [comment] 2016-04-28 15:26
@macdonst  any update on that issue?

**Comment by clembou590** [comment] 2016-04-30 08:45
@macdonst why did you tag it as a question.... it's a bug... not a question... (is it not?)

**Comment by macdonst** [comment] 2016-05-01 15:10
@clembou590 I always tag issues as questions until I get a chance to verify they are bugs. That being said, I haven't been able to verify it and I won't be able to test on an iOS 7 device until sometime after May 9th.

**Comment by clembou590** [comment] 2016-05-04 13:45
thks for the answer.

Another fact that might help:
after the scenario described above has occured, 
 
if i keep sending notifications to "luE0jC7ja7w:APA91bHjVRljQFxTds1Tpbfz5UK6aJzQcKHuIwrJujKufbu62IpYp75mUbqOUdVSpo3QdTq_0F6VuG__Mlk8Wz3zny-RNg98U-Zr9WqkDLls24fHpAKIXHMlJzRai72T2xCsrcuO14yJ"
the notification** is received on the iphone** even if the new registration token is
"a34aaa2ecdf981c42bfa1b07fe2ed8fbeaccdf5c04e2a0de716a26d61fe19aff"

**Comment by Moghul** [comment] 2016-05-13 11:54
Any updates on this? I'm getting it too.

**Comment by clembou590** [comment] 2016-06-02 13:32
@macdonst 
Hi... I really need a fix on this issue...
did you have any time to investigate?

**Comment by Moghul** [comment] 2016-06-02 13:38
@clembou590 The fix for me was to go to [this](https://developers.google.com/mobile/add?platform=ios&cntapi=gcm&cnturl=https:%2F%2Fdevelopers.google.com%2Fcloud-messaging%2Fios%2Fclient&cntlbl=Continue%20Adding%20GCM%20Support&%3Fconfigured%3Dtrue) link and upload the .p12 that could do APNS.

Once that was done, reloading the app (or in our case, index.html) a few times fixed the issue.

If none of this fixes it for you, check back with the author.

**Comment by Dmatafonov** [comment] 2016-07-08 13:39
> a34aaa2ecdf981c42bfa1b07fe2ed8fbeaccdf5c04e2a0de716a26d61fe19aff

that's how APNS token looks like

> luE0jC7ja7w:APA91bHjVRljQFxTds1Tpbfz5UK6aJzQcKHuIwrJujKufbu62IpYp75mUbqOUdVSpo3QdTq_0F6VuG__Mlk8Wz3zny-RNg98U-Zr9WqkDLls24fHpAKIXHMlJzRai72T2xCsrcuO14yJ

that's GCM token


If you try to send GCM notification with APNS token it won't work.

**Comment by clembou590** [comment] 2016-07-10 20:25
@Dmatafonov 
Thanks for trying to answer... but I already knew this! please read the description of the problem:
the token received is always the first time "GCM type" and after that sometimes "GCM type" sometimes "APNS type".
WITHOUT CHANGING THE CODE OF THE APP!

**Comment by macdonst** [comment] 2017-06-28 19:32
Closing as I can't reproduce, I do not have an iOS 7 device and the plugin no longer supports iOS7.

**Closed by macdonst** 2017-06-28 19:32 UTC
Labels: can't reproduce, ios, question
