### ISSUE TITLE
timeout while registration

### ISSUE THREAD

**Issue by pranaydutta89** [phonegap/phonegap-plugin-push#366] opened 2015-11-20 16:06 UTC
I am having a android 4.0.4 device, while trying to register for push notification i am getting "timeout" in error callback, please help me to pin down the issue??

**Comment by macdonst** [comment] 2015-11-20 16:13
@pranaydutta89 Do you have a network connection?

**Comment by pranaydutta89** [comment] 2015-11-20 16:16
yes, its working f9 in android 4.4,5.1 (not tested in 4.1 ,4.2 and 4.3) i have a device of 4.0.4 its showing the error only there

**Comment by pranaydutta89** [comment] 2015-11-20 16:24
it reevaluated the issue and found that ""Empty registration ID received from GCM" its actully throwing this error

**Comment by pranaydutta89** [comment] 2015-11-20 17:30
well its seem to work in 1.4.4, i was working with version 1.4.2 anyways thanks for help

**Comment by pranaydutta89** [comment] 2015-11-20 19:02
but i  am still getting timeout for android 4.0.4 every now and then ,is this  a bug ??

**Comment by macdonst** [comment] 2015-11-27 15:40
@pranaydutta89 I can't reproduce it.

**Comment by softwareolatomiwa** [comment] 2015-12-15 10:16
Hi please i'm having the same issue. I'll like to know if there's any solution(s) yet. Thanks

**Comment by pranaydutta89** [comment] 2015-12-17 17:24
@macdonst, well its happening on some lower device while some works just fine

**Comment by macdonst** [comment] 2015-12-21 15:39
@pranaydutta89 I can only test with the devices I have, which are numerous but not exhaustive. If you can reproduce the error while capturing the logs:

`adb logcat | grep PushPlugin`

that would be helpful.

**Comment by macdonst** [comment] 2016-01-06 15:55
@pranaydutta89 bump

**Comment by zanemcca** [comment] 2016-01-30 00:26
Here is the output of `adb logcat | grep PushPlugin`:

```
V/PushPlugin( 7843): execute: action=init
V/PushPlugin( 7843): execute: data=[{"android":{"senderID":"xxxxxxxxxxxxxx","iconColor":"#F0F0F0","icon":"notif","vibrate":true,"sound":true,"forceShow":true}}]
V/PushPlugin( 7843): execute: jo={"senderID":"xxxxxxxxxxxxxx","iconColor":"##F0F0F0","icon":"notif","vibrate":true,"sound":true,"forceShow":true}
V/PushPlugin( 7843): execute: senderID=xxxxxxxxxxxxxx
E/PushPlugin( 7843): execute: Got JSON Exception TIMEOUT
```

**Comment by motasay** [comment] 2016-02-10 15:41
It's actually a IOException, not a JSON, but in the code it's saying JSON by mistake I think.

The code times out here:
```
if ("".equals(savedRegID)) {
  token = InstanceID.getInstance(getApplicationContext()).getToken(senderID, GCM);
}
```

And this is the full stack trace:
```
java.io.IOException: TIMEOUT
    at com.google.android.gms.iid.zzc.zzb(Unknown Source)
    at com.google.android.gms.iid.zzc.zza(Unknown Source)
    at com.google.android.gms.iid.InstanceID.zzc(Unknown Source)
    at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
    at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
    at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:73)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
    at java.lang.Thread.run(Thread.java:856)
```

**Comment by macdonst** [comment] 2016-02-29 17:19
Honestly, I have no idea why this is happening. As of version 1.4.0 of the plugin we are using the new way to request and Instance ID from Google and it runs in thread so I'm not sure why it is complaining.

**Comment by badpenguin** [comment] 2016-03-24 12:11
Android Galaxy Tab with 4.1.0 i get the timeout too, logcat says just:
E/PushPlugin( 3402): execute: Got JSON Exception TIMEOUT
D/PushPlugin( 3402): no icon option
D/PushPlugin( 3402): no iconColor option

Instead it works perfectly with a 4.2.x device.

Maybe the plugin does not support <4.2 ? It says 4.0.0 in the docs.

**Comment by bobolat** [comment] 2016-03-25 03:58
i got android 4.1.2 show error timeout too..does anyone solve this issue?

**Comment by tioperez** [comment] 2016-04-14 14:02
Same error on android 4.1.2

04-14 15:59:57.955: E/PushPlugin(20077): execute: Got JSON Exception TIMEOUT

**Comment by bobolat** [comment] 2016-04-15 01:24
before this error..my gapps didnt update..after i update google apps and update chrome on my device that run 4.1.2..i can get the token already without any problem

**Comment by badpenguin** [comment] 2016-04-15 01:30
@bobolat thanks i'll try updating gApps and see if this is the problem

**Comment by macdonst** [comment] 2016-04-15 15:10
All, I flashed my old Nexus 7 with Android 4.1.2 and I can reproduce this problem with the stock ROM. However, as soon as I go into Google Play Store and update Google Play Services the problem goes away. So the fix for this is to upgrade to the latest version of Google Play Services.

**Comment by macdonst** [comment] 2016-04-15 15:15
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#got-json-exception-timeout

**Closed by macdonst** 2016-04-15 15:15 UTC
Labels: android, question

**Comment by bobolat** [comment] 2016-04-17 04:53
S s , adxxp
! Xx t c. I d

**Comment by michalchochol** [comment] 2016-04-17 19:46
@macdonst Which version of Google Play Services did you install?  
It does not work with v8.7.03, al least on Genymotion emulator with android 4.1.1

**Comment by macdonst** [comment] 2016-04-18 03:40
@michalchochol I don't have access to the device right now. Also, I don't trust the emulator for anything when it comes to testing push.

**Comment by michalchochol** [comment] 2016-04-18 21:53
@macdonst You are right - it works ok with v8.7.03 on device with android 4.1.2.
Generally I don't have problems with push on genymotion emulators with android 4.2 and higher
