### ISSUE TITLE
Ios push message

### ISSUE THREAD

**Issue by JeffersonApolinario** [phonegap/phonegap-plugin-push#441] opened 2015-12-18 13:56 UTC
Hi, my name is jefferson  i use the API gcm in my project and want know how can i send a push to ios device and if i need specify the sender ID the project ?

**Comment by macdonst** [comment] 2015-12-18 14:37
@JeffersonApolinario this is a duplicate of Issue #115 and I'm in the process of release version 1.5.0 which will support GCM messaging to iOS so stay tuned for that release.

**Closed by macdonst** 2015-12-18 14:37 UTC
Labels: duplicate
