### ISSUE TITLE
Installing "phonegap-plugin-push" for android (node:7059) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: warn

### ISSUE THREAD

**Issue by bhandaribhumin** [phonegap/phonegap-plugin-push#2238] opened 2018-03-01 20:09 UTC
> sudo cordova platform add android

getting Error:

```
Using cordova-fetch for cordova-android@~7.0.0
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: xx.xx.xx
	Name: xxx
	Activity: MainActivity
	Android target: android-26
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@7.0.0
Android Studio project detected
Android Studio project detected
Installing "com.googlemaps.ios" for android
Installing "cordova-plugin-app-event" for android
Installing "cordova-plugin-compat" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 7.0.0, failed version requirement: 
      <6.3.0
Skipping 'cordova-plugin-compat' for android
Installing "cordova-plugin-device" for android
Installing "cordova-plugin-geolocation" for android
Installing "cordova-plugin-googlemaps" for android
Subproject Path: CordovaLib
Subproject Path: app

            Official document
            https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md
        
Installing "cordova-plugin-inappbrowser" for android
Installing "cordova-plugin-ionic-keyboard" for android
Installing "cordova-plugin-ionic-webview" for android
Installing "cordova-plugin-ms-adal" for android
Plugin dependency "cordova-plugin-compat@1.2.0" already fetched, using that version.
Installing "cordova-plugin-compat" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 7.0.0, failed version requirement: 
      <6.3.0
Skipping 'cordova-plugin-compat' for android
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-network-information" for android
Installing "cordova-plugin-splashscreen" for android
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
          
Installing "cordova-sqlite-storage" for android
installing external dependencies via npm
npm install of external dependencies ok
Installing "de.appplant.cordova.plugin.local-notification" for android
Plugin dependency "cordova-plugin-device@2.0.1" already fetched, using that version.
Dependent plugin "cordova-plugin-device" already installed on android.
Plugin dependency "cordova-plugin-app-event@1.2.1" already fetched, using that version.
Dependent plugin "cordova-plugin-app-event" already installed on android.
Subproject Path: CordovaLib
Subproject Path: app
Installing "phonegap-plugin-barcodescanner" for android
Subproject Path: CordovaLib
Subproject Path: app
Installing "phonegap-plugin-push" for android
(node:7059) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: warn
(node:7059) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

> ionic info 

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.9.4
    npm        : 5.6.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

```

**Comment by cbjerg** [comment] 2018-03-02 06:53
We are experiencing the same problem using phonegap build. Using 2.2.0 the last error is just "warn"
Using 2.1.3  i get the following 

```
execution failed for task ':transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v13/view/DragStartHelper$OnDragStartListener.class
```

**Comment by gabn88** [comment] 2018-03-02 08:05
Same here.

**Comment by nprail** [comment] 2018-03-02 16:24
@cbjerg I am having that exact problem as well. See #2243.

**Comment by bhandaribhumin** [comment] 2018-03-05 09:13
still same... please  anyone help me on this.. 
```

Subproject Path: app
Installing "phonegap-plugin-push" for android

(node:1068) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: warn
(node:1068) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by macdonst** [comment] 2018-03-07 14:12
@bhandaribhumin this is probably a duplicate of #2243. Can you please remove the current version of the push plugin you have in your app and add from master?

```
cordova plugin add https://github.com/phonegap/phonegap-plugin-push
```

That should resolve your problem and I'll release a new version soon. Report back what you find.

**Closed** 2018-06-04 15:31 UTC
Labels: android, question, wontfix
