### ISSUE TITLE
Push with action buttons not disappearing on Android

### ISSUE THREAD

**Issue by danieka** [phonegap/phonegap-plugin-push#844] opened 2016-04-28 08:47 UTC
### Expected Behaviour

When tapping an action button in the notification I expect it to disappear. Notifications without action buttons disappear as expected.

### Actual Behaviour

The notification remains in the notification list and I can press the action button multiple times without it disappearing. If I swipe to remove it after having clicked an action button there is an empty space where the notifications ie the list does not collapse on the empty space (screenshot 1). If I swipe to remove before clicking any button the notifications is removed as usual.

#### Steps to Reproduce 

Send notification with action button from server
Tap one of the action buttons on the notification when it appears on the phone
Notification is not removed

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Cyanogen OS version: 12.1.1-YOG7DAS2K1
Android version: 5.1.1

This issue only appears on this device. Other android phones I've tried with does not have this bug.

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

OnePlus One

#### Cordova CLI version and cordova platform version

    cordova --version                                    5.4.1
    cordova platform version android           android 5.1.1

#### Plugin version

phonegap-plugin-push 1.6.2 "PushPlugin"

#### Sample Push Data Payload

I removed extra keys that we use for our app.
```
{
"title": "#test",
"message": "*********** needs your help",
"vibrationPattern":  []int{500, 500, 500, 500, 500, 500, 500, 500},
"actions": []map[string]interface{}{
    map[string]interface{}{
	"icon":       "accept",
	"title":      "ACCEPT",
	"callback":   "app.accept",
	"foreground": true,
   },
  map[string]interface{}{
        "icon":       "view",
	"title":      "VIEW",
	"callback":   "app.view",
	"foreground": true,
   },
}
}
```

#### Logs taken while reproducing problem

adb logcat output (somewhat redacted):
```
I/GCM     ( 2052): GCM message ***************************************
D/PushPlugin_GCMIntentService(30410): onMessage - from: ******************
D/PushPlugin_GCMIntentService(30410): normalize extras
D/PushPlugin_GCMIntentService(30410): key = actions
D/PushPlugin_GCMIntentService(30410): replace key actions with actions
D/PushPlugin_GCMIntentService(30410): key = username
D/PushPlugin_GCMIntentService(30410): replace key username with username
D/PushPlugin_GCMIntentService(30410): key = profile_image_url
D/PushPlugin_GCMIntentService(30410): replace key profile_image_url with profile_image_url
D/PushPlugin_GCMIntentService(30410): key = user_id
D/PushPlugin_GCMIntentService(30410): replace key user_id with user_id
D/PushPlugin_GCMIntentService(30410): key = url
D/PushPlugin_GCMIntentService(30410): replace key url with url
D/PushPlugin_GCMIntentService(30410): key = name
D/PushPlugin_GCMIntentService(30410): replace key name with name
D/PushPlugin_GCMIntentService(30410): key = rate
D/PushPlugin_GCMIntentService(30410): replace key rate with rate
D/PushPlugin_GCMIntentService(30410): key = tags
D/PushPlugin_GCMIntentService(30410): replace key tags with tags
D/PushPlugin_GCMIntentService(30410): key = notId
D/PushPlugin_GCMIntentService(30410): replace key notId with notId
D/PushPlugin_GCMIntentService(30410): key = title
D/PushPlugin_GCMIntentService(30410): replace key title with title
D/PushPlugin_GCMIntentService(30410): key = vibrationPattern
D/PushPlugin_GCMIntentService(30410): replace key vibrationPattern with vibrationPattern
D/PushPlugin_GCMIntentService(30410): key = message
D/PushPlugin_GCMIntentService(30410): replace key message with message
D/PushPlugin_GCMIntentService(30410): key = country
D/PushPlugin_GCMIntentService(30410): replace key country with country
D/PushPlugin_GCMIntentService(30410): key = session_id
D/PushPlugin_GCMIntentService(30410): replace key session_id with session_id
D/PushPlugin_GCMIntentService(30410): key = collapse_key
D/PushPlugin_GCMIntentService(30410): replace key collapse_key with collapse_key
D/PushPlugin_GCMIntentService(30410): background
D/PushPlugin_GCMIntentService(30410): message =[************* needs your help]
D/PushPlugin_GCMIntentService(30410): title =[#test]
D/PushPlugin_GCMIntentService(30410): contentAvailable =[null]
D/PushPlugin_GCMIntentService(30410): create notification
D/PushPlugin_GCMIntentService(30410): stored icon=icon
D/PushPlugin_GCMIntentService(30410): stored iconColor=blue
D/PushPlugin_GCMIntentService(30410): stored sound=true
D/PushPlugin_GCMIntentService(30410): stored vibrate=true
D/PushPlugin_GCMIntentService(30410): using icon from plugin options
D/PushPlugin_GCMIntentService(30410): create actions
D/PushPlugin_GCMIntentService(30410): adding action
D/PushPlugin_GCMIntentService(30410): adding callback = app.accept
D/PushPlugin_GCMIntentService(30410): adding action
D/PushPlugin_GCMIntentService(30410): adding callback = app.view
D/PhoneStatusBar( 1144): disable: < expand ICONS* alerts SYSTEM_INFO* back home recent clock search >
D/BluetoothAdapter( 1144): 440757039: getState() :  mService = null. Returning STATE_OFF
D/BluetoothAdapter( 1144): 440757039: getState() :  mService = null. Returning STATE_OFF
D/BluetoothAdapter( 1144): 440757039: getState() :  mService = null. Returning STATE_OFF
D/BluetoothAdapter( 1144): 440757039: getState() :  mService = null. Returning STATE_OFF
D/BluetoothAdapter( 1144): 440757039: getState() :  mService = null. Returning STATE_OFF
D/BluetoothAdapter( 1144): 440757039: getState() :  mService = null. Returning STATE_OFF
D/StatusBar( 1144): Clicked on button 0 for 0|com.fliffr.app|62|Fliffr|10173
I/ActivityManager(  768): START u0 {flg=0x10000000 cmp=com.fliffr.app/com.adobe.phonegap.push.PushHandlerActivity bnds=[193,413][624,557] (has extras)} from uid 10173 on display 0
V/WindowManager(  768): addAppToken: AppWindowToken{33b5c041 token=Token{17a12b28 ActivityRecord{2193654b u0 com.fliffr.app/com.adobe.phonegap.push.PushHandlerActivity t17957}}} to stack=1 task=17957 at 1
D/PushPlugin_PushHandlerActivity(30410): not id = 62
V/PushPlugin_PushHandlerActivity(30410): onCreate
D/PushPlugin_PushHandlerActivity(30410): callback = app.accept
D/PushPlugin_PushHandlerActivity(30410): bringToForeground = true
D/PushPlugin(30410): convert extras to json
D/PushPlugin(30410): key = actions
D/PushPlugin(30410): key = username
D/PushPlugin(30410): key = profile_image_url
D/PushPlugin(30410): key = callback
D/PushPlugin(30410): key = user_id
D/PushPlugin(30410): key = url
D/PushPlugin(30410): key = name
D/PushPlugin(30410): key = rate
D/PushPlugin(30410): key = tags
D/PushPlugin(30410): key = notId
D/PushPlugin(30410): key = title
D/PushPlugin(30410): key = vibrationPattern
D/PushPlugin(30410): key = message
D/PushPlugin(30410): key = country
D/PushPlugin(30410): key = session_id
D/PushPlugin(30410): key = coldstart
D/PushPlugin(30410): key = collapse_key
D/PushPlugin(30410): key = foreground
V/StatusBar(30410): Executing action: hide
W/art     (30410): Attempt to remove local handle scope entry from IRT, ignoring

```

**Comment by danieka** [comment] 2016-04-28 08:50
Screenshot 1
![](mtp://[usb:003,062]/Internminne/Pictures/Screenshots/Screenshot_2016-04-28-10-31-02.png)

**Comment by macdonst** [comment] 2016-05-02 19:48
@danieka I can't reproduce this on the phones I've tried. Mind you I'm not running Cyanogen OS version: 12.1.1-YOG7DAS2K1

**Comment by danieka** [comment] 2016-05-03 07:29
@macdonst Probably it's only affecting my version of Cyanogen. I might have some time this weekend to do some additional troubleshooting. Do you know if the last line of the log: `W/art     (30410): Attempt to remove local handle scope entry from IRT, ignoring` is normal? Is it even related to the push plugin?

**Comment by macdonst** [comment] 2016-05-04 17:18
@danieka yeah, my OnePlusOne Cyanogen version is later than yours and I can't reproduce. With regards to that log, I don't think it is related to the push plugin.

**Comment by macdonst** [comment] 2016-05-26 14:17
@danieka I'm going to close this as a quirk of Cyanogen but please feel to re-open it if you can reproduce on another phone.

**Closed by macdonst** 2016-05-26 14:17 UTC
Labels: android, can't reproduce
