### ISSUE TITLE
Plugin Push not working in Android

### ISSUE THREAD

**Issue by amexassessoria** [phonegap/phonegap-plugin-push#2115] opened 2017-12-20 17:06 UTC
### Expected Behaviour

> Seguindo o passo-a-passo de vocês, o esperado é que variando o senderID, varie também o registratioID.

Following the step-by-step guide, the expected is that changing the `senderID`, the `registrationID` would change accordingly.

### Actual Behaviour

> Quando alterado o senderID, ele retorna o mesmo registrationID

When the `senderID` is changed, the same `registrationID` is returned.

### Reproduce Scenario (including but not limited to)

> Utilizando o Phonegap for Desktop, e abrindo ele no meu celular Android, ele retorna o registrationID, e apenas alterando o senderID do código e atualizando o aplicativo ele retorna o mesmo registrationID

Using Phonegap for Desktop, opening it on my Android device, it returns the `registrationID`, and simply changing the `senderID` on the source and updating the app it returns the same `registrationID`.

#### Steps to Reproduce 

> Ao aplicar um senderID no código, visualizar o retorno no registrationID, assim que houver esse retorno, alterar o senderID, e ele retornará o mesmo registrationID de antes

Basically the same as what is described in the previous section.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 7.1.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Lenovo Moto Z Play

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.5.0
    cordova platform version android                     # e.g. 6.3.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 2.1.2

#### Sample Code that illustrates the problem

```typescript
const push = PushNotification.init({
	"android": {
		"senderID": "XXXXXXXXXX"
	},
	"ios": {
		"gcmSandbox": false,
		"sound": true,
		"vibration": true,
		"badge": true,
		"alert": true
	},
	"windows": {}
});
push.on('registration', (data) => {
	alert('on registration');
	$.post(webService + 'Registro_Dispositivo/Salvar', {
		"id": data.registrationId,
		"plataforma": device.platform
	}).always(function () {
		window.localStorage.setItem(appnome + "-registrationId", data.registrationId);
		alert(data.registrationId);
	});
});
push.on('notification', (data) => {
	var href = '#/' + data.additionalData.link;
	window.location.href = href;
});
push.on('error', (e) => {
	alert("Erro no Push = " + e.message);
	console.log(data.registrationId);
});
```

#### Logs taken while reproducing problem

**Comment by fredgalvao** [comment] 2017-12-20 22:23
I'll translate inline for him, as he contacted me for help personally.

**Comment by OtavioBraga0** [comment] 2017-12-21 13:02
I was able to solve it, I was using version 2.1.2, for some reason it was not working properly with Android, so I had to downgrade to version 1.8.0, so it worked perfectly.

Fred, thank you for helping me!

**Comment by satish-nikam** [comment] 2017-12-21 13:05
If plugin version 2.1.2 is broken with android, then I think we should not close the issue.

**Comment by fredgalvao** [comment] 2017-12-21 19:02
I agree with @satish-nikam . If you can reproduce the issue with 2.1.2 and cannot on 1.8.0, then it's an improvement to the debugging and investigation process, but it doesn't mean the issue is solved at all.

**Comment by macdonst** [comment] 2017-12-22 15:12
@amexassessoria without a push payload you are sending or logs that show the problem we can't provide much help other than random guesses so more info is needed on this one.

**Comment by agil-NUBBA** [comment] 2018-01-02 10:23
Hi, got the same problem:

`$ ionic info`
```
@ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : android 6.3.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node  : v8.9.3
    npm   : 5.6.0 
    OS    : macOS High Sierra
    Xcode : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

`phonegap-plugin-push@2.1.2`
```js
let push:PushObject = this.push.init({
    ios: {
        alert: true,
        badge: true,
        sound: true
    },
    android: {
        senderID: '483809196988',
        iconColor: '#343434',
        forceShow: true
    }
});
push.on('registration').subscribe((registration: any) => this.post('/setToken', { push: registration['registrationId']}));
push.on('notification').subscribe((notification: any) => {
    console.log(notification)
});
```

`Payload`
```php
<?php

$fcm = '';
$user = '';

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send');
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type:application/json', 'Authorization:key='.$fcm]);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode([
    'registration_ids' => [$user],
    'notification' => [
        'title' => 'TEST',
        'body' => 'body test',
        'content-available' => true,
        'priority' => 'high',
        'sound' => 'default',
        'color' => '#cecece',
        'badge' => 1
    ],
    'data' => [
        'test' => 'some random data'
    ]
]));
echo curl_exec($ch);
```

I guess expected behavior would be:
* No push notification if the app is open.
* Print the `console.log(notification)` instead;

But, the application shows the notification and doesn't trigger the `.on('notification')` event.

Tested on Android 7.0, iOS works fine.

**Comment by macdonst** [comment] 2018-01-03 15:22
@agil-NUBBA do you get a registration ID? Are you delivering the google-services.json file? That is a required file for 2.0.0 and higher of the push plugin.

**Comment by agil-NUBBA** [comment] 2018-01-03 16:08
@macdonst yes, I've placed the `google-services.json`, the `registrationId` is beeing correctly obtained/sent to the server, and if the server uses that `token` the phone receibes it, but if the app is open and it receives a push notification `.on('notification')` doesn't trigger.

**Comment by macdonst** [comment] 2018-01-08 15:50
@agil-NUBBA You are running into a the [data vs notification](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads) problem. Please read up on the differences at that link.

For FCM on iOS you will send payloads of:

```
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode([
    'registration_ids' => [$user],
    'notification' => [
        'title' => 'TEST',
        'body' => 'body test',
        'content-available' => true,
        'priority' => 'high',
        'sound' => 'default',
        'color' => '#cecece',
        'badge' => 1
    ],
    'data' => [
        'test' => 'some random data'
    ]
]));
```

but on Android you'll have to modify the payload so everything is in data:

```
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode([
    'registration_ids' => [$user],
    'data' => [
        'title' => 'TEST',
        'body' => 'body test',
        'content-available' => true,
        'priority' => 'high',
        'sound' => 'default',
        'color' => '#cecece',
        'badge' => 1,
        'test' => 'some random data'
    ]
]));
```

**Comment by Vaishnavi-optisol** [comment] 2018-01-09 10:07
@macdonst : I have sent everything in data payload and using the same 2.1.2 version of plugin. I'm not receiving notifications when app in background.

**Comment by ishwaryas01** [comment] 2018-01-11 09:43
Ionic Info 
cli packages: 

    @ionic/cli-plugin-proxy : 1.5.6
    @ionic/cli-utils        : 1.19.0
    ionic (Ionic CLI)       : 3.19.0

global packages:

    cordova (Cordova CLI) : 6.5.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.3
    Node              : v8.6.0
    npm               : 5.4.2
    OS                : Windows 8.1

Code :
let options1: any = {
      android:{
        senderID: 'xxxxxxxxxx'
      },
      ios: {
        alert: 'true',
        badge: true,
        sound: 'false'
      },
      windows: {},
      browser: {
        pushServiceURL: 'http://push.api.phonegap.com/v1/push'
      }
    };

    const pushObject: PushObject = this.push.init(options1);

    pushObject.on('notification').subscribe((notification: any) => {
      console.log('Received a notification', notification);
      alert('Received a notification'+ notification.message);
      if(notification.additionalData.foreground){
        let youralert = this.alertCtrl.create({
          title: 'New Push Notification',
          message: notification.message
        });
      }
    
  });

    pushObject.on('registration').subscribe((registration: any) => {
      console.log('Device registered', registration);
      alert('Device registered'+ registration);
    });

    pushObject.on('error').subscribe(error => {
      console.error('Error with Push plugin', error);
      alert('Error with Push plugin'+ error);

  });

I have tried to install 2.1.2 and 1.8.0 this was working once but later on I am facing issue like the app is getting registered , message is sent from the firebase console ( Completed status ) but it is not reaching my phone. Please share me if there is any solution for this.

**Comment by macdonst** [comment] 2018-01-19 21:50
@Vaishnavi-optisol nowhere near enough info to be able to help you.

@ishwaryas01 if you are sending everything into the Firebase console you are running into the data vs notification payload problem I linked to earlier.

**Comment by waynelidza** [comment] 2018-03-28 09:16
Good  day i have the same it does register the device but when i send the push i dont receive the notification
here  is my spinet initPushNotification() {
    if (!this.platform.is('cordova')) {
      console.warn('Push notifications not initialized. Cordova is not available - Run in physical device');
      return;
    }
    const options: PushOptions = {
      android: {
        senderID: 'xxxxxxxxx'
      },
      ios: {
        alert: 'true',
        badge: false,
        sound: 'true'
      },
    };
    const pushObject: PushObject = this.push.init(options);

    pushObject.on('registration').subscribe((data: any) => {
      console.log('device token -> ' + data.registrationId);
      //TODO - send device token to server
    });

    pushObject.on('notification').subscribe((data: any) => {
      console.log('message -> ' + data.message);
      //if user using app and push notification comes
      if (data.additionalData.foreground) {
        // if application open, show popup
        let confirmAlert = this.alertCtrl.create({
          title: 'New Notification',
          message: data.message,
          buttons: [{
            text: 'Ignore',
            role: 'cancel'
          }, {
            text: 'View',
            handler: () => {
              //TODO: Your logic here
              this.nav.push(DetailsPage, { message: data.message });
            }
          }]
        });
        confirmAlert.present();
      } else {
        //if user NOT using app and push notification comes
        //TODO: Your logic on click of push notification directly
        this.nav.push(DetailsPage, { message: data.message });
        console.log('Push notification clicked');
      }
    });

    pushObject.on('error').subscribe(error => console.error('Error with Push plugin' + error));
  }
}

___________________________________________________+++++++++++++++++++++++++++++++++++++++
**my details**
cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 1.3.12
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.5.0

System:

    Android SDK Tools : 26.1.1
    Node              : v9.4.0
    npm               : 5.6.0 
    OS                : Linux 4.10

Environment Variables:

    ANDROID_HOME : /home/leewayne/Android/Sdk

Misc:

    backend : pro

**Comment by waynelidza** [comment] 2018-03-28 09:18
my conslole log message device token -> fP9d1bGzlDg:APA91bHNs42moFtXtsV0r6bhBbXrfil7nEzhoM-

**Comment by waynelidza** [comment] 2018-03-28 09:25
yes i do get the token

**Comment by waynelidza** [comment] 2018-03-28 09:27
but when i send the message via firebase my android device doesn't recieve the message .

**Comment by waynelidza** [comment] 2018-03-28 09:29
![screenshot_20180328_112550](https://user-images.githubusercontent.com/12393267/38020681-2ff918e0-327b-11e8-9f45-cae6f0559415.png)
when i try to to this i dont get the message on my device

**Comment by macdonst** [comment] 2018-06-04 15:56
I'm closing this issue as the original reporter's issue was resolved. There was a lot of other folks chiming in but I have a feeling they are running into the [data vs notification](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads) problem because of sending from the Firebase Console.

**Closed by macdonst** 2018-06-04 15:56 UTC
Labels: android, question, wontfix

**Comment by KadioArnaud** [comment] 2018-06-10 12:59
@macdonst , I am facing the same issue and i am not sending from the firebase console but from my app. I follow the link you put about the data vs notification problem, and i am doing thing well.


ionic info prints the following:
``
 @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v8.9.3
    npm               : 5.5.1
    OS                : Windows 10
 ``

**Comment by NavKumarV** [comment] 2018-06-11 02:37
I have the same problem, 
        I implemented push notification using two methods:   1) Push plugin  and 2) FCM Plugin

With these methods I am able to get the device registration ID, but when I send the push notification from Firebase or even from AWS-SNS, I am not receiving and notification to my device. 

I even tried creating a new projects and implement in that, but still the same problem.

In recent updates i am facing this issue, 4 months before it was working well. 

cli packages: 
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:
    cordova (Cordova CLI) : 8.0.0

local packages:
    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.1.0
    Ionic Framework    : ionic-angular 3.9.2

System:
    Android SDK Tools : 26.1.1
    Node              : v8.9.3
    npm               : 5.5.1
    OS                : Windows 10

It would be a great support if someone has a solution for this.
