### ISSUE TITLE
Re-register

### ISSUE THREAD

**Issue by adyz** [phonegap/phonegap-plugin-push#250] opened 2015-10-21 11:06 UTC
Hi guys,

Wonderfull project here.

In my app I have a check-box for notifications (on and of)

On app device ready I call the init method

		push = PushNotification.init({
			"android": {"senderID": "12345679"},
			"ios": {"alert": "true", "badge": "true", "sound": "true"},
			"windows": {}
		});

when the users unchecks the box I call the unregister function

		push.unregister(successHandler, errorHandler);

What do I do to register the user back? Will I call the same init function? is so, the `on('registration')` does not trigger.

**Comment by Hirbod** [comment] 2015-10-21 14:59
Yes that should be the correct way

**Comment by adyz** [comment] 2015-10-21 15:14
Cool, thanks for the reply


Thing is that if I do this, the `push.on('registration', function(data) {` triggers twice. Any ideea why?


Thanks!

**Comment by macdonst** [comment] 2015-10-21 15:16
@adyz I believe I will need to unregister the registration/notification events when unregister is called. Probably a bug, I will re-test.

**Comment by macdonst** [comment] 2015-10-21 16:07
@adyz What platform are you testing on iOS/Android? What version of the operating system? What version of the plugin are you using? I'm having issue reproducing this one.

**Comment by kaclark28** [comment] 2015-10-21 19:49
@macdonst I have the same issue as @adyz where push.on('registration', .... triggers twice. I see it happening on an iPad Air 2 with iOS 9.0. I tried it on another device (iPad mini on 6.1.3), and do NOT see a double registration.

**Comment by macdonst** [comment] 2015-10-21 20:06
@kaclark28 you are probably running into issue #57 which has been fixed in master and will be in the 1.4.0 release. Trying to determine if @adyz has the same problem.

**Comment by adyz** [comment] 2015-10-22 06:09
I have crosswalk and facebook4 or facebook plugin and I managed to test this only on ios8 and 9 so far due to build failing on android.

**Comment by macdonst** [comment] 2015-10-22 13:21
@adyz Do you see the same double registration problem on both iOS8 and iOS9?

**Comment by adyz** [comment] 2015-10-22 13:32
On iOS 8, at the momen I get `- no valid 'aps-environment' entitlement string found for application`

**Comment by macdonst** [comment] 2015-10-22 13:38
@adyz okay if you see the double registration on iOS9 then it is most probably #57 which is fixed in master and will be in the 1.4.0 release (currently in master).

The error you are seeing on iOS8 have something to do with the your application ID not matching your certificate. Make sure that the "Bundle Identifier" in Xcode is what you expect.

**Comment by adyz** [comment] 2015-10-22 14:58
The iOS8 device is new, so I assume that it has something to do with xcode and apple. When I solve this problem I will let you know what is happening on my devices.

On android this works fine, I don't get two callbacks!

Thank for all the help!

**Comment by zwacky** [comment] 2015-10-23 15:03
same here, although i'm seeing 4x `registration` events called after 1 init on iOS (9.1). android runs perfectly fine.

**Comment by macdonst** [comment] 2015-10-26 20:47
Cannot reproduce, assume it is fixed by the code for issue #57.

**Closed by macdonst** 2015-10-26 20:47 UTC
Labels: retest

**Comment by adyz** [comment] 2015-10-30 14:50
Yes, it's fixed. Thanks a lot!!!
