### ISSUE TITLE
undefined PushNotification

### ISSUE THREAD

**Issue by afedisa** [phonegap/phonegap-plugin-push#965] opened 2016-06-07 11:49 UTC
I have problem with some versions of this plugin, if i use a versio bigger than 1.5.3, my IOS app, show an error " undefined PushNotification", but it works in Android, but if version is smaller than 1.6.3, Android app crash.

I use PGB to compile.
IOS 9.3.2
Android 5.0.2
Cordova CLI: cli-5.2.0
 IOS 3.9.1
 Android: 4.1.1

**Comment by macdonst** [comment] 2016-06-07 13:37
This is a duplicate of #779.

Version 1.6.x of the plugin requires cordova-ios 4 or greater.

**Closed by macdonst** 2016-06-07 13:37 UTC
Labels: duplicate
