### ISSUE TITLE
Android App Crashes on Startup at InstanceID.getInstance(getApplicationContext())

### ISSUE THREAD

**Issue by jiankai82** [phonegap/phonegap-plugin-push#913] opened 2016-05-21 03:38 UTC
### Expected Behaviour
The app launches and registers with GCM.

### Actual Behaviour
The app crashes at this line in the phonegap-plugin-push:
token = InstanceID.getInstance(getApplicationContext()).getToken(senderID, GCM);
A valid senderID was passed in.

Here is the exception:
java.lang.IncompatibleClassChangeError: The method 'java.io.File android.support.v4.content.ContextCompat.getNoBackupFilesDir(android.content.Context)' was expected to be of type virtual but instead was found to be of type direct (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)

### Reproduce Scenario (including but not limited to)
Launch the app

#### Steps to Reproduce 
Launch the app

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.1.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
NEXUS

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.1.1
    cordova platform version android           4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.6.3

**Comment by Jojr** [comment] 2016-05-21 14:25
Hi,

You are facing the same trouble as us.

That's solution used by @zimski

> I fixed the issue by removing the support of v4 in app/platforms/android/project.properties
> Line to remove

`cordova.system.library.2=com.android.support:support-v4:+`

> this file in my case already contains an other version of support

`cordova.system.library.3=com.android.support:support-v13:23+`

> I think the v4 is deprecated for the latest version of service-gcm
> The app starts correctly and the register is OK.
> 
> If some one can help and explain to me how the project.properties is generated/update ? this will allow us to fix this issue in a cleaner way.

Refer to this issue:
https://github.com/phonegap/phonegap-plugin-push/issues/911#issuecomment-220717195

**Comment by macdonst** [comment] 2016-05-22 09:31
Duplicate of #909

**Closed by macdonst** 2016-05-22 09:31 UTC
